library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Vivado-packaged AXI wrapper around the RadILA capture core.
-- Maps AXI register transactions onto analyzer control, trigger, status, and capture-buffer readback signals.
entity radila_v1_0 is
  generic (
    -- Sets the bit width for C S00 AXI DATA WIDTH values carried by this module.
    C_S00_AXI_DATA_WIDTH : integer := 32;
    -- Sets the bit width for C S00 AXI ADDR WIDTH values carried by this module.
    C_S00_AXI_ADDR_WIDTH : integer := 6;
    -- Sets the bit width for SAMPLE WIDTH values carried by this module.
    SAMPLE_WIDTH         : integer := 32;
    -- Sets the bit width for EVENT WIDTH values carried by this module.
    EVENT_WIDTH          : integer := 8;
    -- Sets the storage depth, frame length, or number of buffered samples used internally.
    DEPTH                : integer := 1024;
    -- Sets the bit width for ADDR WIDTH values carried by this module.
    ADDR_WIDTH           : integer := 10;
    -- Sets the number of parallel sample lanes processed per handshake beat.
    CMD_LANES            : integer := 4;
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR_TAG           : string  := "XILINX";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_SERIES_TAG   : string  := "7SERIES";
    -- Configures G DEBUG BUS for this instance.
    G_DEBUG_BUS          : string  := "AXI_LITE"
  );
  port (
    -- Input sample vector captured or processed by the datapath.
    sample_i       : in  std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
    -- Event or trigger metadata associated with the current sample stream.
    event_i        : in  std_logic_vector(EVENT_WIDTH - 1 downto 0);
    -- Output irq o signal generated by this module.
    irq_o          : out std_logic;
    -- S00 axi aclk interface signal.
    s00_axi_aclk   : in  std_logic;
    -- S00 axi aresetn interface signal.
    s00_axi_aresetn: in  std_logic;
    -- S00 axi awaddr interface signal.
    s00_axi_awaddr : in  std_logic_vector(C_S00_AXI_ADDR_WIDTH - 1 downto 0);
    -- S00 axi awprot interface signal.
    s00_axi_awprot : in  std_logic_vector(2 downto 0);
    -- S00 axi awvalid interface signal.
    s00_axi_awvalid: in  std_logic;
    -- S00 axi awready interface signal.
    s00_axi_awready: out std_logic;
    -- S00 axi wdata interface signal.
    s00_axi_wdata  : in  std_logic_vector(C_S00_AXI_DATA_WIDTH - 1 downto 0);
    -- S00 axi wstrb interface signal.
    s00_axi_wstrb  : in  std_logic_vector((C_S00_AXI_DATA_WIDTH / 8) - 1 downto 0);
    -- S00 axi wvalid interface signal.
    s00_axi_wvalid : in  std_logic;
    -- S00 axi wready interface signal.
    s00_axi_wready : out std_logic;
    -- S00 axi bresp interface signal.
    s00_axi_bresp  : out std_logic_vector(1 downto 0);
    -- S00 axi bvalid interface signal.
    s00_axi_bvalid : out std_logic;
    -- S00 axi bready interface signal.
    s00_axi_bready : in  std_logic;
    -- S00 axi araddr interface signal.
    s00_axi_araddr : in  std_logic_vector(C_S00_AXI_ADDR_WIDTH - 1 downto 0);
    -- S00 axi arprot interface signal.
    s00_axi_arprot : in  std_logic_vector(2 downto 0);
    -- S00 axi arvalid interface signal.
    s00_axi_arvalid: in  std_logic;
    -- S00 axi arready interface signal.
    s00_axi_arready: out std_logic;
    -- S00 axi rdata interface signal.
    s00_axi_rdata  : out std_logic_vector(C_S00_AXI_DATA_WIDTH - 1 downto 0);
    -- S00 axi rresp interface signal.
    s00_axi_rresp  : out std_logic_vector(1 downto 0);
    -- S00 axi rvalid interface signal.
    s00_axi_rvalid : out std_logic;
    -- S00 axi rready interface signal.
    s00_axi_rready : in  std_logic
  );
end entity;

architecture rtl of radila_v1_0 is
begin
  u_rad_debug_hub : entity work.RadDebugHub
    generic map (
      C_S_AXI_DATA_WIDTH => C_S00_AXI_DATA_WIDTH,
      C_S_AXI_ADDR_WIDTH => C_S00_AXI_ADDR_WIDTH,
      SAMPLE_WIDTH       => SAMPLE_WIDTH,
      EVENT_WIDTH        => EVENT_WIDTH,
      DEPTH              => DEPTH,
      ADDR_WIDTH         => ADDR_WIDTH,
      CMD_LANES          => CMD_LANES,
      VENDOR_TAG         => VENDOR_TAG,
      PRODUCT_SERIES_TAG => PRODUCT_SERIES_TAG,
      G_DEBUG_BUS        => G_DEBUG_BUS
    )
    port map (
      sample_clk     => s00_axi_aclk,
      sample_rstn    => s00_axi_aresetn,
      sample_i       => sample_i,
      event_i        => event_i,
      irq_o          => irq_o,
      S_AXI_ACLK     => s00_axi_aclk,
      S_AXI_ARESETN  => s00_axi_aresetn,
      S_AXI_AWADDR   => s00_axi_awaddr,
      S_AXI_AWPROT   => s00_axi_awprot,
      S_AXI_AWVALID  => s00_axi_awvalid,
      S_AXI_AWREADY  => s00_axi_awready,
      S_AXI_WDATA    => s00_axi_wdata,
      S_AXI_WSTRB    => s00_axi_wstrb,
      S_AXI_WVALID   => s00_axi_wvalid,
      S_AXI_WREADY   => s00_axi_wready,
      S_AXI_BRESP    => s00_axi_bresp,
      S_AXI_BVALID   => s00_axi_bvalid,
      S_AXI_BREADY   => s00_axi_bready,
      S_AXI_ARADDR   => s00_axi_araddr,
      S_AXI_ARPROT   => s00_axi_arprot,
      S_AXI_ARVALID  => s00_axi_arvalid,
      S_AXI_ARREADY  => s00_axi_arready,
      S_AXI_RDATA    => s00_axi_rdata,
      S_AXI_RRESP    => s00_axi_rresp,
      S_AXI_RVALID   => s00_axi_rvalid,
      S_AXI_RREADY   => s00_axi_rready
    );
end architecture;
