library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library raddsp;

-- Synthesis-report top level for RadFFT 1024-point utilization studies.
-- Instantiates the target FFT core configuration with minimal surrounding logic for repeatable timing and resource reports.
entity radhdl_radfft_1024_util_top is
  generic (
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY    : string := "ultrascaleplus";
    -- Sets the transform, frame, or vector size used by the datapath.
    FFT_RADIX        : positive := 4;
    -- Sets the transform, frame, or vector size used by the datapath.
    FFT_MEMORY_STYLE : string := "block";
    -- Sets the transform, frame, or vector size used by the datapath.
    FFT_TWIDDLE_MEMORY_STYLE : string := "block";
    -- Sets the transform, frame, or vector size used by the datapath.
    FFT_TWIDDLE_INIT_FILE : string := "none";
    -- Sets the transform, frame, or vector size used by the datapath.
    FFT_WORD_SAMPLES : positive := 4;
    -- Sets the bit width for INPUT WIDTH values carried by this module.
    INPUT_WIDTH      : positive := 16;
    -- Sets the bit width for TWIDDLE WIDTH values carried by this module.
    TWIDDLE_WIDTH    : positive := 16;
    -- Sets the bit width for OUTPUT WIDTH values carried by this module.
    OUTPUT_WIDTH     : positive := 24
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk      : in  std_logic;
    -- Active-low reset for this clock domain.
    rstn     : in  std_logic;
    -- Output digest o signal generated by this module.
    digest_o : out std_logic_vector(31 downto 0)
  );
end entity;

architecture rtl of radhdl_radfft_1024_util_top is
  constant C_POINTS : positive := 1024;

  signal rst : std_logic;
  signal src_valid : std_logic := '0';
  signal src_ready : std_logic;
  signal src_data  : std_logic_vector((2 * INPUT_WIDTH) - 1 downto 0) := (others => '0');
  signal src_last  : std_logic := '0';
  signal src_index : unsigned(9 downto 0) := (others => '0');

  signal fft_valid : std_logic;
  signal fft_data  : std_logic_vector((2 * OUTPUT_WIDTH) - 1 downto 0);
  signal fft_last  : std_logic;
  signal fft_done  : std_logic;
  signal fft_busy  : std_logic;
  signal digest_r  : unsigned(31 downto 0) := (others => '0');

  attribute dont_touch : string;
  attribute dont_touch of digest_r : signal is "true";
begin
  rst <= not rstn;
  digest_o <= std_logic_vector(digest_r);

  process(clk)
    variable re_v : signed(INPUT_WIDTH - 1 downto 0);
    variable im_v : signed(INPUT_WIDTH - 1 downto 0);
  begin
    if rising_edge(clk) then
      if rst = '1' then
        src_valid <= '0';
        src_last <= '0';
        src_data <= (others => '0');
        src_index <= (others => '0');
      else
        src_valid <= '1';
        if src_ready = '1' then
          re_v := resize(signed('0' & src_index(8 downto 0)), INPUT_WIDTH);
          im_v := resize(signed('0' & not src_index(8 downto 0)), INPUT_WIDTH);
          src_data <= std_logic_vector(re_v) & std_logic_vector(im_v);
          src_last <= '1' when src_index = C_POINTS - 1 else '0';
          if src_index = C_POINTS - 1 then
            src_index <= (others => '0');
          else
            src_index <= src_index + 1;
          end if;
        end if;
      end if;
    end if;
  end process;

  fft_i: entity raddsp.raddsp_axis_radfft
    generic map (
      VENDOR => "xilinx",
      DEVICE_FAMILY => DEVICE_FAMILY,
      G_POINTS => C_POINTS,
      G_MAX_POINTS => C_POINTS,
      G_RADIX => FFT_RADIX,
      G_PIPELINED_STREAMING => false,
      G_INVERSE_FFT => false,
      G_INPUT_WIDTH => INPUT_WIDTH,
      G_TWIDDLE_WIDTH => TWIDDLE_WIDTH,
      G_OUTPUT_WIDTH => OUTPUT_WIDTH,
      G_SCALE_EACH_STAGE => true,
      G_MEMORY_STYLE => FFT_MEMORY_STYLE,
      G_TWIDDLE_MEMORY_STYLE => FFT_TWIDDLE_MEMORY_STYLE,
      G_TWIDDLE_INIT_FILE => FFT_TWIDDLE_INIT_FILE,
      G_MULTIPLIER_LANES => 1,
      G_MAX_MULTIPLIER_LANES => 8,
      G_MEMORY_WORD_SAMPLES => FFT_WORD_SAMPLES
    )
    port map (
      clk => clk,
      rst => rst,
      s_axis_tvalid => src_valid,
      s_axis_tready => src_ready,
      s_axis_tdata => src_data,
      s_axis_tlast => src_last,
      m_axis_tvalid => fft_valid,
      m_axis_tready => '1',
      m_axis_tdata => fft_data,
      m_axis_tlast => fft_last,
      twiddle_addr_o => open,
      twiddle_re_i => (others => '0'),
      twiddle_im_i => (others => '0'),
      busy_o => fft_busy,
      frame_done_o => fft_done
    );

  process(clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        digest_r <= (others => '0');
      elsif fft_valid = '1' then
        digest_r <= digest_r xor resize(unsigned(fft_data(31 downto 0)), digest_r'length);
        if fft_last = '1' then
          digest_r <= digest_r + 1;
        end if;
      elsif fft_busy = '0' then
        digest_r <= digest_r + 1;
      end if;
    end if;
  end process;
end architecture;
