library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library radif;
use radif.radif_pkg.all;

library raddsp;

-- Integration top level for the RadHDL DSP AXI smoke design.
-- Connects RadDSP streaming and register-interface blocks into a board-testable reference design with address-map artifacts.
entity radhdl_dsp_axi_smoke_top is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR_TAG         : string := "XILINX";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_SERIES_TAG : string := "GENERIC";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DSP48_FAMILY       : string := "7series";
    -- Sets the number of parallel sample lanes processed per handshake beat.
    FIR_DSP_LANES      : positive := 1;
    -- Sets the number of parallel sample lanes processed per handshake beat.
    BIQUAD_DSP_LANES   : positive := 1;
    -- Sets the bit width for DMA DATA WIDTH values carried by this module.
    DMA_DATA_WIDTH      : positive := 64
  );
  port (
    -- Aclk interface signal.
    aclk           : in  std_logic;
    -- Aresetn interface signal.
    aresetn        : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awaddr   : in  std_logic_vector(15 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awprot   : in  std_logic_vector(2 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awvalid  : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awready  : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wdata    : in  std_logic_vector(31 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wstrb    : in  std_logic_vector(3 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wvalid   : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wready   : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_bresp    : out std_logic_vector(1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_bvalid   : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_bready   : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_araddr   : in  std_logic_vector(15 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_arprot   : in  std_logic_vector(2 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_arvalid  : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_arready  : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rdata    : out std_logic_vector(31 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rresp    : out std_logic_vector(1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rvalid   : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rready   : in  std_logic;
    -- Output irq o signal generated by this module.
    irq_o          : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awaddr   : out std_logic_vector(31 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awlen    : out std_logic_vector(7 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awsize   : out std_logic_vector(2 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awburst  : out std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awvalid  : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awready  : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wdata    : out std_logic_vector(DMA_DATA_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wstrb    : out std_logic_vector((DMA_DATA_WIDTH / 8) - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wlast    : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wvalid   : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wready   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bresp    : in  std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bvalid   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bready   : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_araddr   : out std_logic_vector(31 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arlen    : out std_logic_vector(7 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arsize   : out std_logic_vector(2 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arburst  : out std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arvalid  : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arready  : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rdata    : in  std_logic_vector(DMA_DATA_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rresp    : in  std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rlast    : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rvalid   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rready   : out std_logic;
    -- Dma m axis tdata interface signal.
    dma_m_axis_tdata  : out std_logic_vector(DMA_DATA_WIDTH - 1 downto 0);
    -- Dma m axis tvalid interface signal.
    dma_m_axis_tvalid : out std_logic;
    -- Dma m axis tready interface signal.
    dma_m_axis_tready : in  std_logic;
    -- Dma m axis tlast interface signal.
    dma_m_axis_tlast  : out std_logic;
    -- Dma s axis tdata interface signal.
    dma_s_axis_tdata  : in  std_logic_vector(DMA_DATA_WIDTH - 1 downto 0);
    -- Dma s axis tvalid interface signal.
    dma_s_axis_tvalid : in  std_logic;
    -- Dma s axis tready interface signal.
    dma_s_axis_tready : out std_logic;
    -- Dma s axis tlast interface signal.
    dma_s_axis_tlast  : in  std_logic
  );
end entity;

architecture rtl of radhdl_dsp_axi_smoke_top is
  constant C_DATA_WIDTH : integer := 32;
  constant C_ADDR_WIDTH : integer := 16;
  constant C_SLAVES     : integer := 3;
  constant C_CTRL_RW    : integer := 8;
  constant C_CTRL_RO    : integer := 8;
  constant C_DSP_RW     : integer := 32;
  constant C_DSP_RO     : integer := 16;

  constant C_SLAVE_BASES : std_logic_vector((C_SLAVES * C_ADDR_WIDTH) - 1 downto 0) := x"200010000000";
  constant C_SLAVE_MASKS : std_logic_vector((C_SLAVES * C_ADDR_WIDTH) - 1 downto 0) := x"F000F000F000";

  signal reg_wr_addr   : std_logic_vector(C_ADDR_WIDTH - 1 downto 0);
  signal reg_rd_addr   : std_logic_vector(C_ADDR_WIDTH - 1 downto 0);
  signal reg_wr_en     : std_logic;
  signal reg_rd_en     : std_logic;
  signal reg_data_in   : std_logic_vector(C_DATA_WIDTH - 1 downto 0);
  signal reg_data_out  : std_logic_vector(C_DATA_WIDTH - 1 downto 0);
  signal reg_wr_rdy    : std_logic;
  signal reg_rd_rdy    : std_logic;
  signal reg_wr_valid  : std_logic;
  signal reg_rd_valid  : std_logic;
  signal reg_error     : std_logic;

  signal s_wr_addr     : std_logic_vector((C_SLAVES * C_ADDR_WIDTH) - 1 downto 0);
  signal s_rd_addr     : std_logic_vector((C_SLAVES * C_ADDR_WIDTH) - 1 downto 0);
  signal s_wr_en       : std_logic_vector(C_SLAVES - 1 downto 0);
  signal s_rd_en       : std_logic_vector(C_SLAVES - 1 downto 0);
  signal s_data_in     : std_logic_vector((C_SLAVES * C_DATA_WIDTH) - 1 downto 0);
  signal s_data_out    : std_logic_vector((C_SLAVES * C_DATA_WIDTH) - 1 downto 0);
  signal s_wr_rdy      : std_logic_vector(C_SLAVES - 1 downto 0);
  signal s_rd_rdy      : std_logic_vector(C_SLAVES - 1 downto 0);
  signal s_wr_valid    : std_logic_vector(C_SLAVES - 1 downto 0);
  signal s_rd_valid    : std_logic_vector(C_SLAVES - 1 downto 0);
  signal s_error       : std_logic_vector(C_SLAVES - 1 downto 0);

  signal ctrl_ro       : radif_reg_array_t(0 to C_CTRL_RO - 1)(31 downto 0);
  signal ctrl_rw       : radif_reg_array_t(0 to C_CTRL_RW - 1)(31 downto 0);
  signal dsp_ro        : radif_reg_array_t(0 to C_DSP_RO - 1)(31 downto 0);
  signal dsp_rw        : radif_reg_array_t(0 to C_DSP_RW - 1)(31 downto 0);

  signal dsp_rst       : std_logic;
  signal dsp_enable    : std_logic;
  signal dsp_clear     : std_logic;
  signal sample_count  : unsigned(15 downto 0) := (others => '0');
  signal sample_valid  : std_logic;
  signal sample_last   : std_logic;
  signal sample_a      : std_logic_vector(15 downto 0);
  signal sample_b      : std_logic_vector(15 downto 0);
  signal fir_taps      : std_logic_vector((4 * 18) - 1 downto 0);

  signal gain_valid    : std_logic;
  signal gain_data     : std_logic_vector(15 downto 0);
  signal gain_last     : std_logic;
  signal gain_p_valid  : std_logic := '0';
  signal gain_p_data   : std_logic_vector(15 downto 0) := (others => '0');
  signal gain_p_last   : std_logic := '0';
  signal lp_valid      : std_logic;
  signal lp_data       : std_logic_vector(15 downto 0);
  signal lp_last       : std_logic;
  signal lp_p_valid    : std_logic := '0';
  signal lp_p_data     : std_logic_vector(15 downto 0) := (others => '0');
  signal lp_p_last     : std_logic := '0';
  signal fir_valid     : std_logic;
  signal fir_data      : std_logic_vector(15 downto 0);
  signal fir_last      : std_logic;
  signal fir_p_valid   : std_logic := '0';
  signal fir_p_data    : std_logic_vector(15 downto 0) := (others => '0');
  signal fir_p_last    : std_logic := '0';
  signal biquad_valid  : std_logic;
  signal biquad_data   : std_logic_vector(15 downto 0);
  signal biquad_last   : std_logic;
  signal biquad_p_valid : std_logic := '0';
  signal biquad_p_data  : std_logic_vector(15 downto 0) := (others => '0');
  signal biquad_p_last  : std_logic := '0';
  signal dds_valid     : std_logic;
  signal dds_data      : std_logic_vector(15 downto 0);
  signal dds_last      : std_logic;
  signal dds_p_valid   : std_logic := '0';
  signal dds_p_data    : std_logic_vector(15 downto 0) := (others => '0');
  signal dds_p_last    : std_logic := '0';
  signal dds_phase     : std_logic_vector(31 downto 0);
  signal dds_lut_addr  : std_logic_vector(3 downto 0);
  signal iq_valid      : std_logic;
  signal iq_data       : std_logic_vector(31 downto 0);
  signal iq_last       : std_logic;
  signal stats_valid   : std_logic;
  signal stats_peak    : std_logic_vector(15 downto 0);
  signal stats_power   : std_logic_vector(63 downto 0);
  signal stats_count   : std_logic_vector(31 downto 0);
  signal mat_valid     : std_logic;
  signal mat_data      : std_logic_vector(15 downto 0);
  signal mat_last      : std_logic;
  signal dot_valid     : std_logic;
  signal dot_data      : std_logic_vector(47 downto 0);
  signal dot_count     : std_logic_vector(31 downto 0);
  signal dma_irq       : std_logic;

  attribute dont_touch : string;
  attribute dont_touch of gain_p_valid : signal is "true";
  attribute dont_touch of gain_p_data : signal is "true";
  attribute dont_touch of gain_p_last : signal is "true";
  attribute dont_touch of lp_p_valid : signal is "true";
  attribute dont_touch of lp_p_data : signal is "true";
  attribute dont_touch of lp_p_last : signal is "true";
  attribute dont_touch of fir_p_valid : signal is "true";
  attribute dont_touch of fir_p_data : signal is "true";
  attribute dont_touch of fir_p_last : signal is "true";
  attribute dont_touch of biquad_p_valid : signal is "true";
  attribute dont_touch of biquad_p_data : signal is "true";
  attribute dont_touch of biquad_p_last : signal is "true";
  attribute dont_touch of dds_p_valid : signal is "true";
  attribute dont_touch of dds_p_data : signal is "true";
  attribute dont_touch of dds_p_last : signal is "true";
begin
  assert (DMA_DATA_WIDTH = 32) or (DMA_DATA_WIDTH = 64) or (DMA_DATA_WIDTH = 128)
    report "DMA_DATA_WIDTH must be 32, 64, or 128 bits"
    severity failure;

  dsp_enable <= ctrl_rw(0)(0);
  dsp_rst <= (not aresetn) or ctrl_rw(0)(1);
  dsp_clear <= ctrl_rw(0)(2);
  sample_valid <= dsp_enable;
  sample_last <= '1' when sample_count(3 downto 0) = x"F" else '0';
  sample_a <= std_logic_vector(sample_count);
  sample_b <= std_logic_vector(sample_count + unsigned(dsp_rw(1)(15 downto 0)));
  fir_taps <= dsp_rw(7)(17 downto 0) & dsp_rw(6)(17 downto 0) & dsp_rw(5)(17 downto 0) & dsp_rw(4)(17 downto 0);
  irq_o <= stats_valid or dot_valid or dma_irq;

  process(aclk)
  begin
    if rising_edge(aclk) then
      if dsp_rst = '1' then
        sample_count <= (others => '0');
        gain_p_valid <= '0';
        gain_p_data <= (others => '0');
        gain_p_last <= '0';
        lp_p_valid <= '0';
        lp_p_data <= (others => '0');
        lp_p_last <= '0';
        fir_p_valid <= '0';
        fir_p_data <= (others => '0');
        fir_p_last <= '0';
        biquad_p_valid <= '0';
        biquad_p_data <= (others => '0');
        biquad_p_last <= '0';
        dds_p_valid <= '0';
        dds_p_data <= (others => '0');
        dds_p_last <= '0';
      elsif dsp_enable = '1' then
        sample_count <= sample_count + 1;
        gain_p_valid <= gain_valid;
        gain_p_data <= gain_data;
        gain_p_last <= gain_last;
        lp_p_valid <= lp_valid;
        lp_p_data <= lp_data;
        lp_p_last <= lp_last;
        fir_p_valid <= fir_valid;
        fir_p_data <= fir_data;
        fir_p_last <= fir_last;
        biquad_p_valid <= biquad_valid;
        biquad_p_data <= biquad_data;
        biquad_p_last <= biquad_last;
        dds_p_valid <= dds_valid;
        dds_p_data <= dds_data;
        dds_p_last <= dds_last;
      end if;
    end if;
  end process;

  process(all)
  begin
    ctrl_ro <= (others => (others => '0'));
    ctrl_ro(0) <= x"52414444";
    ctrl_ro(1) <= x"00010000";
    ctrl_ro(2)(0) <= dsp_enable;
    ctrl_ro(2)(1) <= stats_valid;
    ctrl_ro(2)(2) <= dot_valid;
    ctrl_ro(3)(15 downto 0) <= std_logic_vector(sample_count);

    dsp_ro <= (others => (others => '0'));
    dsp_ro(0)(15 downto 0) <= stats_peak;
    dsp_ro(1) <= stats_count;
    dsp_ro(2) <= stats_power(31 downto 0);
    dsp_ro(3) <= stats_power(63 downto 32);
    dsp_ro(4) <= dot_data(31 downto 0);
    dsp_ro(5)(15 downto 0) <= dot_data(47 downto 32);
    dsp_ro(6) <= dot_count;
    dsp_ro(7) <= dds_phase;
    dsp_ro(8)(3 downto 0) <= dds_lut_addr;
    dsp_ro(9)(15 downto 0) <= gain_p_data;
    dsp_ro(10)(15 downto 0) <= biquad_p_data;
    dsp_ro(11)(15 downto 0) <= mat_data;
    dsp_ro(12) <= iq_data;
  end process;

  axi_lite_i: entity radif.radif_axi_lite_to_reg
    generic map (
      DATA_WIDTH => C_DATA_WIDTH,
      ADDR_WIDTH => C_ADDR_WIDTH,
      AXI_ADDR_WIDTH => C_ADDR_WIDTH,
      VENDOR_TAG => VENDOR_TAG,
      PRODUCT_SERIES_TAG => PRODUCT_SERIES_TAG
    )
    port map (
      clk => aclk,
      rstn => aresetn,
      s_axi_awaddr => s_axi_awaddr,
      s_axi_awprot => s_axi_awprot,
      s_axi_awvalid => s_axi_awvalid,
      s_axi_awready => s_axi_awready,
      s_axi_wdata => s_axi_wdata,
      s_axi_wstrb => s_axi_wstrb,
      s_axi_wvalid => s_axi_wvalid,
      s_axi_wready => s_axi_wready,
      s_axi_bresp => s_axi_bresp,
      s_axi_bvalid => s_axi_bvalid,
      s_axi_bready => s_axi_bready,
      s_axi_araddr => s_axi_araddr,
      s_axi_arprot => s_axi_arprot,
      s_axi_arvalid => s_axi_arvalid,
      s_axi_arready => s_axi_arready,
      s_axi_rdata => s_axi_rdata,
      s_axi_rresp => s_axi_rresp,
      s_axi_rvalid => s_axi_rvalid,
      s_axi_rready => s_axi_rready,
      reg_wr_addr => reg_wr_addr,
      reg_rd_addr => reg_rd_addr,
      reg_wr_en => reg_wr_en,
      reg_rd_en => reg_rd_en,
      reg_data_in => reg_data_in,
      reg_data_out => reg_data_out,
      reg_wr_rdy => reg_wr_rdy,
      reg_rd_rdy => reg_rd_rdy,
      reg_wr_valid => reg_wr_valid,
      reg_rd_valid => reg_rd_valid,
      reg_error => reg_error
    );

  interconnect_i: entity radif.radif_reg_interconnect
    generic map (
      DATA_WIDTH => C_DATA_WIDTH,
      ADDR_WIDTH => C_ADDR_WIDTH,
      SLAVE_COUNT => C_SLAVES,
      SLAVE_BASE_ADDRS => C_SLAVE_BASES,
      SLAVE_ADDR_MASKS => C_SLAVE_MASKS,
      VENDOR_TAG => VENDOR_TAG,
      PRODUCT_SERIES_TAG => PRODUCT_SERIES_TAG
    )
    port map (
      clk => aclk,
      rstn => aresetn,
      wr_addr_i => reg_wr_addr,
      rd_addr_i => reg_rd_addr,
      wr_en_i => reg_wr_en,
      rd_en_i => reg_rd_en,
      data_in_i => reg_data_in,
      data_out_o => reg_data_out,
      wr_rdy_o => reg_wr_rdy,
      rd_rdy_o => reg_rd_rdy,
      wr_valid_o => reg_wr_valid,
      rd_valid_o => reg_rd_valid,
      error_o => reg_error,
      s_wr_addr_o => s_wr_addr,
      s_rd_addr_o => s_rd_addr,
      s_wr_en_o => s_wr_en,
      s_rd_en_o => s_rd_en,
      s_data_in_o => s_data_in,
      s_data_out_i => s_data_out,
      s_wr_rdy_i => s_wr_rdy,
      s_rd_rdy_i => s_rd_rdy,
      s_wr_valid_i => s_wr_valid,
      s_rd_valid_i => s_rd_valid,
      s_error_i => s_error
    );

  ctrl_bank_i: entity radif.radif_reg_bank
    generic map (
      DATA_WIDTH => C_DATA_WIDTH,
      ADDR_WIDTH => C_ADDR_WIDTH,
      READ_ONLY_REG_COUNT => C_CTRL_RO,
      READ_WRITE_REG_COUNT => C_CTRL_RW,
      VENDOR_TAG => VENDOR_TAG,
      PRODUCT_SERIES_TAG => PRODUCT_SERIES_TAG
    )
    port map (
      clk => aclk,
      rstn => aresetn,
      wr_addr => s_wr_addr(15 downto 0),
      rd_addr => s_rd_addr(15 downto 0),
      wr_en => s_wr_en(0),
      rd_en => s_rd_en(0),
      data_in => s_data_in(31 downto 0),
      data_out => s_data_out(31 downto 0),
      read_only_regs_i => ctrl_ro,
      read_write_regs_o => ctrl_rw,
      wr_rdy => s_wr_rdy(0),
      rd_rdy => s_rd_rdy(0),
      wr_valid => s_wr_valid(0),
      rd_valid => s_rd_valid(0),
      error => s_error(0)
    );

  dsp_bank_i: entity radif.radif_reg_bank
    generic map (
      DATA_WIDTH => C_DATA_WIDTH,
      ADDR_WIDTH => C_ADDR_WIDTH,
      READ_ONLY_REG_COUNT => C_DSP_RO,
      READ_WRITE_REG_COUNT => C_DSP_RW,
      VENDOR_TAG => VENDOR_TAG,
      PRODUCT_SERIES_TAG => PRODUCT_SERIES_TAG
    )
    port map (
      clk => aclk,
      rstn => aresetn,
      wr_addr => s_wr_addr(31 downto 16),
      rd_addr => s_rd_addr(31 downto 16),
      wr_en => s_wr_en(1),
      rd_en => s_rd_en(1),
      data_in => s_data_in(63 downto 32),
      data_out => s_data_out(63 downto 32),
      read_only_regs_i => dsp_ro,
      read_write_regs_o => dsp_rw,
      wr_rdy => s_wr_rdy(1),
      rd_rdy => s_rd_rdy(1),
      wr_valid => s_wr_valid(1),
      rd_valid => s_rd_valid(1),
      error => s_error(1)
    );

  dma_i: entity radif.radif_axi4_axis_dma
    generic map (
      REG_DATA_WIDTH => C_DATA_WIDTH,
      REG_ADDR_WIDTH => C_ADDR_WIDTH,
      AXI_ADDR_WIDTH => 32,
      AXI_DATA_WIDTH => DMA_DATA_WIDTH,
      AXIS_DATA_WIDTH => DMA_DATA_WIDTH,
      ENABLE_MM2S => true,
      ENABLE_S2MM => true,
      FIFO_DEPTH => 1024,
      FIFO_FWFT => true,
      VENDOR_TAG => VENDOR_TAG,
      PRODUCT_SERIES_TAG => PRODUCT_SERIES_TAG
    )
    port map (
      clk => aclk,
      rstn => aresetn,
      reg_wr_addr => s_wr_addr(47 downto 32),
      reg_rd_addr => s_rd_addr(47 downto 32),
      reg_wr_en => s_wr_en(2),
      reg_rd_en => s_rd_en(2),
      reg_data_in => s_data_in(95 downto 64),
      reg_data_out => s_data_out(95 downto 64),
      reg_wr_rdy => s_wr_rdy(2),
      reg_rd_rdy => s_rd_rdy(2),
      reg_wr_valid => s_wr_valid(2),
      reg_rd_valid => s_rd_valid(2),
      reg_error => s_error(2),
      irq_o => dma_irq,
      m_axi_awaddr => m_axi_awaddr,
      m_axi_awlen => m_axi_awlen,
      m_axi_awsize => m_axi_awsize,
      m_axi_awburst => m_axi_awburst,
      m_axi_awvalid => m_axi_awvalid,
      m_axi_awready => m_axi_awready,
      m_axi_wdata => m_axi_wdata,
      m_axi_wstrb => m_axi_wstrb,
      m_axi_wlast => m_axi_wlast,
      m_axi_wvalid => m_axi_wvalid,
      m_axi_wready => m_axi_wready,
      m_axi_bresp => m_axi_bresp,
      m_axi_bvalid => m_axi_bvalid,
      m_axi_bready => m_axi_bready,
      m_axi_araddr => m_axi_araddr,
      m_axi_arlen => m_axi_arlen,
      m_axi_arsize => m_axi_arsize,
      m_axi_arburst => m_axi_arburst,
      m_axi_arvalid => m_axi_arvalid,
      m_axi_arready => m_axi_arready,
      m_axi_rdata => m_axi_rdata,
      m_axi_rresp => m_axi_rresp,
      m_axi_rlast => m_axi_rlast,
      m_axi_rvalid => m_axi_rvalid,
      m_axi_rready => m_axi_rready,
      m_axis_tdata => dma_m_axis_tdata,
      m_axis_tvalid => dma_m_axis_tvalid,
      m_axis_tready => dma_m_axis_tready,
      m_axis_tlast => dma_m_axis_tlast,
      s_axis_tdata => dma_s_axis_tdata,
      s_axis_tvalid => dma_s_axis_tvalid,
      s_axis_tready => dma_s_axis_tready,
      s_axis_tlast => dma_s_axis_tlast
    );

  gain_i: entity raddsp.raddsp_axis_gain
    generic map (
      DEVICE_FAMILY => DSP48_FAMILY,
      CHANNEL_COUNT => 1,
      DATA_WIDTH => 16,
      COEFF_WIDTH => 18,
      COEFF_FRAC_BITS => 15
    )
    port map (
      clk => aclk, rst => dsp_rst, gain_i => dsp_rw(2)(17 downto 0),
      s_axis_tvalid => sample_valid, s_axis_tready => open, s_axis_tdata => sample_a, s_axis_tlast => sample_last,
      m_axis_tvalid => gain_valid, m_axis_tready => '1', m_axis_tdata => gain_data, m_axis_tlast => gain_last
    );

  lowpass_i: entity raddsp.raddsp_axis_one_pole_lowpass
    generic map (
      DEVICE_FAMILY => DSP48_FAMILY,
      DATA_WIDTH => 16,
      COEFF_WIDTH => 18,
      COEFF_FRAC_BITS => 15,
      IMPLEMENTATION => "sequential_mac"
    )
    port map (
      clk => aclk, rst => dsp_rst, clear_i => dsp_clear, alpha_i => dsp_rw(3)(17 downto 0),
      s_axis_tvalid => gain_p_valid, s_axis_tready => open, s_axis_tdata => gain_p_data, s_axis_tlast => gain_p_last,
      m_axis_tvalid => lp_valid, m_axis_tready => '1', m_axis_tdata => lp_data, m_axis_tlast => lp_last
    );

  fir_i: entity raddsp.raddsp_axis_fir
    generic map (
      DEVICE_FAMILY => DSP48_FAMILY,
      DATA_WIDTH => 16,
      TAP_WIDTH => 18,
      TAP_COUNT => 4,
      COEFF_FRAC_BITS => 15,
      IMPLEMENTATION => "sequential_mac",
      DSP_LANES => FIR_DSP_LANES
    )
    port map (
      clk => aclk, rst => dsp_rst, clear_i => dsp_clear, taps_i => fir_taps,
      s_axis_tvalid => lp_p_valid, s_axis_tready => open, s_axis_tdata => lp_p_data, s_axis_tlast => lp_p_last,
      m_axis_tvalid => fir_valid, m_axis_tready => '1', m_axis_tdata => fir_data, m_axis_tlast => fir_last
    );

  biquad_i: entity raddsp.raddsp_axis_biquad
    generic map (
      DEVICE_FAMILY => DSP48_FAMILY,
      DATA_WIDTH => 16,
      COEFF_WIDTH => 18,
      COEFF_FRAC_BITS => 15,
      IMPLEMENTATION => "sequential_mac",
      DSP_LANES => BIQUAD_DSP_LANES
    )
    port map (
      clk => aclk, rst => dsp_rst, clear_i => dsp_clear,
      b0_i => dsp_rw(8)(17 downto 0), b1_i => dsp_rw(9)(17 downto 0), b2_i => dsp_rw(10)(17 downto 0),
      a1_i => dsp_rw(11)(17 downto 0), a2_i => dsp_rw(12)(17 downto 0),
      s_axis_tvalid => fir_p_valid, s_axis_tready => open, s_axis_tdata => fir_p_data, s_axis_tlast => fir_p_last,
      m_axis_tvalid => biquad_valid, m_axis_tready => '1', m_axis_tdata => biquad_data, m_axis_tlast => biquad_last
    );

  dds_i: entity raddsp.raddsp_axis_dds
    generic map (DATA_WIDTH => 16, PHASE_WIDTH => 32, LUT_ADDR_WIDTH => 4, FRAME_LENGTH => 16)
    port map (
      clk => aclk, rst => dsp_rst, enable_i => dsp_enable, phase_reset_i => dsp_clear,
      phase_inc_i => dsp_rw(13), phase_offset_i => dsp_rw(14),
      wav_wr_en_i => dsp_rw(15)(0), wav_wr_addr_i => dsp_rw(16)(3 downto 0), wav_wr_data_i => dsp_rw(17)(15 downto 0),
      m_axis_tvalid => dds_valid, m_axis_tready => '1', m_axis_tdata => dds_data, m_axis_tlast => dds_last,
      phase_o => dds_phase, lut_addr_o => dds_lut_addr
    );

  iq_mag_i: entity raddsp.raddsp_axis_iq_magnitude_sq
    generic map (
      DEVICE_FAMILY => DSP48_FAMILY,
      DATA_WIDTH => 16,
      MAG_WIDTH => 32
    )
    port map (
      clk => aclk, rst => dsp_rst,
      s_axis_tvalid => gain_p_valid and dds_p_valid, s_axis_tready => open, s_axis_tdata => gain_p_data & dds_p_data, s_axis_tlast => gain_p_last or dds_p_last,
      m_axis_tvalid => iq_valid, m_axis_tready => '1', m_axis_tdata => iq_data, m_axis_tlast => iq_last
    );

  stats_i: entity raddsp.raddsp_axis_frame_stats
    generic map (
      DEVICE_FAMILY => DSP48_FAMILY,
      DATA_WIDTH => 16,
      COUNT_WIDTH => 32,
      POWER_WIDTH => 64
    )
    port map (
      clk => aclk, rst => dsp_rst, clear_i => dsp_clear,
      s_axis_tvalid => biquad_p_valid, s_axis_tready => open, s_axis_tdata => biquad_p_data, s_axis_tlast => biquad_p_last,
      m_axis_tvalid => open, m_axis_tready => '1', m_axis_tdata => open, m_axis_tlast => open,
      stats_valid_o => stats_valid, peak_o => stats_peak, sum_squares_o => stats_power, sample_count_o => stats_count
    );

  matrix_elementwise_i: entity raddsp.raddsp_axis_matrix_elementwise
    generic map (
      DEVICE_FAMILY => DSP48_FAMILY,
      DATA_WIDTH => 16,
      COEFF_FRAC_BITS => 15
    )
    port map (
      clk => aclk, rst => dsp_rst, op_i => dsp_rw(18)(1 downto 0),
      s0_axis_tvalid => sample_valid, s0_axis_tready => open, s0_axis_tdata => sample_a, s0_axis_tlast => sample_last,
      s1_axis_tvalid => sample_valid, s1_axis_tready => open, s1_axis_tdata => sample_b, s1_axis_tlast => sample_last,
      m_axis_tvalid => mat_valid, m_axis_tready => '1', m_axis_tdata => mat_data, m_axis_tlast => mat_last
    );

  matrix_dot_i: entity raddsp.raddsp_axis_matrix_dot
    generic map (
      DEVICE_FAMILY => DSP48_FAMILY,
      DATA_WIDTH => 16,
      ACC_WIDTH => 48,
      COEFF_FRAC_BITS => 15
    )
    port map (
      clk => aclk, rst => dsp_rst, clear_i => dsp_clear,
      s0_axis_tvalid => sample_valid, s0_axis_tready => open, s0_axis_tdata => sample_a, s0_axis_tlast => sample_last,
      s1_axis_tvalid => sample_valid, s1_axis_tready => open, s1_axis_tdata => sample_b, s1_axis_tlast => sample_last,
      m_axis_tvalid => dot_valid, m_axis_tready => '1', m_axis_tdata => dot_data, m_axis_tlast => open, sample_count_o => dot_count
    );
end architecture;
