set RADHDL_BOARD_NAME "kria_k26"
set RADHDL_BOARD_DISPLAY_NAME "AMD Kria K26 SOM"
set RADHDL_PART "xck26-sfvc784-2LV-c"
set RADHDL_PRODUCT_SERIES_TAG "ZYNQ_USPLUS"
set RADHDL_DSP48_FAMILY "ultrascaleplus"
set RADHDL_CLOCK_PERIOD_NS 5.000
set RADHDL_DMA_DATA_WIDTH 128
set RADHDL_AXI_MASTER_HINT "AXI-Lite: ZynqMP M_AXI_HPM*_FPD or M_AXI_HPM*_LPD; DMA: ZynqMP S_AXI_HP*/HPC* 128-bit"
set RADHDL_HAS_URAM 1
