set RADHDL_BOARD_NAME "zynq_usplus_zu9eg_uram"
set RADHDL_BOARD_DISPLAY_NAME "Generic Zynq UltraScale+ ZU9EG URAM Target"
set RADHDL_PART "xczu9eg-ffvb1156-2-e"
set RADHDL_PRODUCT_SERIES_TAG "ZYNQ_USPLUS"
set RADHDL_DSP48_FAMILY "ultrascaleplus"
set RADHDL_CLOCK_PERIOD_NS 5.000
set RADHDL_DMA_DATA_WIDTH 128
set RADHDL_AXI_MASTER_HINT "AXI-Lite: ZynqMP M_AXI_HPM*_FPD or M_AXI_HPM*_LPD; DMA: ZynqMP S_AXI_HP*/HPC* 128-bit"
set RADHDL_HAS_URAM 1
