set RADHDL_BOARD_NAME "zynq_usplus_zu3eg"
set RADHDL_BOARD_DISPLAY_NAME "Generic Zynq UltraScale+ ZU3EG"
set RADHDL_PART "xczu3eg-sfvc784-1-e"
set RADHDL_PRODUCT_SERIES_TAG "ZYNQ_USPLUS"
set RADHDL_DSP48_FAMILY "ultrascaleplus"
set RADHDL_CLOCK_PERIOD_NS 6.667
set RADHDL_DMA_DATA_WIDTH 128
set RADHDL_AXI_MASTER_HINT "AXI-Lite: ZynqMP M_AXI_HPM*_FPD or M_AXI_HPM*_LPD; DMA: ZynqMP S_AXI_HP*/HPC* 128-bit"
