library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Top-level AXI-stream RadFFT block.
-- Routes streaming frames through the configured RadDSP FFT implementation and returns ordered frequency-domain samples.
entity raddsp_axis_radfft is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR               : string := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY        : string := "ultrascale+";
    -- Sets the transform, frame, or vector size used by the datapath.
    G_POINTS             : positive := 16;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_MAX_POINTS         : positive := 2048;
    -- Configures G RADIX for this instance.
    G_RADIX              : positive := 2;
    -- Configures G PIPELINED STREAMING for this instance.
    G_PIPELINED_STREAMING : boolean := false;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_INVERSE_FFT        : boolean := false;
    -- Sets the bit width for G INPUT WIDTH values carried by this module.
    G_INPUT_WIDTH        : positive := 16;
    -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
    G_TWIDDLE_WIDTH      : positive := 16;
    -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
    G_OUTPUT_WIDTH       : positive := 32;
    -- Configures G SCALE EACH STAGE for this instance.
    G_SCALE_EACH_STAGE   : boolean := true;
    -- Configures G MEMORY STYLE for this instance.
    G_MEMORY_STYLE       : string := "block";
    -- Configures G TWIDDLE MEMORY STYLE for this instance.
    G_TWIDDLE_MEMORY_STYLE : string := "block";
    -- Configures G TWIDDLE INIT FILE for this instance.
    G_TWIDDLE_INIT_FILE  : string := "none";
    -- Configures G EXTERNAL TWIDDLES for this instance.
    G_EXTERNAL_TWIDDLES  : boolean := false;
    -- Sets the number of parallel sample lanes processed per handshake beat.
    G_MULTIPLIER_LANES   : positive := 1;
    -- Sets the number of parallel sample lanes processed per handshake beat.
    G_MAX_MULTIPLIER_LANES : positive := 8;
    -- Sets the width or count of samples handled by the datapath.
    G_MEMORY_WORD_SAMPLES : positive := 1
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk          : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst          : in  std_logic;
    -- Input AXI-stream valid qualifier for the current sample beat.
    s_axis_tvalid : in  std_logic;
    -- Input AXI-stream ready response indicating this block can accept a beat.
    s_axis_tready : out std_logic;
    -- Input AXI-stream payload containing packed sample or feature lanes.
    s_axis_tdata  : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
    -- Input AXI-stream frame marker for the final beat of a frame.
    s_axis_tlast  : in  std_logic;
    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready : in  std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata  : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast  : out std_logic;
    -- Input runtime inverse i signal for this module.
    runtime_inverse_i : in std_logic := '0';
    -- Output twiddle addr o signal generated by this module.
    twiddle_addr_o : out std_logic_vector(31 downto 0);
    -- Input twiddle re i signal for this module.
    twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Input twiddle im i signal for this module.
    twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Output busy o signal generated by this module.
    busy_o          : out std_logic;
    -- Output frame done o signal generated by this module.
    frame_done_o    : out std_logic
  );
end entity;

architecture rtl of raddsp_axis_radfft is
  function is_power_of_two(value : positive) return boolean is
    variable v : positive := value;
  begin
    while (v mod 2) = 0 loop
      v := v / 2;
    end loop;
    return v = 1;
  end function;

  function is_power_of_four(value : positive) return boolean is
    variable v : positive := value;
  begin
    while (v mod 4) = 0 loop
      v := v / 4;
    end loop;
    return v = 1;
  end function;
begin
  assert G_POINTS <= G_MAX_POINTS report "RADFFT G_POINTS must not exceed G_MAX_POINTS" severity failure;
  assert is_power_of_two(G_POINTS) report "RADFFT G_POINTS must be a power of two" severity failure;
  assert G_RADIX = 2 or G_RADIX = 4 report "RADFFT G_RADIX must be 2 or 4" severity failure;
  assert G_RADIX = 2 or is_power_of_four(G_POINTS) report "RADFFT G_RADIX=4 requires points to be a power of four" severity failure;
  assert G_INPUT_WIDTH <= 32 report "RADFFT G_INPUT_WIDTH maximum supported value is 32" severity failure;
  assert G_OUTPUT_WIDTH <= 32 report "RADFFT G_OUTPUT_WIDTH maximum supported value is 32" severity failure;
  assert G_TWIDDLE_WIDTH <= 30 report "RADFFT G_TWIDDLE_WIDTH maximum supported value is 30" severity failure;
  assert G_MULTIPLIER_LANES <= G_MAX_MULTIPLIER_LANES report "RADFFT G_MULTIPLIER_LANES must not exceed G_MAX_MULTIPLIER_LANES" severity failure;
  assert G_MAX_MULTIPLIER_LANES <= 16 report "RADFFT G_MAX_MULTIPLIER_LANES maximum supported value is 16" severity failure;
  assert G_MEMORY_WORD_SAMPLES = 1 or G_MEMORY_WORD_SAMPLES = 2 or G_MEMORY_WORD_SAMPLES = 4
    report "RADFFT G_MEMORY_WORD_SAMPLES must be 1, 2, or 4"
    severity failure;
  assert G_MEMORY_STYLE = "auto" or G_MEMORY_STYLE = "block" or G_MEMORY_STYLE = "distributed" or G_MEMORY_STYLE = "ultra"
    report "RADFFT G_MEMORY_STYLE must be auto, block, distributed, or ultra"
    severity failure;

  gen_batch_radix2 : if (not G_PIPELINED_STREAMING) and G_RADIX = 2 generate
  begin
    fft_i: entity work.raddsp_axis_radfft_radix2_tdp
      generic map (
        VENDOR => VENDOR,
        DEVICE_FAMILY => DEVICE_FAMILY,
        G_POINTS => G_POINTS,
        G_MAX_POINTS => G_MAX_POINTS,
        G_INVERSE_FFT => G_INVERSE_FFT,
        G_INPUT_WIDTH => G_INPUT_WIDTH,
        G_TWIDDLE_WIDTH => G_TWIDDLE_WIDTH,
        G_OUTPUT_WIDTH => G_OUTPUT_WIDTH,
        G_SCALE_EACH_STAGE => G_SCALE_EACH_STAGE,
        G_MEMORY_STYLE => G_MEMORY_STYLE,
        G_TWIDDLE_MEMORY_STYLE => G_TWIDDLE_MEMORY_STYLE,
        G_TWIDDLE_INIT_FILE => G_TWIDDLE_INIT_FILE,
        G_EXTERNAL_TWIDDLES => G_EXTERNAL_TWIDDLES,
        G_MEMORY_WORD_SAMPLES => G_MEMORY_WORD_SAMPLES
      )
      port map (
        clk => clk,
        rst => rst,
        s_axis_tvalid => s_axis_tvalid,
        s_axis_tready => s_axis_tready,
        s_axis_tdata => s_axis_tdata,
        s_axis_tlast => s_axis_tlast,
        m_axis_tvalid => m_axis_tvalid,
        m_axis_tready => m_axis_tready,
        m_axis_tdata => m_axis_tdata,
        m_axis_tlast => m_axis_tlast,
        runtime_inverse_i => runtime_inverse_i,
        twiddle_addr_o => twiddle_addr_o,
        twiddle_re_i => twiddle_re_i,
        twiddle_im_i => twiddle_im_i,
        busy_o => busy_o,
        frame_done_o => frame_done_o
      );
  end generate;

  gen_batch_radix4 : if (not G_PIPELINED_STREAMING) and G_RADIX = 4 generate
  begin
    fft_i: entity work.raddsp_axis_radfft_radix4_tdp
      generic map (
        VENDOR => VENDOR,
        DEVICE_FAMILY => DEVICE_FAMILY,
        G_POINTS => G_POINTS,
        G_MAX_POINTS => G_MAX_POINTS,
        G_INVERSE_FFT => G_INVERSE_FFT,
        G_INPUT_WIDTH => G_INPUT_WIDTH,
        G_TWIDDLE_WIDTH => G_TWIDDLE_WIDTH,
        G_OUTPUT_WIDTH => G_OUTPUT_WIDTH,
        G_SCALE_EACH_STAGE => G_SCALE_EACH_STAGE,
        G_MEMORY_STYLE => G_MEMORY_STYLE,
        G_TWIDDLE_MEMORY_STYLE => G_TWIDDLE_MEMORY_STYLE,
        G_TWIDDLE_INIT_FILE => G_TWIDDLE_INIT_FILE,
        G_EXTERNAL_TWIDDLES => G_EXTERNAL_TWIDDLES,
        G_MEMORY_WORD_SAMPLES => G_MEMORY_WORD_SAMPLES
      )
      port map (
        clk => clk,
        rst => rst,
        s_axis_tvalid => s_axis_tvalid,
        s_axis_tready => s_axis_tready,
        s_axis_tdata => s_axis_tdata,
        s_axis_tlast => s_axis_tlast,
        m_axis_tvalid => m_axis_tvalid,
        m_axis_tready => m_axis_tready,
        m_axis_tdata => m_axis_tdata,
        m_axis_tlast => m_axis_tlast,
        twiddle_addr_o => twiddle_addr_o,
        twiddle_re_i => twiddle_re_i,
        twiddle_im_i => twiddle_im_i,
        busy_o => busy_o,
        frame_done_o => frame_done_o
      );
  end generate;

  gen_streaming : if G_PIPELINED_STREAMING generate
  begin
    fft_i: entity work.raddsp_axis_radfft_streaming
      generic map (
        VENDOR => VENDOR,
        DEVICE_FAMILY => DEVICE_FAMILY,
        G_POINTS => G_POINTS,
        G_MAX_POINTS => G_MAX_POINTS,
        G_RADIX => G_RADIX,
        G_INVERSE_FFT => G_INVERSE_FFT,
        G_INPUT_WIDTH => G_INPUT_WIDTH,
        G_TWIDDLE_WIDTH => G_TWIDDLE_WIDTH,
        G_OUTPUT_WIDTH => G_OUTPUT_WIDTH,
        G_SCALE_EACH_STAGE => G_SCALE_EACH_STAGE,
        G_MEMORY_STYLE => G_MEMORY_STYLE,
        G_OVERLAP_FRAMES => true,
        G_MULTIPLIER_LANES => G_MULTIPLIER_LANES,
        G_MAX_MULTIPLIER_LANES => G_MAX_MULTIPLIER_LANES
      )
      port map (
        clk => clk,
        rst => rst,
        s_axis_tvalid => s_axis_tvalid,
        s_axis_tready => s_axis_tready,
        s_axis_tdata => s_axis_tdata,
        s_axis_tlast => s_axis_tlast,
        m_axis_tvalid => m_axis_tvalid,
        m_axis_tready => m_axis_tready,
        m_axis_tdata => m_axis_tdata,
        m_axis_tlast => m_axis_tlast,
        twiddle_addr_o => twiddle_addr_o,
        twiddle_re_i => twiddle_re_i,
        twiddle_im_i => twiddle_im_i,
        busy_o => busy_o,
        frame_done_o => frame_done_o
      );
  end generate;
end architecture;
