library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library raddsp;
use raddsp.raddsp_axis_pkg.all;

-- AXI-stream frame statistics accumulator.
-- Computes per-frame metrics such as count, extrema, and energy-style summaries while preserving stream boundaries.
entity raddsp_axis_frame_stats is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR       : string  := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY : string := "generic";
    -- Sets the bit width for DATA WIDTH values carried by this module.
    DATA_WIDTH   : positive := 16;
    -- Sets the bit width for COUNT WIDTH values carried by this module.
    COUNT_WIDTH  : positive := 32;
    -- Sets the bit width for POWER WIDTH values carried by this module.
    POWER_WIDTH  : positive := 64
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk             : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst             : in  std_logic;
    -- Input clear i signal for this module.
    clear_i         : in  std_logic;
    -- Input AXI-stream valid qualifier for the current sample beat.
    s_axis_tvalid   : in  std_logic;
    -- Input AXI-stream ready response indicating this block can accept a beat.
    s_axis_tready   : out std_logic;
    -- Input AXI-stream payload containing packed sample or feature lanes.
    s_axis_tdata    : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Input AXI-stream frame marker for the final beat of a frame.
    s_axis_tlast    : in  std_logic;
    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid   : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready   : in  std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata    : out std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast    : out std_logic;
    -- Output valid qualifier aligned with the produced result.
    stats_valid_o   : out std_logic;
    -- Output peak o signal generated by this module.
    peak_o          : out std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Output sum squares o signal generated by this module.
    sum_squares_o   : out std_logic_vector(POWER_WIDTH - 1 downto 0);
    -- Output sample vector or current sample status from the datapath.
    sample_count_o  : out std_logic_vector(COUNT_WIDTH - 1 downto 0)
  );
end entity;

architecture rtl of raddsp_axis_frame_stats is
begin
  gen_xilinx_vendor : if VENDOR = "xilinx" or VENDOR = "XILINX" generate
    signal out_valid_r : std_logic := '0';
    signal out_data_r  : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
    signal out_last_r  : std_logic := '0';
    signal ready_i     : std_logic;
    signal peak_r      : unsigned(DATA_WIDTH - 1 downto 0) := (others => '0');
    signal power_r     : unsigned(POWER_WIDTH - 1 downto 0) := (others => '0');
    signal count_r     : unsigned(COUNT_WIDTH - 1 downto 0) := (others => '0');
    signal peak_out_r  : unsigned(DATA_WIDTH - 1 downto 0) := (others => '0');
    signal power_out_r : unsigned(POWER_WIDTH - 1 downto 0) := (others => '0');
    signal count_out_r : unsigned(COUNT_WIDTH - 1 downto 0) := (others => '0');
    signal stats_v_r   : std_logic := '0';
    signal busy_r      : std_logic := '0';
    signal sample_r    : signed(DATA_WIDTH - 1 downto 0) := (others => '0');
    signal sample_out_r : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
    signal abs_r       : unsigned(DATA_WIDTH - 1 downto 0) := (others => '0');
    signal last_r      : std_logic := '0';
    signal mul_valid   : std_logic := '0';
    signal mul_p       : signed(47 downto 0);
    signal mul_p_valid : std_logic;
    signal unused_sub  : std_logic;
    signal unused_last : std_logic;
  begin
    assert DATA_WIDTH <= 18
      report "DSP48 frame stats square supports DATA_WIDTH <= 18"
      severity failure;

    ready_i <= '1' when busy_r = '0' and (out_valid_r = '0' or m_axis_tready = '1') else '0';
    s_axis_tready <= ready_i;
    m_axis_tvalid <= out_valid_r;
    m_axis_tdata <= out_data_r;
    m_axis_tlast <= out_last_r;
    stats_valid_o <= stats_v_r;
    peak_o <= std_logic_vector(peak_out_r);
    sum_squares_o <= std_logic_vector(power_out_r);
    sample_count_o <= std_logic_vector(count_out_r);

    square_i: entity raddsp.raddsp_xilinx_dsp48_mul
      generic map (
        DEVICE_FAMILY => DEVICE_FAMILY,
        A_WIDTH => DATA_WIDTH,
        B_WIDTH => DATA_WIDTH
      )
      port map (
        clk => clk,
        rst => rst,
        valid_i => mul_valid,
        subtract_i => '0',
        last_i => last_r,
        a_i => sample_r,
        b_i => sample_r,
        valid_o => mul_p_valid,
        subtract_o => unused_sub,
        last_o => unused_last,
        p_o => mul_p
      );

    process(clk)
      variable next_peak  : unsigned(DATA_WIDTH - 1 downto 0);
      variable next_power : unsigned(POWER_WIDTH - 1 downto 0);
      variable next_count : unsigned(COUNT_WIDTH - 1 downto 0);
      variable abs_v      : unsigned(DATA_WIDTH - 1 downto 0);
      variable sample_i   : integer;
    begin
      if rising_edge(clk) then
        stats_v_r <= '0';

        if rst = '1' then
          out_valid_r <= '0';
          out_data_r <= (others => '0');
          out_last_r <= '0';
          peak_r <= (others => '0');
          power_r <= (others => '0');
          count_r <= (others => '0');
          peak_out_r <= (others => '0');
          power_out_r <= (others => '0');
          count_out_r <= (others => '0');
          busy_r <= '0';
          sample_r <= (others => '0');
          sample_out_r <= (others => '0');
          abs_r <= (others => '0');
          last_r <= '0';
          mul_valid <= '0';
        else
          mul_valid <= '0';

          if clear_i = '1' then
            peak_r <= (others => '0');
            power_r <= (others => '0');
            count_r <= (others => '0');
          end if;

          if out_valid_r = '1' and m_axis_tready = '1' then
            out_valid_r <= '0';
          end if;

          if mul_p_valid = '1' then
            next_peak := peak_r;
            if abs_r > peak_r then
              next_peak := abs_r;
            end if;
            next_power := power_r + resize(unsigned(mul_p), POWER_WIDTH);
            next_count := count_r + 1;
            peak_r <= next_peak;
            power_r <= next_power;
            count_r <= next_count;

            out_valid_r <= '1';
            out_data_r <= sample_out_r;
            out_last_r <= unused_last;
            busy_r <= '0';

            if unused_last = '1' then
              peak_out_r <= next_peak;
              power_out_r <= next_power;
              count_out_r <= next_count;
              stats_v_r <= '1';
              peak_r <= (others => '0');
              power_r <= (others => '0');
              count_r <= (others => '0');
            end if;
          end if;

          if clear_i = '0' and s_axis_tvalid = '1' and ready_i = '1' then
            sample_i := to_integer(signed(s_axis_tdata));
            abs_v := to_unsigned(raddsp_abs_int(sample_i), DATA_WIDTH);
            sample_r <= signed(s_axis_tdata);
            sample_out_r <= s_axis_tdata;
            abs_r <= abs_v;
            last_r <= s_axis_tlast;
            mul_valid <= '1';
            busy_r <= '1';
          end if;
        end if;
      end if;
    end process;
  end generate;

  gen_generic_vendor : if VENDOR /= "xilinx" and VENDOR /= "XILINX" generate
    signal out_valid_r : std_logic := '0';
    signal out_data_r  : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
    signal out_last_r  : std_logic := '0';
    signal ready_i     : std_logic;
    signal peak_r      : unsigned(DATA_WIDTH - 1 downto 0) := (others => '0');
    signal power_r     : unsigned(POWER_WIDTH - 1 downto 0) := (others => '0');
    signal count_r     : unsigned(COUNT_WIDTH - 1 downto 0) := (others => '0');
    signal peak_out_r  : unsigned(DATA_WIDTH - 1 downto 0) := (others => '0');
    signal power_out_r : unsigned(POWER_WIDTH - 1 downto 0) := (others => '0');
    signal count_out_r : unsigned(COUNT_WIDTH - 1 downto 0) := (others => '0');
    signal stats_v_r   : std_logic := '0';
  begin
    ready_i <= (not out_valid_r) or m_axis_tready;
    s_axis_tready <= ready_i;
    m_axis_tvalid <= out_valid_r;
    m_axis_tdata <= out_data_r;
    m_axis_tlast <= out_last_r;
    stats_valid_o <= stats_v_r;
    peak_o <= std_logic_vector(peak_out_r);
    sum_squares_o <= std_logic_vector(power_out_r);
    sample_count_o <= std_logic_vector(count_out_r);

    process(clk)
      variable sample_i : integer;
      variable abs_i    : integer;
      variable sq_v     : unsigned((2 * DATA_WIDTH) - 1 downto 0);
      variable next_peak : unsigned(DATA_WIDTH - 1 downto 0);
      variable next_power : unsigned(POWER_WIDTH - 1 downto 0);
      variable next_count : unsigned(COUNT_WIDTH - 1 downto 0);
    begin
      if rising_edge(clk) then
        stats_v_r <= '0';

        if rst = '1' then
          out_valid_r <= '0';
          out_data_r <= (others => '0');
          out_last_r <= '0';
          peak_r <= (others => '0');
          power_r <= (others => '0');
          count_r <= (others => '0');
          peak_out_r <= (others => '0');
          power_out_r <= (others => '0');
          count_out_r <= (others => '0');
        else
          if clear_i = '1' then
            peak_r <= (others => '0');
            power_r <= (others => '0');
            count_r <= (others => '0');
          end if;

          if ready_i = '1' then
            out_valid_r <= s_axis_tvalid;
            out_data_r <= s_axis_tdata;
            out_last_r <= s_axis_tlast;
            if s_axis_tvalid = '1' then
              sample_i := to_integer(signed(s_axis_tdata));
              abs_i := raddsp_abs_int(sample_i);
              sq_v := unsigned(to_signed(sample_i * sample_i, sq_v'length));
              next_peak := peak_r;
              if abs_i > to_integer(peak_r) then
                next_peak := to_unsigned(abs_i, DATA_WIDTH);
              end if;
              next_power := power_r + resize(sq_v, POWER_WIDTH);
              next_count := count_r + 1;
              peak_r <= next_peak;
              power_r <= next_power;
              count_r <= next_count;

              if s_axis_tlast = '1' then
                peak_out_r <= next_peak;
                power_out_r <= next_power;
                count_out_r <= next_count;
                stats_v_r <= '1';
                peak_r <= (others => '0');
                power_r <= (others => '0');
                count_r <= (others => '0');
              end if;
            end if;
          end if;
        end if;
      end if;
    end process;
  end generate;
end architecture;
