library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library xpm;
use xpm.vcomponents.all;

-- AXI-stream fingerprint matcher for spectral feature vectors.
-- Compares incoming fingerprint data against reference features and emits match scores for recognition pipelines.
entity raddsp_axis_fingerprint_matcher is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR           : string := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY    : string := "generic";
    -- Sets the bit width for HASH WIDTH values carried by this module.
    HASH_WIDTH       : positive := 64;
    -- Sets the bit width for META WIDTH values carried by this module.
    META_WIDTH       : positive := 32;
    -- Sets the bit width for TABLE ADDR WIDTH values carried by this module.
    TABLE_ADDR_WIDTH : positive := 10;
    -- Sets the bit width for AXI ADDR WIDTH values carried by this module.
    AXI_ADDR_WIDTH   : positive := 8;
    -- Sets the bit width for AXI DATA WIDTH values carried by this module.
    AXI_DATA_WIDTH   : positive := 32;
    -- Configures MEMORY STYLE for this instance.
    MEMORY_STYLE     : string := "block"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk           : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst           : in  std_logic;

    -- Input AXI-stream valid qualifier for the current sample beat.
    s_axis_tvalid : in  std_logic;
    -- Input AXI-stream ready response indicating this block can accept a beat.
    s_axis_tready : out std_logic;
    -- Input AXI-stream payload containing packed sample or feature lanes.
    s_axis_tdata  : in  std_logic_vector(HASH_WIDTH + 64 - 1 downto 0);
    -- Input AXI-stream frame marker for the final beat of a frame.
    s_axis_tlast  : in  std_logic;

    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready : in  std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata  : out std_logic_vector(HASH_WIDTH + META_WIDTH + 32 - 1 downto 0);
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast  : out std_logic;

    -- Output match irq o signal generated by this module.
    match_irq_o   : out std_logic;

    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awaddr  : in  std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awprot  : in  std_logic_vector(2 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awvalid : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awready : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wdata   : in  std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wstrb   : in  std_logic_vector((AXI_DATA_WIDTH / 8) - 1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wvalid  : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wready  : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_bresp   : out std_logic_vector(1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_bvalid  : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_bready  : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_araddr  : in  std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_arprot  : in  std_logic_vector(2 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_arvalid : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_arready : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rdata   : out std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rresp   : out std_logic_vector(1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rvalid  : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rready  : in  std_logic
  );
end entity;

architecture rtl of raddsp_axis_fingerprint_matcher is
  constant C_REG_CTRL         : natural := 16#00#;
  constant C_REG_LOAD_ADDR    : natural := 16#04#;
  constant C_REG_LOAD_HASH_LO : natural := 16#08#;
  constant C_REG_LOAD_HASH_HI : natural := 16#0C#;
  constant C_REG_LOAD_META    : natural := 16#10#;
  constant C_REG_COMMAND      : natural := 16#14#;
  constant C_REG_MASK_LO      : natural := 16#18#;
  constant C_REG_MASK_HI      : natural := 16#1C#;
  constant C_REG_STATUS       : natural := 16#20#;
  constant C_REG_LAST_HASH_LO : natural := 16#24#;
  constant C_REG_LAST_HASH_HI : natural := 16#28#;
  constant C_REG_LAST_META    : natural := 16#2C#;
  constant C_REG_LAST_BUCKET  : natural := 16#30#;
  constant C_REG_MATCH_COUNT  : natural := 16#34#;
  constant C_REG_TABLE_SIZE   : natural := 16#38#;

  constant C_TABLE_DEPTH : positive := 2 ** TABLE_ADDR_WIDTH;
  constant C_ENTRY_WIDTH : positive := 1 + META_WIDTH + HASH_WIDTH;

  signal enable_r        : std_logic := '0';
  signal irq_enable_r    : std_logic := '0';
  signal load_addr_r     : unsigned(TABLE_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal load_hash_r     : unsigned(HASH_WIDTH - 1 downto 0) := (others => '0');
  signal load_meta_r     : unsigned(META_WIDTH - 1 downto 0) := (others => '0');
  signal match_mask_r    : unsigned(HASH_WIDTH - 1 downto 0) := (others => '1');

  signal mem_wr_en       : std_logic := '0';
  signal mem_wr_addr     : std_logic_vector(TABLE_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal mem_wr_data     : std_logic_vector(C_ENTRY_WIDTH - 1 downto 0) := (others => '0');
  signal mem_rd_addr     : std_logic_vector(TABLE_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal mem_rd_data     : std_logic_vector(C_ENTRY_WIDTH - 1 downto 0);

  signal pending_r       : std_logic := '0';
  signal pending_data_r  : std_logic := '0';
  signal pending_hash_r  : unsigned(HASH_WIDTH - 1 downto 0) := (others => '0');
  signal pending_bucket_r : unsigned(TABLE_ADDR_WIDTH - 1 downto 0) := (others => '0');

  signal out_valid_r     : std_logic := '0';
  signal out_data_r      : std_logic_vector(HASH_WIDTH + META_WIDTH + 32 - 1 downto 0) := (others => '0');
  signal irq_r           : std_logic := '0';
  signal last_hash_r     : unsigned(HASH_WIDTH - 1 downto 0) := (others => '0');
  signal last_meta_r     : unsigned(META_WIDTH - 1 downto 0) := (others => '0');
  signal last_bucket_r   : unsigned(TABLE_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal match_count_r   : unsigned(31 downto 0) := (others => '0');

  signal awready_r       : std_logic := '0';
  signal wready_r        : std_logic := '0';
  signal bvalid_r        : std_logic := '0';
  signal arready_r       : std_logic := '0';
  signal rvalid_r        : std_logic := '0';
  signal rdata_r         : std_logic_vector(AXI_DATA_WIDTH - 1 downto 0) := (others => '0');

  function axi_word_addr(addr : std_logic_vector) return natural is
    variable a : unsigned(addr'length - 1 downto 0) := unsigned(addr);
  begin
    return to_integer(a(a'high downto 2) & "00");
  end function;

  function low_word(value : unsigned) return std_logic_vector is
    variable result : std_logic_vector(31 downto 0) := (others => '0');
  begin
    if value'length >= 32 then
      result := std_logic_vector(value(31 downto 0));
    else
      result(value'length - 1 downto 0) := std_logic_vector(value);
    end if;
    return result;
  end function;

  function high_word(value : unsigned) return std_logic_vector is
    variable result : std_logic_vector(31 downto 0) := (others => '0');
  begin
    if value'length > 32 then
      if value'length >= 64 then
        result := std_logic_vector(value(63 downto 32));
      else
        result(value'length - 33 downto 0) := std_logic_vector(value(value'length - 1 downto 32));
      end if;
    end if;
    return result;
  end function;

begin
  assert HASH_WIDTH = 32 or HASH_WIDTH = 64
    report "raddsp_axis_fingerprint_matcher HASH_WIDTH must be 32 or 64"
    severity failure;
  assert AXI_DATA_WIDTH = 32
    report "raddsp_axis_fingerprint_matcher currently supports 32-bit AXI-Lite data"
    severity failure;
  assert MEMORY_STYLE = "auto" or MEMORY_STYLE = "block" or MEMORY_STYLE = "distributed" or MEMORY_STYLE = "ultra"
    report "raddsp_axis_fingerprint_matcher MEMORY_STYLE must be auto, block, distributed, or ultra"
    severity failure;

  s_axis_tready <= '1' when enable_r = '1' and pending_r = '0' and out_valid_r = '0' else '0';
  m_axis_tvalid <= out_valid_r;
  m_axis_tdata <= out_data_r;
  m_axis_tlast <= out_valid_r;
  match_irq_o <= irq_r;

  s_axi_awready <= awready_r;
  s_axi_wready <= wready_r;
  s_axi_bresp <= "00";
  s_axi_bvalid <= bvalid_r;
  s_axi_arready <= arready_r;
  s_axi_rdata <= rdata_r;
  s_axi_rresp <= "00";
  s_axi_rvalid <= rvalid_r;

  gen_xilinx_mem : if VENDOR = "xilinx" or VENDOR = "XILINX" generate
    signal wea_v : std_logic_vector(0 downto 0);
  begin
    wea_v(0) <= mem_wr_en;
    mem_i: xpm_memory_sdpram
      generic map (
        MEMORY_SIZE => C_ENTRY_WIDTH * C_TABLE_DEPTH,
        MEMORY_PRIMITIVE => MEMORY_STYLE,
        CLOCKING_MODE => "common_clock",
        ECC_MODE => "no_ecc",
        MEMORY_INIT_FILE => "none",
        MEMORY_INIT_PARAM => "0",
        USE_MEM_INIT => 1,
        WAKEUP_TIME => "disable_sleep",
        MESSAGE_CONTROL => 0,
        MEMORY_OPTIMIZATION => "true",
        CASCADE_HEIGHT => 0,
        WRITE_DATA_WIDTH_A => C_ENTRY_WIDTH,
        BYTE_WRITE_WIDTH_A => C_ENTRY_WIDTH,
        ADDR_WIDTH_A => TABLE_ADDR_WIDTH,
        READ_DATA_WIDTH_B => C_ENTRY_WIDTH,
        ADDR_WIDTH_B => TABLE_ADDR_WIDTH,
        READ_RESET_VALUE_B => "0",
        READ_LATENCY_B => 1,
        WRITE_MODE_B => "read_first",
        RST_MODE_A => "SYNC",
        RST_MODE_B => "SYNC"
      )
      port map (
        sleep => '0',
        clka => clk,
        ena => '1',
        wea => wea_v,
        addra => mem_wr_addr,
        dina => mem_wr_data,
        injectsbiterra => '0',
        injectdbiterra => '0',
        clkb => clk,
        rstb => '0',
        enb => '1',
        regceb => '1',
        addrb => mem_rd_addr,
        doutb => mem_rd_data,
        sbiterrb => open,
        dbiterrb => open
      );
  end generate;

  gen_generic_mem : if VENDOR /= "xilinx" and VENDOR /= "XILINX" generate
    type table_t is array (0 to C_TABLE_DEPTH - 1) of std_logic_vector(C_ENTRY_WIDTH - 1 downto 0);
    signal table_r : table_t := (others => (others => '0'));
    signal rd_data_r : std_logic_vector(C_ENTRY_WIDTH - 1 downto 0) := (others => '0');
  begin
    mem_rd_data <= rd_data_r;
    process(clk)
    begin
      if rising_edge(clk) then
        if mem_wr_en = '1' then
          table_r(to_integer(unsigned(mem_wr_addr))) <= mem_wr_data;
        end if;
        rd_data_r <= table_r(to_integer(unsigned(mem_rd_addr)));
      end if;
    end process;
  end generate;

  process(clk)
    variable wr_addr     : natural;
    variable rd_addr     : natural;
    variable in_hash_v   : unsigned(HASH_WIDTH - 1 downto 0);
    variable stored_valid_v : std_logic;
    variable stored_meta_v  : unsigned(META_WIDTH - 1 downto 0);
    variable stored_hash_v  : unsigned(HASH_WIDTH - 1 downto 0);
    variable diff_v      : unsigned(HASH_WIDTH - 1 downto 0);
    variable bucket32_v  : unsigned(31 downto 0);
  begin
    if rising_edge(clk) then
      awready_r <= '0';
      wready_r <= '0';
      arready_r <= '0';
      mem_wr_en <= '0';
      irq_r <= '0';

      if rst = '1' then
        enable_r <= '0';
        irq_enable_r <= '0';
        load_addr_r <= (others => '0');
        load_hash_r <= (others => '0');
        load_meta_r <= (others => '0');
        match_mask_r <= (others => '1');
        mem_wr_addr <= (others => '0');
        mem_wr_data <= (others => '0');
        mem_rd_addr <= (others => '0');
        pending_r <= '0';
        pending_data_r <= '0';
        pending_hash_r <= (others => '0');
        pending_bucket_r <= (others => '0');
        out_valid_r <= '0';
        out_data_r <= (others => '0');
        last_hash_r <= (others => '0');
        last_meta_r <= (others => '0');
        last_bucket_r <= (others => '0');
        match_count_r <= (others => '0');
        bvalid_r <= '0';
        rvalid_r <= '0';
        rdata_r <= (others => '0');
      else
        if bvalid_r = '1' and s_axi_bready = '1' then
          bvalid_r <= '0';
        end if;
        if rvalid_r = '1' and s_axi_rready = '1' then
          rvalid_r <= '0';
        end if;
        if out_valid_r = '1' and m_axis_tready = '1' then
          out_valid_r <= '0';
        end if;

        if s_axi_awvalid = '1' and s_axi_wvalid = '1' and bvalid_r = '0' then
          awready_r <= '1';
          wready_r <= '1';
          bvalid_r <= '1';
          wr_addr := axi_word_addr(s_axi_awaddr);
          case wr_addr is
            when C_REG_CTRL =>
              enable_r <= s_axi_wdata(0);
              irq_enable_r <= s_axi_wdata(1);
              if s_axi_wdata(2) = '1' then
                match_count_r <= (others => '0');
              end if;
            when C_REG_LOAD_ADDR =>
              load_addr_r <= resize(unsigned(s_axi_wdata), TABLE_ADDR_WIDTH);
            when C_REG_LOAD_HASH_LO =>
              load_hash_r(31 downto 0) <= unsigned(s_axi_wdata);
            when C_REG_LOAD_HASH_HI =>
              if HASH_WIDTH > 32 then
                load_hash_r(HASH_WIDTH - 1 downto 32) <= resize(unsigned(s_axi_wdata), HASH_WIDTH - 32);
              end if;
            when C_REG_LOAD_META =>
              load_meta_r <= resize(unsigned(s_axi_wdata), META_WIDTH);
            when C_REG_COMMAND =>
              if s_axi_wdata(0) = '1' then
                mem_wr_addr <= std_logic_vector(load_addr_r);
                mem_wr_data <= '1' & std_logic_vector(load_meta_r) & std_logic_vector(load_hash_r);
                mem_wr_en <= '1';
              elsif s_axi_wdata(1) = '1' then
                mem_wr_addr <= std_logic_vector(load_addr_r);
                mem_wr_data <= (others => '0');
                mem_wr_en <= '1';
              end if;
            when C_REG_MASK_LO =>
              match_mask_r(31 downto 0) <= unsigned(s_axi_wdata);
            when C_REG_MASK_HI =>
              if HASH_WIDTH > 32 then
                match_mask_r(HASH_WIDTH - 1 downto 32) <= resize(unsigned(s_axi_wdata), HASH_WIDTH - 32);
              end if;
            when others =>
              null;
          end case;
        end if;

        if s_axi_arvalid = '1' and rvalid_r = '0' then
          arready_r <= '1';
          rd_addr := axi_word_addr(s_axi_araddr);
          rdata_r <= (others => '0');
          case rd_addr is
            when C_REG_CTRL =>
              rdata_r(0) <= enable_r;
              rdata_r(1) <= irq_enable_r;
            when C_REG_LOAD_ADDR =>
              rdata_r <= low_word(load_addr_r);
            when C_REG_LOAD_HASH_LO =>
              rdata_r <= low_word(load_hash_r);
            when C_REG_LOAD_HASH_HI =>
              rdata_r <= high_word(load_hash_r);
            when C_REG_LOAD_META =>
              rdata_r <= low_word(load_meta_r);
            when C_REG_MASK_LO =>
              rdata_r <= low_word(match_mask_r);
            when C_REG_MASK_HI =>
              rdata_r <= high_word(match_mask_r);
            when C_REG_STATUS =>
              rdata_r(0) <= pending_r;
              rdata_r(1) <= out_valid_r;
            when C_REG_LAST_HASH_LO =>
              rdata_r <= low_word(last_hash_r);
            when C_REG_LAST_HASH_HI =>
              rdata_r <= high_word(last_hash_r);
            when C_REG_LAST_META =>
              rdata_r <= low_word(last_meta_r);
            when C_REG_LAST_BUCKET =>
              rdata_r <= low_word(last_bucket_r);
            when C_REG_MATCH_COUNT =>
              rdata_r <= std_logic_vector(match_count_r);
            when C_REG_TABLE_SIZE =>
              rdata_r <= std_logic_vector(to_unsigned(C_TABLE_DEPTH, 32));
            when others =>
              null;
          end case;
          rvalid_r <= '1';
        end if;

        if pending_r = '1' and pending_data_r = '0' then
          pending_data_r <= '1';
        elsif pending_r = '1' and pending_data_r = '1' then
          stored_valid_v := mem_rd_data(C_ENTRY_WIDTH - 1);
          stored_meta_v := unsigned(mem_rd_data(C_ENTRY_WIDTH - 2 downto HASH_WIDTH));
          stored_hash_v := unsigned(mem_rd_data(HASH_WIDTH - 1 downto 0));
          diff_v := (stored_hash_v xor pending_hash_r) and match_mask_r;
          if stored_valid_v = '1' and diff_v = 0 then
            last_hash_r <= pending_hash_r;
            last_meta_r <= stored_meta_v;
            last_bucket_r <= pending_bucket_r;
            match_count_r <= match_count_r + 1;
            bucket32_v := resize(pending_bucket_r, 32);
            out_data_r <= std_logic_vector(pending_hash_r) &
                          std_logic_vector(stored_meta_v) &
                          std_logic_vector(bucket32_v);
            out_valid_r <= '1';
            if irq_enable_r = '1' then
              irq_r <= '1';
            end if;
          end if;
          pending_r <= '0';
          pending_data_r <= '0';
        end if;

        if enable_r = '1' and pending_r = '0' and out_valid_r = '0' and s_axis_tvalid = '1' then
          in_hash_v := unsigned(s_axis_tdata(HASH_WIDTH + 64 - 1 downto 64));
          pending_hash_r <= in_hash_v;
          pending_bucket_r <= resize(in_hash_v(TABLE_ADDR_WIDTH - 1 downto 0), TABLE_ADDR_WIDTH);
          mem_rd_addr <= std_logic_vector(in_hash_v(TABLE_ADDR_WIDTH - 1 downto 0));
          pending_r <= '1';
          pending_data_r <= '0';
        end if;
      end if;
    end if;
  end process;
end architecture;
