library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Wide signed multiplication helper built from Xilinx DSP48 resources.
-- Splits operands across DSP slices and recombines partial products for widths beyond a single DSP primitive.
entity raddsp_xilinx_dsp48_wide_mul is
  generic (
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY : string := "7series";
    -- Sets the bit width for A WIDTH values carried by this module.
    A_WIDTH       : positive := 16;
    -- Sets the bit width for B WIDTH values carried by this module.
    B_WIDTH       : positive := 16;
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_WIDTH : positive := 64;
    -- Sets the bit width for CHUNK WIDTH values carried by this module.
    CHUNK_WIDTH   : positive := 16
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk      : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst      : in  std_logic;
    -- Input valid qualifier for this operation or sideband channel.
    valid_i  : in  std_logic;
    -- Input a i signal for this module.
    a_i      : in  signed(A_WIDTH - 1 downto 0);
    -- Input b i signal for this module.
    b_i      : in  signed(B_WIDTH - 1 downto 0);
    -- Output valid qualifier aligned with the produced result.
    valid_o  : out std_logic;
    -- Output p o signal generated by this module.
    p_o      : out signed(PRODUCT_WIDTH - 1 downto 0)
  );
end entity;

architecture rtl of raddsp_xilinx_dsp48_wide_mul is
  function chunks_for(width : positive) return positive is
  begin
    return (width + CHUNK_WIDTH - 1) / CHUNK_WIDTH;
  end function;

  constant C_A_CHUNKS : positive := chunks_for(A_WIDTH);
  constant C_B_CHUNKS : positive := chunks_for(B_WIDTH);
  constant C_PARTS    : positive := C_A_CHUNKS * C_B_CHUNKS;
  constant C_DSP_IN_WIDTH : positive := CHUNK_WIDTH + 1;

  subtype dsp_product_t is signed(47 downto 0);
  type dsp_product_array_t is array (0 to C_PARTS - 1) of dsp_product_t;

  signal a_ext : signed(A_WIDTH downto 0);
  signal b_ext : signed(B_WIDTH downto 0);
  signal a_abs : unsigned(A_WIDTH downto 0);
  signal b_abs : unsigned(B_WIDTH downto 0);
  signal neg_pipe : std_logic_vector(2 downto 0) := (others => '0');
  signal valid_sum_r : std_logic := '0';
  signal valid_parts : std_logic_vector(0 to C_PARTS - 1);
  signal part_p : dsp_product_array_t := (others => (others => '0'));

  function part_index(ai : natural; bi : natural) return natural is
  begin
    return (ai * C_B_CHUNKS) + bi;
  end function;

  function get_chunk(value : unsigned; chunk : natural) return signed is
    variable ret : signed(C_DSP_IN_WIDTH - 1 downto 0) := (others => '0');
    variable bit_index : natural;
  begin
    for i in 0 to CHUNK_WIDTH - 1 loop
      bit_index := (chunk * CHUNK_WIDTH) + i;
      if bit_index <= value'left then
        ret(i) := value(bit_index);
      end if;
    end loop;
    return ret;
  end function;
begin
  assert CHUNK_WIDTH <= 16 report "wide DSP48 multiplier CHUNK_WIDTH must be <= 16" severity failure;
  assert C_DSP_IN_WIDTH <= 18 report "wide DSP48 multiplier DSP chunk width must fit DSP48 B input" severity failure;
  assert PRODUCT_WIDTH >= A_WIDTH + B_WIDTH report "PRODUCT_WIDTH must fit A_WIDTH+B_WIDTH" severity failure;

  a_ext <= resize(a_i, A_WIDTH + 1);
  b_ext <= resize(b_i, B_WIDTH + 1);
  a_abs <= unsigned(-a_ext) when a_i(A_WIDTH - 1) = '1' else unsigned(a_ext);
  b_abs <= unsigned(-b_ext) when b_i(B_WIDTH - 1) = '1' else unsigned(b_ext);

  process(clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        neg_pipe <= (others => '0');
      else
        if valid_i = '1' then
          neg_pipe <= neg_pipe(1 downto 0) & (a_i(A_WIDTH - 1) xor b_i(B_WIDTH - 1));
        else
          neg_pipe <= neg_pipe(1 downto 0) & '0';
        end if;
      end if;
    end if;
  end process;

  gen_a : for ai in 0 to C_A_CHUNKS - 1 generate
    gen_b : for bi in 0 to C_B_CHUNKS - 1 generate
      constant C_INDEX : natural := part_index(ai, bi);
    begin
      mul_i: entity work.raddsp_xilinx_dsp48_mul
        generic map (
          DEVICE_FAMILY => DEVICE_FAMILY,
          A_WIDTH => C_DSP_IN_WIDTH,
          B_WIDTH => C_DSP_IN_WIDTH
        )
        port map (
          clk => clk,
          rst => rst,
          valid_i => valid_i,
          subtract_i => '0',
          last_i => '0',
          a_i => get_chunk(a_abs, ai),
          b_i => get_chunk(b_abs, bi),
          valid_o => valid_parts(C_INDEX),
          subtract_o => open,
          last_o => open,
          p_o => part_p(C_INDEX)
        );
    end generate;
  end generate;

  process(clk)
    variable sum_v : signed(PRODUCT_WIDTH - 1 downto 0);
    variable shifted_v : signed(PRODUCT_WIDTH - 1 downto 0);
    variable idx : natural;
  begin
    if rising_edge(clk) then
      if rst = '1' then
        valid_o <= '0';
        valid_sum_r <= '0';
        p_o <= (others => '0');
      else
        sum_v := (others => '0');
        for ai in 0 to C_A_CHUNKS - 1 loop
          for bi in 0 to C_B_CHUNKS - 1 loop
            idx := part_index(ai, bi);
            shifted_v := shift_left(resize(part_p(idx), PRODUCT_WIDTH), (ai + bi) * CHUNK_WIDTH);
            sum_v := sum_v + shifted_v;
          end loop;
        end loop;

        if neg_pipe(2) = '1' then
          p_o <= -sum_v;
        else
          p_o <= sum_v;
        end if;
        valid_sum_r <= valid_parts(0);
        valid_o <= valid_sum_r;
      end if;
    end if;
  end process;
end architecture;
