library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library xpm;
use xpm.vcomponents.all;

-- Lookup ROM for FFT twiddle factors used by RadDSP FFT implementations.
-- Returns fixed-point sine/cosine coefficients indexed by stage and butterfly position.
entity raddsp_fft_twiddle_rom is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR          : string := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY   : string := "ultrascaleplus";
    -- Sets the transform, frame, or vector size used by the datapath.
    G_POINTS        : positive := 1024;
    -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
    G_TWIDDLE_WIDTH : positive := 16;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_INVERSE_FFT   : boolean := false;
    -- Configures G MEMORY STYLE for this instance.
    G_MEMORY_STYLE  : string := "block";
    -- Configures G INIT FILE for this instance.
    G_INIT_FILE     : string := "none"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk            : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst            : in  std_logic;
    -- Input addr i signal for this module.
    addr_i         : in  std_logic_vector;
    -- Output twiddle re o signal generated by this module.
    twiddle_re_o   : out signed(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Output twiddle im o signal generated by this module.
    twiddle_im_o   : out signed(G_TWIDDLE_WIDTH - 1 downto 0)
  );
end entity;

architecture rtl of raddsp_fft_twiddle_rom is
  function clog2(value : positive) return natural is
    variable v : natural := value - 1;
    variable result : natural := 0;
  begin
    while v > 0 loop
      v := v / 2;
      result := result + 1;
    end loop;
    if result = 0 then
      return 1;
    end if;
    return result;
  end function;

  constant C_ADDR_WIDTH : positive := clog2(G_POINTS);
  constant C_DATA_WIDTH : positive := 2 * G_TWIDDLE_WIDTH;
  signal rom_addr : std_logic_vector(C_ADDR_WIDTH - 1 downto 0);
  signal rom_dout : std_logic_vector(C_DATA_WIDTH - 1 downto 0);
  signal im_raw   : signed(G_TWIDDLE_WIDTH - 1 downto 0);
begin
  assert VENDOR = "xilinx" report "RADFFT twiddle ROM currently uses Xilinx XPM memory" severity failure;
  assert G_INIT_FILE /= "none" report "RADFFT twiddle ROM requires a .mem init file" severity failure;

  rom_addr <= std_logic_vector(resize(unsigned(addr_i), C_ADDR_WIDTH));
  twiddle_re_o <= signed(rom_dout(C_DATA_WIDTH - 1 downto G_TWIDDLE_WIDTH));
  im_raw <= signed(rom_dout(G_TWIDDLE_WIDTH - 1 downto 0));
  twiddle_im_o <= -im_raw when G_INVERSE_FFT else im_raw;

  xpm_twiddle_i: xpm_memory_sprom
    generic map (
      MEMORY_SIZE => G_POINTS * C_DATA_WIDTH,
      MEMORY_PRIMITIVE => G_MEMORY_STYLE,
      ECC_MODE => "no_ecc",
      MEMORY_INIT_FILE => G_INIT_FILE,
      MEMORY_INIT_PARAM => "",
      USE_MEM_INIT => 1,
      USE_MEM_INIT_MMI => 0,
      WAKEUP_TIME => "disable_sleep",
      MESSAGE_CONTROL => 0,
      MEMORY_OPTIMIZATION => "true",
      READ_DATA_WIDTH_A => C_DATA_WIDTH,
      ADDR_WIDTH_A => C_ADDR_WIDTH,
      READ_RESET_VALUE_A => "0",
      READ_LATENCY_A => 1,
      RST_MODE_A => "SYNC"
    )
    port map (
      sleep => '0',
      clka => clk,
      rsta => rst,
      ena => '1',
      regcea => '1',
      addra => rom_addr,
      injectsbiterra => '0',
      injectdbiterra => '0',
      douta => rom_dout,
      sbiterra => open,
      dbiterra => open
    );
end architecture;
