library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library raddsp;

-- Sequential DSP48 square helper for Xilinx FPGA targets.
-- Computes squared signed samples with explicit handshake timing for resource-conscious DSP pipelines.
entity raddsp_xilinx_dsp48_square_seq is
  generic (
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY : string := "7series";
    -- Sets the bit width for WIDTH values carried by this module.
    WIDTH         : positive := 32
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk     : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst     : in  std_logic;
    -- Input start i signal for this module.
    start_i : in  std_logic;
    -- Input x i signal for this module.
    x_i     : in  signed(WIDTH - 1 downto 0);
    -- Output busy o signal generated by this module.
    busy_o  : out std_logic;
    -- Output valid qualifier aligned with the produced result.
    valid_o : out std_logic;
    -- Output y o signal generated by this module.
    y_o     : out unsigned((2 * WIDTH) - 1 downto 0)
  );
end entity;

architecture rtl of raddsp_xilinx_dsp48_square_seq is
  constant C_LIMB_BITS : positive := 16;
  constant C_LIMBS     : positive := (WIDTH + C_LIMB_BITS - 1) / C_LIMB_BITS;

  type state_t is (S_IDLE, S_ISSUE, S_WAIT);

  signal state      : state_t := S_IDLE;
  signal abs_x      : unsigned(WIDTH - 1 downto 0) := (others => '0');
  signal i_idx      : integer range 0 to C_LIMBS - 1 := 0;
  signal j_idx      : integer range 0 to C_LIMBS - 1 := 0;
  signal acc        : unsigned((2 * WIDTH) - 1 downto 0) := (others => '0');
  signal y_reg      : unsigned((2 * WIDTH) - 1 downto 0) := (others => '0');
  signal valid_reg  : std_logic := '0';
  signal mul_valid  : std_logic := '0';
  signal mul_a      : signed(C_LIMB_BITS downto 0) := (others => '0');
  signal mul_b      : signed(C_LIMB_BITS downto 0) := (others => '0');
  signal mul_p      : signed(47 downto 0);
  signal mul_p_valid : std_logic;
  signal unused_sub : std_logic;
  signal unused_last : std_logic;

  function abs_signed(value : signed) return unsigned is
    variable result : unsigned(value'length - 1 downto 0);
  begin
    if value(value'high) = '1' then
      result := unsigned(not std_logic_vector(value)) + 1;
    else
      result := unsigned(value);
    end if;
    return result;
  end function;

  function limb(value : unsigned; index : integer) return signed is
    variable result : signed(C_LIMB_BITS downto 0) := (others => '0');
    variable bit_idx : integer;
  begin
    for n in 0 to C_LIMB_BITS - 1 loop
      bit_idx := (index * C_LIMB_BITS) + n;
      if bit_idx < value'length then
        result(n) := value(bit_idx);
      end if;
    end loop;
    return result;
  end function;
begin
  busy_o <= '1' when state /= S_IDLE else '0';
  valid_o <= valid_reg;
  y_o <= y_reg;

  mul_i: entity raddsp.raddsp_xilinx_dsp48_mul
    generic map (
      DEVICE_FAMILY => DEVICE_FAMILY,
      A_WIDTH       => C_LIMB_BITS + 1,
      B_WIDTH       => C_LIMB_BITS + 1
    )
    port map (
      clk        => clk,
      rst        => rst,
      valid_i    => mul_valid,
      subtract_i => '0',
      last_i     => '0',
      a_i        => mul_a,
      b_i        => mul_b,
      valid_o    => mul_p_valid,
      subtract_o => unused_sub,
      last_o     => unused_last,
      p_o        => mul_p
    );

  process(clk)
    variable term     : unsigned((2 * WIDTH) - 1 downto 0);
    variable next_acc : unsigned((2 * WIDTH) - 1 downto 0);
  begin
    if rising_edge(clk) then
      if rst = '1' then
        state <= S_IDLE;
        abs_x <= (others => '0');
        i_idx <= 0;
        j_idx <= 0;
        acc <= (others => '0');
        y_reg <= (others => '0');
        valid_reg <= '0';
        mul_valid <= '0';
        mul_a <= (others => '0');
        mul_b <= (others => '0');
      else
        valid_reg <= '0';
        mul_valid <= '0';

        case state is
          when S_IDLE =>
            if start_i = '1' then
              abs_x <= abs_signed(x_i);
              i_idx <= 0;
              j_idx <= 0;
              acc <= (others => '0');
              state <= S_ISSUE;
            end if;

          when S_ISSUE =>
            mul_a <= limb(abs_x, i_idx);
            mul_b <= limb(abs_x, j_idx);
            mul_valid <= '1';
            state <= S_WAIT;

          when S_WAIT =>
            if mul_p_valid = '1' then
              term := shift_left(
                resize(unsigned(mul_p(31 downto 0)), term'length),
                C_LIMB_BITS * (i_idx + j_idx)
              );
              next_acc := acc + term;
              acc <= next_acc;

              if j_idx = C_LIMBS - 1 then
                if i_idx = C_LIMBS - 1 then
                  y_reg <= next_acc;
                  valid_reg <= '1';
                  state <= S_IDLE;
                else
                  i_idx <= i_idx + 1;
                  j_idx <= 0;
                  state <= S_ISSUE;
                end if;
              else
                j_idx <= j_idx + 1;
                state <= S_ISSUE;
              end if;
            end if;
        end case;
      end if;
    end if;
  end process;
end architecture;
