library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.raddsp_axis_pkg.all;

-- AXI-stream numerically controlled oscillator and direct digital synthesis source.
-- Generates phase-continuous sine/cosine or waveform samples from programmable tuning words for DSP stimulus and mixing chains.
entity raddsp_axis_dds is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR          : string  := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY   : string  := "generic";
    -- Sets the bit width for DATA WIDTH values carried by this module.
    DATA_WIDTH      : positive := 16;
    -- Sets the bit width for PHASE WIDTH values carried by this module.
    PHASE_WIDTH     : positive := 32;
    -- Sets the bit width for LUT ADDR WIDTH values carried by this module.
    LUT_ADDR_WIDTH  : positive := 4;
    -- Sets the transform, frame, or vector size used by the datapath.
    FRAME_LENGTH    : natural  := 0;
    -- Configures MEM INIT FILE for this instance.
    MEM_INIT_FILE   : string   := "dsp/hdl/raddsp/mem/sine_q15_16.mem"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk             : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst             : in  std_logic;
    -- Input enable i signal for this module.
    enable_i        : in  std_logic;
    -- Input phase reset i signal for this module.
    phase_reset_i   : in  std_logic;
    -- Input phase inc i signal for this module.
    phase_inc_i     : in  std_logic_vector(PHASE_WIDTH - 1 downto 0);
    -- Input phase offset i signal for this module.
    phase_offset_i  : in  std_logic_vector(PHASE_WIDTH - 1 downto 0);
    -- Input wav wr en i signal for this module.
    wav_wr_en_i     : in  std_logic;
    -- Input wav wr addr i signal for this module.
    wav_wr_addr_i   : in  std_logic_vector(LUT_ADDR_WIDTH - 1 downto 0);
    -- Input wav wr data i signal for this module.
    wav_wr_data_i   : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid   : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready   : in  std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata    : out std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast    : out std_logic;
    -- Output phase o signal generated by this module.
    phase_o         : out std_logic_vector(PHASE_WIDTH - 1 downto 0);
    -- Output lut addr o signal generated by this module.
    lut_addr_o      : out std_logic_vector(LUT_ADDR_WIDTH - 1 downto 0)
  );
end entity;

architecture rtl of raddsp_axis_dds is
  constant C_LUT_DEPTH : positive := 2 ** LUT_ADDR_WIDTH;
  constant C_IS_XILINX : boolean := VENDOR = "xilinx" or VENDOR = "XILINX";
  constant C_IS_LATTICE : boolean := VENDOR = "lattice" or VENDOR = "LATTICE" or VENDOR = "ecp5" or VENDOR = "ECP5";
  constant C_USE_MEM_INIT : integer := 1 when C_IS_XILINX else 0;

  signal phase_r       : unsigned(PHASE_WIDTH - 1 downto 0) := (others => '0');
  signal rd_addr_r     : std_logic_vector(LUT_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal lut_dout      : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
  signal out_valid_r   : std_logic := '0';
  signal out_data_r    : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
  signal out_last_r    : std_logic := '0';
  signal pending_r     : std_logic := '0';
  signal frame_count_r : natural range 0 to integer'high := 0;
  signal ready_i       : std_logic;

  component radhdl_ram is
    generic (
      VENDOR : string := "xilinx"; DEVICE_FAMILY : string := "7series"; MODE : string := "tdp"; MEMORY_KIND : string := "bram";
      DATA_WIDTH : positive := 18; ADDR_WIDTH : positive := 10; DEPTH : positive := 1024;
      CLOCKING_MODE : string := "common_clock";
      MEMORY_INIT_FILE : string := "none"; USE_MEM_INIT : integer := 0
    );
    port (
      clka : in std_logic; rsta : in std_logic; a_addr : in std_logic_vector(ADDR_WIDTH - 1 downto 0);
      a_din : in std_logic_vector(DATA_WIDTH - 1 downto 0); a_dout : out std_logic_vector(DATA_WIDTH - 1 downto 0); a_we : in std_logic;
      clkb : in std_logic; rstb : in std_logic; b_addr : in std_logic_vector(ADDR_WIDTH - 1 downto 0);
      b_din : in std_logic_vector(DATA_WIDTH - 1 downto 0); b_dout : out std_logic_vector(DATA_WIDTH - 1 downto 0); b_we : in std_logic
    );
  end component;
begin
  assert PHASE_WIDTH >= LUT_ADDR_WIDTH
    report "PHASE_WIDTH must be greater than or equal to LUT_ADDR_WIDTH"
    severity failure;

  ready_i <= (not out_valid_r) or m_axis_tready;
  m_axis_tvalid <= out_valid_r;
  m_axis_tdata <= out_data_r;
  m_axis_tlast <= out_last_r;
  phase_o <= std_logic_vector(phase_r);
  lut_addr_o <= rd_addr_r;

  assert C_IS_XILINX or C_IS_LATTICE
    report "raddsp_axis_dds unsupported VENDOR; expected xilinx or lattice/ecp5"
    severity failure;

  gen_lut_ram : if C_IS_XILINX or C_IS_LATTICE generate
    signal unused_dout_b : std_logic_vector(DATA_WIDTH - 1 downto 0);
  begin
    lut_i : radhdl_ram
      generic map (
        VENDOR => VENDOR,
        DEVICE_FAMILY => DEVICE_FAMILY,
        MODE => "sdp",
        MEMORY_KIND => "bram",
        DATA_WIDTH => DATA_WIDTH,
        ADDR_WIDTH => LUT_ADDR_WIDTH,
        DEPTH => C_LUT_DEPTH,
        CLOCKING_MODE => "common_clock",
        MEMORY_INIT_FILE => MEM_INIT_FILE,
        USE_MEM_INIT => C_USE_MEM_INIT
      )
      port map (
        clka => clk,
        rsta => rst,
        a_addr => rd_addr_r,
        a_din => (others => '0'),
        a_dout => lut_dout,
        a_we => '0',
        clkb => clk,
        rstb => rst,
        b_addr => wav_wr_addr_i,
        b_din => wav_wr_data_i,
        b_dout => unused_dout_b,
        b_we => wav_wr_en_i
      );
  end generate;

  process(clk)
    variable phase_next_v : unsigned(PHASE_WIDTH - 1 downto 0);
    variable addr_phase_v : unsigned(PHASE_WIDTH - 1 downto 0);
    variable emit_v       : std_logic;
  begin
    if rising_edge(clk) then
      if rst = '1' then
        phase_r <= (others => '0');
        rd_addr_r <= (others => '0');
        out_valid_r <= '0';
        out_data_r <= (others => '0');
        out_last_r <= '0';
        pending_r <= '0';
        frame_count_r <= 0;
      else
        if phase_reset_i = '1' then
          phase_r <= (others => '0');
          pending_r <= '0';
          out_valid_r <= '0';
          frame_count_r <= 0;
        elsif ready_i = '1' then
          emit_v := pending_r;
          out_valid_r <= emit_v;
          out_data_r <= lut_dout;
          out_last_r <= '0';

          if emit_v = '1' and FRAME_LENGTH > 0 then
            if frame_count_r = FRAME_LENGTH - 1 then
              out_last_r <= '1';
              frame_count_r <= 0;
            else
              frame_count_r <= frame_count_r + 1;
            end if;
          end if;

          if enable_i = '1' then
            phase_next_v := phase_r + unsigned(phase_inc_i);
            addr_phase_v := phase_next_v + unsigned(phase_offset_i);
            phase_r <= phase_next_v;
            rd_addr_r <= std_logic_vector(addr_phase_v(PHASE_WIDTH - 1 downto PHASE_WIDTH - LUT_ADDR_WIDTH));
            pending_r <= '1';
          else
            pending_r <= '0';
          end if;
        end if;
      end if;
    end if;
  end process;
end architecture;
