library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Radix-2 true-dual-port-memory AXI-stream RadFFT engine.
-- Uses dual-port scratch memories to schedule butterfly passes with predictable memory access patterns.
entity raddsp_axis_radfft_radix2_tdp is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR               : string := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY        : string := "ultrascaleplus";
    -- Sets the transform, frame, or vector size used by the datapath.
    G_POINTS             : positive := 1024;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_MAX_POINTS         : positive := 1024;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_INVERSE_FFT        : boolean := false;
    -- Sets the bit width for G INPUT WIDTH values carried by this module.
    G_INPUT_WIDTH        : positive := 16;
    -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
    G_TWIDDLE_WIDTH      : positive := 16;
    -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
    G_OUTPUT_WIDTH       : positive := 24;
    -- Configures G SCALE EACH STAGE for this instance.
    G_SCALE_EACH_STAGE   : boolean := true;
    -- Configures G MEMORY STYLE for this instance.
    G_MEMORY_STYLE       : string := "block";
    -- Configures G TWIDDLE MEMORY STYLE for this instance.
    G_TWIDDLE_MEMORY_STYLE : string := "block";
    -- Configures G TWIDDLE INIT FILE for this instance.
    G_TWIDDLE_INIT_FILE  : string := "none";
    -- Configures G EXTERNAL TWIDDLES for this instance.
    G_EXTERNAL_TWIDDLES  : boolean := false;
    -- Sets the width or count of samples handled by the datapath.
    G_MEMORY_WORD_SAMPLES : positive := 4
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk            : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst            : in  std_logic;
    -- Input AXI-stream valid qualifier for the current sample beat.
    s_axis_tvalid  : in  std_logic;
    -- Input AXI-stream ready response indicating this block can accept a beat.
    s_axis_tready  : out std_logic;
    -- Input AXI-stream payload containing packed sample or feature lanes.
    s_axis_tdata   : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
    -- Input AXI-stream frame marker for the final beat of a frame.
    s_axis_tlast   : in  std_logic;
    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid  : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready  : in  std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata   : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast   : out std_logic;
    -- Input runtime inverse i signal for this module.
    runtime_inverse_i : in std_logic := '0';
    -- Input active point log2 i signal for this module.
    active_point_log2_i : in std_logic_vector(7 downto 0) := (others => '0');
    -- Input active radix4 i signal for this module.
    active_radix4_i     : in std_logic := '0';
    -- Input active input width i signal for this module.
    active_input_width_i : in std_logic_vector(7 downto 0) := (others => '0');
    -- Input active output width i signal for this module.
    active_output_width_i : in std_logic_vector(7 downto 0) := (others => '0');
    -- Output twiddle addr o signal generated by this module.
    twiddle_addr_o : out std_logic_vector(31 downto 0);
    -- Input twiddle re i signal for this module.
    twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Input twiddle im i signal for this module.
    twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Output busy o signal generated by this module.
    busy_o         : out std_logic;
    -- Output frame done o signal generated by this module.
    frame_done_o   : out std_logic
  );
end entity;

architecture rtl of raddsp_axis_radfft_radix2_tdp is
  function is_power_of_two(value : positive) return boolean is
    variable v : positive := value;
  begin
    while (v mod 2) = 0 loop
      v := v / 2;
    end loop;
    return v = 1;
  end function;

  function clog2(value : positive) return natural is
    variable v : natural := value - 1;
    variable result : natural := 0;
  begin
    while v > 0 loop
      v := v / 2;
      result := result + 1;
    end loop;
    return result;
  end function;

  function ceil_div(left : positive; right : positive) return positive is
  begin
    return (left + right - 1) / right;
  end function;

  constant C_MAX_POINT_LOG2 : positive := clog2(G_MAX_POINTS);

  function bit_reverse(value : natural; bits : natural) return natural is
    variable v : natural := value;
    variable r : natural := 0;
  begin
    for i in 0 to C_MAX_POINT_LOG2 - 1 loop
      if i < bits then
        r := r + r + (v mod 2);
        v := v / 2;
      end if;
    end loop;
    return r;
  end function;

  function base4_reverse(value : natural; digits : natural) return natural is
    variable v : natural := value;
    variable r : natural := 0;
  begin
    for i in 0 to C_MAX_POINT_LOG2 - 1 loop
      if i < digits then
        r := r + r + r + r + (v mod 4);
        v := v / 4;
      end if;
    end loop;
    return r;
  end function;

  function high_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value(value'left downto value'length / 2);
  end function;

  function low_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value((value'length / 2) - 1 downto 0);
  end function;

  constant C_SCALE_SHIFT   : natural := clog2(G_MAX_POINTS);
  constant C_TWIDDLE_SHIFT : natural := G_TWIDDLE_WIDTH - 2;
  constant C_ACC_WIDTH     : positive := G_INPUT_WIDTH + G_TWIDDLE_WIDTH + C_SCALE_SHIFT + 4;
  constant C_MUL_WIDTH     : positive := C_ACC_WIDTH + G_TWIDDLE_WIDTH;
  constant C_SAMPLE_WIDTH  : positive := 2 * C_ACC_WIDTH;
  constant C_WORD_SAMPLES  : positive := G_MEMORY_WORD_SAMPLES;
  constant C_WORD_WIDTH    : positive := C_SAMPLE_WIDTH * C_WORD_SAMPLES;
  constant C_MEM_DEPTH     : positive := ceil_div(G_MAX_POINTS, C_WORD_SAMPLES);
  constant C_ADDR_WIDTH    : positive := clog2(C_MEM_DEPTH);
  constant C_TW_ADDR_WIDTH : positive := C_MAX_POINT_LOG2;

  subtype acc_t is signed(C_ACC_WIDTH - 1 downto 0);
  subtype mul_t is signed(C_MUL_WIDTH - 1 downto 0);
  subtype word_t is std_logic_vector(C_WORD_WIDTH - 1 downto 0);

  type state_t is (
    ST_LOAD_READ,
    ST_LOAD_CAPTURE,
    ST_LOAD_WRITE,
    ST_R2_READ,
    ST_R2_READ_WAIT,
    ST_R2_CAPTURE,
    ST_R2_TW_WAIT,
    ST_R2_MUL_START,
    ST_R2_WAIT,
    ST_R4_READ0,
    ST_R4_READ0_WAIT,
    ST_R4_READ0_CAPTURE,
    ST_R4_READ1_WAIT,
    ST_R4_READ1_CAPTURE,
    ST_R4_READ2_WAIT,
    ST_R4_READ2_CAPTURE,
    ST_R4_READ3_WAIT,
    ST_R4_READ3_CAPTURE,
    ST_R4_TW1_WAIT,
    ST_R4_MUL1_START,
    ST_R4_MUL1_WAIT,
    ST_R4_TW2_WAIT,
    ST_R4_MUL2_START,
    ST_R4_MUL2_WAIT,
    ST_R4_TW3_WAIT,
    ST_R4_MUL3_START,
    ST_R4_MUL3_WAIT,
    ST_R4_COMPUTE,
    ST_R4_WRITE_READ,
    ST_R4_WRITE_WAIT,
    ST_R4_WRITE_APPLY,
    ST_OUT_READ,
    ST_OUT_WAIT,
    ST_OUT_EMIT,
    ST_DONE
  );

  signal state_r : state_t := ST_LOAD_READ;
  signal load_index_r : natural range 0 to G_MAX_POINTS := 0;
  signal output_index_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal stage_size_r : natural range 2 to G_MAX_POINTS := 2;
  signal group_base_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal butterfly_j_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal active_point_log2_r : natural range 1 to clog2(G_MAX_POINTS) := clog2(G_POINTS);
  signal active_points_r : natural range 2 to G_MAX_POINTS := G_POINTS;
  signal active_radix4_r : std_logic := '0';
  signal active_inverse_r : std_logic := '0';

  signal ram_a_addr : std_logic_vector(C_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal ram_a_din  : word_t := (others => '0');
  signal ram_a_dout : word_t;
  signal ram_a_we   : std_logic := '0';
  signal ram_b_addr : std_logic_vector(C_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal ram_b_din  : word_t := (others => '0');
  signal ram_b_dout : word_t;
  signal ram_b_we   : std_logic := '0';

  signal idx0_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal idx1_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal idx2_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal idx3_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal word0_r : word_t := (others => '0');
  signal word1_r : word_t := (others => '0');
  signal x0_re_r : acc_t := (others => '0');
  signal x0_im_r : acc_t := (others => '0');
  signal x1_re_r : acc_t := (others => '0');
  signal x1_im_r : acc_t := (others => '0');
  signal x2_re_r : acc_t := (others => '0');
  signal x2_im_r : acc_t := (others => '0');
  signal x3_re_r : acc_t := (others => '0');
  signal x3_im_r : acc_t := (others => '0');
  signal t1_re_r : acc_t := (others => '0');
  signal t1_im_r : acc_t := (others => '0');
  signal t2_re_r : acc_t := (others => '0');
  signal t2_im_r : acc_t := (others => '0');
  signal t3_re_r : acc_t := (others => '0');
  signal t3_im_r : acc_t := (others => '0');
  signal y0_re_r : acc_t := (others => '0');
  signal y0_im_r : acc_t := (others => '0');
  signal y1_re_r : acc_t := (others => '0');
  signal y1_im_r : acc_t := (others => '0');
  signal y2_re_r : acc_t := (others => '0');
  signal y2_im_r : acc_t := (others => '0');
  signal y3_re_r : acc_t := (others => '0');
  signal y3_im_r : acc_t := (others => '0');
  signal write_phase_r : natural range 0 to 3 := 0;

  signal tw_exp_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal tw1_exp_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal tw2_exp_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal tw3_exp_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal tw_step_r : natural range 1 to G_MAX_POINTS := 1;
  signal tw_rom_addr : std_logic_vector(C_TW_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal tw_re_s : signed(G_TWIDDLE_WIDTH - 1 downto 0);
  signal tw_im_s : signed(G_TWIDDLE_WIDTH - 1 downto 0);
  signal tw_im_mul_s : signed(G_TWIDDLE_WIDTH - 1 downto 0);
  signal mul_valid_r : std_logic := '0';
  signal mul_a_re_r : acc_t := (others => '0');
  signal mul_a_im_r : acc_t := (others => '0');
  signal rr_p : mul_t;
  signal ii_p : mul_t;
  signal ri_p : mul_t;
  signal ir_p : mul_t;
  signal rr_valid : std_logic;

  signal out_valid_r : std_logic := '0';
  signal out_last_r : std_logic := '0';
  signal out_data_r : std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0) := (others => '0');
  signal done_r : std_logic := '0';
  signal load_sample_r : std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0) := (others => '0');

  function word_addr(index : natural) return natural is
  begin
    return index / C_WORD_SAMPLES;
  end function;

  function word_lane(index : natural) return natural is
  begin
    return index mod C_WORD_SAMPLES;
  end function;

  function lane_low(lane : natural) return natural is
  begin
    case lane is
      when 0 => return 0;
      when 1 => return C_SAMPLE_WIDTH;
      when 2 => return C_SAMPLE_WIDTH + C_SAMPLE_WIDTH;
      when others => return C_SAMPLE_WIDTH + C_SAMPLE_WIDTH + C_SAMPLE_WIDTH;
    end case;
  end function;

  function get_re(word : word_t; lane : natural) return acc_t is
    variable lo : natural := lane_low(lane);
  begin
    return signed(word(lo + C_SAMPLE_WIDTH - 1 downto lo + C_ACC_WIDTH));
  end function;

  function get_im(word : word_t; lane : natural) return acc_t is
    variable lo : natural := lane_low(lane);
  begin
    return signed(word(lo + C_ACC_WIDTH - 1 downto lo));
  end function;

  function set_sample(word : word_t; lane : natural; re_value : acc_t; im_value : acc_t) return word_t is
    variable ret : word_t := word;
    variable lo : natural := lane_low(lane);
  begin
    ret(lo + C_SAMPLE_WIDTH - 1 downto lo + C_ACC_WIDTH) := std_logic_vector(re_value);
    ret(lo + C_ACC_WIDTH - 1 downto lo) := std_logic_vector(im_value);
    return ret;
  end function;

  function pow2(value : natural) return natural is
    variable ret : natural := 1;
  begin
    for i in 1 to C_TW_ADDR_WIDTH loop
      if i <= value then
        ret := ret * 2;
      end if;
    end loop;
    return ret;
  end function;

  function sanitize_log2(value : std_logic_vector(7 downto 0)) return natural is
    variable requested : natural := to_integer(unsigned(value));
    variable max_log2 : natural := clog2(G_MAX_POINTS);
  begin
    if requested = 0 then
      return clog2(G_POINTS);
    elsif requested < 1 then
      return 1;
    elsif requested > max_log2 then
      return max_log2;
    end if;
    return requested;
  end function;

  function scaled_output(value : acc_t; scale_shift : natural) return signed is
    variable scaled : acc_t;
  begin
    if G_SCALE_EACH_STAGE then
      scaled := shift_right(value, scale_shift);
    else
      scaled := value;
    end if;
    return resize(scaled, G_OUTPUT_WIDTH);
  end function;
begin
  assert is_power_of_two(G_POINTS) report "radix2 TDP RADFFT G_POINTS must be a power of two" severity failure;
  assert G_POINTS <= G_MAX_POINTS report "radix2 TDP RADFFT G_POINTS must not exceed G_MAX_POINTS" severity failure;
  assert G_MEMORY_WORD_SAMPLES = 1 or G_MEMORY_WORD_SAMPLES = 2 or G_MEMORY_WORD_SAMPLES = 4
    report "radix2 TDP RADFFT G_MEMORY_WORD_SAMPLES must be 1, 2, or 4"
    severity failure;

  s_axis_tready <= '1' when state_r = ST_LOAD_READ and load_index_r < active_points_r else '0';
  m_axis_tvalid <= out_valid_r;
  m_axis_tlast <= out_last_r;
  m_axis_tdata <= out_data_r;
  twiddle_addr_o <= std_logic_vector(resize(unsigned(tw_rom_addr), 32));
  busy_o <= '0' when state_r = ST_LOAD_READ and load_index_r = 0 and out_valid_r = '0' else '1';
  frame_done_o <= done_r;
  tw_im_mul_s <= tw_im_s when G_INVERSE_FFT or active_inverse_r = '0' else -tw_im_s;

  ram_i: entity work.fft_tdp_ram
    generic map (
      DEVICE_FAMILY => DEVICE_FAMILY,
      MEMORY_STYLE => G_MEMORY_STYLE,
      DATA_WIDTH => C_WORD_WIDTH,
      ADDR_WIDTH => C_ADDR_WIDTH,
      DEPTH => C_MEM_DEPTH
    )
    port map (
      clk => clk,
      a_addr => ram_a_addr,
      a_din => ram_a_din,
      a_dout => ram_a_dout,
      a_we => ram_a_we,
      b_addr => ram_b_addr,
      b_din => ram_b_din,
      b_dout => ram_b_dout,
      b_we => ram_b_we
    );

  gen_external_twiddles : if G_EXTERNAL_TWIDDLES generate
  begin
    tw_re_s <= signed(twiddle_re_i);
    tw_im_s <= signed(twiddle_im_i);
  end generate;

  gen_rom_twiddles : if not G_EXTERNAL_TWIDDLES generate
  begin
    twiddle_rom_i: entity work.raddsp_fft_twiddle_rom
      generic map (
        VENDOR => VENDOR,
        DEVICE_FAMILY => DEVICE_FAMILY,
        G_POINTS => G_POINTS,
        G_TWIDDLE_WIDTH => G_TWIDDLE_WIDTH,
        G_INVERSE_FFT => G_INVERSE_FFT,
        G_MEMORY_STYLE => G_TWIDDLE_MEMORY_STYLE,
        G_INIT_FILE => G_TWIDDLE_INIT_FILE
      )
      port map (
        clk => clk,
        rst => rst,
        addr_i => tw_rom_addr,
        twiddle_re_o => tw_re_s,
        twiddle_im_o => tw_im_s
      );
  end generate;

  rr_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
    generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => C_ACC_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_MUL_WIDTH)
    port map (clk => clk, rst => rst, valid_i => mul_valid_r, a_i => mul_a_re_r, b_i => tw_re_s, valid_o => rr_valid, p_o => rr_p);

  ii_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
    generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => C_ACC_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_MUL_WIDTH)
    port map (clk => clk, rst => rst, valid_i => mul_valid_r, a_i => mul_a_im_r, b_i => tw_im_mul_s, valid_o => open, p_o => ii_p);

  ri_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
    generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => C_ACC_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_MUL_WIDTH)
    port map (clk => clk, rst => rst, valid_i => mul_valid_r, a_i => mul_a_re_r, b_i => tw_im_mul_s, valid_o => open, p_o => ri_p);

  ir_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
    generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => C_ACC_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_MUL_WIDTH)
    port map (clk => clk, rst => rst, valid_i => mul_valid_r, a_i => mul_a_im_r, b_i => tw_re_s, valid_o => open, p_o => ir_p);

  process(clk)
    variable load_idx : natural;
    variable half_v : natural;
    variable t_re : acc_t;
    variable t_im : acc_t;
    variable y0_re : acc_t;
    variable y0_im : acc_t;
    variable y1_re : acc_t;
    variable y1_im : acc_t;
    variable tmp_word0 : word_t;
    variable tmp_word1 : word_t;
    variable out_re : acc_t;
    variable out_im : acc_t;
    variable quarter_v : natural;
    variable a_re : acc_t;
    variable a_im : acc_t;
    variable b_re : acc_t;
    variable b_im : acc_t;
    variable c_re : acc_t;
    variable c_im : acc_t;
    variable e_re : acc_t;
    variable e_im : acc_t;
    variable write_idx : natural;
    variable write_re : acc_t;
    variable write_im : acc_t;
    variable tmp_word : word_t;
    variable next_log2 : natural;
    variable next_points : natural;
    variable next_radix4 : std_logic;
  begin
    if rising_edge(clk) then
      ram_a_we <= '0';
      ram_b_we <= '0';
      mul_valid_r <= '0';
      done_r <= '0';

      if rst = '1' then
        state_r <= ST_LOAD_READ;
        load_index_r <= 0;
        output_index_r <= 0;
        stage_size_r <= 2;
        active_point_log2_r <= clog2(G_POINTS);
        active_points_r <= G_POINTS;
        active_radix4_r <= '0';
        active_inverse_r <= '0';
        group_base_r <= 0;
        butterfly_j_r <= 0;
        write_phase_r <= 0;
        tw_exp_r <= 0;
        tw1_exp_r <= 0;
        tw2_exp_r <= 0;
        tw3_exp_r <= 0;
        tw_step_r <= 1;
        tw_rom_addr <= (others => '0');
        out_valid_r <= '0';
        out_last_r <= '0';
        out_data_r <= (others => '0');
      else
        case state_r is
          when ST_LOAD_READ =>
            out_valid_r <= '0';
            out_last_r <= '0';
            if s_axis_tvalid = '1' and s_axis_tready = '1' then
              if load_index_r = 0 then
                next_log2 := sanitize_log2(active_point_log2_i);
                next_points := pow2(next_log2);
                next_radix4 := active_radix4_i;
                active_point_log2_r <= next_log2;
                active_points_r <= next_points;
                active_radix4_r <= next_radix4;
                active_inverse_r <= runtime_inverse_i;
              else
                next_log2 := active_point_log2_r;
                next_points := active_points_r;
                next_radix4 := active_radix4_r;
              end if;
              if next_radix4 = '1' then
                load_idx := base4_reverse(load_index_r, next_log2 / 2);
              else
                load_idx := bit_reverse(load_index_r, next_log2);
              end if;
              load_sample_r <= s_axis_tdata;
              ram_a_addr <= std_logic_vector(to_unsigned(word_addr(load_idx), C_ADDR_WIDTH));
              idx0_r <= load_idx;
              state_r <= ST_LOAD_CAPTURE;
            end if;

          when ST_LOAD_CAPTURE =>
            state_r <= ST_LOAD_WRITE;

          when ST_LOAD_WRITE =>
            tmp_word0 := set_sample(
              ram_a_dout,
              word_lane(idx0_r),
              resize(signed(high_half(load_sample_r)), C_ACC_WIDTH),
              resize(signed(low_half(load_sample_r)), C_ACC_WIDTH)
            );
            ram_a_addr <= std_logic_vector(to_unsigned(word_addr(idx0_r), C_ADDR_WIDTH));
            ram_a_din <= tmp_word0;
            ram_a_we <= '1';
            if load_index_r = active_points_r - 1 then
              load_index_r <= 0;
              group_base_r <= 0;
              butterfly_j_r <= 0;
              write_phase_r <= 0;
              tw_exp_r <= 0;
              tw1_exp_r <= 0;
              tw2_exp_r <= 0;
              tw3_exp_r <= 0;
              if active_radix4_r = '1' then
                stage_size_r <= 4;
                tw_step_r <= active_points_r / 4;
                state_r <= ST_R4_READ0;
              else
                stage_size_r <= 2;
                tw_step_r <= active_points_r / 2;
                state_r <= ST_R2_READ;
              end if;
            else
              load_index_r <= load_index_r + 1;
              state_r <= ST_LOAD_READ;
            end if;

          when ST_R2_READ =>
            half_v := stage_size_r / 2;
            idx0_r <= group_base_r + butterfly_j_r;
            idx1_r <= group_base_r + butterfly_j_r + half_v;
            ram_a_addr <= std_logic_vector(to_unsigned(word_addr(group_base_r + butterfly_j_r), C_ADDR_WIDTH));
            ram_b_addr <= std_logic_vector(to_unsigned(word_addr(group_base_r + butterfly_j_r + half_v), C_ADDR_WIDTH));
            state_r <= ST_R2_READ_WAIT;

          when ST_R2_READ_WAIT =>
            state_r <= ST_R2_CAPTURE;

          when ST_R2_CAPTURE =>
            word0_r <= ram_a_dout;
            word1_r <= ram_b_dout;
            if word_addr(idx0_r) = word_addr(idx1_r) then
              x0_re_r <= get_re(ram_a_dout, word_lane(idx0_r));
              x0_im_r <= get_im(ram_a_dout, word_lane(idx0_r));
              x1_re_r <= get_re(ram_a_dout, word_lane(idx1_r));
              x1_im_r <= get_im(ram_a_dout, word_lane(idx1_r));
            else
              x0_re_r <= get_re(ram_a_dout, word_lane(idx0_r));
              x0_im_r <= get_im(ram_a_dout, word_lane(idx0_r));
              x1_re_r <= get_re(ram_b_dout, word_lane(idx1_r));
              x1_im_r <= get_im(ram_b_dout, word_lane(idx1_r));
            end if;
            tw_rom_addr <= std_logic_vector(resize(to_unsigned(tw_exp_r, clog2(G_MAX_POINTS)), C_TW_ADDR_WIDTH));
            mul_a_re_r <= get_re(ram_b_dout, word_lane(idx1_r));
            mul_a_im_r <= get_im(ram_b_dout, word_lane(idx1_r));
            state_r <= ST_R2_TW_WAIT;

          when ST_R2_TW_WAIT =>
            state_r <= ST_R2_MUL_START;

          when ST_R2_MUL_START =>
            mul_a_re_r <= x1_re_r;
            mul_a_im_r <= x1_im_r;
            mul_valid_r <= '1';
            state_r <= ST_R2_WAIT;

          when ST_R2_WAIT =>
            if rr_valid = '1' then
              t_re := resize(shift_right(rr_p - ii_p, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
              t_im := resize(shift_right(ri_p + ir_p, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
              y0_re := x0_re_r + t_re;
              y0_im := x0_im_r + t_im;
              y1_re := x0_re_r - t_re;
              y1_im := x0_im_r - t_im;

              if word_addr(idx0_r) = word_addr(idx1_r) then
                tmp_word0 := set_sample(word0_r, word_lane(idx0_r), y0_re, y0_im);
                tmp_word0 := set_sample(tmp_word0, word_lane(idx1_r), y1_re, y1_im);
                ram_a_addr <= std_logic_vector(to_unsigned(word_addr(idx0_r), C_ADDR_WIDTH));
                ram_a_din <= tmp_word0;
                ram_a_we <= '1';
              else
                tmp_word0 := set_sample(word0_r, word_lane(idx0_r), y0_re, y0_im);
                tmp_word1 := set_sample(word1_r, word_lane(idx1_r), y1_re, y1_im);
                ram_a_addr <= std_logic_vector(to_unsigned(word_addr(idx0_r), C_ADDR_WIDTH));
                ram_a_din <= tmp_word0;
                ram_a_we <= '1';
                ram_b_addr <= std_logic_vector(to_unsigned(word_addr(idx1_r), C_ADDR_WIDTH));
                ram_b_din <= tmp_word1;
                ram_b_we <= '1';
              end if;

              half_v := stage_size_r / 2;
              if butterfly_j_r = half_v - 1 then
                butterfly_j_r <= 0;
                if group_base_r + stage_size_r >= active_points_r then
                  group_base_r <= 0;
                  if stage_size_r >= active_points_r then
                    output_index_r <= 0;
                    state_r <= ST_OUT_READ;
                  else
                    tw_exp_r <= 0;
                    tw_step_r <= tw_step_r / 2;
                    stage_size_r <= stage_size_r + stage_size_r;
                    state_r <= ST_R2_READ;
                  end if;
                else
                  tw_exp_r <= 0;
                  group_base_r <= group_base_r + stage_size_r;
                  state_r <= ST_R2_READ;
                end if;
              else
                tw_exp_r <= tw_exp_r + tw_step_r;
                butterfly_j_r <= butterfly_j_r + 1;
                state_r <= ST_R2_READ;
              end if;
            end if;

          when ST_R4_READ0 =>
            quarter_v := stage_size_r / 4;
            idx0_r <= group_base_r + butterfly_j_r;
            idx1_r <= group_base_r + butterfly_j_r + quarter_v;
            idx2_r <= group_base_r + butterfly_j_r + quarter_v + quarter_v;
            idx3_r <= group_base_r + butterfly_j_r + quarter_v + quarter_v + quarter_v;
            ram_a_addr <= std_logic_vector(to_unsigned(word_addr(group_base_r + butterfly_j_r), C_ADDR_WIDTH));
            state_r <= ST_R4_READ0_WAIT;

          when ST_R4_READ0_WAIT =>
            state_r <= ST_R4_READ0_CAPTURE;

          when ST_R4_READ0_CAPTURE =>
            x0_re_r <= get_re(ram_a_dout, word_lane(idx0_r));
            x0_im_r <= get_im(ram_a_dout, word_lane(idx0_r));
            ram_a_addr <= std_logic_vector(to_unsigned(word_addr(idx1_r), C_ADDR_WIDTH));
            state_r <= ST_R4_READ1_WAIT;

          when ST_R4_READ1_WAIT =>
            state_r <= ST_R4_READ1_CAPTURE;

          when ST_R4_READ1_CAPTURE =>
            x1_re_r <= get_re(ram_a_dout, word_lane(idx1_r));
            x1_im_r <= get_im(ram_a_dout, word_lane(idx1_r));
            ram_a_addr <= std_logic_vector(to_unsigned(word_addr(idx2_r), C_ADDR_WIDTH));
            state_r <= ST_R4_READ2_WAIT;

          when ST_R4_READ2_WAIT =>
            state_r <= ST_R4_READ2_CAPTURE;

          when ST_R4_READ2_CAPTURE =>
            x2_re_r <= get_re(ram_a_dout, word_lane(idx2_r));
            x2_im_r <= get_im(ram_a_dout, word_lane(idx2_r));
            ram_a_addr <= std_logic_vector(to_unsigned(word_addr(idx3_r), C_ADDR_WIDTH));
            state_r <= ST_R4_READ3_WAIT;

          when ST_R4_READ3_WAIT =>
            state_r <= ST_R4_READ3_CAPTURE;

          when ST_R4_READ3_CAPTURE =>
            x3_re_r <= get_re(ram_a_dout, word_lane(idx3_r));
            x3_im_r <= get_im(ram_a_dout, word_lane(idx3_r));
            tw_rom_addr <= std_logic_vector(resize(to_unsigned(tw1_exp_r, clog2(G_MAX_POINTS)), C_TW_ADDR_WIDTH));
            mul_a_re_r <= x1_re_r;
            mul_a_im_r <= x1_im_r;
            state_r <= ST_R4_TW1_WAIT;

          when ST_R4_TW1_WAIT =>
            state_r <= ST_R4_MUL1_START;

          when ST_R4_MUL1_START =>
            mul_valid_r <= '1';
            state_r <= ST_R4_MUL1_WAIT;

          when ST_R4_MUL1_WAIT =>
            if rr_valid = '1' then
              t1_re_r <= resize(shift_right(rr_p - ii_p, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
              t1_im_r <= resize(shift_right(ri_p + ir_p, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
              tw_rom_addr <= std_logic_vector(resize(to_unsigned(tw2_exp_r, clog2(G_MAX_POINTS)), C_TW_ADDR_WIDTH));
              mul_a_re_r <= x2_re_r;
              mul_a_im_r <= x2_im_r;
              state_r <= ST_R4_TW2_WAIT;
            end if;

          when ST_R4_TW2_WAIT =>
            state_r <= ST_R4_MUL2_START;

          when ST_R4_MUL2_START =>
            mul_valid_r <= '1';
            state_r <= ST_R4_MUL2_WAIT;

          when ST_R4_MUL2_WAIT =>
            if rr_valid = '1' then
              t2_re_r <= resize(shift_right(rr_p - ii_p, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
              t2_im_r <= resize(shift_right(ri_p + ir_p, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
              tw_rom_addr <= std_logic_vector(resize(to_unsigned(tw3_exp_r, clog2(G_MAX_POINTS)), C_TW_ADDR_WIDTH));
              mul_a_re_r <= x3_re_r;
              mul_a_im_r <= x3_im_r;
              state_r <= ST_R4_TW3_WAIT;
            end if;

          when ST_R4_TW3_WAIT =>
            state_r <= ST_R4_MUL3_START;

          when ST_R4_MUL3_START =>
            mul_valid_r <= '1';
            state_r <= ST_R4_MUL3_WAIT;

          when ST_R4_MUL3_WAIT =>
            if rr_valid = '1' then
              t3_re_r <= resize(shift_right(rr_p - ii_p, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
              t3_im_r <= resize(shift_right(ri_p + ir_p, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
              state_r <= ST_R4_COMPUTE;
            end if;

          when ST_R4_COMPUTE =>
            a_re := x0_re_r + t2_re_r;
            a_im := x0_im_r + t2_im_r;
            b_re := x0_re_r - t2_re_r;
            b_im := x0_im_r - t2_im_r;
            c_re := t1_re_r + t3_re_r;
            c_im := t1_im_r + t3_im_r;
            e_re := t1_re_r - t3_re_r;
            e_im := t1_im_r - t3_im_r;
            y0_re_r <= a_re + c_re;
            y0_im_r <= a_im + c_im;
            y2_re_r <= a_re - c_re;
            y2_im_r <= a_im - c_im;
            if G_INVERSE_FFT or active_inverse_r = '1' then
              y1_re_r <= b_re - e_im;
              y1_im_r <= b_im + e_re;
              y3_re_r <= b_re + e_im;
              y3_im_r <= b_im - e_re;
            else
              y1_re_r <= b_re + e_im;
              y1_im_r <= b_im - e_re;
              y3_re_r <= b_re - e_im;
              y3_im_r <= b_im + e_re;
            end if;
            write_phase_r <= 0;
            state_r <= ST_R4_WRITE_READ;

          when ST_R4_WRITE_READ =>
            case write_phase_r is
              when 0 => write_idx := idx0_r;
              when 1 => write_idx := idx1_r;
              when 2 => write_idx := idx2_r;
              when others => write_idx := idx3_r;
            end case;
            ram_a_addr <= std_logic_vector(to_unsigned(word_addr(write_idx), C_ADDR_WIDTH));
            state_r <= ST_R4_WRITE_WAIT;

          when ST_R4_WRITE_WAIT =>
            state_r <= ST_R4_WRITE_APPLY;

          when ST_R4_WRITE_APPLY =>
            case write_phase_r is
              when 0 =>
                write_idx := idx0_r;
                write_re := y0_re_r;
                write_im := y0_im_r;
              when 1 =>
                write_idx := idx1_r;
                write_re := y1_re_r;
                write_im := y1_im_r;
              when 2 =>
                write_idx := idx2_r;
                write_re := y2_re_r;
                write_im := y2_im_r;
              when others =>
                write_idx := idx3_r;
                write_re := y3_re_r;
                write_im := y3_im_r;
            end case;
            tmp_word := set_sample(ram_a_dout, word_lane(write_idx), write_re, write_im);
            ram_a_addr <= std_logic_vector(to_unsigned(word_addr(write_idx), C_ADDR_WIDTH));
            ram_a_din <= tmp_word;
            ram_a_we <= '1';
            if write_phase_r = 3 then
              quarter_v := stage_size_r / 4;
              write_phase_r <= 0;
              if butterfly_j_r = quarter_v - 1 then
                butterfly_j_r <= 0;
                if group_base_r + stage_size_r >= active_points_r then
                  group_base_r <= 0;
                  if stage_size_r >= active_points_r then
                    output_index_r <= 0;
                    state_r <= ST_OUT_READ;
                  else
                    tw1_exp_r <= 0;
                    tw2_exp_r <= 0;
                    tw3_exp_r <= 0;
                    tw_step_r <= tw_step_r / 4;
                    stage_size_r <= stage_size_r * 4;
                    state_r <= ST_R4_READ0;
                  end if;
                else
                  tw1_exp_r <= 0;
                  tw2_exp_r <= 0;
                  tw3_exp_r <= 0;
                  group_base_r <= group_base_r + stage_size_r;
                  state_r <= ST_R4_READ0;
                end if;
              else
                tw1_exp_r <= (tw1_exp_r + tw_step_r) mod active_points_r;
                tw2_exp_r <= (tw2_exp_r + tw_step_r + tw_step_r) mod active_points_r;
                tw3_exp_r <= (tw3_exp_r + tw_step_r + tw_step_r + tw_step_r) mod active_points_r;
                butterfly_j_r <= butterfly_j_r + 1;
                state_r <= ST_R4_READ0;
              end if;
            else
              write_phase_r <= write_phase_r + 1;
              state_r <= ST_R4_WRITE_READ;
            end if;

          when ST_OUT_READ =>
            if out_valid_r = '0' or m_axis_tready = '1' then
              out_valid_r <= '0';
              out_last_r <= '0';
              ram_a_addr <= std_logic_vector(to_unsigned(word_addr(output_index_r), C_ADDR_WIDTH));
              state_r <= ST_OUT_WAIT;
            end if;

          when ST_OUT_WAIT =>
            state_r <= ST_OUT_EMIT;

          when ST_OUT_EMIT =>
            if out_valid_r = '0' or m_axis_tready = '1' then
              out_re := get_re(ram_a_dout, word_lane(output_index_r));
              out_im := get_im(ram_a_dout, word_lane(output_index_r));
              out_data_r <= std_logic_vector(scaled_output(out_re, active_point_log2_r)) & std_logic_vector(scaled_output(out_im, active_point_log2_r));
              out_valid_r <= '1';
              out_last_r <= '1' when output_index_r = active_points_r - 1 else '0';
              if output_index_r = active_points_r - 1 then
                state_r <= ST_DONE;
              else
                output_index_r <= output_index_r + 1;
                state_r <= ST_OUT_READ;
              end if;
            end if;

          when ST_DONE =>
            if out_valid_r = '1' and m_axis_tready = '1' then
              out_valid_r <= '0';
              out_last_r <= '0';
              done_r <= '1';
              load_index_r <= 0;
              state_r <= ST_LOAD_READ;
            end if;
        end case;
      end if;
    end if;
  end process;
end architecture;
