library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.raddsp_fft_twiddle_pkg.all;

-- Streaming AXI-stream RadFFT architecture.
-- Pushes samples through a streaming transform pipeline for lower buffering pressure and continuous frame processing.
entity raddsp_axis_radfft_streaming is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR               : string := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY        : string := "ultrascale+";
    -- Sets the transform, frame, or vector size used by the datapath.
    G_POINTS             : positive := 16;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_MAX_POINTS         : positive := 64;
    -- Configures G RADIX for this instance.
    G_RADIX              : positive := 2;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_INVERSE_FFT        : boolean := false;
    -- Sets the bit width for G INPUT WIDTH values carried by this module.
    G_INPUT_WIDTH        : positive := 16;
    -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
    G_TWIDDLE_WIDTH      : positive := 16;
    -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
    G_OUTPUT_WIDTH       : positive := 32;
    -- Configures G SCALE EACH STAGE for this instance.
    G_SCALE_EACH_STAGE   : boolean := true;
    -- Configures G MEMORY STYLE for this instance.
    G_MEMORY_STYLE       : string := "distributed";
    -- Configures G OVERLAP FRAMES for this instance.
    G_OVERLAP_FRAMES     : boolean := true;
    -- Sets the number of parallel sample lanes processed per handshake beat.
    G_MULTIPLIER_LANES   : positive := 1;
    -- Sets the number of parallel sample lanes processed per handshake beat.
    G_MAX_MULTIPLIER_LANES : positive := 8
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk          : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst          : in  std_logic;
    -- Input AXI-stream valid qualifier for the current sample beat.
    s_axis_tvalid : in  std_logic;
    -- Input AXI-stream ready response indicating this block can accept a beat.
    s_axis_tready : out std_logic;
    -- Input AXI-stream payload containing packed sample or feature lanes.
    s_axis_tdata  : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
    -- Input AXI-stream frame marker for the final beat of a frame.
    s_axis_tlast  : in  std_logic;
    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready : in  std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata  : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast  : out std_logic;
    -- Output twiddle addr o signal generated by this module.
    twiddle_addr_o : out std_logic_vector(31 downto 0);
    -- Input twiddle re i signal for this module.
    twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Input twiddle im i signal for this module.
    twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Output busy o signal generated by this module.
    busy_o          : out std_logic;
    -- Output frame done o signal generated by this module.
    frame_done_o    : out std_logic
  );
end entity;

architecture rtl of raddsp_axis_radfft_streaming is
  function is_power_of_two(value : positive) return boolean is
    variable v : positive := value;
  begin
    while (v mod 2) = 0 loop
      v := v / 2;
    end loop;
    return v = 1;
  end function;

  function is_power_of_four(value : positive) return boolean is
    variable v : positive := value;
  begin
    while (v mod 4) = 0 loop
      v := v / 4;
    end loop;
    return v = 1;
  end function;

  function clog2(value : positive) return natural is
    variable v : natural := value - 1;
    variable result : natural := 0;
  begin
    while v > 0 loop
      v := v / 2;
      result := result + 1;
    end loop;
    return result;
  end function;

  constant C_SCALE_SHIFT : natural := clog2(G_POINTS);
  constant C_TWIDDLE_SHIFT : natural := G_TWIDDLE_WIDTH - 2;
  constant C_ACC_WIDTH   : positive := G_INPUT_WIDTH + G_TWIDDLE_WIDTH + C_SCALE_SHIFT + 3;

  subtype acc_t is signed(C_ACC_WIDTH - 1 downto 0);
  type acc_array_t is array (natural range <>) of acc_t;

  subtype input_t is signed(G_INPUT_WIDTH - 1 downto 0);
  subtype twiddle_t is signed(G_TWIDDLE_WIDTH - 1 downto 0);
  type twiddle_array_t is array (natural range <>) of twiddle_t;

  signal bank0_re : acc_array_t(0 to G_POINTS - 1) := (others => (others => '0'));
  signal bank0_im : acc_array_t(0 to G_POINTS - 1) := (others => (others => '0'));
  signal bank1_re : acc_array_t(0 to G_POINTS - 1) := (others => (others => '0'));
  signal bank1_im : acc_array_t(0 to G_POINTS - 1) := (others => (others => '0'));

  signal active_bank_r : std_logic := '0';
  signal bank0_full_r  : std_logic := '0';
  signal bank1_full_r  : std_logic := '0';
  signal sample_index_r : integer range 0 to G_POINTS - 1 := 0;
  signal input_pause_r  : std_logic := '0';

  signal output_active_r : std_logic := '0';
  signal output_bank_r   : std_logic := '0';
  signal output_index_r  : integer range 0 to G_POINTS - 1 := 0;
  signal done_r          : std_logic := '0';

  signal input_ready_i : std_logic;
  signal output_stalled_i : std_logic;
  signal active_full_i : std_logic;
  signal overlap_ready_i : std_logic;
  signal collecting_i : std_logic;
  signal out_re_i : acc_t;
  signal out_im_i : acc_t;
  signal sample_re_i : input_t;
  signal sample_im_i : input_t;
  signal mul_valid_i : std_logic;
  signal tw_re_i : twiddle_array_t(0 to G_POINTS - 1);
  signal tw_im_i : twiddle_array_t(0 to G_POINTS - 1);
  signal rr_p : acc_array_t(0 to G_POINTS - 1);
  signal ii_p : acc_array_t(0 to G_POINTS - 1);
  signal ri_p : acc_array_t(0 to G_POINTS - 1);
  signal ir_p : acc_array_t(0 to G_POINTS - 1);
  signal rr_valid : std_logic_vector(0 to G_POINTS - 1);
  signal product_valid_i : std_logic;
  signal product_active_bank_pipe : std_logic_vector(3 downto 0) := (others => '0');
  type index_pipe_t is array (0 to 3) of integer range 0 to G_POINTS - 1;
  signal product_index_pipe : index_pipe_t := (others => 0);

  function high_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value(value'left downto value'length / 2);
  end function;

  function low_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value((value'length / 2) - 1 downto 0);
  end function;

  function scaled_output(value : acc_t) return signed is
    variable scaled : acc_t;
  begin
    if G_SCALE_EACH_STAGE then
      scaled := shift_right(value, C_SCALE_SHIFT);
    else
      scaled := value;
    end if;
    return resize(scaled, G_OUTPUT_WIDTH);
  end function;

  function const_mod_sum(value : natural; repeats : natural; modulus : positive) return natural is
    variable result : natural := 0;
  begin
    if repeats > 0 then
      for i in 1 to repeats loop
        result := result + value;
        if result >= modulus then
          result := result - modulus;
        end if;
      end loop;
    end if;
    return result;
  end function;
begin
  assert G_POINTS <= G_MAX_POINTS report "G_POINTS must not exceed G_MAX_POINTS" severity failure;
  assert G_POINTS <= 64 report "streaming RADFFT currently supports up to 64 points" severity failure;
  assert is_power_of_two(G_POINTS) report "streaming RADFFT G_POINTS must be a power of two" severity failure;
  assert G_RADIX = 2 or G_RADIX = 4 report "streaming RADFFT G_RADIX must be 2 or 4" severity failure;
  assert G_RADIX = 2 or is_power_of_four(G_POINTS) report "streaming RADFFT G_RADIX=4 requires points to be a power of four" severity failure;
  assert G_TWIDDLE_WIDTH >= 2 report "streaming RADFFT G_TWIDDLE_WIDTH must be at least 2" severity failure;
  assert G_MULTIPLIER_LANES = 1 report "streaming RADFFT currently uses the fully parallel small-FFT engine; lane-limited large streaming FFT scheduling is reserved by the public generic" severity failure;
  assert G_MAX_MULTIPLIER_LANES <= 16 report "streaming RADFFT G_MAX_MULTIPLIER_LANES maximum supported value is 16" severity failure;

  output_stalled_i <= output_active_r and (not m_axis_tready);
  active_full_i <= bank0_full_r when active_bank_r = '0' else bank1_full_r;
  overlap_ready_i <= '1' when G_OVERLAP_FRAMES or sample_index_r /= 0 or (output_active_r = '0' and bank0_full_r = '0' and bank1_full_r = '0') else '0';
  collecting_i <= '1' when sample_index_r /= 0 else '0';
  input_ready_i <= '1' when output_stalled_i = '0' and active_full_i = '0' and input_pause_r = '0' and overlap_ready_i = '1' else '0';
  s_axis_tready <= input_ready_i;
  mul_valid_i <= s_axis_tvalid and input_ready_i;
  sample_re_i <= signed(high_half(s_axis_tdata));
  sample_im_i <= signed(low_half(s_axis_tdata));

  m_axis_tvalid <= output_active_r;
  out_re_i <= bank1_re(output_index_r) when output_bank_r = '1' else bank0_re(output_index_r);
  out_im_i <= bank1_im(output_index_r) when output_bank_r = '1' else bank0_im(output_index_r);
  m_axis_tdata <= std_logic_vector(scaled_output(out_re_i)) & std_logic_vector(scaled_output(out_im_i));
  m_axis_tlast <= '1' when output_active_r = '1' and output_index_r = G_POINTS - 1 else '0';
  twiddle_addr_o <= (others => '0');
  busy_o <= output_active_r or bank0_full_r or bank1_full_r or collecting_i;
  frame_done_o <= done_r;

  gen_twiddle : for bin in 0 to G_POINTS - 1 generate
    constant C_BIN : natural := bin;
  begin
    tw_re_i(bin) <= to_signed(radfft_twiddle_re(G_POINTS, const_mod_sum(sample_index_r, C_BIN, G_POINTS), G_TWIDDLE_WIDTH), G_TWIDDLE_WIDTH);
    tw_im_i(bin) <= to_signed(radfft_twiddle_im(G_POINTS, const_mod_sum(sample_index_r, C_BIN, G_POINTS), G_TWIDDLE_WIDTH, G_INVERSE_FFT), G_TWIDDLE_WIDTH);

    rr_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
      generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => G_INPUT_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_ACC_WIDTH)
      port map (clk => clk, rst => rst, valid_i => mul_valid_i, a_i => sample_re_i, b_i => tw_re_i(bin), valid_o => rr_valid(bin), p_o => rr_p(bin));

    ii_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
      generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => G_INPUT_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_ACC_WIDTH)
      port map (clk => clk, rst => rst, valid_i => mul_valid_i, a_i => sample_im_i, b_i => tw_im_i(bin), valid_o => open, p_o => ii_p(bin));

    ri_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
      generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => G_INPUT_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_ACC_WIDTH)
      port map (clk => clk, rst => rst, valid_i => mul_valid_i, a_i => sample_re_i, b_i => tw_im_i(bin), valid_o => open, p_o => ri_p(bin));

    ir_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
      generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => G_INPUT_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_ACC_WIDTH)
      port map (clk => clk, rst => rst, valid_i => mul_valid_i, a_i => sample_im_i, b_i => tw_re_i(bin), valid_o => open, p_o => ir_p(bin));
  end generate;

  product_valid_i <= rr_valid(0);

  process(clk)
    variable pr : acc_t;
    variable pi : acc_t;
  begin
    if rising_edge(clk) then
      done_r <= '0';

      if rst = '1' then
        bank0_re <= (others => (others => '0'));
        bank0_im <= (others => (others => '0'));
        bank1_re <= (others => (others => '0'));
        bank1_im <= (others => (others => '0'));
        active_bank_r <= '0';
        bank0_full_r <= '0';
        bank1_full_r <= '0';
        sample_index_r <= 0;
        input_pause_r <= '0';
        output_active_r <= '0';
        output_bank_r <= '0';
        output_index_r <= 0;
        product_active_bank_pipe <= (others => '0');
        product_index_pipe <= (others => 0);
      else
        product_active_bank_pipe(3 downto 1) <= product_active_bank_pipe(2 downto 0);
        product_index_pipe(3) <= product_index_pipe(2);
        product_index_pipe(2) <= product_index_pipe(1);
        product_index_pipe(1) <= product_index_pipe(0);
        if mul_valid_i = '1' then
          product_active_bank_pipe(0) <= active_bank_r;
          product_index_pipe(0) <= sample_index_r;
        else
          product_active_bank_pipe(0) <= '0';
          product_index_pipe(0) <= 0;
        end if;

        if output_active_r = '1' and m_axis_tready = '1' then
          if output_index_r = G_POINTS - 1 then
            output_active_r <= '0';
            output_index_r <= 0;
            done_r <= '1';
            if output_bank_r = '0' then
              bank0_full_r <= '0';
            else
              bank1_full_r <= '0';
            end if;
          else
            output_index_r <= output_index_r + 1;
          end if;
        elsif output_active_r = '0' then
          if bank0_full_r = '1' then
            output_active_r <= '1';
            output_bank_r <= '0';
            output_index_r <= 0;
          elsif bank1_full_r = '1' then
            output_active_r <= '1';
            output_bank_r <= '1';
            output_index_r <= 0;
          end if;
        end if;

        if product_valid_i = '1' then
          for bin in 0 to G_POINTS - 1 loop
            pr := shift_right(rr_p(bin) - ii_p(bin), C_TWIDDLE_SHIFT);
            pi := shift_right(ri_p(bin) + ir_p(bin), C_TWIDDLE_SHIFT);

            if product_active_bank_pipe(3) = '0' then
              if product_index_pipe(3) = 0 then
                bank0_re(bin) <= pr;
                bank0_im(bin) <= pi;
              else
                bank0_re(bin) <= bank0_re(bin) + pr;
                bank0_im(bin) <= bank0_im(bin) + pi;
              end if;
            else
              if product_index_pipe(3) = 0 then
                bank1_re(bin) <= pr;
                bank1_im(bin) <= pi;
              else
                bank1_re(bin) <= bank1_re(bin) + pr;
                bank1_im(bin) <= bank1_im(bin) + pi;
              end if;
            end if;
          end loop;

          if product_index_pipe(3) = G_POINTS - 1 then
            if product_active_bank_pipe(3) = '0' then
              bank0_full_r <= '1';
              active_bank_r <= '1';
            else
              bank1_full_r <= '1';
              active_bank_r <= '0';
            end if;
            input_pause_r <= '0';
          end if;
        end if;

        if s_axis_tvalid = '1' and input_ready_i = '1' then
          if sample_index_r = G_POINTS - 1 then
            sample_index_r <= 0;
            input_pause_r <= '1';
          else
            sample_index_r <= sample_index_r + 1;
          end if;
        end if;
      end if;
    end if;
  end process;
end architecture;
