library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Batch-oriented AXI-stream RadFFT implementation.
-- Buffers a complete frame, computes the transform, and streams the transformed frame out with deterministic frame timing.
entity raddsp_axis_radfft_batch is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR               : string := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY        : string := "ultrascale+";
    -- Sets the transform, frame, or vector size used by the datapath.
    G_POINTS             : positive := 16;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_MAX_POINTS         : positive := 2048;
    -- Configures G RADIX for this instance.
    G_RADIX              : positive := 2;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_INVERSE_FFT        : boolean := false;
    -- Sets the bit width for G INPUT WIDTH values carried by this module.
    G_INPUT_WIDTH        : positive := 16;
    -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
    G_TWIDDLE_WIDTH      : positive := 16;
    -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
    G_OUTPUT_WIDTH       : positive := 32;
    -- Configures G SCALE EACH STAGE for this instance.
    G_SCALE_EACH_STAGE   : boolean := true;
    -- Configures G MEMORY STYLE for this instance.
    G_MEMORY_STYLE       : string := "block"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk          : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst          : in  std_logic;
    -- Input AXI-stream valid qualifier for the current sample beat.
    s_axis_tvalid : in  std_logic;
    -- Input AXI-stream ready response indicating this block can accept a beat.
    s_axis_tready : out std_logic;
    -- Input AXI-stream payload containing packed sample or feature lanes.
    s_axis_tdata  : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
    -- Input AXI-stream frame marker for the final beat of a frame.
    s_axis_tlast  : in  std_logic;
    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready : in  std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata  : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast  : out std_logic;
    -- Output twiddle addr o signal generated by this module.
    twiddle_addr_o : out std_logic_vector(31 downto 0);
    -- Input twiddle re i signal for this module.
    twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Input twiddle im i signal for this module.
    twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Output busy o signal generated by this module.
    busy_o          : out std_logic;
    -- Output frame done o signal generated by this module.
    frame_done_o    : out std_logic
  );
end entity;

architecture rtl of raddsp_axis_radfft_batch is
  type state_t is (ST_IDLE, ST_START, ST_SEND_HELD, ST_COLLECT, ST_RUN_OUTPUT);

  signal state_r : state_t := ST_IDLE;
  signal held_re_r : std_logic_vector(G_INPUT_WIDTH - 1 downto 0) := (others => '0');
  signal held_im_r : std_logic_vector(G_INPUT_WIDTH - 1 downto 0) := (others => '0');
  signal accepted_count_r : integer range 0 to G_MAX_POINTS := 0;

  signal core_start : std_logic := '0';
  signal core_sample_valid : std_logic;
  signal core_sample_ready : std_logic;
  signal core_sample_re : integer := 0;
  signal core_sample_im : integer := 0;
  signal core_twiddle_addr : integer range 0 to G_MAX_POINTS / 2 - 1 := 0;
  signal core_twiddle_im : integer := 0;
  signal core_busy : std_logic;
  signal core_done : std_logic;
  signal core_output_valid : std_logic;
  signal core_output_index : integer range 0 to G_MAX_POINTS - 1 := 0;
  signal core_output_re : integer := 0;
  signal core_output_im : integer := 0;

  function high_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value(value'left downto value'length / 2);
  end function;

  function low_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value((value'length / 2) - 1 downto 0);
  end function;
begin
  s_axis_tready <= '1' when state_r = ST_IDLE else
                   core_sample_ready when state_r = ST_COLLECT else
                   '0';

  core_sample_valid <= '1' when state_r = ST_SEND_HELD and core_sample_ready = '1' else
                       s_axis_tvalid when state_r = ST_COLLECT and core_sample_ready = '1' else
                       '0';
  core_sample_re <= to_integer(signed(held_re_r)) when state_r = ST_SEND_HELD else
                    to_integer(signed(high_half(s_axis_tdata)));
  core_sample_im <= to_integer(signed(held_im_r)) when state_r = ST_SEND_HELD else
                    to_integer(signed(low_half(s_axis_tdata)));
  core_twiddle_im <= -to_integer(signed(twiddle_im_i)) when G_INVERSE_FFT else
                     to_integer(signed(twiddle_im_i));

  twiddle_addr_o <= std_logic_vector(to_unsigned(core_twiddle_addr, 32));
  m_axis_tvalid <= core_output_valid;
  m_axis_tdata <= std_logic_vector(to_signed(core_output_re, G_OUTPUT_WIDTH)) &
                  std_logic_vector(to_signed(core_output_im, G_OUTPUT_WIDTH));
  m_axis_tlast <= '1' when core_output_valid = '1' and core_output_index = G_POINTS - 1 else '0';
  busy_o <= '1' when state_r /= ST_IDLE else core_busy;
  frame_done_o <= core_done;

  process(clk)
  begin
    if rising_edge(clk) then
      core_start <= '0';

      if rst = '1' then
        state_r <= ST_IDLE;
        held_re_r <= (others => '0');
        held_im_r <= (others => '0');
        accepted_count_r <= 0;
      else
        case state_r is
          when ST_IDLE =>
            accepted_count_r <= 0;
            if s_axis_tvalid = '1' then
              held_re_r <= high_half(s_axis_tdata);
              held_im_r <= low_half(s_axis_tdata);
              state_r <= ST_START;
            end if;

          when ST_START =>
            core_start <= '1';
            state_r <= ST_SEND_HELD;

          when ST_SEND_HELD =>
            if core_sample_ready = '1' then
              accepted_count_r <= 1;
              if G_POINTS = 1 then
                state_r <= ST_RUN_OUTPUT;
              else
                state_r <= ST_COLLECT;
              end if;
            end if;

          when ST_COLLECT =>
            if s_axis_tvalid = '1' and core_sample_ready = '1' then
              if accepted_count_r = G_POINTS - 1 then
                state_r <= ST_RUN_OUTPUT;
              end if;
              accepted_count_r <= accepted_count_r + 1;
            end if;

          when ST_RUN_OUTPUT =>
            if core_done = '1' then
              state_r <= ST_IDLE;
            end if;
        end case;
      end if;
    end if;
  end process;

  core_i: entity work.fft_radix2_batch_core
    generic map (
      VENDOR => VENDOR,
      DEVICE_FAMILY => DEVICE_FAMILY,
      G_POINTS => G_POINTS,
      G_MAX_POINTS => G_MAX_POINTS,
      G_RADIX => G_RADIX,
      G_INPUT_WIDTH => G_INPUT_WIDTH,
      G_TWIDDLE_WIDTH => G_TWIDDLE_WIDTH,
      G_OUTPUT_WIDTH => G_OUTPUT_WIDTH,
      G_SCALE_EACH_STAGE => G_SCALE_EACH_STAGE,
      G_MEMORY_STYLE => G_MEMORY_STYLE
    )
    port map (
      clk => clk,
      rst => rst,
      start_frame => core_start,
      sample_valid => core_sample_valid,
      sample_re => core_sample_re,
      sample_im => core_sample_im,
      sample_ready => core_sample_ready,
      twiddle_addr => core_twiddle_addr,
      twiddle_re => to_integer(signed(twiddle_re_i)),
      twiddle_im => core_twiddle_im,
      busy => core_busy,
      done => core_done,
      output_ready => m_axis_tready,
      output_valid => core_output_valid,
      output_index => core_output_index,
      output_re => core_output_re,
      output_im => core_output_im
    );
end architecture;
