library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.math_real.all;

-- Eight-lane parallel AXI-stream RadFFT engine.
-- Processes multiple samples per cycle for high-throughput spectral pipelines on larger FPGA devices.
entity raddsp_axis_radfft_parallel8 is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR               : string := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY        : string := "ultrascaleplus";
    -- Sets the transform, frame, or vector size used by the datapath.
    G_POINTS             : positive := 1024;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_MAX_POINTS         : positive := 1024;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_INVERSE_FFT        : boolean := false;
    -- Sets the bit width for G INPUT WIDTH values carried by this module.
    G_INPUT_WIDTH        : positive := 32;
    -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
    G_TWIDDLE_WIDTH      : positive := 16;
    -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
    G_OUTPUT_WIDTH       : positive := 32;
    -- Configures G SCALE EACH STAGE for this instance.
    G_SCALE_EACH_STAGE   : boolean := true;
    -- Sets the number of parallel sample lanes processed per handshake beat.
    G_MULTIPLIER_LANES   : positive := 8
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk            : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst            : in  std_logic;
    -- Input AXI-stream valid qualifier for the current sample beat.
    s_axis_tvalid  : in  std_logic;
    -- Input AXI-stream ready response indicating this block can accept a beat.
    s_axis_tready  : out std_logic;
    -- Input AXI-stream payload containing packed sample or feature lanes.
    s_axis_tdata   : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
    -- Input AXI-stream frame marker for the final beat of a frame.
    s_axis_tlast   : in  std_logic;
    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid  : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready  : in  std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata   : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast   : out std_logic;
    -- Input runtime inverse i signal for this module.
    runtime_inverse_i : in std_logic := '0';
    -- Input active point log2 i signal for this module.
    active_point_log2_i : in std_logic_vector(7 downto 0) := (others => '0');
    -- Input active radix4 i signal for this module.
    active_radix4_i     : in std_logic := '0';
    -- Input active input width i signal for this module.
    active_input_width_i : in std_logic_vector(7 downto 0) := (others => '0');
    -- Input active output width i signal for this module.
    active_output_width_i : in std_logic_vector(7 downto 0) := (others => '0');
    -- Output twiddle addr o signal generated by this module.
    twiddle_addr_o : out std_logic_vector(31 downto 0);
    -- Input twiddle re i signal for this module.
    twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Input twiddle im i signal for this module.
    twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Output busy o signal generated by this module.
    busy_o         : out std_logic;
    -- Output frame done o signal generated by this module.
    frame_done_o   : out std_logic
  );
end entity;

architecture rtl of raddsp_axis_radfft_parallel8 is
  function clog2(value : positive) return natural is
    variable v : natural := value - 1;
    variable result : natural := 0;
  begin
    while v > 0 loop
      v := v / 2;
      result := result + 1;
    end loop;
    return result;
  end function;

  constant C_MAX_POINT_LOG2 : positive := clog2(G_MAX_POINTS);
  constant C_TWIDDLE_SHIFT  : natural := G_TWIDDLE_WIDTH - 2;
  constant C_ACC_WIDTH      : positive := G_INPUT_WIDTH + G_TWIDDLE_WIDTH + C_MAX_POINT_LOG2 + 4;
  constant C_MUL_WIDTH      : positive := C_ACC_WIDTH + G_TWIDDLE_WIDTH;
  constant C_LANES          : positive := G_MULTIPLIER_LANES;

  subtype acc_t is signed(C_ACC_WIDTH - 1 downto 0);
  subtype mul_t is signed(C_MUL_WIDTH - 1 downto 0);
  type acc_array_t is array (0 to G_MAX_POINTS - 1) of acc_t;

  type state_t is (ST_LOAD, ST_COMPUTE, ST_OUTPUT, ST_DONE);

  signal state_r : state_t := ST_LOAD;
  signal data_re_r : acc_array_t := (others => (others => '0'));
  signal data_im_r : acc_array_t := (others => (others => '0'));
  signal load_index_r : natural range 0 to G_MAX_POINTS := 0;
  signal output_index_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal stage_size_r : natural range 2 to G_MAX_POINTS := 2;
  signal group_base_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal butterfly_j_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal active_point_log2_r : natural range 1 to C_MAX_POINT_LOG2 := clog2(G_POINTS);
  signal active_points_r : natural range 2 to G_MAX_POINTS := G_POINTS;
  signal active_inverse_r : std_logic := '0';
  signal out_valid_r : std_logic := '0';
  signal out_last_r : std_logic := '0';
  signal out_data_r : std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0) := (others => '0');
  signal done_r : std_logic := '0';

  function pow2(value : natural) return natural is
    variable ret : natural := 1;
  begin
    for i in 1 to C_MAX_POINT_LOG2 loop
      if i <= value then
        ret := ret * 2;
      end if;
    end loop;
    return ret;
  end function;

  function sanitize_log2(value : std_logic_vector(7 downto 0)) return natural is
    variable requested : natural := to_integer(unsigned(value));
  begin
    if requested = 0 then
      return clog2(G_POINTS);
    elsif requested < 1 then
      return 1;
    elsif requested > C_MAX_POINT_LOG2 then
      return C_MAX_POINT_LOG2;
    end if;
    return requested;
  end function;

  function bit_reverse(value : natural; bits : natural) return natural is
    variable v : natural := value;
    variable r : natural := 0;
  begin
    for i in 0 to C_MAX_POINT_LOG2 - 1 loop
      if i < bits then
        r := r + r + (v mod 2);
        v := v / 2;
      end if;
    end loop;
    return r;
  end function;

  function high_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value(value'left downto value'length / 2);
  end function;

  function low_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value((value'length / 2) - 1 downto 0);
  end function;

  function twiddle_re(points : positive; exponent : natural) return signed is
    variable angle : real;
    variable scale : real := real(2 ** (G_TWIDDLE_WIDTH - 2));
    variable value : integer;
  begin
    angle := -2.0 * MATH_PI * real(exponent mod points) / real(points);
    value := integer(round(cos(angle) * scale));
    return to_signed(value, G_TWIDDLE_WIDTH);
  end function;

  function twiddle_im(points : positive; exponent : natural; inverse_fft : boolean) return signed is
    variable angle : real;
    variable scale : real := real(2 ** (G_TWIDDLE_WIDTH - 2));
    variable value : integer;
  begin
    angle := -2.0 * MATH_PI * real(exponent mod points) / real(points);
    if inverse_fft then
      angle := -angle;
    end if;
    value := integer(round(sin(angle) * scale));
    return to_signed(value, G_TWIDDLE_WIDTH);
  end function;

  function scaled_output(value : acc_t; scale_shift : natural) return signed is
    variable scaled : acc_t;
  begin
    if G_SCALE_EACH_STAGE then
      scaled := shift_right(value, scale_shift);
    else
      scaled := value;
    end if;
    return resize(scaled, G_OUTPUT_WIDTH);
  end function;
begin
  assert G_MULTIPLIER_LANES = 8 or G_MULTIPLIER_LANES = 16 or G_MULTIPLIER_LANES = 32
    report "raddsp_axis_radfft_parallel8 supports 8, 16, or 32 butterfly lanes"
    severity failure;
  assert G_TWIDDLE_WIDTH <= 30
    report "raddsp_axis_radfft_parallel8 twiddle width must fit integer real conversion"
    severity failure;

  s_axis_tready <= '1' when state_r = ST_LOAD and load_index_r < active_points_r else '0';
  m_axis_tvalid <= out_valid_r;
  m_axis_tlast <= out_last_r;
  m_axis_tdata <= out_data_r;
  twiddle_addr_o <= (others => '0');
  busy_o <= '0' when state_r = ST_LOAD and load_index_r = 0 and out_valid_r = '0' else '1';
  frame_done_o <= done_r;

  process(clk)
    variable next_log2 : natural;
    variable next_points : natural;
    variable load_idx : natural;
    variable half_v : natural;
    variable lane_j : natural;
    variable idx0 : natural;
    variable idx1 : natural;
    variable tw_exp : natural;
    variable tw_re_v : signed(G_TWIDDLE_WIDTH - 1 downto 0);
    variable tw_im_v : signed(G_TWIDDLE_WIDTH - 1 downto 0);
    variable x0_re : acc_t;
    variable x0_im : acc_t;
    variable x1_re : acc_t;
    variable x1_im : acc_t;
    variable rr : mul_t;
    variable ii : mul_t;
    variable ri : mul_t;
    variable ir : mul_t;
    variable t_re : acc_t;
    variable t_im : acc_t;
    variable lanes_this_cycle : natural;
    variable out_re : acc_t;
    variable out_im : acc_t;
  begin
    if rising_edge(clk) then
      done_r <= '0';

      if rst = '1' then
        state_r <= ST_LOAD;
        load_index_r <= 0;
        output_index_r <= 0;
        stage_size_r <= 2;
        group_base_r <= 0;
        butterfly_j_r <= 0;
        active_point_log2_r <= clog2(G_POINTS);
        active_points_r <= G_POINTS;
        active_inverse_r <= '0';
        out_valid_r <= '0';
        out_last_r <= '0';
        out_data_r <= (others => '0');
      else
        case state_r is
          when ST_LOAD =>
            out_valid_r <= '0';
            out_last_r <= '0';
            if s_axis_tvalid = '1' and s_axis_tready = '1' then
              if load_index_r = 0 then
                next_log2 := sanitize_log2(active_point_log2_i);
                next_points := pow2(next_log2);
                active_point_log2_r <= next_log2;
                active_points_r <= next_points;
                active_inverse_r <= runtime_inverse_i;
              else
                next_log2 := active_point_log2_r;
                next_points := active_points_r;
              end if;

              load_idx := bit_reverse(load_index_r, next_log2);
              data_re_r(load_idx) <= resize(signed(high_half(s_axis_tdata)), C_ACC_WIDTH);
              data_im_r(load_idx) <= resize(signed(low_half(s_axis_tdata)), C_ACC_WIDTH);

              if load_index_r = next_points - 1 then
                load_index_r <= 0;
                stage_size_r <= 2;
                group_base_r <= 0;
                butterfly_j_r <= 0;
                state_r <= ST_COMPUTE;
              else
                load_index_r <= load_index_r + 1;
              end if;
            end if;

          when ST_COMPUTE =>
            half_v := stage_size_r / 2;
            lanes_this_cycle := C_LANES;
            for lane in 0 to C_LANES - 1 loop
              lane_j := butterfly_j_r + lane;
              if lane_j < half_v then
                idx0 := group_base_r + lane_j;
                idx1 := idx0 + half_v;
                tw_exp := lane_j * (active_points_r / stage_size_r);
                tw_re_v := twiddle_re(active_points_r, tw_exp);
                tw_im_v := twiddle_im(active_points_r, tw_exp, G_INVERSE_FFT or active_inverse_r = '1');

                x0_re := data_re_r(idx0);
                x0_im := data_im_r(idx0);
                x1_re := data_re_r(idx1);
                x1_im := data_im_r(idx1);

                rr := resize(x1_re * tw_re_v, C_MUL_WIDTH);
                ii := resize(x1_im * tw_im_v, C_MUL_WIDTH);
                ri := resize(x1_re * tw_im_v, C_MUL_WIDTH);
                ir := resize(x1_im * tw_re_v, C_MUL_WIDTH);
                t_re := resize(shift_right(rr - ii, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
                t_im := resize(shift_right(ri + ir, C_TWIDDLE_SHIFT), C_ACC_WIDTH);

                data_re_r(idx0) <= x0_re + t_re;
                data_im_r(idx0) <= x0_im + t_im;
                data_re_r(idx1) <= x0_re - t_re;
                data_im_r(idx1) <= x0_im - t_im;
              end if;
            end loop;

            if butterfly_j_r + lanes_this_cycle >= half_v then
              butterfly_j_r <= 0;
              if group_base_r + stage_size_r >= active_points_r then
                group_base_r <= 0;
                if stage_size_r >= active_points_r then
                  output_index_r <= 0;
                  state_r <= ST_OUTPUT;
                else
                  stage_size_r <= stage_size_r + stage_size_r;
                end if;
              else
                group_base_r <= group_base_r + stage_size_r;
              end if;
            else
              butterfly_j_r <= butterfly_j_r + lanes_this_cycle;
            end if;

          when ST_OUTPUT =>
            if out_valid_r = '0' or m_axis_tready = '1' then
              out_re := data_re_r(output_index_r);
              out_im := data_im_r(output_index_r);
              out_data_r <= std_logic_vector(scaled_output(out_re, active_point_log2_r)) &
                            std_logic_vector(scaled_output(out_im, active_point_log2_r));
              out_valid_r <= '1';
              out_last_r <= '1' when output_index_r = active_points_r - 1 else '0';
              if output_index_r = active_points_r - 1 then
                state_r <= ST_DONE;
              else
                output_index_r <= output_index_r + 1;
              end if;
            end if;

          when ST_DONE =>
            if out_valid_r = '1' and m_axis_tready = '1' then
              out_valid_r <= '0';
              out_last_r <= '0';
              done_r <= '1';
              load_index_r <= 0;
              state_r <= ST_LOAD;
            end if;
        end case;
      end if;
    end if;
  end process;
end architecture;
