library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library unisim;
use unisim.vcomponents.all;

-- DSP48-backed signed multiplier wrapper for Xilinx FPGA targets.
-- Standardizes valid/last pipelining around vendor DSP blocks so higher-level RadDSP cores can share one multiplication interface.
entity raddsp_xilinx_dsp48_mul is
  generic (
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY : string := "7series";
    -- Sets the bit width for A WIDTH values carried by this module.
    A_WIDTH       : positive := 16;
    -- Sets the bit width for B WIDTH values carried by this module.
    B_WIDTH       : positive := 18
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk        : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst        : in  std_logic;
    -- Input valid qualifier for this operation or sideband channel.
    valid_i    : in  std_logic;
    -- Input subtract i signal for this module.
    subtract_i : in  std_logic;
    -- Input last i signal for this module.
    last_i     : in  std_logic;
    -- Input a i signal for this module.
    a_i        : in  signed(A_WIDTH - 1 downto 0);
    -- Input b i signal for this module.
    b_i        : in  signed(B_WIDTH - 1 downto 0);
    -- Output valid qualifier aligned with the produced result.
    valid_o    : out std_logic;
    -- Output subtract o signal generated by this module.
    subtract_o : out std_logic;
    -- Output last o signal generated by this module.
    last_o     : out std_logic;
    -- Output p o signal generated by this module.
    p_o        : out signed(47 downto 0)
  );
end entity;

architecture rtl of raddsp_xilinx_dsp48_mul is
  signal a_e1        : std_logic_vector(29 downto 0);
  signal b_dsp       : std_logic_vector(17 downto 0);
  signal p_dsp       : std_logic_vector(47 downto 0);
  signal valid_pipe  : std_logic_vector(1 downto 0) := (others => '0');
  signal sub_pipe    : std_logic_vector(1 downto 0) := (others => '0');
  signal last_pipe   : std_logic_vector(1 downto 0) := (others => '0');

  signal acout_unused        : std_logic_vector(29 downto 0);
  signal bcout_unused        : std_logic_vector(17 downto 0);
  signal carryout_unused     : std_logic_vector(3 downto 0);
  signal pcout_unused        : std_logic_vector(47 downto 0);
  signal carrycascout_unused : std_ulogic;
  signal multsignout_unused  : std_ulogic;
  signal overflow_unused     : std_ulogic;
  signal patbdetect_unused   : std_ulogic;
  signal patdetect_unused    : std_ulogic;
  signal underflow_unused    : std_ulogic;
  signal xorout_unused       : std_logic_vector(7 downto 0);
begin
  assert A_WIDTH <= 25
    report "DSP48E1/E2 direct multiplier wrapper supports A_WIDTH <= 25"
    severity failure;
  assert B_WIDTH <= 18
    report "DSP48E1/E2 direct multiplier wrapper supports B_WIDTH <= 18"
    severity failure;

  a_e1 <= std_logic_vector(resize(a_i, a_e1'length));
  b_dsp <= std_logic_vector(resize(b_i, b_dsp'length));
  p_o <= signed(p_dsp);

  process(clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        valid_pipe <= (others => '0');
        sub_pipe <= (others => '0');
        last_pipe <= (others => '0');
      else
        valid_pipe <= valid_pipe(0) & valid_i;
        sub_pipe <= sub_pipe(0) & subtract_i;
        last_pipe <= last_pipe(0) & last_i;
      end if;
    end if;
  end process;

  valid_o <= valid_pipe(1);
  subtract_o <= sub_pipe(1);
  last_o <= last_pipe(1);

  gen_dsp48e2 : if DEVICE_FAMILY = "ultrascale" or DEVICE_FAMILY = "ultrascaleplus" or DEVICE_FAMILY = "zynqmp" generate
  begin
    dsp_i: DSP48E2
      generic map (
        ACASCREG => 0,
        AREG => 0,
        BCASCREG => 0,
        BREG => 0,
        CREG => 0,
        MREG => 1,
        PREG => 1,
        OPMODEREG => 0,
        ALUMODEREG => 0,
        CARRYINREG => 0,
        CARRYINSELREG => 0,
        INMODEREG => 0,
        USE_MULT => "MULTIPLY",
        USE_SIMD => "ONE48"
      )
      port map (
        ACOUT => acout_unused,
        BCOUT => bcout_unused,
        CARRYCASCOUT => carrycascout_unused,
        CARRYOUT => carryout_unused,
        MULTSIGNOUT => multsignout_unused,
        OVERFLOW => overflow_unused,
        P => p_dsp,
        PATTERNBDETECT => patbdetect_unused,
        PATTERNDETECT => patdetect_unused,
        PCOUT => pcout_unused,
        UNDERFLOW => underflow_unused,
        XOROUT => xorout_unused,
        A => a_e1,
        ACIN => (others => '0'),
        ALUMODE => "0000",
        B => b_dsp,
        BCIN => (others => '0'),
        C => (others => '0'),
        CARRYCASCIN => '0',
        CARRYIN => '0',
        CARRYINSEL => "000",
        CEA1 => '1',
        CEA2 => '1',
        CEAD => '1',
        CEALUMODE => '1',
        CEB1 => '1',
        CEB2 => '1',
        CEC => '1',
        CECARRYIN => '1',
        CECTRL => '1',
        CED => '1',
        CEINMODE => '1',
        CEM => valid_i,
        CEP => valid_pipe(0),
        CLK => clk,
        D => (others => '0'),
        INMODE => "00000",
        MULTSIGNIN => '0',
        OPMODE => "000000101",
        PCIN => (others => '0'),
        RSTA => rst,
        RSTALLCARRYIN => rst,
        RSTALUMODE => rst,
        RSTB => rst,
        RSTC => rst,
        RSTCTRL => rst,
        RSTD => rst,
        RSTINMODE => rst,
        RSTM => rst,
        RSTP => rst
      );
  end generate;

  gen_dsp48e1 : if not (DEVICE_FAMILY = "ultrascale" or DEVICE_FAMILY = "ultrascaleplus" or DEVICE_FAMILY = "zynqmp") generate
  begin
    dsp_i: DSP48E1
      generic map (
        ACASCREG => 0,
        AREG => 0,
        BCASCREG => 0,
        BREG => 0,
        CREG => 0,
        MREG => 1,
        PREG => 1,
        OPMODEREG => 0,
        ALUMODEREG => 0,
        CARRYINREG => 0,
        CARRYINSELREG => 0,
        INMODEREG => 0,
        USE_DPORT => false,
        USE_MULT => "MULTIPLY",
        USE_SIMD => "ONE48"
      )
      port map (
        ACOUT => acout_unused,
        BCOUT => bcout_unused,
        CARRYCASCOUT => carrycascout_unused,
        CARRYOUT => carryout_unused,
        MULTSIGNOUT => multsignout_unused,
        OVERFLOW => overflow_unused,
        P => p_dsp,
        PATTERNBDETECT => patbdetect_unused,
        PATTERNDETECT => patdetect_unused,
        PCOUT => pcout_unused,
        UNDERFLOW => underflow_unused,
        A => a_e1,
        ACIN => (others => '0'),
        ALUMODE => "0000",
        B => b_dsp,
        BCIN => (others => '0'),
        C => (others => '0'),
        CARRYCASCIN => '0',
        CARRYIN => '0',
        CARRYINSEL => "000",
        CEA1 => '1',
        CEA2 => '1',
        CEAD => '1',
        CEALUMODE => '1',
        CEB1 => '1',
        CEB2 => '1',
        CEC => '1',
        CECARRYIN => '1',
        CECTRL => '1',
        CED => '1',
        CEINMODE => '1',
        CEM => valid_i,
        CEP => valid_pipe(0),
        CLK => clk,
        D => (others => '0'),
        INMODE => "00000",
        MULTSIGNIN => '0',
        OPMODE => "0000101",
        PCIN => (others => '0'),
        RSTA => rst,
        RSTALLCARRYIN => rst,
        RSTALUMODE => rst,
        RSTB => rst,
        RSTC => rst,
        RSTCTRL => rst,
        RSTD => rst,
        RSTINMODE => rst,
        RSTM => rst,
        RSTP => rst
      );
  end generate;
end architecture;
