library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.raddsp_fft_twiddle_pkg.all;

-- Iterative AXI-stream RadFFT engine.
-- Reuses butterfly resources across stages to trade latency for a smaller FPGA footprint.
entity raddsp_axis_radfft_iterative is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR               : string := "xilinx";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY        : string := "ultrascale+";
    -- Sets the transform, frame, or vector size used by the datapath.
    G_POINTS             : positive := 1024;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_MAX_POINTS         : positive := 2048;
    -- Configures G RADIX for this instance.
    G_RADIX              : positive := 2;
    -- Sets the transform, frame, or vector size used by the datapath.
    G_INVERSE_FFT        : boolean := false;
    -- Sets the bit width for G INPUT WIDTH values carried by this module.
    G_INPUT_WIDTH        : positive := 16;
    -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
    G_TWIDDLE_WIDTH      : positive := 16;
    -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
    G_OUTPUT_WIDTH       : positive := 32;
    -- Configures G SCALE EACH STAGE for this instance.
    G_SCALE_EACH_STAGE   : boolean := true;
    -- Configures G MEMORY STYLE for this instance.
    G_MEMORY_STYLE       : string := "block";
    -- Sets the number of parallel sample lanes processed per handshake beat.
    G_MULTIPLIER_LANES   : positive := 1;
    -- Sets the number of parallel sample lanes processed per handshake beat.
    G_MAX_MULTIPLIER_LANES : positive := 8
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk            : in  std_logic;
    -- Active-high synchronous reset for this clock domain.
    rst            : in  std_logic;
    -- Input AXI-stream valid qualifier for the current sample beat.
    s_axis_tvalid  : in  std_logic;
    -- Input AXI-stream ready response indicating this block can accept a beat.
    s_axis_tready  : out std_logic;
    -- Input AXI-stream payload containing packed sample or feature lanes.
    s_axis_tdata   : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
    -- Input AXI-stream frame marker for the final beat of a frame.
    s_axis_tlast   : in  std_logic;
    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid  : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready  : in  std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata   : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast   : out std_logic;
    -- Output twiddle addr o signal generated by this module.
    twiddle_addr_o : out std_logic_vector(31 downto 0);
    -- Input twiddle re i signal for this module.
    twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Input twiddle im i signal for this module.
    twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
    -- Output busy o signal generated by this module.
    busy_o         : out std_logic;
    -- Output frame done o signal generated by this module.
    frame_done_o   : out std_logic
  );
end entity;

architecture rtl of raddsp_axis_radfft_iterative is
  function is_power_of_two(value : positive) return boolean is
    variable v : positive := value;
  begin
    while (v mod 2) = 0 loop
      v := v / 2;
    end loop;
    return v = 1;
  end function;

  function is_power_of_four(value : positive) return boolean is
    variable v : positive := value;
  begin
    while (v mod 4) = 0 loop
      v := v / 4;
    end loop;
    return v = 1;
  end function;

  function clog2(value : positive) return natural is
    variable v : natural := value - 1;
    variable result : natural := 0;
  begin
    while v > 0 loop
      v := v / 2;
      result := result + 1;
    end loop;
    return result;
  end function;

  function bit_reverse(value : natural; bits : natural) return natural is
    variable v : natural := value;
    variable r : natural := 0;
  begin
    for i in 0 to bits - 1 loop
      r := (r * 2) + (v mod 2);
      v := v / 2;
    end loop;
    return r;
  end function;

  function base4_reverse(value : natural; digits : natural) return natural is
    variable v : natural := value;
    variable r : natural := 0;
  begin
    for i in 0 to digits - 1 loop
      r := (r * 4) + (v mod 4);
      v := v / 4;
    end loop;
    return r;
  end function;

  function output_permutation(value : natural) return natural is
  begin
    if G_RADIX = 4 then
      return base4_reverse(value, clog2(G_POINTS) / 2);
    end if;
    return bit_reverse(value, clog2(G_POINTS));
  end function;

  function high_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value(value'left downto value'length / 2);
  end function;

  function low_half(value : std_logic_vector) return std_logic_vector is
  begin
    return value((value'length / 2) - 1 downto 0);
  end function;

  constant C_SCALE_SHIFT   : natural := clog2(G_POINTS);
  constant C_TWIDDLE_SHIFT : natural := G_TWIDDLE_WIDTH - 2;
  constant C_ACC_WIDTH     : positive := G_INPUT_WIDTH + G_TWIDDLE_WIDTH + C_SCALE_SHIFT + 4;
  constant C_MUL_WIDTH     : positive := C_ACC_WIDTH + G_TWIDDLE_WIDTH;
  constant C_INDEX_WIDTH   : positive := clog2(G_MAX_POINTS);

  subtype acc_t is signed(C_ACC_WIDTH - 1 downto 0);
  subtype mul_t is signed(C_MUL_WIDTH - 1 downto 0);
  type acc_mem_t is array (0 to G_MAX_POINTS - 1) of acc_t;

  type state_t is (
    ST_LOAD,
    ST_R2_START,
    ST_R2_WAIT,
    ST_R4_MUL1_START,
    ST_R4_MUL1_WAIT,
    ST_R4_MUL2_START,
    ST_R4_MUL2_WAIT,
    ST_R4_MUL3_START,
    ST_R4_MUL3_WAIT,
    ST_OUTPUT,
    ST_DONE
  );

  signal state_r : state_t := ST_LOAD;
  signal mem_re : acc_mem_t := (others => (others => '0'));
  signal mem_im : acc_mem_t := (others => (others => '0'));

  signal load_index_r  : natural range 0 to G_MAX_POINTS := 0;
  signal output_index_r : natural range 0 to G_MAX_POINTS - 1 := 0;

  signal stage_size_r  : natural range 2 to G_MAX_POINTS := 2;
  signal group_base_r  : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal butterfly_j_r : natural range 0 to G_MAX_POINTS - 1 := 0;

  signal idx0_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal idx1_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal idx2_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal idx3_r : natural range 0 to G_MAX_POINTS - 1 := 0;

  signal x0_re_r : acc_t := (others => '0');
  signal x0_im_r : acc_t := (others => '0');
  signal x1_re_r : acc_t := (others => '0');
  signal x1_im_r : acc_t := (others => '0');
  signal x2_re_r : acc_t := (others => '0');
  signal x2_im_r : acc_t := (others => '0');
  signal x3_re_r : acc_t := (others => '0');
  signal x3_im_r : acc_t := (others => '0');
  signal t1_re_r : acc_t := (others => '0');
  signal t1_im_r : acc_t := (others => '0');
  signal t2_re_r : acc_t := (others => '0');
  signal t2_im_r : acc_t := (others => '0');
  signal t3_re_r : acc_t := (others => '0');
  signal t3_im_r : acc_t := (others => '0');

  signal tw_exp_r : natural range 0 to G_MAX_POINTS - 1 := 0;
  signal tw_re_s  : signed(G_TWIDDLE_WIDTH - 1 downto 0);
  signal tw_im_s  : signed(G_TWIDDLE_WIDTH - 1 downto 0);
  signal mul_valid_r : std_logic := '0';
  signal mul_a_re_r  : acc_t := (others => '0');
  signal mul_a_im_r  : acc_t := (others => '0');

  signal rr_p : mul_t;
  signal ii_p : mul_t;
  signal ri_p : mul_t;
  signal ir_p : mul_t;
  signal rr_valid : std_logic;

  signal out_valid_r : std_logic := '0';
  signal out_last_r  : std_logic := '0';
  signal out_data_r  : std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0) := (others => '0');
  signal done_r      : std_logic := '0';

  function scaled_output(value : acc_t) return signed is
    variable scaled : acc_t;
  begin
    if G_SCALE_EACH_STAGE then
      scaled := shift_right(value, C_SCALE_SHIFT);
    else
      scaled := value;
    end if;
    return resize(scaled, G_OUTPUT_WIDTH);
  end function;

  procedure complex_product(
    signal rr : in mul_t;
    signal ii : in mul_t;
    signal ri : in mul_t;
    signal ir : in mul_t;
    variable out_re : out acc_t;
    variable out_im : out acc_t
  ) is
  begin
    out_re := resize(shift_right(rr - ii, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
    out_im := resize(shift_right(ri + ir, C_TWIDDLE_SHIFT), C_ACC_WIDTH);
  end procedure;
begin
  assert G_POINTS <= G_MAX_POINTS report "iterative RADFFT G_POINTS must not exceed G_MAX_POINTS" severity failure;
  assert is_power_of_two(G_POINTS) report "iterative RADFFT G_POINTS must be a power of two" severity failure;
  assert G_RADIX = 2 or G_RADIX = 4 report "iterative RADFFT G_RADIX must be 2 or 4" severity failure;
  assert G_RADIX = 2 or is_power_of_four(G_POINTS) report "iterative RADFFT G_RADIX=4 requires points to be a power of four" severity failure;
  assert G_TWIDDLE_WIDTH >= 2 report "iterative RADFFT G_TWIDDLE_WIDTH must be at least 2" severity failure;
  assert G_POINTS <= 1024 report "iterative RADFFT currently supports up to 1024 points" severity failure;
  assert G_MULTIPLIER_LANES = 1 report "iterative RADFFT currently validates one complex multiplier lane; wider lane scheduling is reserved by the public generic" severity failure;
  assert G_MAX_MULTIPLIER_LANES <= 16 report "iterative RADFFT G_MAX_MULTIPLIER_LANES maximum supported value is 16" severity failure;

  tw_re_s <= to_signed(radfft_twiddle_re(G_POINTS, tw_exp_r, G_TWIDDLE_WIDTH), G_TWIDDLE_WIDTH);
  tw_im_s <= to_signed(radfft_twiddle_im(G_POINTS, tw_exp_r, G_TWIDDLE_WIDTH, G_INVERSE_FFT), G_TWIDDLE_WIDTH);

  s_axis_tready <= '1' when state_r = ST_LOAD and load_index_r < G_POINTS else '0';
  m_axis_tvalid <= out_valid_r;
  m_axis_tlast <= out_last_r;
  m_axis_tdata <= out_data_r;
  twiddle_addr_o <= std_logic_vector(resize(to_unsigned(tw_exp_r, C_INDEX_WIDTH), 32));
  busy_o <= '0' when state_r = ST_LOAD and load_index_r = 0 and out_valid_r = '0' else '1';
  frame_done_o <= done_r;

  rr_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
    generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => C_ACC_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_MUL_WIDTH)
    port map (clk => clk, rst => rst, valid_i => mul_valid_r, a_i => mul_a_re_r, b_i => tw_re_s, valid_o => rr_valid, p_o => rr_p);

  ii_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
    generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => C_ACC_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_MUL_WIDTH)
    port map (clk => clk, rst => rst, valid_i => mul_valid_r, a_i => mul_a_im_r, b_i => tw_im_s, valid_o => open, p_o => ii_p);

  ri_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
    generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => C_ACC_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_MUL_WIDTH)
    port map (clk => clk, rst => rst, valid_i => mul_valid_r, a_i => mul_a_re_r, b_i => tw_im_s, valid_o => open, p_o => ri_p);

  ir_mul_i: entity work.raddsp_xilinx_dsp48_wide_mul
    generic map (DEVICE_FAMILY => DEVICE_FAMILY, A_WIDTH => C_ACC_WIDTH, B_WIDTH => G_TWIDDLE_WIDTH, PRODUCT_WIDTH => C_MUL_WIDTH)
    port map (clk => clk, rst => rst, valid_i => mul_valid_r, a_i => mul_a_im_r, b_i => tw_re_s, valid_o => open, p_o => ir_p);

  process(clk)
    variable t_re : acc_t;
    variable t_im : acc_t;
    variable a_re : acc_t;
    variable a_im : acc_t;
    variable b_re : acc_t;
    variable b_im : acc_t;
    variable c_re : acc_t;
    variable c_im : acc_t;
    variable e_re : acc_t;
    variable e_im : acc_t;
    variable out_idx : natural;
    variable load_idx : natural;
    variable quarter : natural;
    variable half : natural;
    variable tw_step : natural;
  begin
    if rising_edge(clk) then
      done_r <= '0';
      mul_valid_r <= '0';

      if rst = '1' then
        state_r <= ST_LOAD;
        load_index_r <= 0;
        output_index_r <= 0;
        stage_size_r <= 2;
        group_base_r <= 0;
        butterfly_j_r <= 0;
        out_valid_r <= '0';
        out_last_r <= '0';
        out_data_r <= (others => '0');
        done_r <= '0';
      else
        case state_r is
          when ST_LOAD =>
            out_valid_r <= '0';
            out_last_r <= '0';
            if s_axis_tvalid = '1' and s_axis_tready = '1' then
              load_idx := output_permutation(load_index_r);
              mem_re(load_idx) <= resize(signed(high_half(s_axis_tdata)), C_ACC_WIDTH);
              mem_im(load_idx) <= resize(signed(low_half(s_axis_tdata)), C_ACC_WIDTH);
              if load_index_r = G_POINTS - 1 then
                load_index_r <= 0;
                group_base_r <= 0;
                butterfly_j_r <= 0;
                if G_RADIX = 4 then
                  stage_size_r <= 4;
                  state_r <= ST_R4_MUL1_START;
                else
                  stage_size_r <= 2;
                  state_r <= ST_R2_START;
                end if;
              else
                load_index_r <= load_index_r + 1;
              end if;
            end if;

          when ST_R2_START =>
            half := stage_size_r / 2;
            tw_step := G_POINTS / stage_size_r;
            idx0_r <= group_base_r + butterfly_j_r;
            idx1_r <= group_base_r + butterfly_j_r + half;
            x0_re_r <= mem_re(group_base_r + butterfly_j_r);
            x0_im_r <= mem_im(group_base_r + butterfly_j_r);
            mul_a_re_r <= mem_re(group_base_r + butterfly_j_r + half);
            mul_a_im_r <= mem_im(group_base_r + butterfly_j_r + half);
            tw_exp_r <= butterfly_j_r * tw_step;
            mul_valid_r <= '1';
            state_r <= ST_R2_WAIT;

          when ST_R2_WAIT =>
            if rr_valid = '1' then
              complex_product(rr_p, ii_p, ri_p, ir_p, t_re, t_im);
              mem_re(idx0_r) <= x0_re_r + t_re;
              mem_im(idx0_r) <= x0_im_r + t_im;
              mem_re(idx1_r) <= x0_re_r - t_re;
              mem_im(idx1_r) <= x0_im_r - t_im;

              half := stage_size_r / 2;
              if butterfly_j_r = half - 1 then
                butterfly_j_r <= 0;
                if group_base_r + stage_size_r >= G_POINTS then
                  group_base_r <= 0;
                  if stage_size_r >= G_POINTS then
                    output_index_r <= 0;
                    state_r <= ST_OUTPUT;
                  else
                    stage_size_r <= stage_size_r * 2;
                    state_r <= ST_R2_START;
                  end if;
                else
                  group_base_r <= group_base_r + stage_size_r;
                  state_r <= ST_R2_START;
                end if;
              else
                butterfly_j_r <= butterfly_j_r + 1;
                state_r <= ST_R2_START;
              end if;
            end if;

          when ST_R4_MUL1_START =>
            quarter := stage_size_r / 4;
            tw_step := G_POINTS / stage_size_r;
            idx0_r <= group_base_r + butterfly_j_r;
            idx1_r <= group_base_r + butterfly_j_r + quarter;
            idx2_r <= group_base_r + butterfly_j_r + (2 * quarter);
            idx3_r <= group_base_r + butterfly_j_r + (3 * quarter);
            x0_re_r <= mem_re(group_base_r + butterfly_j_r);
            x0_im_r <= mem_im(group_base_r + butterfly_j_r);
            x1_re_r <= mem_re(group_base_r + butterfly_j_r + quarter);
            x1_im_r <= mem_im(group_base_r + butterfly_j_r + quarter);
            x2_re_r <= mem_re(group_base_r + butterfly_j_r + (2 * quarter));
            x2_im_r <= mem_im(group_base_r + butterfly_j_r + (2 * quarter));
            x3_re_r <= mem_re(group_base_r + butterfly_j_r + (3 * quarter));
            x3_im_r <= mem_im(group_base_r + butterfly_j_r + (3 * quarter));
            mul_a_re_r <= mem_re(group_base_r + butterfly_j_r + quarter);
            mul_a_im_r <= mem_im(group_base_r + butterfly_j_r + quarter);
            tw_exp_r <= butterfly_j_r * tw_step;
            mul_valid_r <= '1';
            state_r <= ST_R4_MUL1_WAIT;

          when ST_R4_MUL1_WAIT =>
            if rr_valid = '1' then
              complex_product(rr_p, ii_p, ri_p, ir_p, t_re, t_im);
              t1_re_r <= t_re;
              t1_im_r <= t_im;
              tw_exp_r <= (2 * butterfly_j_r * (G_POINTS / stage_size_r)) mod G_POINTS;
              mul_a_re_r <= x2_re_r;
              mul_a_im_r <= x2_im_r;
              mul_valid_r <= '1';
              state_r <= ST_R4_MUL2_WAIT;
            end if;

          when ST_R4_MUL2_START =>
            state_r <= ST_R4_MUL2_WAIT;

          when ST_R4_MUL2_WAIT =>
            if rr_valid = '1' then
              complex_product(rr_p, ii_p, ri_p, ir_p, t_re, t_im);
              t2_re_r <= t_re;
              t2_im_r <= t_im;
              tw_exp_r <= (3 * butterfly_j_r * (G_POINTS / stage_size_r)) mod G_POINTS;
              mul_a_re_r <= x3_re_r;
              mul_a_im_r <= x3_im_r;
              mul_valid_r <= '1';
              state_r <= ST_R4_MUL3_WAIT;
            end if;

          when ST_R4_MUL3_START =>
            state_r <= ST_R4_MUL3_WAIT;

          when ST_R4_MUL3_WAIT =>
            if rr_valid = '1' then
              complex_product(rr_p, ii_p, ri_p, ir_p, t_re, t_im);
              t3_re_r <= t_re;
              t3_im_r <= t_im;
              a_re := x0_re_r + t2_re_r;
              a_im := x0_im_r + t2_im_r;
              b_re := x0_re_r - t2_re_r;
              b_im := x0_im_r - t2_im_r;
              c_re := t1_re_r + t_re;
              c_im := t1_im_r + t_im;
              e_re := t1_re_r - t_re;
              e_im := t1_im_r - t_im;
              mem_re(idx0_r) <= a_re + c_re;
              mem_im(idx0_r) <= a_im + c_im;
              mem_re(idx2_r) <= a_re - c_re;
              mem_im(idx2_r) <= a_im - c_im;
              if G_INVERSE_FFT then
                mem_re(idx1_r) <= b_re - e_im;
                mem_im(idx1_r) <= b_im + e_re;
                mem_re(idx3_r) <= b_re + e_im;
                mem_im(idx3_r) <= b_im - e_re;
              else
                mem_re(idx1_r) <= b_re + e_im;
                mem_im(idx1_r) <= b_im - e_re;
                mem_re(idx3_r) <= b_re - e_im;
                mem_im(idx3_r) <= b_im + e_re;
              end if;

              quarter := stage_size_r / 4;
              if butterfly_j_r = quarter - 1 then
                butterfly_j_r <= 0;
                if group_base_r + stage_size_r >= G_POINTS then
                  group_base_r <= 0;
                  if stage_size_r >= G_POINTS then
                    output_index_r <= 0;
                    state_r <= ST_OUTPUT;
                  else
                    stage_size_r <= stage_size_r * 4;
                    state_r <= ST_R4_MUL1_START;
                  end if;
                else
                  group_base_r <= group_base_r + stage_size_r;
                  state_r <= ST_R4_MUL1_START;
                end if;
              else
                butterfly_j_r <= butterfly_j_r + 1;
                state_r <= ST_R4_MUL1_START;
              end if;
            end if;

          when ST_OUTPUT =>
            if out_valid_r = '0' or m_axis_tready = '1' then
              out_idx := output_index_r;
              out_data_r <= std_logic_vector(scaled_output(mem_re(out_idx))) & std_logic_vector(scaled_output(mem_im(out_idx)));
              out_valid_r <= '1';
              out_last_r <= '1' when output_index_r = G_POINTS - 1 else '0';
              if output_index_r = G_POINTS - 1 then
                state_r <= ST_DONE;
              else
                output_index_r <= output_index_r + 1;
              end if;
            end if;

          when ST_DONE =>
            if out_valid_r = '1' and m_axis_tready = '1' then
              out_valid_r <= '0';
              out_last_r <= '0';
              done_r <= '1';
              load_index_r <= 0;
              state_r <= ST_LOAD;
            end if;
        end case;
      end if;
    end if;
  end process;
end architecture;
