library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- RadIF register interconnect for routing one host interface to multiple register banks.
-- Decodes address ranges, forwards transactions, and returns the selected peripheral response.
entity radif_reg_interconnect is
  generic (
    -- Sets the bit width for DATA WIDTH values carried by this module.
    DATA_WIDTH       : integer := 32;
    -- Sets the bit width for ADDR WIDTH values carried by this module.
    ADDR_WIDTH       : integer := 16;
    -- Configures SLAVE COUNT for this instance.
    SLAVE_COUNT      : integer := 2;
    -- Configures SLAVE BASE ADDRS for this instance.
    SLAVE_BASE_ADDRS : std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0) := x"00000000";
    -- Configures SLAVE ADDR MASKS for this instance.
    SLAVE_ADDR_MASKS : std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0) := x"F000F000";
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR_TAG       : string  := "XILINX";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_SERIES_TAG : string := "GENERIC"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk             : in  std_logic;
    -- Active-low reset for this clock domain.
    rstn            : in  std_logic;
    -- Input wr addr i signal for this module.
    wr_addr_i       : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
    -- Readback control or data signal for host-visible captured state.
    rd_addr_i       : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
    -- Input wr en i signal for this module.
    wr_en_i         : in  std_logic;
    -- Readback control or data signal for host-visible captured state.
    rd_en_i         : in  std_logic;
    -- Input data in i signal for this module.
    data_in_i       : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Output data out o signal generated by this module.
    data_out_o      : out std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Output wr rdy o signal generated by this module.
    wr_rdy_o        : out std_logic;
    -- Readback control or data signal for host-visible captured state.
    rd_rdy_o        : out std_logic;
    -- Output valid qualifier aligned with the produced result.
    wr_valid_o      : out std_logic;
    -- Readback control or data signal for host-visible captured state.
    rd_valid_o      : out std_logic;
    -- Output error o signal generated by this module.
    error_o         : out std_logic;
    -- Output s wr addr o signal generated by this module.
    s_wr_addr_o     : out std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0);
    -- Output s rd addr o signal generated by this module.
    s_rd_addr_o     : out std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0);
    -- Output s wr en o signal generated by this module.
    s_wr_en_o       : out std_logic_vector(SLAVE_COUNT - 1 downto 0);
    -- Output s rd en o signal generated by this module.
    s_rd_en_o       : out std_logic_vector(SLAVE_COUNT - 1 downto 0);
    -- Output s data in o signal generated by this module.
    s_data_in_o     : out std_logic_vector((SLAVE_COUNT * DATA_WIDTH) - 1 downto 0);
    -- Input s data out i signal for this module.
    s_data_out_i    : in  std_logic_vector((SLAVE_COUNT * DATA_WIDTH) - 1 downto 0);
    -- Input s wr rdy i signal for this module.
    s_wr_rdy_i      : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
    -- Input s rd rdy i signal for this module.
    s_rd_rdy_i      : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
    -- Input valid qualifier for this operation or sideband channel.
    s_wr_valid_i    : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
    -- Input valid qualifier for this operation or sideband channel.
    s_rd_valid_i    : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
    -- Input s error i signal for this module.
    s_error_i       : in  std_logic_vector(SLAVE_COUNT - 1 downto 0)
  );
end entity;

architecture rtl of radif_reg_interconnect is
  signal wr_sel        : natural range 0 to SLAVE_COUNT - 1 := 0;
  signal rd_sel        : natural range 0 to SLAVE_COUNT - 1 := 0;
  signal wr_hit        : std_logic := '0';
  signal rd_hit        : std_logic := '0';
  signal wr_resp_sel_r : natural range 0 to SLAVE_COUNT - 1 := 0;
  signal rd_resp_sel_r : natural range 0 to SLAVE_COUNT - 1 := 0;
  signal wr_miss_r     : std_logic := '0';
  signal rd_miss_r     : std_logic := '0';

  function vector_slice(data : std_logic_vector; index : natural; width : positive) return std_logic_vector is
    variable outv : std_logic_vector(width - 1 downto 0);
    variable lo   : natural;
  begin
    lo := index * width;
    outv := data(lo + width - 1 downto lo);
    return outv;
  end function;

  function addr_matches(addr : std_logic_vector; index : natural) return boolean is
    variable base_v : std_logic_vector(ADDR_WIDTH - 1 downto 0);
    variable mask_v : std_logic_vector(ADDR_WIDTH - 1 downto 0);
    variable zero_v : std_logic_vector(ADDR_WIDTH - 1 downto 0) := (others => '0');
  begin
    base_v := vector_slice(SLAVE_BASE_ADDRS, index, ADDR_WIDTH);
    mask_v := vector_slice(SLAVE_ADDR_MASKS, index, ADDR_WIDTH);
    return ((addr xor base_v) and mask_v) = zero_v;
  end function;
begin
  assert SLAVE_COUNT > 0
    report "radif_reg_interconnect SLAVE_COUNT must be greater than zero"
    severity failure;
  assert SLAVE_BASE_ADDRS'length = SLAVE_COUNT * ADDR_WIDTH
    report "radif_reg_interconnect SLAVE_BASE_ADDRS width must equal SLAVE_COUNT*ADDR_WIDTH"
    severity failure;
  assert SLAVE_ADDR_MASKS'length = SLAVE_COUNT * ADDR_WIDTH
    report "radif_reg_interconnect SLAVE_ADDR_MASKS width must equal SLAVE_COUNT*ADDR_WIDTH"
    severity failure;

  gen_xilinx_vendor : if VENDOR_TAG = "XILINX" generate
  begin
  end generate;

  gen_generic_vendor : if VENDOR_TAG /= "XILINX" generate
  begin
  end generate;

  process(all)
    variable found : boolean;
  begin
    wr_sel <= 0;
    wr_hit <= '0';
    found := false;
    for i in 0 to SLAVE_COUNT - 1 loop
      if not found and addr_matches(wr_addr_i, i) then
        wr_sel <= i;
        wr_hit <= '1';
        found := true;
      end if;
    end loop;

    rd_sel <= 0;
    rd_hit <= '0';
    found := false;
    for i in 0 to SLAVE_COUNT - 1 loop
      if not found and addr_matches(rd_addr_i, i) then
        rd_sel <= i;
        rd_hit <= '1';
        found := true;
      end if;
    end loop;
  end process;

  process(all)
    variable wr_addr_v  : std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0);
    variable rd_addr_v  : std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0);
    variable data_in_v  : std_logic_vector((SLAVE_COUNT * DATA_WIDTH) - 1 downto 0);
    variable wr_en_v    : std_logic_vector(SLAVE_COUNT - 1 downto 0);
    variable rd_en_v    : std_logic_vector(SLAVE_COUNT - 1 downto 0);
    variable base_v     : std_logic_vector(ADDR_WIDTH - 1 downto 0);
    variable local_wr_v : std_logic_vector(ADDR_WIDTH - 1 downto 0);
    variable local_rd_v : std_logic_vector(ADDR_WIDTH - 1 downto 0);
  begin
    wr_addr_v := (others => '0');
    rd_addr_v := (others => '0');
    data_in_v := (others => '0');
    wr_en_v := (others => '0');
    rd_en_v := (others => '0');

    for i in 0 to SLAVE_COUNT - 1 loop
      base_v := vector_slice(SLAVE_BASE_ADDRS, i, ADDR_WIDTH);
      local_wr_v := std_logic_vector(unsigned(wr_addr_i) - unsigned(base_v));
      local_rd_v := std_logic_vector(unsigned(rd_addr_i) - unsigned(base_v));
      wr_addr_v(((i + 1) * ADDR_WIDTH) - 1 downto i * ADDR_WIDTH) := local_wr_v;
      rd_addr_v(((i + 1) * ADDR_WIDTH) - 1 downto i * ADDR_WIDTH) := local_rd_v;
      data_in_v(((i + 1) * DATA_WIDTH) - 1 downto i * DATA_WIDTH) := data_in_i;
    end loop;

    if wr_en_i = '1' and wr_hit = '1' then
      wr_en_v(wr_sel) := '1';
    end if;
    if rd_en_i = '1' and rd_hit = '1' then
      rd_en_v(rd_sel) := '1';
    end if;

    s_wr_addr_o <= wr_addr_v;
    s_rd_addr_o <= rd_addr_v;
    s_data_in_o <= data_in_v;
    s_wr_en_o <= wr_en_v;
    s_rd_en_o <= rd_en_v;
  end process;

  wr_rdy_o <= s_wr_rdy_i(wr_sel) when wr_hit = '1' else '1';
  rd_rdy_o <= s_rd_rdy_i(rd_sel) when rd_hit = '1' else '1';
  wr_valid_o <= wr_miss_r or s_wr_valid_i(wr_resp_sel_r);
  rd_valid_o <= rd_miss_r or s_rd_valid_i(rd_resp_sel_r);
  data_out_o <= s_data_out_i(((rd_resp_sel_r + 1) * DATA_WIDTH) - 1 downto rd_resp_sel_r * DATA_WIDTH)
                when rd_miss_r = '0' else (others => '0');
  error_o <= wr_miss_r or rd_miss_r or s_error_i(wr_resp_sel_r) or s_error_i(rd_resp_sel_r);

  process(clk)
  begin
    if rising_edge(clk) then
      wr_miss_r <= '0';
      rd_miss_r <= '0';

      if rstn = '0' then
        wr_resp_sel_r <= 0;
        rd_resp_sel_r <= 0;
      else
        if wr_en_i = '1' then
          wr_resp_sel_r <= wr_sel;
          if wr_hit = '0' then
            wr_miss_r <= '1';
          end if;
        end if;

        if rd_en_i = '1' then
          rd_resp_sel_r <= rd_sel;
          if rd_hit = '0' then
            rd_miss_r <= '1';
          end if;
        end if;
      end if;
    end if;
  end process;
end architecture;
