library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- 16-bit SMI-style parallel management interface bridge to RadIF registers.
-- Converts external management bus strobes into synchronous register transactions for FPGA peripherals.
entity radif_smi16_to_reg is
  generic (
    -- Sets the bit width for DATA WIDTH values carried by this module.
    DATA_WIDTH         : integer := 32;
    -- Sets the bit width for REG ADDR WIDTH values carried by this module.
    REG_ADDR_WIDTH     : integer := 16;
    -- Sets the bit width for SMI ADDR WIDTH values carried by this module.
    SMI_ADDR_WIDTH     : integer := 16;
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR_TAG         : string  := "XILINX";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_SERIES_TAG : string  := "GENERIC"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk           : in  std_logic;
    -- Active-low reset for this clock domain.
    rstn          : in  std_logic;
    -- Input smi cs n i signal for this module.
    smi_cs_n_i    : in  std_logic;
    -- Input smi rd n i signal for this module.
    smi_rd_n_i    : in  std_logic;
    -- Input smi wr n i signal for this module.
    smi_wr_n_i    : in  std_logic;
    -- Input smi addr i signal for this module.
    smi_addr_i    : in  std_logic_vector(SMI_ADDR_WIDTH - 1 downto 0);
    -- Input smi data i signal for this module.
    smi_data_i    : in  std_logic_vector(15 downto 0);
    -- Output smi data o signal generated by this module.
    smi_data_o    : out std_logic_vector(15 downto 0);
    -- Smi data oen interface signal.
    smi_data_oen  : out std_logic;
    -- Output smi ack o signal generated by this module.
    smi_ack_o     : out std_logic;
    -- Register write address issued to the internal RadIF register target.
    reg_wr_addr   : out std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
    -- Register read address issued to the internal RadIF register target.
    reg_rd_addr   : out std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
    -- One-cycle write request pulse for the internal register target.
    reg_wr_en     : out std_logic;
    -- One-cycle read request pulse for the internal register target.
    reg_rd_en     : out std_logic;
    -- Write data presented to the internal register target.
    reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Read data returned by the internal register target.
    reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Write-side ready indication from the internal register target.
    reg_wr_rdy    : in  std_logic;
    -- Read-side ready indication from the internal register target.
    reg_rd_rdy    : in  std_logic;
    -- Write response valid indication from the internal register target.
    reg_wr_valid  : in  std_logic;
    -- Read response valid indication from the internal register target.
    reg_rd_valid  : in  std_logic;
    -- Register target error flag converted into the external bus error response.
    reg_error     : in  std_logic
  );
end entity;

architecture rtl of radif_smi16_to_reg is
  function ceil_log2(n : positive) return natural is
    variable v : natural := n - 1;
    variable r : natural := 0;
  begin
    while v > 0 loop
      v := v / 2;
      r := r + 1;
    end loop;
    return r;
  end function;

  constant HALFWORD_BYTES : natural := 2;
  constant WORD_BYTES     : natural := DATA_WIDTH / 8;
  constant LANES_PER_WORD : natural := DATA_WIDTH / 16;
  constant WORD_BYTE_BITS : natural := ceil_log2(WORD_BYTES);
  constant LANE_BITS      : natural := ceil_log2(LANES_PER_WORD);

  type state_t is (IDLE, WAIT_WRITE, WAIT_READ);

  signal cs_meta       : std_logic := '1';
  signal cs_sync       : std_logic := '1';
  signal rd_meta       : std_logic := '1';
  signal rd_sync       : std_logic := '1';
  signal rd_prev       : std_logic := '1';
  signal wr_meta       : std_logic := '1';
  signal wr_sync       : std_logic := '1';
  signal wr_prev       : std_logic := '1';
  signal state         : state_t := IDLE;
  signal wr_addr_r     : std_logic_vector(REG_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal rd_addr_r     : std_logic_vector(REG_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal wr_data_r     : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
  signal rd_cache_r    : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
  signal rd_data_r     : std_logic_vector(15 downto 0) := (others => '0');
  signal wr_lane_valid : std_logic_vector(LANES_PER_WORD - 1 downto 0) := (others => '0');
  signal wr_base_addr  : std_logic_vector(REG_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal rd_cache_addr : std_logic_vector(REG_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal pending_lane  : natural range 0 to LANES_PER_WORD - 1 := 0;
  signal rd_cache_v    : std_logic := '0';
  signal wr_en_r       : std_logic := '0';
  signal rd_en_r       : std_logic := '0';
  signal ack_r         : std_logic := '0';

  function smi_lane(a : std_logic_vector) return natural is
    variable idx : natural := 0;
  begin
    for i in 0 to LANE_BITS - 1 loop
      if i < a'length and a(i) = '1' then
        idx := idx + (2 ** i);
      end if;
    end loop;
    if idx >= LANES_PER_WORD then
      return LANES_PER_WORD - 1;
    end if;
    return idx;
  end function;

  function smi_to_reg_addr(a : std_logic_vector) return std_logic_vector is
    variable byte_addr : unsigned(REG_ADDR_WIDTH - 1 downto 0) := (others => '0');
    variable smi_ext   : unsigned(REG_ADDR_WIDTH - 1 downto 0) := (others => '0');
  begin
    if a'length >= REG_ADDR_WIDTH then
      smi_ext := unsigned(a(REG_ADDR_WIDTH - 1 downto 0));
    else
      smi_ext(a'length - 1 downto 0) := unsigned(a);
    end if;

    byte_addr := shift_left(smi_ext, 1);
    for i in 0 to WORD_BYTE_BITS - 1 loop
      byte_addr(i) := '0';
    end loop;
    return std_logic_vector(byte_addr);
  end function;

  function get_lane(data : std_logic_vector; lane : natural) return std_logic_vector is
    variable outv : std_logic_vector(15 downto 0) := (others => '0');
    variable lo   : natural := lane * 16;
  begin
    outv := data(lo + 15 downto lo);
    return outv;
  end function;

  function all_valid(v : std_logic_vector) return boolean is
  begin
    for i in v'range loop
      if v(i) = '0' then
        return false;
      end if;
    end loop;
    return true;
  end function;
begin
  assert DATA_WIDTH mod 16 = 0
    report "radif_smi16_to_reg DATA_WIDTH must be a multiple of 16"
    severity failure;

  assert REG_ADDR_WIDTH >= 2
    report "radif_smi16_to_reg REG_ADDR_WIDTH must be at least 2"
    severity failure;

  smi_data_o <= rd_data_r;
  smi_data_oen <= '0' when cs_sync = '0' and rd_sync = '0' else '1';
  smi_ack_o <= ack_r;
  reg_wr_addr <= wr_addr_r;
  reg_rd_addr <= rd_addr_r;
  reg_data_in <= wr_data_r;
  reg_wr_en <= wr_en_r;
  reg_rd_en <= rd_en_r;

  gen_xilinx_vendor : if VENDOR_TAG = "XILINX" generate
  begin
  end generate;

  gen_generic_vendor : if VENDOR_TAG /= "XILINX" generate
  begin
  end generate;

  process(clk)
    variable lane        : natural range 0 to LANES_PER_WORD - 1;
    variable base_addr   : std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
    variable next_data   : std_logic_vector(DATA_WIDTH - 1 downto 0);
    variable next_valid  : std_logic_vector(LANES_PER_WORD - 1 downto 0);
    variable lane_low    : natural;
  begin
    if rising_edge(clk) then
      cs_meta <= smi_cs_n_i;
      cs_sync <= cs_meta;
      rd_meta <= smi_rd_n_i;
      rd_sync <= rd_meta;
      rd_prev <= rd_sync;
      wr_meta <= smi_wr_n_i;
      wr_sync <= wr_meta;
      wr_prev <= wr_sync;

      wr_en_r <= '0';
      rd_en_r <= '0';
      ack_r <= '0';

      if rstn = '0' then
        state <= IDLE;
        wr_data_r <= (others => '0');
        rd_cache_r <= (others => '0');
        rd_data_r <= (others => '0');
        wr_lane_valid <= (others => '0');
        rd_cache_v <= '0';
      else
        case state is
          when IDLE =>
            lane := smi_lane(smi_addr_i);
            base_addr := smi_to_reg_addr(smi_addr_i);

            if cs_sync = '0' and wr_prev = '1' and wr_sync = '0' then
              next_data := wr_data_r;
              next_valid := wr_lane_valid;
              if base_addr /= wr_base_addr then
                next_data := (others => '0');
                next_valid := (others => '0');
                wr_base_addr <= base_addr;
              end if;

              lane_low := lane * 16;
              next_data(lane_low + 15 downto lane_low) := smi_data_i;
              next_valid(lane) := '1';
              wr_data_r <= next_data;
              wr_lane_valid <= next_valid;

              if all_valid(next_valid) and reg_wr_rdy = '1' then
                wr_addr_r <= base_addr;
                wr_data_r <= next_data;
                wr_en_r <= '1';
                state <= WAIT_WRITE;
              else
                ack_r <= '1';
              end if;

            elsif cs_sync = '0' and rd_prev = '1' and rd_sync = '0' then
              if rd_cache_v = '1' and rd_cache_addr = base_addr then
                rd_data_r <= get_lane(rd_cache_r, lane);
                ack_r <= '1';
              elsif reg_rd_rdy = '1' then
                rd_addr_r <= base_addr;
                pending_lane <= lane;
                rd_en_r <= '1';
                state <= WAIT_READ;
              end if;
            end if;

          when WAIT_WRITE =>
            if reg_wr_valid = '1' then
              if reg_error = '1' then
                ack_r <= '0';
              else
                ack_r <= '1';
                wr_lane_valid <= (others => '0');
              end if;
              state <= IDLE;
            end if;

          when WAIT_READ =>
            if reg_rd_valid = '1' then
              if reg_error = '1' then
                rd_cache_v <= '0';
                rd_data_r <= (others => '0');
                ack_r <= '0';
              else
                rd_cache_r <= reg_data_out;
                rd_cache_addr <= rd_addr_r;
                rd_cache_v <= '1';
                rd_data_r <= get_lane(reg_data_out, pending_lane);
                ack_r <= '1';
              end if;
              state <= IDLE;
            end if;
        end case;
      end if;
    end if;
  end process;
end architecture;
