library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.radif_pkg.all;

-- SPI-controlled AXI master bridge.
-- Accepts SPI command traffic and issues AXI-style memory transactions for systems that need a serial control/debug path.
entity radif_spi_axi_master is
  generic (
    -- Sets the bit width for AXI DATA WIDTH values carried by this module.
    AXI_DATA_WIDTH     : integer := 32;
    -- Sets the bit width for AXI ADDR WIDTH values carried by this module.
    AXI_ADDR_WIDTH     : integer := 32;
    -- Configures AXI MODE for this instance.
    AXI_MODE           : string  := "AXI_LITE";
    -- Configures ENABLE CRC16 for this instance.
    ENABLE_CRC16       : boolean := false;
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR_TAG         : string  := "XILINX";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_SERIES_TAG : string  := "GENERIC"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk            : in  std_logic;
    -- Active-low reset for this clock domain.
    rstn           : in  std_logic;
    -- Input spi sclk i signal for this module.
    spi_sclk_i     : in  std_logic;
    -- Input spi cs n i signal for this module.
    spi_cs_n_i     : in  std_logic;
    -- Input spi mosi i signal for this module.
    spi_mosi_i     : in  std_logic;
    -- Output spi miso o signal generated by this module.
    spi_miso_o     : out std_logic;
    -- Spi miso oen interface signal.
    spi_miso_oen   : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awaddr   : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awlen    : out std_logic_vector(7 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awsize   : out std_logic_vector(2 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awburst  : out std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awvalid  : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awready  : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wdata    : out std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wstrb    : out std_logic_vector((AXI_DATA_WIDTH / 8) - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wlast    : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wvalid   : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wready   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bresp    : in  std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bvalid   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bready   : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_araddr   : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arlen    : out std_logic_vector(7 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arsize   : out std_logic_vector(2 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arburst  : out std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arvalid  : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arready  : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rdata    : in  std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rresp    : in  std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rlast    : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rvalid   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rready   : out std_logic
  );
end entity;

architecture rtl of radif_spi_axi_master is
  type state_t is (
    WAIT_SOF, GET_OP, GET_ADDR, GET_WDATA,
    AXI_WRITE_ADDR_DATA, AXI_WRITE_RESP, AXI_READ_ADDR, AXI_READ_DATA
  );

  constant WORD_BYTES : natural := AXI_DATA_WIDTH / 8;
  constant ADDR_BYTES : natural := AXI_ADDR_WIDTH / 8;

  signal sclk_meta  : std_logic := '0';
  signal sclk_sync  : std_logic := '0';
  signal sclk_prev  : std_logic := '0';
  signal cs_meta    : std_logic := '1';
  signal cs_sync    : std_logic := '1';
  signal mosi_meta  : std_logic := '0';
  signal mosi_sync  : std_logic := '0';
  signal rx_shift   : std_logic_vector(7 downto 0) := (others => '0');
  signal tx_shift   : std_logic_vector(7 downto 0) := (others => '0');
  signal bit_count  : unsigned(2 downto 0) := (others => '0');
  signal state      : state_t := WAIT_SOF;
  signal op_r       : std_logic_vector(7 downto 0) := (others => '0');
  signal addr_r     : std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal wdata_r    : std_logic_vector(AXI_DATA_WIDTH - 1 downto 0) := (others => '0');
  signal rdata_r    : std_logic_vector(AXI_DATA_WIDTH - 1 downto 0) := (others => '0');
  signal byte_index : natural range 0 to 64 := 0;
  signal tx_index   : natural range 0 to 64 := 0;
  signal status_r   : std_logic_vector(7 downto 0) := RADIF_STATUS_OK;
  signal awvalid_r  : std_logic := '0';
  signal wvalid_r   : std_logic := '0';
  signal bready_r   : std_logic := '0';
  signal arvalid_r  : std_logic := '0';
  signal rready_r   : std_logic := '0';

  function axi_size return std_logic_vector is
  begin
    case AXI_DATA_WIDTH / 8 is
      when 1 => return "000";
      when 2 => return "001";
      when 4 => return "010";
      when 8 => return "011";
      when 16 => return "100";
      when 32 => return "101";
      when 64 => return "110";
      when others => return "010";
    end case;
  end function;

  function byte_from_word(w : std_logic_vector; idx : natural) return std_logic_vector is
    variable b : std_logic_vector(7 downto 0) := (others => '0');
    variable hi : integer;
  begin
    hi := w'length - 1 - integer(idx * 8);
    if hi >= 7 then
      b := w(hi downto hi - 7);
    end if;
    return b;
  end function;
begin
  spi_miso_o <= tx_shift(7);
  spi_miso_oen <= spi_cs_n_i;
  m_axi_awaddr <= addr_r;
  m_axi_awlen <= (others => '0');
  m_axi_awsize <= axi_size;
  m_axi_awburst <= "01";
  m_axi_awvalid <= awvalid_r;
  m_axi_wdata <= wdata_r;
  m_axi_wstrb <= (others => '1');
  m_axi_wlast <= '1';
  m_axi_wvalid <= wvalid_r;
  m_axi_bready <= bready_r;
  m_axi_araddr <= addr_r;
  m_axi_arlen <= (others => '0');
  m_axi_arsize <= axi_size;
  m_axi_arburst <= "01";
  m_axi_arvalid <= arvalid_r;
  m_axi_rready <= rready_r;

  gen_xilinx_vendor : if VENDOR_TAG = "XILINX" generate
  begin
  end generate;

  gen_generic_vendor : if VENDOR_TAG /= "XILINX" generate
  begin
  end generate;

  process(clk)
    variable rx_byte : std_logic_vector(7 downto 0);
    variable byte_valid : boolean;
  begin
    if rising_edge(clk) then
      sclk_meta <= spi_sclk_i;
      sclk_sync <= sclk_meta;
      sclk_prev <= sclk_sync;
      cs_meta <= spi_cs_n_i;
      cs_sync <= cs_meta;
      mosi_meta <= spi_mosi_i;
      mosi_sync <= mosi_meta;

      byte_valid := false;
      rx_byte := rx_shift(6 downto 0) & mosi_sync;

      if rstn = '0' then
        state <= WAIT_SOF;
        bit_count <= (others => '0');
        rx_shift <= (others => '0');
        tx_shift <= (others => '0');
        addr_r <= (others => '0');
        wdata_r <= (others => '0');
        awvalid_r <= '0';
        wvalid_r <= '0';
        bready_r <= '0';
        arvalid_r <= '0';
        rready_r <= '0';
        status_r <= RADIF_STATUS_OK;
      elsif cs_sync = '1' then
        state <= WAIT_SOF;
        bit_count <= (others => '0');
        tx_shift <= status_r;
        tx_index <= 0;
      else
        if sclk_sync = '1' and sclk_prev = '0' then
          rx_shift <= rx_shift(6 downto 0) & mosi_sync;
          if bit_count = "111" then
            bit_count <= (others => '0');
            byte_valid := true;
          else
            bit_count <= bit_count + 1;
          end if;
        end if;

        if sclk_sync = '0' and sclk_prev = '1' then
          tx_shift <= tx_shift(6 downto 0) & '0';
        end if;

        if awvalid_r = '1' and m_axi_awready = '1' then
          awvalid_r <= '0';
        end if;
        if wvalid_r = '1' and m_axi_wready = '1' then
          wvalid_r <= '0';
        end if;
        if arvalid_r = '1' and m_axi_arready = '1' then
          arvalid_r <= '0';
          rready_r <= '1';
        end if;

        case state is
          when WAIT_SOF =>
            if byte_valid and rx_byte = x"A5" then
              tx_shift <= status_r;
              state <= GET_OP;
            end if;

          when GET_OP =>
            if byte_valid then
              op_r <= rx_byte;
              status_r <= RADIF_STATUS_OK;
              if rx_byte = RADIF_OP_REG_WRITE or rx_byte = RADIF_OP_REG_READ then
                addr_r <= (others => '0');
                byte_index <= 0;
                state <= GET_ADDR;
              elsif rx_byte = RADIF_OP_CAPS then
                tx_shift <= x"02";
                state <= WAIT_SOF;
              else
                status_r <= RADIF_STATUS_BAD_OP;
                state <= WAIT_SOF;
              end if;
            end if;

          when GET_ADDR =>
            if byte_valid then
              addr_r(AXI_ADDR_WIDTH - 1 - (byte_index * 8) downto AXI_ADDR_WIDTH - 8 - (byte_index * 8)) <= rx_byte;
              if byte_index = ADDR_BYTES - 1 then
                byte_index <= 0;
                if op_r = RADIF_OP_REG_WRITE then
                  wdata_r <= (others => '0');
                  state <= GET_WDATA;
                else
                  arvalid_r <= '1';
                  state <= AXI_READ_ADDR;
                end if;
              else
                byte_index <= byte_index + 1;
              end if;
            end if;

          when GET_WDATA =>
            if byte_valid then
              wdata_r(AXI_DATA_WIDTH - 1 - (byte_index * 8) downto AXI_DATA_WIDTH - 8 - (byte_index * 8)) <= rx_byte;
              if byte_index = WORD_BYTES - 1 then
                awvalid_r <= '1';
                wvalid_r <= '1';
                state <= AXI_WRITE_ADDR_DATA;
              else
                byte_index <= byte_index + 1;
              end if;
            end if;

          when AXI_WRITE_ADDR_DATA =>
            if awvalid_r = '0' and wvalid_r = '0' then
              bready_r <= '1';
              state <= AXI_WRITE_RESP;
            end if;

          when AXI_WRITE_RESP =>
            if m_axi_bvalid = '1' then
              bready_r <= '0';
              if m_axi_bresp = "00" then
                status_r <= RADIF_STATUS_OK;
              else
                status_r <= RADIF_STATUS_ERROR;
              end if;
              state <= WAIT_SOF;
            end if;

          when AXI_READ_ADDR =>
            if rready_r = '1' then
              state <= AXI_READ_DATA;
            end if;

          when AXI_READ_DATA =>
            if m_axi_rvalid = '1' then
              rready_r <= '0';
              if m_axi_rresp = "00" then
                status_r <= RADIF_STATUS_OK;
                rdata_r <= m_axi_rdata;
                tx_shift <= byte_from_word(m_axi_rdata, 0);
                tx_index <= 1;
              else
                status_r <= RADIF_STATUS_ERROR;
                tx_shift <= (others => '0');
                tx_index <= 0;
              end if;
              state <= WAIT_SOF;
            end if;
        end case;

        if tx_index > 0 and tx_index < WORD_BYTES and sclk_sync = '0' and sclk_prev = '1' and bit_count = "000" then
          tx_shift <= byte_from_word(rdata_r, tx_index);
          tx_index <= tx_index + 1;
        end if;
      end if;
    end if;
  end process;
end architecture;
