library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

use work.radif_pkg.all;

-- QSPI slave bridge to the RadIF register transaction interface.
-- Maps serial quad-SPI command traffic onto a compact internal register bus for embedded control planes.
entity radif_qspi_slave_to_reg is
  generic (
    -- Sets the bit width for DATA WIDTH values carried by this module.
    DATA_WIDTH         : integer := 32;
    -- Sets the bit width for ADDR WIDTH values carried by this module.
    ADDR_WIDTH         : integer := 16;
    -- Configures ENABLE QUAD DATA for this instance.
    ENABLE_QUAD_DATA   : boolean := true;
    -- Configures ENABLE CRC16 for this instance.
    ENABLE_CRC16       : boolean := false;
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR_TAG         : string  := "XILINX";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_SERIES_TAG : string  := "GENERIC"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk           : in  std_logic;
    -- Active-low reset for this clock domain.
    rstn          : in  std_logic;
    -- Input qspi sclk i signal for this module.
    qspi_sclk_i   : in  std_logic;
    -- Input qspi cs n i signal for this module.
    qspi_cs_n_i   : in  std_logic;
    -- Input qspi io i signal for this module.
    qspi_io_i     : in  std_logic_vector(3 downto 0);
    -- Output qspi io o signal generated by this module.
    qspi_io_o     : out std_logic_vector(3 downto 0);
    -- Qspi io oen interface signal.
    qspi_io_oen   : out std_logic_vector(3 downto 0);
    -- Register write address issued to the internal RadIF register target.
    reg_wr_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
    -- Register read address issued to the internal RadIF register target.
    reg_rd_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
    -- One-cycle write request pulse for the internal register target.
    reg_wr_en     : out std_logic;
    -- One-cycle read request pulse for the internal register target.
    reg_rd_en     : out std_logic;
    -- Write data presented to the internal register target.
    reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Read data returned by the internal register target.
    reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Write-side ready indication from the internal register target.
    reg_wr_rdy    : in  std_logic;
    -- Read-side ready indication from the internal register target.
    reg_rd_rdy    : in  std_logic;
    -- Write response valid indication from the internal register target.
    reg_wr_valid  : in  std_logic;
    -- Read response valid indication from the internal register target.
    reg_rd_valid  : in  std_logic;
    -- Register target error flag converted into the external bus error response.
    reg_error     : in  std_logic
  );
end entity;

architecture rtl of radif_qspi_slave_to_reg is
  type state_t is (WAIT_SOF, GET_OP, GET_ADDR_H, GET_ADDR_L, GET_WRITE_DATA, WAIT_WRITE, WAIT_READ);

  constant WORD_BYTES : natural := (DATA_WIDTH + 7) / 8;

  signal sclk_meta   : std_logic := '0';
  signal sclk_sync   : std_logic := '0';
  signal sclk_prev   : std_logic := '0';
  signal cs_meta     : std_logic := '1';
  signal cs_sync     : std_logic := '1';
  signal io_meta     : std_logic_vector(3 downto 0) := (others => '0');
  signal io_sync     : std_logic_vector(3 downto 0) := (others => '0');
  signal rx_shift    : std_logic_vector(7 downto 0) := (others => '0');
  signal tx_shift    : std_logic_vector(7 downto 0) := (others => '0');
  signal bit_count   : unsigned(2 downto 0) := (others => '0');
  signal nibble_high : std_logic := '1';
  signal tx_active   : std_logic := '0';
  signal state       : state_t := WAIT_SOF;
  signal op_r        : std_logic_vector(7 downto 0) := (others => '0');
  signal addr_r      : std_logic_vector(15 downto 0) := (others => '0');
  signal wr_data_r   : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
  signal wr_addr_r   : std_logic_vector(ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal rd_addr_r   : std_logic_vector(ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal wr_en_r     : std_logic := '0';
  signal rd_en_r     : std_logic := '0';
  signal data_index  : natural range 0 to WORD_BYTES := 0;
  signal tx_word     : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
  signal tx_index    : natural range 0 to WORD_BYTES := 0;
  signal status_r    : std_logic_vector(7 downto 0) := RADIF_STATUS_OK;

  function resize_addr(a : std_logic_vector(15 downto 0)) return std_logic_vector is
    variable outv : std_logic_vector(ADDR_WIDTH - 1 downto 0) := (others => '0');
  begin
    if ADDR_WIDTH <= 16 then
      outv := a(ADDR_WIDTH - 1 downto 0);
    else
      outv(15 downto 0) := a;
    end if;
    return outv;
  end function;

  function byte_from_word(w : std_logic_vector; idx : natural) return std_logic_vector is
    variable b : std_logic_vector(7 downto 0) := (others => '0');
    variable hi : integer;
  begin
    hi := w'length - 1 - integer(idx * 8);
    if hi >= 7 then
      b := w(hi downto hi - 7);
    end if;
    return b;
  end function;
begin
  qspi_io_o <= tx_shift(7 downto 4) when ENABLE_QUAD_DATA else "00" & tx_shift(7) & '0';
  qspi_io_oen <= "0000" when ENABLE_QUAD_DATA and qspi_cs_n_i = '0' and tx_active = '1' else
                 "1101" when (not ENABLE_QUAD_DATA) and qspi_cs_n_i = '0' else
                 "1111";
  reg_wr_addr <= wr_addr_r;
  reg_rd_addr <= rd_addr_r;
  reg_data_in <= wr_data_r;
  reg_wr_en <= wr_en_r;
  reg_rd_en <= rd_en_r;

  gen_xilinx_vendor : if VENDOR_TAG = "XILINX" generate
  begin
  end generate;

  gen_generic_vendor : if VENDOR_TAG /= "XILINX" generate
  begin
  end generate;

  process(clk)
    variable rx_byte : std_logic_vector(7 downto 0);
    variable byte_valid : boolean;
    variable next_addr : std_logic_vector(15 downto 0);
    variable lane_in : std_logic_vector(3 downto 0);
  begin
    if rising_edge(clk) then
      sclk_meta <= qspi_sclk_i;
      sclk_sync <= sclk_meta;
      sclk_prev <= sclk_sync;
      cs_meta <= qspi_cs_n_i;
      cs_sync <= cs_meta;
      io_meta <= qspi_io_i;
      io_sync <= io_meta;

      wr_en_r <= '0';
      rd_en_r <= '0';
      byte_valid := false;
      rx_byte := rx_shift;
      lane_in := io_sync;

      if rstn = '0' then
        state <= WAIT_SOF;
        bit_count <= (others => '0');
        nibble_high <= '1';
        rx_shift <= (others => '0');
        tx_shift <= (others => '0');
        tx_active <= '0';
        status_r <= RADIF_STATUS_OK;
      elsif cs_sync = '1' then
        state <= WAIT_SOF;
        bit_count <= (others => '0');
        nibble_high <= '1';
        tx_shift <= status_r;
        tx_index <= 0;
        tx_active <= '0';
      else
        if sclk_sync = '1' and sclk_prev = '0' then
          if ENABLE_QUAD_DATA then
            if nibble_high = '1' then
              rx_shift(7 downto 4) <= lane_in;
              nibble_high <= '0';
            else
              rx_shift(3 downto 0) <= lane_in;
              rx_byte := rx_shift(7 downto 4) & lane_in;
              byte_valid := true;
              nibble_high <= '1';
            end if;
          else
            rx_byte := rx_shift(6 downto 0) & lane_in(0);
            rx_shift <= rx_shift(6 downto 0) & lane_in(0);
            if bit_count = "111" then
              bit_count <= (others => '0');
              byte_valid := true;
            else
              bit_count <= bit_count + 1;
            end if;
          end if;
        end if;

        if sclk_sync = '0' and sclk_prev = '1' then
          if ENABLE_QUAD_DATA then
            tx_shift <= tx_shift(3 downto 0) & "0000";
          else
            tx_shift <= tx_shift(6 downto 0) & '0';
          end if;
        end if;

        if byte_valid then
          case state is
            when WAIT_SOF =>
              if rx_byte = x"A5" then
                tx_shift <= status_r;
                state <= GET_OP;
              end if;

            when GET_OP =>
              op_r <= rx_byte;
              status_r <= RADIF_STATUS_OK;
              tx_active <= '0';
              if rx_byte = RADIF_OP_REG_WRITE or rx_byte = RADIF_OP_REG_READ then
                state <= GET_ADDR_H;
              elsif rx_byte = RADIF_OP_CAPS then
                tx_shift <= x"04";
                tx_active <= '1';
                state <= WAIT_SOF;
              else
                status_r <= RADIF_STATUS_BAD_OP;
                state <= WAIT_SOF;
              end if;

            when GET_ADDR_H =>
              addr_r(15 downto 8) <= rx_byte;
              state <= GET_ADDR_L;

            when GET_ADDR_L =>
              next_addr := addr_r(15 downto 8) & rx_byte;
              addr_r(7 downto 0) <= rx_byte;
              if op_r = RADIF_OP_REG_WRITE then
                data_index <= 0;
                wr_data_r <= (others => '0');
                state <= GET_WRITE_DATA;
              elsif reg_rd_rdy = '1' then
                rd_addr_r <= resize_addr(next_addr);
                rd_en_r <= '1';
                state <= WAIT_READ;
              end if;

            when GET_WRITE_DATA =>
              wr_data_r(DATA_WIDTH - 1 - (data_index * 8) downto DATA_WIDTH - 8 - (data_index * 8)) <= rx_byte;
              if data_index = WORD_BYTES - 1 then
                if reg_wr_rdy = '1' then
                  wr_addr_r <= resize_addr(addr_r);
                  wr_en_r <= '1';
                  state <= WAIT_WRITE;
                end if;
              else
                data_index <= data_index + 1;
              end if;

            when WAIT_WRITE =>
              if reg_wr_valid = '1' then
                if reg_error = '1' then
                  status_r <= RADIF_STATUS_ERROR;
                else
                  status_r <= RADIF_STATUS_OK;
                end if;
                tx_shift <= status_r;
                tx_active <= '1';
                state <= WAIT_SOF;
              end if;

            when WAIT_READ =>
              if reg_rd_valid = '1' then
                if reg_error = '1' then
                  status_r <= RADIF_STATUS_ERROR;
                  tx_word <= (others => '0');
                  tx_shift <= (others => '0');
                else
                  status_r <= RADIF_STATUS_OK;
                  tx_word <= reg_data_out;
                  tx_shift <= byte_from_word(reg_data_out, 0);
                  tx_index <= 1;
                end if;
                tx_active <= '1';
                state <= WAIT_SOF;
              end if;
          end case;
        elsif tx_active = '1' and tx_index > 0 and tx_index < WORD_BYTES and sclk_sync = '0' and sclk_prev = '1' then
          if ENABLE_QUAD_DATA or bit_count = "000" then
            tx_shift <= byte_from_word(tx_word, tx_index);
            tx_index <= tx_index + 1;
          end if;
        end if;
      end if;
    end if;
  end process;
end architecture;
