library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- AXI4 memory-mapped to AXI-stream DMA bridge for RadIF systems.
-- Moves register-controlled memory bursts into and out of streaming datapaths with simple status and flow-control signals.
entity radif_axi4_axis_dma is
  generic (
    -- Sets the bit width for REG DATA WIDTH values carried by this module.
    REG_DATA_WIDTH     : integer := 32;
    -- Sets the bit width for REG ADDR WIDTH values carried by this module.
    REG_ADDR_WIDTH     : integer := 16;
    -- Sets the bit width for AXI ADDR WIDTH values carried by this module.
    AXI_ADDR_WIDTH     : integer := 32;
    -- Sets the bit width for AXI DATA WIDTH values carried by this module.
    AXI_DATA_WIDTH     : integer := 32;
    -- Sets the bit width for AXIS DATA WIDTH values carried by this module.
    AXIS_DATA_WIDTH    : integer := 32;
    -- Configures ENABLE MM2S for this instance.
    ENABLE_MM2S        : boolean := true;
    -- Configures ENABLE S2MM for this instance.
    ENABLE_S2MM        : boolean := true;
    -- Sets the storage depth, frame length, or number of buffered samples used internally.
    FIFO_DEPTH         : integer := 1024;
    -- Configures FIFO FWFT for this instance.
    FIFO_FWFT          : boolean := true;
    -- Configures MAX BURST LEN for this instance.
    MAX_BURST_LEN      : integer := 16;
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR_TAG         : string  := "XILINX";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_SERIES_TAG : string  := "GENERIC"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk             : in  std_logic;
    -- Active-low reset for this clock domain.
    rstn            : in  std_logic;
    -- Register write address issued to the internal RadIF register target.
    reg_wr_addr     : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
    -- Register read address issued to the internal RadIF register target.
    reg_rd_addr     : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
    -- One-cycle write request pulse for the internal register target.
    reg_wr_en       : in  std_logic;
    -- One-cycle read request pulse for the internal register target.
    reg_rd_en       : in  std_logic;
    -- Write data presented to the internal register target.
    reg_data_in     : in  std_logic_vector(REG_DATA_WIDTH - 1 downto 0);
    -- Read data returned by the internal register target.
    reg_data_out    : out std_logic_vector(REG_DATA_WIDTH - 1 downto 0);
    -- Write-side ready indication from the internal register target.
    reg_wr_rdy      : out std_logic;
    -- Read-side ready indication from the internal register target.
    reg_rd_rdy      : out std_logic;
    -- Write response valid indication from the internal register target.
    reg_wr_valid    : out std_logic;
    -- Read response valid indication from the internal register target.
    reg_rd_valid    : out std_logic;
    -- Register target error flag converted into the external bus error response.
    reg_error       : out std_logic;
    -- Output irq o signal generated by this module.
    irq_o           : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awaddr    : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awlen     : out std_logic_vector(7 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awsize    : out std_logic_vector(2 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awburst   : out std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awvalid   : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awready   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wdata     : out std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wstrb     : out std_logic_vector((AXI_DATA_WIDTH / 8) - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wlast     : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wvalid    : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wready    : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bresp     : in  std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bvalid    : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bready    : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_araddr    : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arlen     : out std_logic_vector(7 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arsize    : out std_logic_vector(2 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arburst   : out std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arvalid   : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arready   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rdata     : in  std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rresp     : in  std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rlast     : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rvalid    : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rready    : out std_logic;
    -- Output AXI-stream payload containing packed processed result lanes.
    m_axis_tdata    : out std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0);
    -- Output AXI-stream valid qualifier for the current result beat.
    m_axis_tvalid   : out std_logic;
    -- Output AXI-stream ready input from the downstream block.
    m_axis_tready   : in  std_logic;
    -- Output AXI-stream frame marker aligned with the processed result beat.
    m_axis_tlast    : out std_logic;
    -- Input AXI-stream payload containing packed sample or feature lanes.
    s_axis_tdata    : in  std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0);
    -- Input AXI-stream valid qualifier for the current sample beat.
    s_axis_tvalid   : in  std_logic;
    -- Input AXI-stream ready response indicating this block can accept a beat.
    s_axis_tready   : out std_logic;
    -- Input AXI-stream frame marker for the final beat of a frame.
    s_axis_tlast    : in  std_logic
  );
end entity;

architecture rtl of radif_axi4_axis_dma is
  component xpm_fifo_sync
    generic (
      -- Configures CASCADE HEIGHT for this instance.
      CASCADE_HEIGHT      : integer := 0;
      -- Configures DOUT RESET VALUE for this instance.
      DOUT_RESET_VALUE    : string  := "0";
      -- Configures ECC MODE for this instance.
      ECC_MODE            : string  := "no_ecc";
      -- Configures FIFO MEMORY TYPE for this instance.
      FIFO_MEMORY_TYPE    : string  := "auto";
      -- Configures FIFO READ LATENCY for this instance.
      FIFO_READ_LATENCY   : integer := 1;
      -- Sets the storage depth, frame length, or number of buffered samples used internally.
      FIFO_WRITE_DEPTH    : integer := 1024;
      -- Configures FULL RESET VALUE for this instance.
      FULL_RESET_VALUE    : integer := 0;
      -- Configures PROG EMPTY THRESH for this instance.
      PROG_EMPTY_THRESH   : integer := 10;
      -- Configures PROG FULL THRESH for this instance.
      PROG_FULL_THRESH    : integer := 10;
      -- Sets the bit width for RD DATA COUNT WIDTH values carried by this module.
      RD_DATA_COUNT_WIDTH : integer := 1;
      -- Sets the bit width for READ DATA WIDTH values carried by this module.
      READ_DATA_WIDTH     : integer := 32;
      -- Configures READ MODE for this instance.
      READ_MODE           : string  := "std";
      -- Configures SIM ASSERT CHK for this instance.
      SIM_ASSERT_CHK      : integer := 0;
      -- Configures USE ADV FEATURES for this instance.
      USE_ADV_FEATURES    : string  := "0707";
      -- Configures WAKEUP TIME for this instance.
      WAKEUP_TIME         : integer := 0;
      -- Sets the bit width for WRITE DATA WIDTH values carried by this module.
      WRITE_DATA_WIDTH    : integer := 32;
      -- Sets the bit width for WR DATA COUNT WIDTH values carried by this module.
      WR_DATA_COUNT_WIDTH : integer := 1
    );
    port (
      -- Almost empty interface signal.
      almost_empty  : out std_logic;
      -- Almost full interface signal.
      almost_full   : out std_logic;
      -- Data valid interface signal.
      data_valid    : out std_logic;
      -- Dbiterr interface signal.
      dbiterr       : out std_logic;
      -- Dout interface signal.
      dout          : out std_logic_vector(READ_DATA_WIDTH - 1 downto 0);
      -- Empty interface signal.
      empty         : out std_logic;
      -- Full interface signal.
      full          : out std_logic;
      -- Overflow interface signal.
      overflow      : out std_logic;
      -- Prog empty interface signal.
      prog_empty    : out std_logic;
      -- Prog full interface signal.
      prog_full     : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_data_count : out std_logic_vector(RD_DATA_COUNT_WIDTH - 1 downto 0);
      -- Readback control or data signal for host-visible captured state.
      rd_rst_busy   : out std_logic;
      -- Sbiterr interface signal.
      sbiterr       : out std_logic;
      -- Underflow interface signal.
      underflow     : out std_logic;
      -- Wr ack interface signal.
      wr_ack        : out std_logic;
      -- Wr data count interface signal.
      wr_data_count : out std_logic_vector(WR_DATA_COUNT_WIDTH - 1 downto 0);
      -- Wr rst busy interface signal.
      wr_rst_busy   : out std_logic;
      -- Din interface signal.
      din           : in  std_logic_vector(WRITE_DATA_WIDTH - 1 downto 0);
      -- Injectdbiterr interface signal.
      injectdbiterr : in  std_logic;
      -- Injectsbiterr interface signal.
      injectsbiterr : in  std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_en         : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst           : in  std_logic;
      -- Sleep interface signal.
      sleep         : in  std_logic;
      -- Clock for the associated synchronous logic and handshake domain.
      wr_clk        : in  std_logic;
      -- Wr en interface signal.
      wr_en         : in  std_logic
    );
  end component;

  type mm2s_state_t is (MM2S_IDLE, MM2S_AR, MM2S_R);
  type s2mm_state_t is (S2MM_IDLE, S2MM_AW_W, S2MM_B);

  constant AXI_BYTES        : natural := AXI_DATA_WIDTH / 8;
  constant MM_FIFO_WIDTH    : natural := AXIS_DATA_WIDTH + 1;
  constant S2_FIFO_WIDTH    : natural := AXIS_DATA_WIDTH + 1;

  signal control_r       : std_logic_vector(REG_DATA_WIDTH - 1 downto 0) := (others => '0');
  signal status_r        : std_logic_vector(REG_DATA_WIDTH - 1 downto 0) := (others => '0');
  signal mm2s_base_r     : unsigned(AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal mm2s_end_r      : unsigned(AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal mm2s_addr_r     : unsigned(AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal mm2s_len_r      : unsigned(31 downto 0) := (others => '0');
  signal mm2s_rem_r      : unsigned(31 downto 0) := (others => '0');
  signal s2mm_base_r     : unsigned(AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal s2mm_end_r      : unsigned(AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal s2mm_addr_r     : unsigned(AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal s2mm_len_r      : unsigned(31 downto 0) := (others => '0');
  signal s2mm_rem_r      : unsigned(31 downto 0) := (others => '0');
  signal mm2s_state      : mm2s_state_t := MM2S_IDLE;
  signal s2mm_state      : s2mm_state_t := S2MM_IDLE;

  signal rd_data_r       : std_logic_vector(REG_DATA_WIDTH - 1 downto 0) := (others => '0');
  signal wr_valid_r      : std_logic := '0';
  signal rd_valid_r      : std_logic := '0';
  signal error_r         : std_logic := '0';
  signal irq_r           : std_logic := '0';

  signal awaddr_r        : std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal araddr_r        : std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0) := (others => '0');
  signal awvalid_r       : std_logic := '0';
  signal wvalid_r        : std_logic := '0';
  signal bready_r        : std_logic := '0';
  signal arvalid_r       : std_logic := '0';
  signal rready_r        : std_logic := '0';
  signal wdata_r         : std_logic_vector(AXI_DATA_WIDTH - 1 downto 0) := (others => '0');

  signal mm_fifo_din     : std_logic_vector(MM_FIFO_WIDTH - 1 downto 0) := (others => '0');
  signal mm_fifo_dout    : std_logic_vector(MM_FIFO_WIDTH - 1 downto 0);
  signal mm_fifo_wr_en   : std_logic := '0';
  signal mm_fifo_rd_en   : std_logic := '0';
  signal mm_fifo_empty   : std_logic;
  signal mm_fifo_full    : std_logic;
  signal mm_fifo_valid   : std_logic;
  signal mm_fifo_rst     : std_logic;
  signal mm_word_valid   : std_logic := '0';
  signal mm_word_data    : std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0) := (others => '0');
  signal mm_word_last    : std_logic := '0';
  signal mm_wait_data    : std_logic := '0';

  signal s2_fifo_din     : std_logic_vector(S2_FIFO_WIDTH - 1 downto 0);
  signal s2_fifo_dout    : std_logic_vector(S2_FIFO_WIDTH - 1 downto 0);
  signal s2_fifo_wr_en   : std_logic;
  signal s2_fifo_rd_en   : std_logic := '0';
  signal s2_fifo_empty   : std_logic;
  signal s2_fifo_full    : std_logic;
  signal s2_fifo_valid   : std_logic;
  signal s2_fifo_rst     : std_logic;
  signal s2_word_valid   : std_logic := '0';
  signal s2_word_data    : std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0) := (others => '0');
  signal s2_word_last    : std_logic := '0';
  signal s2_wait_data    : std_logic := '0';
  signal s2_aw_done      : std_logic := '0';
  signal s2_w_done       : std_logic := '0';

  function ceil_log2(n : positive) return natural is
    variable v : natural := n - 1;
    variable r : natural := 0;
  begin
    while v > 0 loop
      v := v / 2;
      r := r + 1;
    end loop;
    return r;
  end function;

  function fifo_count_width(depth : positive) return natural is
  begin
    return ceil_log2(depth) + 1;
  end function;

  function fifo_read_mode return string is
  begin
    if FIFO_FWFT then
      return "fwft";
    end if;
    return "std";
  end function;

  function fifo_read_latency return integer is
  begin
    if FIFO_FWFT then
      return 0;
    end if;
    return 1;
  end function;

  function axi_size return std_logic_vector is
  begin
    case AXI_BYTES is
      when 1 => return "000";
      when 2 => return "001";
      when 4 => return "010";
      when 8 => return "011";
      when 16 => return "100";
      when 32 => return "101";
      when 64 => return "110";
      when others => return "010";
    end case;
  end function;

  function reg_index(a : std_logic_vector) return natural is
  begin
    return to_integer(shift_right(unsigned(a), 2));
  end function;

  function set_addr_low(old_addr : unsigned; data : std_logic_vector) return unsigned is
    variable outv : unsigned(old_addr'range) := old_addr;
  begin
    if old_addr'length >= data'length then
      outv(data'length - 1 downto 0) := unsigned(data);
    else
      outv := unsigned(data(old_addr'length - 1 downto 0));
    end if;
    return outv;
  end function;

  function set_addr_high(old_addr : unsigned; data : std_logic_vector) return unsigned is
    variable outv : unsigned(old_addr'range) := old_addr;
    variable high_width : natural;
  begin
    if old_addr'length > data'length then
      high_width := old_addr'length - data'length;
      if high_width >= data'length then
        outv((2 * data'length) - 1 downto data'length) := unsigned(data);
      else
        outv(old_addr'length - 1 downto data'length) := unsigned(data(high_width - 1 downto 0));
      end if;
    end if;
    return outv;
  end function;

  function addr_low_word(a : unsigned) return std_logic_vector is
    variable outv : std_logic_vector(REG_DATA_WIDTH - 1 downto 0) := (others => '0');
  begin
    if a'length >= REG_DATA_WIDTH then
      outv := std_logic_vector(a(REG_DATA_WIDTH - 1 downto 0));
    else
      outv(a'length - 1 downto 0) := std_logic_vector(a);
    end if;
    return outv;
  end function;

  function addr_high_word(a : unsigned) return std_logic_vector is
    variable outv : std_logic_vector(REG_DATA_WIDTH - 1 downto 0) := (others => '0');
    variable high_width : natural;
  begin
    if a'length > REG_DATA_WIDTH then
      high_width := a'length - REG_DATA_WIDTH;
      if high_width >= REG_DATA_WIDTH then
        outv := std_logic_vector(a((2 * REG_DATA_WIDTH) - 1 downto REG_DATA_WIDTH));
      else
        outv(high_width - 1 downto 0) := std_logic_vector(a(a'length - 1 downto REG_DATA_WIDTH));
      end if;
    end if;
    return outv;
  end function;

  function advance_addr(
    current_addr : unsigned;
    base_addr    : unsigned;
    end_addr     : unsigned;
    circular     : std_logic
  ) return unsigned is
    variable next_addr : unsigned(current_addr'range);
  begin
    next_addr := current_addr + AXI_BYTES;
    if circular = '1' and end_addr > base_addr and next_addr >= end_addr then
      next_addr := base_addr;
    end if;
    return next_addr;
  end function;
begin
  assert AXI_DATA_WIDTH = AXIS_DATA_WIDTH
    report "radif_axi4_axis_dma currently requires AXI_DATA_WIDTH = AXIS_DATA_WIDTH"
    severity failure;

  reg_wr_rdy <= '1';
  reg_rd_rdy <= '1';
  reg_data_out <= rd_data_r;
  reg_wr_valid <= wr_valid_r;
  reg_rd_valid <= rd_valid_r;
  reg_error <= error_r;
  irq_o <= irq_r;
  mm_fifo_rst <= not rstn;
  s2_fifo_rst <= not rstn;

  m_axi_awaddr <= awaddr_r;
  m_axi_awlen <= (others => '0');
  m_axi_awsize <= axi_size;
  m_axi_awburst <= "01";
  m_axi_awvalid <= awvalid_r;
  m_axi_wdata <= wdata_r;
  m_axi_wstrb <= (others => '1');
  m_axi_wlast <= '1';
  m_axi_wvalid <= wvalid_r;
  m_axi_bready <= bready_r;
  m_axi_araddr <= araddr_r;
  m_axi_arlen <= (others => '0');
  m_axi_arsize <= axi_size;
  m_axi_arburst <= "01";
  m_axi_arvalid <= arvalid_r;
  m_axi_rready <= rready_r;

  m_axis_tdata <= mm_word_data;
  m_axis_tvalid <= mm_word_valid;
  m_axis_tlast <= mm_word_last;

  s_axis_tready <= '1' when ENABLE_S2MM and status_r(2) = '1' and s2_fifo_full = '0' else '0';
  s2_fifo_din <= s_axis_tlast & s_axis_tdata;
  s2_fifo_wr_en <= s_axis_tvalid and s_axis_tready;

  gen_xilinx_vendor : if VENDOR_TAG = "XILINX" generate
  begin
  end generate;

  gen_generic_vendor : if VENDOR_TAG /= "XILINX" generate
  begin
  end generate;

  u_mm2s_fifo : xpm_fifo_sync
    generic map (
      FIFO_MEMORY_TYPE => "auto",
      FIFO_WRITE_DEPTH => FIFO_DEPTH,
      WRITE_DATA_WIDTH => MM_FIFO_WIDTH,
      READ_DATA_WIDTH => MM_FIFO_WIDTH,
      READ_MODE => fifo_read_mode,
      FIFO_READ_LATENCY => fifo_read_latency,
      WR_DATA_COUNT_WIDTH => fifo_count_width(FIFO_DEPTH),
      RD_DATA_COUNT_WIDTH => fifo_count_width(FIFO_DEPTH),
      USE_ADV_FEATURES => "0707"
    )
    port map (
      almost_empty => open,
      almost_full => open,
      data_valid => mm_fifo_valid,
      dbiterr => open,
      dout => mm_fifo_dout,
      empty => mm_fifo_empty,
      full => mm_fifo_full,
      overflow => open,
      prog_empty => open,
      prog_full => open,
      rd_data_count => open,
      rd_rst_busy => open,
      sbiterr => open,
      underflow => open,
      wr_ack => open,
      wr_data_count => open,
      wr_rst_busy => open,
      din => mm_fifo_din,
      injectdbiterr => '0',
      injectsbiterr => '0',
      rd_en => mm_fifo_rd_en,
      rst => mm_fifo_rst,
      sleep => '0',
      wr_clk => clk,
      wr_en => mm_fifo_wr_en
    );

  u_s2mm_fifo : xpm_fifo_sync
    generic map (
      FIFO_MEMORY_TYPE => "auto",
      FIFO_WRITE_DEPTH => FIFO_DEPTH,
      WRITE_DATA_WIDTH => S2_FIFO_WIDTH,
      READ_DATA_WIDTH => S2_FIFO_WIDTH,
      READ_MODE => fifo_read_mode,
      FIFO_READ_LATENCY => fifo_read_latency,
      WR_DATA_COUNT_WIDTH => fifo_count_width(FIFO_DEPTH),
      RD_DATA_COUNT_WIDTH => fifo_count_width(FIFO_DEPTH),
      USE_ADV_FEATURES => "0707"
    )
    port map (
      almost_empty => open,
      almost_full => open,
      data_valid => s2_fifo_valid,
      dbiterr => open,
      dout => s2_fifo_dout,
      empty => s2_fifo_empty,
      full => s2_fifo_full,
      overflow => open,
      prog_empty => open,
      prog_full => open,
      rd_data_count => open,
      rd_rst_busy => open,
      sbiterr => open,
      underflow => open,
      wr_ack => open,
      wr_data_count => open,
      wr_rst_busy => open,
      din => s2_fifo_din,
      injectdbiterr => '0',
      injectsbiterr => '0',
      rd_en => s2_fifo_rd_en,
      rst => s2_fifo_rst,
      sleep => '0',
      wr_clk => clk,
      wr_en => s2_fifo_wr_en
    );

  process(clk)
    variable idx : natural;
  begin
    if rising_edge(clk) then
      wr_valid_r <= '0';
      rd_valid_r <= '0';
      error_r <= '0';
      mm_fifo_wr_en <= '0';
      mm_fifo_rd_en <= '0';
      s2_fifo_rd_en <= '0';
      irq_r <= status_r(1) or status_r(3) or status_r(9) or status_r(11);

      if rstn = '0' then
        control_r <= (others => '0');
        status_r <= (others => '0');
        mm2s_base_r <= (others => '0');
        mm2s_end_r <= (others => '0');
        mm2s_addr_r <= (others => '0');
        mm2s_len_r <= (others => '0');
        mm2s_rem_r <= (others => '0');
        s2mm_base_r <= (others => '0');
        s2mm_end_r <= (others => '0');
        s2mm_addr_r <= (others => '0');
        s2mm_len_r <= (others => '0');
        s2mm_rem_r <= (others => '0');
        mm2s_state <= MM2S_IDLE;
        s2mm_state <= S2MM_IDLE;
        awvalid_r <= '0';
        wvalid_r <= '0';
        bready_r <= '0';
        arvalid_r <= '0';
        rready_r <= '0';
        mm_word_valid <= '0';
        mm_wait_data <= '0';
        s2_word_valid <= '0';
        s2_wait_data <= '0';
        s2_aw_done <= '0';
        s2_w_done <= '0';
      else
        status_r(4) <= mm_fifo_empty;
        status_r(5) <= mm_fifo_full;
        status_r(6) <= s2_fifo_empty;
        status_r(7) <= s2_fifo_full;

        if reg_wr_en = '1' then
          wr_valid_r <= '1';
          idx := reg_index(reg_wr_addr);
          case idx is
            when 0 =>
              control_r <= reg_data_in;
              if reg_data_in(0) = '1' and ENABLE_MM2S then
                status_r(0) <= '1';
                status_r(1) <= '0';
                status_r(8) <= '0';
                mm2s_addr_r <= mm2s_base_r;
                mm2s_rem_r <= mm2s_len_r;
              elsif reg_data_in(0) = '0' then
                status_r(0) <= '0';
              end if;

              if reg_data_in(8) = '1' and ENABLE_S2MM then
                status_r(2) <= '1';
                status_r(3) <= '0';
                status_r(10) <= '0';
                s2mm_addr_r <= s2mm_base_r;
                s2mm_rem_r <= s2mm_len_r;
              elsif reg_data_in(8) = '0' then
                status_r(2) <= '0';
              end if;
            when 1 =>
              status_r <= status_r and not reg_data_in;
            when 2 =>
              mm2s_base_r <= set_addr_low(mm2s_base_r, reg_data_in);
            when 3 =>
              mm2s_base_r <= set_addr_high(mm2s_base_r, reg_data_in);
            when 4 =>
              mm2s_end_r <= set_addr_low(mm2s_end_r, reg_data_in);
            when 5 =>
              mm2s_end_r <= set_addr_high(mm2s_end_r, reg_data_in);
            when 6 =>
              mm2s_len_r <= unsigned(reg_data_in(31 downto 0));
            when 7 =>
              s2mm_base_r <= set_addr_low(s2mm_base_r, reg_data_in);
            when 8 =>
              s2mm_base_r <= set_addr_high(s2mm_base_r, reg_data_in);
            when 9 =>
              s2mm_end_r <= set_addr_low(s2mm_end_r, reg_data_in);
            when 10 =>
              s2mm_end_r <= set_addr_high(s2mm_end_r, reg_data_in);
            when 11 =>
              s2mm_len_r <= unsigned(reg_data_in(31 downto 0));
            when others =>
              error_r <= '1';
          end case;
        end if;

        if reg_rd_en = '1' then
          rd_valid_r <= '1';
          rd_data_r <= (others => '0');
          idx := reg_index(reg_rd_addr);
          case idx is
            when 0 => rd_data_r <= control_r;
            when 1 => rd_data_r <= status_r;
            when 2 => rd_data_r <= addr_low_word(mm2s_base_r);
            when 3 => rd_data_r <= addr_high_word(mm2s_base_r);
            when 4 => rd_data_r <= addr_low_word(mm2s_end_r);
            when 5 => rd_data_r <= addr_high_word(mm2s_end_r);
            when 6 => rd_data_r(31 downto 0) <= std_logic_vector(mm2s_len_r);
            when 7 => rd_data_r <= addr_low_word(s2mm_base_r);
            when 8 => rd_data_r <= addr_high_word(s2mm_base_r);
            when 9 => rd_data_r <= addr_low_word(s2mm_end_r);
            when 10 => rd_data_r <= addr_high_word(s2mm_end_r);
            when 11 => rd_data_r(31 downto 0) <= std_logic_vector(s2mm_len_r);
            when 12 => rd_data_r <= addr_low_word(mm2s_addr_r);
            when 13 => rd_data_r <= addr_low_word(s2mm_addr_r);
            when others => error_r <= '1';
          end case;
        end if;

        if mm_word_valid = '1' then
          if m_axis_tready = '1' then
            mm_word_valid <= '0';
          end if;
        elsif FIFO_FWFT and mm_fifo_empty = '0' then
          mm_word_last <= mm_fifo_dout(MM_FIFO_WIDTH - 1);
          mm_word_data <= mm_fifo_dout(AXIS_DATA_WIDTH - 1 downto 0);
          mm_word_valid <= '1';
          mm_fifo_rd_en <= '1';
        elsif (not FIFO_FWFT) and mm_wait_data = '0' and mm_fifo_empty = '0' then
          mm_fifo_rd_en <= '1';
          mm_wait_data <= '1';
        elsif (not FIFO_FWFT) and mm_wait_data = '1' and mm_fifo_valid = '1' then
          mm_word_last <= mm_fifo_dout(MM_FIFO_WIDTH - 1);
          mm_word_data <= mm_fifo_dout(AXIS_DATA_WIDTH - 1 downto 0);
          mm_word_valid <= '1';
          mm_wait_data <= '0';
        end if;

        if s2_word_valid = '0' and FIFO_FWFT and s2_fifo_empty = '0' then
          s2_word_last <= s2_fifo_dout(S2_FIFO_WIDTH - 1);
          s2_word_data <= s2_fifo_dout(AXIS_DATA_WIDTH - 1 downto 0);
          s2_word_valid <= '1';
          s2_fifo_rd_en <= '1';
        elsif s2_word_valid = '0' and (not FIFO_FWFT) and s2_wait_data = '0' and s2_fifo_empty = '0' then
          s2_fifo_rd_en <= '1';
          s2_wait_data <= '1';
        elsif s2_word_valid = '0' and (not FIFO_FWFT) and s2_wait_data = '1' and s2_fifo_valid = '1' then
          s2_word_last <= s2_fifo_dout(S2_FIFO_WIDTH - 1);
          s2_word_data <= s2_fifo_dout(AXIS_DATA_WIDTH - 1 downto 0);
          s2_word_valid <= '1';
          s2_wait_data <= '0';
        end if;

        case mm2s_state is
          when MM2S_IDLE =>
            if ENABLE_MM2S and status_r(0) = '1' and mm_fifo_full = '0' and (control_r(1) = '1' or mm2s_rem_r /= 0) then
              araddr_r <= std_logic_vector(mm2s_addr_r);
              arvalid_r <= '1';
              mm2s_state <= MM2S_AR;
            end if;

          when MM2S_AR =>
            if m_axi_arready = '1' then
              arvalid_r <= '0';
              rready_r <= '1';
              mm2s_state <= MM2S_R;
            end if;

          when MM2S_R =>
            rready_r <= not mm_fifo_full;
            if m_axi_rvalid = '1' and mm_fifo_full = '0' then
              mm_fifo_din <= '0' & m_axi_rdata(AXIS_DATA_WIDTH - 1 downto 0);
              if control_r(1) = '0' and mm2s_rem_r <= AXI_BYTES then
                mm_fifo_din(MM_FIFO_WIDTH - 1) <= '1';
              end if;
              mm_fifo_wr_en <= '1';
              rready_r <= '0';

              if m_axi_rresp /= "00" then
                status_r(8) <= '1';
              end if;

              mm2s_addr_r <= advance_addr(mm2s_addr_r, mm2s_base_r, mm2s_end_r, control_r(1));
              if control_r(1) = '0' then
                if mm2s_rem_r <= AXI_BYTES then
                  status_r(0) <= '0';
                  status_r(1) <= '1';
                  mm2s_rem_r <= (others => '0');
                else
                  mm2s_rem_r <= mm2s_rem_r - AXI_BYTES;
                end if;
              end if;
              mm2s_state <= MM2S_IDLE;
            end if;
        end case;

        case s2mm_state is
          when S2MM_IDLE =>
            if ENABLE_S2MM and status_r(2) = '1' and s2_word_valid = '1' and (control_r(9) = '1' or s2mm_rem_r /= 0) then
              awaddr_r <= std_logic_vector(s2mm_addr_r);
              wdata_r <= s2_word_data;
              awvalid_r <= '1';
              wvalid_r <= '1';
              s2_aw_done <= '0';
              s2_w_done <= '0';
              s2mm_state <= S2MM_AW_W;
            end if;

          when S2MM_AW_W =>
            if awvalid_r = '1' and m_axi_awready = '1' then
              awvalid_r <= '0';
              s2_aw_done <= '1';
            end if;
            if wvalid_r = '1' and m_axi_wready = '1' then
              wvalid_r <= '0';
              s2_w_done <= '1';
            end if;
            if (s2_aw_done = '1' or (awvalid_r = '1' and m_axi_awready = '1')) and
               (s2_w_done = '1' or (wvalid_r = '1' and m_axi_wready = '1')) then
              bready_r <= '1';
              s2_word_valid <= '0';
              s2mm_state <= S2MM_B;
            end if;

          when S2MM_B =>
            if m_axi_bvalid = '1' then
              bready_r <= '0';
              if m_axi_bresp /= "00" then
                status_r(10) <= '1';
              end if;

              s2mm_addr_r <= advance_addr(s2mm_addr_r, s2mm_base_r, s2mm_end_r, control_r(9));
              if control_r(9) = '0' then
                if s2mm_rem_r <= AXI_BYTES or s2_word_last = '1' then
                  status_r(2) <= '0';
                  status_r(3) <= '1';
                  s2mm_rem_r <= (others => '0');
                else
                  s2mm_rem_r <= s2mm_rem_r - AXI_BYTES;
                end if;
              end if;
              s2mm_state <= S2MM_IDLE;
            end if;
        end case;
      end if;
    end if;
  end process;
end architecture;
