library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library radif;
use radif.radif_pkg.all;

-- Configurable RadIF register bank with software-visible storage.
-- Provides ready/valid read and write responses for a parameterized set of memory-mapped control/status registers.
entity radif_reg_bank is
  generic (
    -- Sets the bit width for DATA WIDTH values carried by this module.
    DATA_WIDTH         : integer := 32;
    -- Sets the bit width for ADDR WIDTH values carried by this module.
    ADDR_WIDTH         : integer := 16;
    -- Configures READ ONLY REG COUNT for this instance.
    READ_ONLY_REG_COUNT  : integer := 8;
    -- Configures READ WRITE REG COUNT for this instance.
    READ_WRITE_REG_COUNT : integer := 64;
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR_TAG         : string  := "XILINX";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_SERIES_TAG : string  := "GENERIC"
  );
  port (
    -- Clock for the associated synchronous logic and handshake domain.
    clk        : in  std_logic;
    -- Active-low reset for this clock domain.
    rstn       : in  std_logic;
    -- Wr addr interface signal.
    wr_addr    : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
    -- Readback control or data signal for host-visible captured state.
    rd_addr    : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
    -- Wr en interface signal.
    wr_en      : in  std_logic;
    -- Readback control or data signal for host-visible captured state.
    rd_en      : in  std_logic;
    -- Data in interface signal.
    data_in    : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Data out interface signal.
    data_out   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
    -- Input read only regs i signal for this module.
    read_only_regs_i  : in  radif_reg_array_t(0 to READ_ONLY_REG_COUNT - 1)(DATA_WIDTH - 1 downto 0);
    -- Output read write regs o signal generated by this module.
    read_write_regs_o : out radif_reg_array_t(0 to READ_WRITE_REG_COUNT - 1)(DATA_WIDTH - 1 downto 0);
    -- Wr rdy interface signal.
    wr_rdy     : out std_logic;
    -- Readback control or data signal for host-visible captured state.
    rd_rdy     : out std_logic;
    -- Wr valid interface signal.
    wr_valid   : out std_logic;
    -- Readback control or data signal for host-visible captured state.
    rd_valid   : out std_logic;
    -- Error interface signal.
    error      : out std_logic
  );
end entity;

architecture rtl of radif_reg_bank is
  signal regs      : radif_reg_array_t(0 to READ_WRITE_REG_COUNT - 1)(DATA_WIDTH - 1 downto 0) := (others => (others => '0'));
  signal rd_data_r : std_logic_vector(DATA_WIDTH - 1 downto 0) := (others => '0');
  signal wr_v_r    : std_logic := '0';
  signal rd_v_r    : std_logic := '0';
  signal err_r     : std_logic := '0';

  function ceil_log2(n : positive) return natural is
    variable v : natural := n - 1;
    variable r : natural := 0;
  begin
    while v > 0 loop
      v := v / 2;
      r := r + 1;
    end loop;
    return r;
  end function;

  function addr_to_index(a : std_logic_vector) return natural is
    variable word_addr : unsigned(a'length - 1 downto 0);
  begin
    word_addr := unsigned(a);
    if DATA_WIDTH > 8 then
      word_addr := shift_right(word_addr, ceil_log2(DATA_WIDTH / 8));
    end if;
    return to_integer(word_addr);
  end function;
begin
  assert READ_ONLY_REG_COUNT > 0
    report "radif_reg_bank READ_ONLY_REG_COUNT must be greater than zero"
    severity failure;

  assert READ_WRITE_REG_COUNT > 0
    report "radif_reg_bank READ_WRITE_REG_COUNT must be greater than zero"
    severity failure;

  wr_rdy <= '1';
  rd_rdy <= '1';
  wr_valid <= wr_v_r;
  rd_valid <= rd_v_r;
  data_out <= rd_data_r;
  read_write_regs_o <= regs;
  error <= err_r;

  gen_xilinx_vendor : if VENDOR_TAG = "XILINX" generate
  begin
  end generate;

  gen_generic_vendor : if VENDOR_TAG /= "XILINX" generate
  begin
  end generate;

  process(clk)
    variable wr_index : natural;
    variable rd_index : natural;
  begin
    if rising_edge(clk) then
      wr_v_r <= '0';
      rd_v_r <= '0';
      err_r <= '0';

      if rstn = '0' then
        regs <= (others => (others => '0'));
        rd_data_r <= (others => '0');
      else
        if wr_en = '1' then
          wr_index := addr_to_index(wr_addr);
          wr_v_r <= '1';
          if wr_index < READ_WRITE_REG_COUNT then
            regs(wr_index) <= data_in;
          else
            err_r <= '1';
          end if;
        end if;

        if rd_en = '1' then
          rd_index := addr_to_index(rd_addr);
          rd_v_r <= '1';
          if rd_index < READ_WRITE_REG_COUNT then
            rd_data_r <= regs(rd_index);
          elsif rd_index < READ_WRITE_REG_COUNT + READ_ONLY_REG_COUNT then
            rd_data_r <= read_only_regs_i(rd_index - READ_WRITE_REG_COUNT);
          else
            rd_data_r <= (others => '0');
            err_r <= '1';
          end if;
        end if;
      end if;
    end if;
  end process;
end architecture;
