library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package debug is
  -- Component declaration sourced from debug/radila/hdl/radila/radila_core.vhd.
  component RadILA is
    generic (
      -- Sets the bit width for SAMPLE WIDTH values carried by this module.
      SAMPLE_WIDTH : integer := 32;
      -- Sets the bit width for EVENT WIDTH values carried by this module.
      EVENT_WIDTH  : integer := 8;
      -- Sets the storage depth, frame length, or number of buffered samples used internally.
      DEPTH        : integer := 1024;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH   : integer := 10;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      CMD_LANES    : integer := 4;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG   : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string := "7SERIES"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      sample_clk       : in  std_logic;
      -- Active-low reset for this clock domain.
      sample_rstn      : in  std_logic;
      -- Clock for the associated synchronous logic and handshake domain.
      axi_clk          : in  std_logic;
      -- Active-low reset for this clock domain.
      axi_rstn         : in  std_logic;
      -- Input sample vector captured or processed by the datapath.
      sample_i         : in  std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
      -- Event or trigger metadata associated with the current sample stream.
      event_i          : in  std_logic_vector(EVENT_WIDTH - 1 downto 0);
      -- Command/control input used to configure or trigger the block.
      cmd_data_i       : in  std_logic_vector(CMD_LANES - 1 downto 0);
      -- Command/control input used to configure or trigger the block.
      cmd_toggle_i     : in  std_logic;
      -- Command/control acknowledgement or status output.
      cmd_ack_toggle_o : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_index_i       : in  unsigned(ADDR_WIDTH - 1 downto 0);
      -- Readback control or data signal for host-visible captured state.
      rd_data_o        : out std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
      -- Output sample vector or current sample status from the datapath.
      sample_now_o     : out std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
      -- Event or trigger metadata associated with the current sample stream.
      event_now_o      : out std_logic_vector(EVENT_WIDTH - 1 downto 0);
      -- Output armed o signal generated by this module.
      armed_o          : out std_logic;
      -- Output capturing o signal generated by this module.
      capturing_o      : out std_logic;
      -- Output done o signal generated by this module.
      done_o           : out std_logic;
      -- Output overflow o signal generated by this module.
      overflow_o       : out std_logic;
      -- Output count o signal generated by this module.
      count_o          : out unsigned(ADDR_WIDTH downto 0)
    );
  end component;

  -- Component declaration sourced from debug/radila/hdl/radila/raddebughub_axi.vhd.
  component RadDebugHub is
    generic (
      -- Sets the bit width for C S AXI DATA WIDTH values carried by this module.
      C_S_AXI_DATA_WIDTH : integer := 32;
      -- Sets the bit width for C S AXI ADDR WIDTH values carried by this module.
      C_S_AXI_ADDR_WIDTH : integer := 6;
      -- Sets the bit width for SAMPLE WIDTH values carried by this module.
      SAMPLE_WIDTH       : integer := 32;
      -- Sets the bit width for EVENT WIDTH values carried by this module.
      EVENT_WIDTH        : integer := 8;
      -- Sets the storage depth, frame length, or number of buffered samples used internally.
      DEPTH              : integer := 1024;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 10;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      CMD_LANES          : integer := 4;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "7SERIES";
      -- Configures G DEBUG BUS for this instance.
      G_DEBUG_BUS        : string  := "AXI_LITE"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      sample_clk     : in  std_logic;
      -- Active-low reset for this clock domain.
      sample_rstn    : in  std_logic;
      -- Input sample vector captured or processed by the datapath.
      sample_i       : in  std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
      -- Event or trigger metadata associated with the current sample stream.
      event_i        : in  std_logic_vector(EVENT_WIDTH - 1 downto 0);
      -- Output irq o signal generated by this module.
      irq_o          : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_ACLK     : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_ARESETN  : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_AWADDR   : in  std_logic_vector(C_S_AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_AWPROT   : in  std_logic_vector(2 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_AWVALID  : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_AWREADY  : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_WDATA    : in  std_logic_vector(C_S_AXI_DATA_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_WSTRB    : in  std_logic_vector((C_S_AXI_DATA_WIDTH / 8) - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_WVALID   : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_WREADY   : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_BRESP    : out std_logic_vector(1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_BVALID   : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_BREADY   : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_ARADDR   : in  std_logic_vector(C_S_AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_ARPROT   : in  std_logic_vector(2 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_ARVALID  : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_ARREADY  : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_RDATA    : out std_logic_vector(C_S_AXI_DATA_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_RRESP    : out std_logic_vector(1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_RVALID   : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      S_AXI_RREADY   : in  std_logic
    );
  end component;

  -- Component declaration sourced from debug/radila/hdl/radila/radila_axi_top.vhd.
  component radila_v1_0 is
    generic (
      -- Sets the bit width for C S00 AXI DATA WIDTH values carried by this module.
      C_S00_AXI_DATA_WIDTH : integer := 32;
      -- Sets the bit width for C S00 AXI ADDR WIDTH values carried by this module.
      C_S00_AXI_ADDR_WIDTH : integer := 6;
      -- Sets the bit width for SAMPLE WIDTH values carried by this module.
      SAMPLE_WIDTH         : integer := 32;
      -- Sets the bit width for EVENT WIDTH values carried by this module.
      EVENT_WIDTH          : integer := 8;
      -- Sets the storage depth, frame length, or number of buffered samples used internally.
      DEPTH                : integer := 1024;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH           : integer := 10;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      CMD_LANES            : integer := 4;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG           : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG   : string  := "7SERIES";
      -- Configures G DEBUG BUS for this instance.
      G_DEBUG_BUS          : string  := "AXI_LITE"
    );
    port (
      -- Input sample vector captured or processed by the datapath.
      sample_i       : in  std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
      -- Event or trigger metadata associated with the current sample stream.
      event_i        : in  std_logic_vector(EVENT_WIDTH - 1 downto 0);
      -- Output irq o signal generated by this module.
      irq_o          : out std_logic;
      -- S00 axi aclk interface signal.
      s00_axi_aclk   : in  std_logic;
      -- S00 axi aresetn interface signal.
      s00_axi_aresetn: in  std_logic;
      -- S00 axi awaddr interface signal.
      s00_axi_awaddr : in  std_logic_vector(C_S00_AXI_ADDR_WIDTH - 1 downto 0);
      -- S00 axi awprot interface signal.
      s00_axi_awprot : in  std_logic_vector(2 downto 0);
      -- S00 axi awvalid interface signal.
      s00_axi_awvalid: in  std_logic;
      -- S00 axi awready interface signal.
      s00_axi_awready: out std_logic;
      -- S00 axi wdata interface signal.
      s00_axi_wdata  : in  std_logic_vector(C_S00_AXI_DATA_WIDTH - 1 downto 0);
      -- S00 axi wstrb interface signal.
      s00_axi_wstrb  : in  std_logic_vector((C_S00_AXI_DATA_WIDTH / 8) - 1 downto 0);
      -- S00 axi wvalid interface signal.
      s00_axi_wvalid : in  std_logic;
      -- S00 axi wready interface signal.
      s00_axi_wready : out std_logic;
      -- S00 axi bresp interface signal.
      s00_axi_bresp  : out std_logic_vector(1 downto 0);
      -- S00 axi bvalid interface signal.
      s00_axi_bvalid : out std_logic;
      -- S00 axi bready interface signal.
      s00_axi_bready : in  std_logic;
      -- S00 axi araddr interface signal.
      s00_axi_araddr : in  std_logic_vector(C_S00_AXI_ADDR_WIDTH - 1 downto 0);
      -- S00 axi arprot interface signal.
      s00_axi_arprot : in  std_logic_vector(2 downto 0);
      -- S00 axi arvalid interface signal.
      s00_axi_arvalid: in  std_logic;
      -- S00 axi arready interface signal.
      s00_axi_arready: out std_logic;
      -- S00 axi rdata interface signal.
      s00_axi_rdata  : out std_logic_vector(C_S00_AXI_DATA_WIDTH - 1 downto 0);
      -- S00 axi rresp interface signal.
      s00_axi_rresp  : out std_logic_vector(1 downto 0);
      -- S00 axi rvalid interface signal.
      s00_axi_rvalid : out std_logic;
      -- S00 axi rready interface signal.
      s00_axi_rready : in  std_logic
    );
  end component;

end package debug;
