library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package dsp_transform is
  -- Component declaration sourced from dsp/hdl/raddsp/src/fft_tdp_ram.vhd.
  component fft_tdp_ram is
    generic (
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY : string := "ultrascale+";
      -- Configures MEMORY STYLE for this instance.
      MEMORY_STYLE  : string := "block";
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH    : integer := 64;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH    : integer := 5;
      -- Sets the storage depth, frame length, or number of buffered samples used internally.
      DEPTH         : integer := 32
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk    : in  std_logic;
      -- A addr interface signal.
      a_addr : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- A din interface signal.
      a_din  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- A dout interface signal.
      a_dout : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- A we interface signal.
      a_we   : in  std_logic;
      -- B addr interface signal.
      b_addr : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- B din interface signal.
      b_din  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- B dout interface signal.
      b_dout : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- B we interface signal.
      b_we   : in  std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_fft_twiddle_rom.vhd.
  component raddsp_fft_twiddle_rom is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR          : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY   : string := "ultrascaleplus";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS        : positive := 1024;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH : positive := 16;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_INVERSE_FFT   : boolean := false;
      -- Configures G MEMORY STYLE for this instance.
      G_MEMORY_STYLE  : string := "block";
      -- Configures G INIT FILE for this instance.
      G_INIT_FILE     : string := "none"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk            : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst            : in  std_logic;
      -- Input addr i signal for this module.
      addr_i         : in  std_logic_vector;
      -- Output twiddle re o signal generated by this module.
      twiddle_re_o   : out signed(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Output twiddle im o signal generated by this module.
      twiddle_im_o   : out signed(G_TWIDDLE_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_sqrt_u32.vhd.
  component raddsp_sqrt_u32 is
    generic (
      -- Width of the unsigned radicand.
      INPUT_WIDTH  : positive := 32;
      -- Width of the unsigned square-root result.
      OUTPUT_WIDTH : positive := 16
    );
    port (
      -- Unsigned input value.
      x_i     : in  std_logic_vector(INPUT_WIDTH - 1 downto 0);
      -- Floor square-root result.
      root_o  : out std_logic_vector(OUTPUT_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_xilinx_dsp48_mul.vhd.
  component raddsp_xilinx_dsp48_mul is
    generic (
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY : string := "7series";
      -- Sets the bit width for A WIDTH values carried by this module.
      A_WIDTH       : positive := 16;
      -- Sets the bit width for B WIDTH values carried by this module.
      B_WIDTH       : positive := 18
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk        : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst        : in  std_logic;
      -- Input valid qualifier for this operation or sideband channel.
      valid_i    : in  std_logic;
      -- Input subtract i signal for this module.
      subtract_i : in  std_logic;
      -- Input last i signal for this module.
      last_i     : in  std_logic;
      -- Input a i signal for this module.
      a_i        : in  signed(A_WIDTH - 1 downto 0);
      -- Input b i signal for this module.
      b_i        : in  signed(B_WIDTH - 1 downto 0);
      -- Output valid qualifier aligned with the produced result.
      valid_o    : out std_logic;
      -- Output subtract o signal generated by this module.
      subtract_o : out std_logic;
      -- Output last o signal generated by this module.
      last_o     : out std_logic;
      -- Output p o signal generated by this module.
      p_o        : out signed(47 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_xilinx_dsp48_square_seq.vhd.
  component raddsp_xilinx_dsp48_square_seq is
    generic (
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY : string := "7series";
      -- Sets the bit width for WIDTH values carried by this module.
      WIDTH         : positive := 32
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk     : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst     : in  std_logic;
      -- Input start i signal for this module.
      start_i : in  std_logic;
      -- Input x i signal for this module.
      x_i     : in  signed(WIDTH - 1 downto 0);
      -- Output busy o signal generated by this module.
      busy_o  : out std_logic;
      -- Output valid qualifier aligned with the produced result.
      valid_o : out std_logic;
      -- Output y o signal generated by this module.
      y_o     : out unsigned((2 * WIDTH) - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_xilinx_dsp48_wide_mul.vhd.
  component raddsp_xilinx_dsp48_wide_mul is
    generic (
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY : string := "7series";
      -- Sets the bit width for A WIDTH values carried by this module.
      A_WIDTH       : positive := 16;
      -- Sets the bit width for B WIDTH values carried by this module.
      B_WIDTH       : positive := 16;
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_WIDTH : positive := 64;
      -- Sets the bit width for CHUNK WIDTH values carried by this module.
      CHUNK_WIDTH   : positive := 16
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk      : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst      : in  std_logic;
      -- Input valid qualifier for this operation or sideband channel.
      valid_i  : in  std_logic;
      -- Input a i signal for this module.
      a_i      : in  signed(A_WIDTH - 1 downto 0);
      -- Input b i signal for this module.
      b_i      : in  signed(B_WIDTH - 1 downto 0);
      -- Output valid qualifier aligned with the produced result.
      valid_o  : out std_logic;
      -- Output p o signal generated by this module.
      p_o      : out signed(PRODUCT_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/cordic_atan2.vhd.
  component cordic_atan2 is
    generic (
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH  : integer := 16;
      -- Sets the bit width for G PHASE WIDTH values carried by this module.
      G_PHASE_WIDTH  : integer := 32;
      -- Configures G ITERATIONS for this instance.
      G_ITERATIONS   : integer := 24
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk         : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst         : in  std_logic;
      -- Input valid interface signal.
      input_valid : in  std_logic;
      -- X in interface signal.
      x_in        : in  signed(G_INPUT_WIDTH - 1 downto 0);
      -- Y in interface signal.
      y_in        : in  signed(G_INPUT_WIDTH - 1 downto 0);
      -- Input ready interface signal.
      input_ready : out std_logic;
      -- Busy interface signal.
      busy        : out std_logic;
      -- Phase valid interface signal.
      phase_valid : out std_logic;
      -- Phase out interface signal.
      phase_out   : out signed(G_PHASE_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/fft_radix2_batch_core.vhd.
  component fft_radix2_batch_core is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR              : string  := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY       : string  := "ultrascale+";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS            : positive := 16;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_MAX_POINTS        : positive := 2048;
      -- Configures G RADIX for this instance.
      G_RADIX             : positive := 2;
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH       : positive := 16;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH     : positive := 16;
      -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
      G_OUTPUT_WIDTH      : positive := 32;
      -- Configures G SCALE EACH STAGE for this instance.
      G_SCALE_EACH_STAGE  : boolean := true;
      -- Configures G MEMORY STYLE for this instance.
      G_MEMORY_STYLE      : string := "block"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk          : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst          : in  std_logic;
      -- Start frame interface signal.
      start_frame  : in  std_logic;
      -- Sample valid interface signal.
      sample_valid : in  std_logic;
      -- Sample re interface signal.
      sample_re    : in  integer;
      -- Sample im interface signal.
      sample_im    : in  integer;
      -- Sample ready interface signal.
      sample_ready : out std_logic;
      -- Twiddle addr interface signal.
      twiddle_addr : out integer range 0 to G_MAX_POINTS / 2 - 1;
      -- Twiddle re interface signal.
      twiddle_re   : in  integer;
      -- Twiddle im interface signal.
      twiddle_im   : in  integer;
      -- Busy interface signal.
      busy         : out std_logic;
      -- Done interface signal.
      done         : out std_logic;
      -- Output ready interface signal.
      output_ready : in  std_logic;
      -- Output valid interface signal.
      output_valid : out std_logic;
      -- Output index interface signal.
      output_index : out integer range 0 to G_MAX_POINTS - 1;
      -- Output re interface signal.
      output_re    : out integer;
      -- Output im interface signal.
      output_im    : out integer
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_gain.vhd.
  component raddsp_axis_gain is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR          : string  := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY   : string  := "generic";
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH      : positive := 16;
      -- Sets the bit width for COEFF WIDTH values carried by this module.
      COEFF_WIDTH     : positive := 18;
      -- Sets coefficient precision or coefficient count for the fixed-point DSP operation.
      COEFF_FRAC_BITS : natural  := 15;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      CHANNEL_COUNT   : positive := 1
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst           : in  std_logic;
      -- Packed fixed-point gain coefficient input, one coefficient per channel.
      gain_i        : in  std_logic_vector((CHANNEL_COUNT * COEFF_WIDTH) - 1 downto 0);
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata  : in  std_logic_vector((CHANNEL_COUNT * DATA_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast  : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata  : out std_logic_vector((CHANNEL_COUNT * DATA_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast  : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_mix2.vhd.
  component raddsp_axis_mix2 is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR        : string  := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY : string  := "generic";
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH    : positive := 16
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk             : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst             : in  std_logic;
      -- S0 axis tvalid interface signal.
      s0_axis_tvalid  : in  std_logic;
      -- S0 axis tready interface signal.
      s0_axis_tready  : out std_logic;
      -- S0 axis tdata interface signal.
      s0_axis_tdata   : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- S0 axis tlast interface signal.
      s0_axis_tlast   : in  std_logic;
      -- S1 axis tvalid interface signal.
      s1_axis_tvalid  : in  std_logic;
      -- S1 axis tready interface signal.
      s1_axis_tready  : out std_logic;
      -- S1 axis tdata interface signal.
      s1_axis_tdata   : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- S1 axis tlast interface signal.
      s1_axis_tlast   : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid   : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready   : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata    : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast    : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_dds.vhd.
  component raddsp_axis_dds is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR          : string  := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY   : string  := "generic";
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH      : positive := 16;
      -- Sets the bit width for PHASE WIDTH values carried by this module.
      PHASE_WIDTH     : positive := 32;
      -- Sets the bit width for LUT ADDR WIDTH values carried by this module.
      LUT_ADDR_WIDTH  : positive := 4;
      -- Sets the transform, frame, or vector size used by the datapath.
      FRAME_LENGTH    : natural  := 0;
      -- Configures MEM INIT FILE for this instance.
      MEM_INIT_FILE   : string   := "dsp/hdl/raddsp/mem/sine_q15_16.mem"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk             : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst             : in  std_logic;
      -- Input enable i signal for this module.
      enable_i        : in  std_logic;
      -- Input phase reset i signal for this module.
      phase_reset_i   : in  std_logic;
      -- Input phase inc i signal for this module.
      phase_inc_i     : in  std_logic_vector(PHASE_WIDTH - 1 downto 0);
      -- Input phase offset i signal for this module.
      phase_offset_i  : in  std_logic_vector(PHASE_WIDTH - 1 downto 0);
      -- Input wav wr en i signal for this module.
      wav_wr_en_i     : in  std_logic;
      -- Input wav wr addr i signal for this module.
      wav_wr_addr_i   : in  std_logic_vector(LUT_ADDR_WIDTH - 1 downto 0);
      -- Input wav wr data i signal for this module.
      wav_wr_data_i   : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid   : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready   : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata    : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast    : out std_logic;
      -- Output phase o signal generated by this module.
      phase_o         : out std_logic_vector(PHASE_WIDTH - 1 downto 0);
      -- Output lut addr o signal generated by this module.
      lut_addr_o      : out std_logic_vector(LUT_ADDR_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_float_to_fixed.vhd.
  component raddsp_axis_float_to_fixed is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR          : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY   : string := "generic";
      -- Sets the bit width for FIXED WIDTH values carried by this module.
      FIXED_WIDTH     : positive := 16;
      -- Sets the number of fractional bits used when scaling fixed-point arithmetic results.
      FIXED_FRAC_BITS : natural := 15;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      CHANNEL_COUNT   : positive := 1
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst           : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata  : in  std_logic_vector((CHANNEL_COUNT * 32) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast  : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata  : out std_logic_vector((CHANNEL_COUNT * FIXED_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast  : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_fixed_to_float.vhd.
  component raddsp_axis_fixed_to_float is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR          : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY   : string := "generic";
      -- Sets the bit width for FIXED WIDTH values carried by this module.
      FIXED_WIDTH     : positive := 16;
      -- Sets the number of fractional bits used when scaling fixed-point arithmetic results.
      FIXED_FRAC_BITS : natural := 15;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      CHANNEL_COUNT   : positive := 1
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst           : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata  : in  std_logic_vector((CHANNEL_COUNT * FIXED_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast  : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata  : out std_logic_vector((CHANNEL_COUNT * 32) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast  : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_iq_magnitude_sq.vhd.
  component raddsp_axis_iq_magnitude_sq is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR        : string  := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY : string  := "generic";
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH    : positive := 16;
      -- Sets the bit width for MAG WIDTH values carried by this module.
      MAG_WIDTH     : positive := 32
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst           : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata  : in  std_logic_vector((2 * DATA_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast  : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata  : out std_logic_vector(MAG_WIDTH - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast  : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_fft_bin_product.vhd.
  component raddsp_axis_fft_bin_product is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR          : string  := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY   : string  := "generic";
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH      : positive := 16;
      -- Sets coefficient precision or coefficient count for the fixed-point DSP operation.
      COEFF_FRAC_BITS : natural  := 15;
      -- Configures IMPLEMENTATION for this instance.
      IMPLEMENTATION  : string  := "latency_optimized"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk             : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst             : in  std_logic;
      -- Input correlate i signal for this module.
      correlate_i     : in  std_logic;
      -- S0 axis tvalid interface signal.
      s0_axis_tvalid  : in  std_logic;
      -- S0 axis tready interface signal.
      s0_axis_tready  : out std_logic;
      -- S0 axis tdata interface signal.
      s0_axis_tdata   : in  std_logic_vector((2 * DATA_WIDTH) - 1 downto 0);
      -- S0 axis tlast interface signal.
      s0_axis_tlast   : in  std_logic;
      -- S1 axis tvalid interface signal.
      s1_axis_tvalid  : in  std_logic;
      -- S1 axis tready interface signal.
      s1_axis_tready  : out std_logic;
      -- S1 axis tdata interface signal.
      s1_axis_tdata   : in  std_logic_vector((2 * DATA_WIDTH) - 1 downto 0);
      -- S1 axis tlast interface signal.
      s1_axis_tlast   : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid   : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready   : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata    : out std_logic_vector((2 * DATA_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast    : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_radfft_batch.vhd.
  component raddsp_axis_radfft_batch is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR               : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY        : string := "ultrascale+";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS             : positive := 16;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_MAX_POINTS         : positive := 2048;
      -- Configures G RADIX for this instance.
      G_RADIX              : positive := 2;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_INVERSE_FFT        : boolean := false;
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH        : positive := 16;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH      : positive := 16;
      -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
      G_OUTPUT_WIDTH       : positive := 32;
      -- Configures G SCALE EACH STAGE for this instance.
      G_SCALE_EACH_STAGE   : boolean := true;
      -- Configures G MEMORY STYLE for this instance.
      G_MEMORY_STYLE       : string := "block"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk          : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst          : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata  : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast  : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata  : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast  : out std_logic;
      -- Output twiddle addr o signal generated by this module.
      twiddle_addr_o : out std_logic_vector(31 downto 0);
      -- Input twiddle re i signal for this module.
      twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Input twiddle im i signal for this module.
      twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Output busy o signal generated by this module.
      busy_o          : out std_logic;
      -- Output frame done o signal generated by this module.
      frame_done_o    : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_radfft_radix2_tdp.vhd.
  component raddsp_axis_radfft_radix2_tdp is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR               : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY        : string := "ultrascaleplus";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS             : positive := 1024;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_MAX_POINTS         : positive := 1024;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_INVERSE_FFT        : boolean := false;
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH        : positive := 16;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH      : positive := 16;
      -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
      G_OUTPUT_WIDTH       : positive := 24;
      -- Configures G SCALE EACH STAGE for this instance.
      G_SCALE_EACH_STAGE   : boolean := true;
      -- Configures G MEMORY STYLE for this instance.
      G_MEMORY_STYLE       : string := "block";
      -- Configures G TWIDDLE MEMORY STYLE for this instance.
      G_TWIDDLE_MEMORY_STYLE : string := "block";
      -- Configures G TWIDDLE INIT FILE for this instance.
      G_TWIDDLE_INIT_FILE  : string := "none";
      -- Configures G EXTERNAL TWIDDLES for this instance.
      G_EXTERNAL_TWIDDLES  : boolean := false;
      -- Sets the width or count of samples handled by the datapath.
      G_MEMORY_WORD_SAMPLES : positive := 4
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk            : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst            : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid  : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready  : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata   : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast   : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid  : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready  : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata   : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast   : out std_logic;
      -- Input runtime inverse i signal for this module.
      runtime_inverse_i : in std_logic := '0';
      -- Input active point log2 i signal for this module.
      active_point_log2_i : in std_logic_vector(7 downto 0) := (others => '0');
      -- Input active radix4 i signal for this module.
      active_radix4_i     : in std_logic := '0';
      -- Input active input width i signal for this module.
      active_input_width_i : in std_logic_vector(7 downto 0) := (others => '0');
      -- Input active output width i signal for this module.
      active_output_width_i : in std_logic_vector(7 downto 0) := (others => '0');
      -- Output twiddle addr o signal generated by this module.
      twiddle_addr_o : out std_logic_vector(31 downto 0);
      -- Input twiddle re i signal for this module.
      twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Input twiddle im i signal for this module.
      twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Output busy o signal generated by this module.
      busy_o         : out std_logic;
      -- Output frame done o signal generated by this module.
      frame_done_o   : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_radfft_radix4_tdp.vhd.
  component raddsp_axis_radfft_radix4_tdp is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR                : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY         : string := "ultrascaleplus";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS              : positive := 1024;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_MAX_POINTS          : positive := 1024;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_INVERSE_FFT         : boolean := false;
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH         : positive := 16;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH       : positive := 16;
      -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
      G_OUTPUT_WIDTH        : positive := 24;
      -- Configures G SCALE EACH STAGE for this instance.
      G_SCALE_EACH_STAGE    : boolean := true;
      -- Configures G MEMORY STYLE for this instance.
      G_MEMORY_STYLE        : string := "block";
      -- Configures G TWIDDLE MEMORY STYLE for this instance.
      G_TWIDDLE_MEMORY_STYLE : string := "block";
      -- Configures G TWIDDLE INIT FILE for this instance.
      G_TWIDDLE_INIT_FILE   : string := "none";
      -- Configures G EXTERNAL TWIDDLES for this instance.
      G_EXTERNAL_TWIDDLES   : boolean := false;
      -- Sets the width or count of samples handled by the datapath.
      G_MEMORY_WORD_SAMPLES : positive := 4
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk            : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst            : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid  : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready  : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata   : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast   : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid  : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready  : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata   : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast   : out std_logic;
      -- Output twiddle addr o signal generated by this module.
      twiddle_addr_o : out std_logic_vector(31 downto 0);
      -- Input twiddle re i signal for this module.
      twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Input twiddle im i signal for this module.
      twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Output busy o signal generated by this module.
      busy_o         : out std_logic;
      -- Output frame done o signal generated by this module.
      frame_done_o   : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_radfft_parallel8.vhd.
  component raddsp_axis_radfft_parallel8 is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR               : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY        : string := "ultrascaleplus";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS             : positive := 1024;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_MAX_POINTS         : positive := 1024;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_INVERSE_FFT        : boolean := false;
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH        : positive := 32;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH      : positive := 16;
      -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
      G_OUTPUT_WIDTH       : positive := 32;
      -- Configures G SCALE EACH STAGE for this instance.
      G_SCALE_EACH_STAGE   : boolean := true;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      G_MULTIPLIER_LANES   : positive := 8
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk            : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst            : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid  : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready  : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata   : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast   : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid  : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready  : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata   : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast   : out std_logic;
      -- Input runtime inverse i signal for this module.
      runtime_inverse_i : in std_logic := '0';
      -- Input active point log2 i signal for this module.
      active_point_log2_i : in std_logic_vector(7 downto 0) := (others => '0');
      -- Input active radix4 i signal for this module.
      active_radix4_i     : in std_logic := '0';
      -- Input active input width i signal for this module.
      active_input_width_i : in std_logic_vector(7 downto 0) := (others => '0');
      -- Input active output width i signal for this module.
      active_output_width_i : in std_logic_vector(7 downto 0) := (others => '0');
      -- Output twiddle addr o signal generated by this module.
      twiddle_addr_o : out std_logic_vector(31 downto 0);
      -- Input twiddle re i signal for this module.
      twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Input twiddle im i signal for this module.
      twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Output busy o signal generated by this module.
      busy_o         : out std_logic;
      -- Output frame done o signal generated by this module.
      frame_done_o   : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_radfft_iterative.vhd.
  component raddsp_axis_radfft_iterative is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR               : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY        : string := "ultrascale+";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS             : positive := 1024;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_MAX_POINTS         : positive := 2048;
      -- Configures G RADIX for this instance.
      G_RADIX              : positive := 2;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_INVERSE_FFT        : boolean := false;
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH        : positive := 16;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH      : positive := 16;
      -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
      G_OUTPUT_WIDTH       : positive := 32;
      -- Configures G SCALE EACH STAGE for this instance.
      G_SCALE_EACH_STAGE   : boolean := true;
      -- Configures G MEMORY STYLE for this instance.
      G_MEMORY_STYLE       : string := "block";
      -- Sets the number of parallel sample lanes processed per handshake beat.
      G_MULTIPLIER_LANES   : positive := 1;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      G_MAX_MULTIPLIER_LANES : positive := 8
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk            : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst            : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid  : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready  : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata   : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast   : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid  : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready  : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata   : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast   : out std_logic;
      -- Output twiddle addr o signal generated by this module.
      twiddle_addr_o : out std_logic_vector(31 downto 0);
      -- Input twiddle re i signal for this module.
      twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Input twiddle im i signal for this module.
      twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Output busy o signal generated by this module.
      busy_o         : out std_logic;
      -- Output frame done o signal generated by this module.
      frame_done_o   : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_radfft_streaming.vhd.
  component raddsp_axis_radfft_streaming is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR               : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY        : string := "ultrascale+";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS             : positive := 16;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_MAX_POINTS         : positive := 64;
      -- Configures G RADIX for this instance.
      G_RADIX              : positive := 2;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_INVERSE_FFT        : boolean := false;
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH        : positive := 16;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH      : positive := 16;
      -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
      G_OUTPUT_WIDTH       : positive := 32;
      -- Configures G SCALE EACH STAGE for this instance.
      G_SCALE_EACH_STAGE   : boolean := true;
      -- Configures G MEMORY STYLE for this instance.
      G_MEMORY_STYLE       : string := "distributed";
      -- Configures G OVERLAP FRAMES for this instance.
      G_OVERLAP_FRAMES     : boolean := true;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      G_MULTIPLIER_LANES   : positive := 1;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      G_MAX_MULTIPLIER_LANES : positive := 8
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk          : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst          : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata  : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast  : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata  : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast  : out std_logic;
      -- Output twiddle addr o signal generated by this module.
      twiddle_addr_o : out std_logic_vector(31 downto 0);
      -- Input twiddle re i signal for this module.
      twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Input twiddle im i signal for this module.
      twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Output busy o signal generated by this module.
      busy_o          : out std_logic;
      -- Output frame done o signal generated by this module.
      frame_done_o    : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_radfft.vhd.
  component raddsp_axis_radfft is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR               : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY        : string := "ultrascale+";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS             : positive := 16;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_MAX_POINTS         : positive := 2048;
      -- Configures G RADIX for this instance.
      G_RADIX              : positive := 2;
      -- Configures G PIPELINED STREAMING for this instance.
      G_PIPELINED_STREAMING : boolean := false;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_INVERSE_FFT        : boolean := false;
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH        : positive := 16;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH      : positive := 16;
      -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
      G_OUTPUT_WIDTH       : positive := 32;
      -- Configures G SCALE EACH STAGE for this instance.
      G_SCALE_EACH_STAGE   : boolean := true;
      -- Configures G MEMORY STYLE for this instance.
      G_MEMORY_STYLE       : string := "block";
      -- Configures G TWIDDLE MEMORY STYLE for this instance.
      G_TWIDDLE_MEMORY_STYLE : string := "block";
      -- Configures G TWIDDLE INIT FILE for this instance.
      G_TWIDDLE_INIT_FILE  : string := "none";
      -- Configures G EXTERNAL TWIDDLES for this instance.
      G_EXTERNAL_TWIDDLES  : boolean := false;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      G_MULTIPLIER_LANES   : positive := 1;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      G_MAX_MULTIPLIER_LANES : positive := 8;
      -- Sets the width or count of samples handled by the datapath.
      G_MEMORY_WORD_SAMPLES : positive := 1
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk          : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst          : in  std_logic;
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata  : in  std_logic_vector((2 * G_INPUT_WIDTH) - 1 downto 0);
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast  : in  std_logic;
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata  : out std_logic_vector((2 * G_OUTPUT_WIDTH) - 1 downto 0);
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast  : out std_logic;
      -- Input runtime inverse i signal for this module.
      runtime_inverse_i : in std_logic := '0';
      -- Output twiddle addr o signal generated by this module.
      twiddle_addr_o : out std_logic_vector(31 downto 0);
      -- Input twiddle re i signal for this module.
      twiddle_re_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Input twiddle im i signal for this module.
      twiddle_im_i   : in  std_logic_vector(G_TWIDDLE_WIDTH - 1 downto 0);
      -- Output busy o signal generated by this module.
      busy_o          : out std_logic;
      -- Output frame done o signal generated by this module.
      frame_done_o    : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_radfft_ddr.vhd.
  component raddsp_axis_radfft_ddr is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR                : string := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY         : string := "ultrascaleplus";
      -- Sets the bit width for G AXI ADDR WIDTH values carried by this module.
      G_AXI_ADDR_WIDTH      : positive := 32;
      -- Sets the bit width for G AXI DATA WIDTH values carried by this module.
      G_AXI_DATA_WIDTH      : positive := 64;
      -- Sets the bit width for G AXIS DATA WIDTH values carried by this module.
      G_AXIS_DATA_WIDTH     : positive := 64;
      -- Sets the bit width for G AXI LITE ADDR WIDTH values carried by this module.
      G_AXI_LITE_ADDR_WIDTH : positive := 16;
      -- Sets the storage depth, frame length, or number of buffered samples used internally.
      G_FIFO_DEPTH          : positive := 1024;
      -- Configures G FIFO FWFT for this instance.
      G_FIFO_FWFT           : boolean := true;
      -- Configures G MAX BURST BEATS for this instance.
      G_MAX_BURST_BEATS     : positive := 64;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_FFT_POINTS          : positive := 1024;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_FFT_RADIX           : positive := 2;
      -- Sets the bit width for G FFT INPUT WIDTH values carried by this module.
      G_FFT_INPUT_WIDTH     : positive := 32;
      -- Sets the bit width for G FFT TWIDDLE WIDTH values carried by this module.
      G_FFT_TWIDDLE_WIDTH   : positive := 16;
      -- Sets the bit width for G FFT OUTPUT WIDTH values carried by this module.
      G_FFT_OUTPUT_WIDTH    : positive := 32;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_FFT_SCALE_EACH_STAGE : boolean := true;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_FFT_MEMORY_STYLE    : string := "block";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_FFT_TWIDDLE_INIT_FILE : string := "../../mem/radfft_twiddle_1024_16_fft.mem";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_FFT_INVERSE         : boolean := false;
      -- Sets the number of parallel sample lanes processed per handshake beat.
      G_MAX_MULTIPLIER_LANES : positive := 16;
      -- Configures G XCORR ENABLE for this instance.
      G_XCORR_ENABLE        : boolean := true;
      -- Sets the storage depth, frame length, or number of buffered samples used internally.
      G_XCORR_FRAME_DEPTH   : positive := 16384;
      -- Configures G XCORR MEMORY STYLE for this instance.
      G_XCORR_MEMORY_STYLE  : string := "block";
      -- Configures G DEFAULT REGION BYTES for this instance.
      G_DEFAULT_REGION_BYTES : natural := 67108864
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk            : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn           : in  std_logic;

      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awaddr   : in  std_logic_vector(G_AXI_LITE_ADDR_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awprot   : in  std_logic_vector(2 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awvalid  : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awready  : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wdata    : in  std_logic_vector(31 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wstrb    : in  std_logic_vector(3 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wvalid   : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wready   : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_bresp    : out std_logic_vector(1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_bvalid   : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_bready   : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_araddr   : in  std_logic_vector(G_AXI_LITE_ADDR_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_arprot   : in  std_logic_vector(2 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_arvalid  : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_arready  : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rdata    : out std_logic_vector(31 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rresp    : out std_logic_vector(1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rvalid   : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rready   : in  std_logic;

      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awaddr   : out std_logic_vector(G_AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awlen    : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awsize   : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awburst  : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awvalid  : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awready  : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wdata    : out std_logic_vector(G_AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wstrb    : out std_logic_vector((G_AXI_DATA_WIDTH / 8) - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wlast    : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wvalid   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wready   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bresp    : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bvalid   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bready   : out std_logic;

      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_araddr   : out std_logic_vector(G_AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arlen    : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arsize   : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arburst  : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arvalid  : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arready  : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rdata    : in  std_logic_vector(G_AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rresp    : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rlast    : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rvalid   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rready   : out std_logic;

      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata   : in  std_logic_vector(G_AXIS_DATA_WIDTH - 1 downto 0);
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid  : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready  : out std_logic;
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast   : in  std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata   : out std_logic_vector(G_AXIS_DATA_WIDTH - 1 downto 0);
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid  : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready  : in  std_logic;
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast   : out std_logic;

      -- Output irq o signal generated by this module.
      irq_o          : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/wrappers/raddsp_cordic_atan2.vhd.
  component raddsp_cordic_atan2 is
    generic (
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH : positive := 16;
      -- Sets the bit width for G PHASE WIDTH values carried by this module.
      G_PHASE_WIDTH : positive := 32;
      -- Configures G ITERATIONS for this instance.
      G_ITERATIONS  : positive := 24
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk          : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst          : in  std_logic;
      -- Input valid interface signal.
      input_valid  : in  std_logic;
      -- X in interface signal.
      x_in         : in  std_logic_vector(G_INPUT_WIDTH - 1 downto 0);
      -- Y in interface signal.
      y_in         : in  std_logic_vector(G_INPUT_WIDTH - 1 downto 0);
      -- Input ready interface signal.
      input_ready  : out std_logic;
      -- Busy interface signal.
      busy         : out std_logic;
      -- Phase valid interface signal.
      phase_valid  : out std_logic;
      -- Phase out interface signal.
      phase_out    : out std_logic_vector(G_PHASE_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/wrappers/raddsp_fft_radix2_batch_core.vhd.
  component raddsp_fft_radix2_batch_core is
    generic (
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR              : string  := "xilinx";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      DEVICE_FAMILY       : string  := "ultrascale+";
      -- Sets the transform, frame, or vector size used by the datapath.
      G_POINTS            : positive := 16;
      -- Sets the transform, frame, or vector size used by the datapath.
      G_MAX_POINTS        : positive := 2048;
      -- Configures G RADIX for this instance.
      G_RADIX             : positive := 2;
      -- Sets the bit width for G INPUT WIDTH values carried by this module.
      G_INPUT_WIDTH       : positive := 16;
      -- Sets the bit width for G TWIDDLE WIDTH values carried by this module.
      G_TWIDDLE_WIDTH     : positive := 16;
      -- Sets the bit width for G OUTPUT WIDTH values carried by this module.
      G_OUTPUT_WIDTH      : positive := 32;
      -- Configures G SCALE EACH STAGE for this instance.
      G_SCALE_EACH_STAGE  : boolean := true;
      -- Configures G MEMORY STYLE for this instance.
      G_MEMORY_STYLE      : string := "block"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk          : in  std_logic;
      -- Active-high synchronous reset for this clock domain.
      rst          : in  std_logic;
      -- Start frame interface signal.
      start_frame  : in  std_logic;
      -- Sample valid interface signal.
      sample_valid : in  std_logic;
      -- Sample re interface signal.
      sample_re    : in  std_logic_vector(31 downto 0);
      -- Sample im interface signal.
      sample_im    : in  std_logic_vector(31 downto 0);
      -- Sample ready interface signal.
      sample_ready : out std_logic;
      -- Twiddle addr interface signal.
      twiddle_addr : out std_logic_vector(31 downto 0);
      -- Twiddle re interface signal.
      twiddle_re   : in  std_logic_vector(31 downto 0);
      -- Twiddle im interface signal.
      twiddle_im   : in  std_logic_vector(31 downto 0);
      -- Busy interface signal.
      busy         : out std_logic;
      -- Done interface signal.
      done         : out std_logic;
      -- Output valid interface signal.
      output_valid : out std_logic;
      -- Output index interface signal.
      output_index : out std_logic_vector(31 downto 0);
      -- Output re interface signal.
      output_re    : out std_logic_vector(31 downto 0);
      -- Output im interface signal.
      output_im    : out std_logic_vector(31 downto 0)
    );
  end component;

end package dsp_transform;
