-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
context dsp_context is
  library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;
  library radhdl;
  use radhdl.radhdl_axi_pkg.all;
  use radhdl.radhdl_axis_pkg.all;
  use radhdl.radhdl_spi_pkg.all;
  use radhdl.dsp.all;
end context dsp_context;
