library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package dsp_comms is
  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_am_iq_modulator.vhd.
  component raddsp_axis_am_iq_modulator is
    generic (
      -- Sample width for envelope, carrier, and I/Q output lanes.
      SAMPLE_WIDTH : positive := 16;
      -- Number of fractional bits used by carrier and envelope fixed-point values.
      FRAC_BITS    : natural := 14;
      -- Vendor selector retained for generated package consistency.
      VENDOR       : string := "GENERIC";
      -- Device-family selector retained for generated package consistency.
      DEVICE_FAMILY: string := "GENERIC"
    );
    port (
      -- Stream clock.
      clk             : in  std_logic;
      -- Active-high synchronous reset.
      rst             : in  std_logic;
      -- Signed fixed-point carrier cosine sample.
      carrier_i_i     : in  std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
      -- Signed fixed-point carrier sine sample.
      carrier_q_i     : in  std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
      -- Envelope stream valid.
      s_axis_tvalid   : in  std_logic;
      -- Envelope stream ready.
      s_axis_tready   : out std_logic;
      -- Signed fixed-point envelope sample.
      s_axis_tdata    : in  std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
      -- Envelope stream frame marker.
      s_axis_tlast    : in  std_logic;
      -- Packed I/Q output valid.
      m_axis_tvalid   : out std_logic;
      -- Packed I/Q output ready.
      m_axis_tready   : in  std_logic;
      -- Packed I/Q output, I in bits SAMPLE_WIDTH-1:0 and Q above it.
      m_axis_tdata    : out std_logic_vector((2 * SAMPLE_WIDTH) - 1 downto 0);
      -- Output frame marker aligned with output sample.
      m_axis_tlast    : out std_logic
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_axis_am_iq_demodulator.vhd.
  component raddsp_axis_am_iq_demodulator is
    generic (
      -- Signed I/Q sample width.
      SAMPLE_WIDTH : positive := 16;
      -- Vendor selector retained for generated package consistency.
      VENDOR       : string := "GENERIC";
      -- Device-family selector retained for generated package consistency.
      DEVICE_FAMILY: string := "GENERIC"
    );
    port (
      -- Stream clock.
      clk             : in  std_logic;
      -- Active-high synchronous reset.
      rst             : in  std_logic;
      -- Packed I/Q input valid.
      s_axis_tvalid   : in  std_logic;
      -- Packed I/Q input ready.
      s_axis_tready   : out std_logic;
      -- Packed I/Q input, I in bits SAMPLE_WIDTH-1:0 and Q above it.
      s_axis_tdata    : in  std_logic_vector((2 * SAMPLE_WIDTH) - 1 downto 0);
      -- Input frame marker.
      s_axis_tlast    : in  std_logic;
      -- Envelope output valid.
      m_axis_tvalid   : out std_logic;
      -- Envelope output ready.
      m_axis_tready   : in  std_logic;
      -- Unsigned envelope magnitude in SAMPLE_WIDTH bits.
      m_axis_tdata    : out std_logic_vector(SAMPLE_WIDTH - 1 downto 0);
      -- Output frame marker aligned with envelope sample.
      m_axis_tlast    : out std_logic
    );
  end component;

end package dsp_comms;
