library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.radif_pkg.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package interfaces_regbank is
  -- Component declaration sourced from interfaces/hdl/radif/src/radif_reg_bank.vhd.
  component radif_reg_bank is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Configures READ ONLY REG COUNT for this instance.
      READ_ONLY_REG_COUNT  : integer := 8;
      -- Configures READ WRITE REG COUNT for this instance.
      READ_WRITE_REG_COUNT : integer := 64;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk        : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn       : in  std_logic;
      -- Wr addr interface signal.
      wr_addr    : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Readback control or data signal for host-visible captured state.
      rd_addr    : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Wr en interface signal.
      wr_en      : in  std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_en      : in  std_logic;
      -- Data in interface signal.
      data_in    : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Data out interface signal.
      data_out   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Input read only regs i signal for this module.
      read_only_regs_i  : in  radif_reg_array_t(0 to READ_ONLY_REG_COUNT - 1)(DATA_WIDTH - 1 downto 0);
      -- Output read write regs o signal generated by this module.
      read_write_regs_o : out radif_reg_array_t(0 to READ_WRITE_REG_COUNT - 1)(DATA_WIDTH - 1 downto 0);
      -- Wr rdy interface signal.
      wr_rdy     : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_rdy     : out std_logic;
      -- Wr valid interface signal.
      wr_valid   : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_valid   : out std_logic;
      -- Error interface signal.
      error      : out std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_reg_interconnect.vhd.
  component radif_reg_interconnect is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH       : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH       : integer := 16;
      -- Configures SLAVE COUNT for this instance.
      SLAVE_COUNT      : integer := 2;
      -- Configures SLAVE BASE ADDRS for this instance.
      SLAVE_BASE_ADDRS : std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0) := x"00000000";
      -- Configures SLAVE ADDR MASKS for this instance.
      SLAVE_ADDR_MASKS : std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0) := x"F000F000";
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG       : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk             : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn            : in  std_logic;
      -- Input wr addr i signal for this module.
      wr_addr_i       : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Readback control or data signal for host-visible captured state.
      rd_addr_i       : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Input wr en i signal for this module.
      wr_en_i         : in  std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_en_i         : in  std_logic;
      -- Input data in i signal for this module.
      data_in_i       : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Output data out o signal generated by this module.
      data_out_o      : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Output wr rdy o signal generated by this module.
      wr_rdy_o        : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_rdy_o        : out std_logic;
      -- Output valid qualifier aligned with the produced result.
      wr_valid_o      : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_valid_o      : out std_logic;
      -- Output error o signal generated by this module.
      error_o         : out std_logic;
      -- Output s wr addr o signal generated by this module.
      s_wr_addr_o     : out std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0);
      -- Output s rd addr o signal generated by this module.
      s_rd_addr_o     : out std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0);
      -- Output s wr en o signal generated by this module.
      s_wr_en_o       : out std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Output s rd en o signal generated by this module.
      s_rd_en_o       : out std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Output s data in o signal generated by this module.
      s_data_in_o     : out std_logic_vector((SLAVE_COUNT * DATA_WIDTH) - 1 downto 0);
      -- Input s data out i signal for this module.
      s_data_out_i    : in  std_logic_vector((SLAVE_COUNT * DATA_WIDTH) - 1 downto 0);
      -- Input s wr rdy i signal for this module.
      s_wr_rdy_i      : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Input s rd rdy i signal for this module.
      s_rd_rdy_i      : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Input valid qualifier for this operation or sideband channel.
      s_wr_valid_i    : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Input valid qualifier for this operation or sideband channel.
      s_rd_valid_i    : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Input s error i signal for this module.
      s_error_i       : in  std_logic_vector(SLAVE_COUNT - 1 downto 0)
    );
  end component;

end package interfaces_regbank;
