library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.radif_pkg.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package interfaces_axi is
  -- Component declaration sourced from interfaces/hdl/radif/src/radif_axi_lite_to_reg.vhd.
  component radif_axi_lite_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Sets the bit width for AXI ADDR WIDTH values carried by this module.
      AXI_ADDR_WIDTH     : integer := 16;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk          : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn         : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awaddr : in  std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awprot : in  std_logic_vector(2 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awvalid: in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awready: out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wdata  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wstrb  : in  std_logic_vector((DATA_WIDTH / 8) - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wvalid : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wready : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_bresp  : out std_logic_vector(1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_bvalid : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_bready : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_araddr : in  std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_arprot : in  std_logic_vector(2 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_arvalid: in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_arready: out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rdata  : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rresp  : out std_logic_vector(1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rvalid : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rready : in  std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr  : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr  : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en    : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en    : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in  : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy   : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy   : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error    : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_axi4_axis_dma.vhd.
  component radif_axi4_axis_dma is
    generic (
      -- Sets the bit width for REG DATA WIDTH values carried by this module.
      REG_DATA_WIDTH     : integer := 32;
      -- Sets the bit width for REG ADDR WIDTH values carried by this module.
      REG_ADDR_WIDTH     : integer := 16;
      -- Sets the bit width for AXI ADDR WIDTH values carried by this module.
      AXI_ADDR_WIDTH     : integer := 32;
      -- Sets the bit width for AXI DATA WIDTH values carried by this module.
      AXI_DATA_WIDTH     : integer := 32;
      -- Sets the bit width for AXIS DATA WIDTH values carried by this module.
      AXIS_DATA_WIDTH    : integer := 32;
      -- Configures ENABLE MM2S for this instance.
      ENABLE_MM2S        : boolean := true;
      -- Configures ENABLE S2MM for this instance.
      ENABLE_S2MM        : boolean := true;
      -- Sets the storage depth, frame length, or number of buffered samples used internally.
      FIFO_DEPTH         : integer := 1024;
      -- Configures FIFO FWFT for this instance.
      FIFO_FWFT          : boolean := true;
      -- Configures MAX BURST LEN for this instance.
      MAX_BURST_LEN      : integer := 16;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk             : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn            : in  std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr     : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr     : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en       : in  std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en       : in  std_logic;
      -- Write data presented to the internal register target.
      reg_data_in     : in  std_logic_vector(REG_DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out    : out std_logic_vector(REG_DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy      : out std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy      : out std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid    : out std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid    : out std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error       : out std_logic;
      -- Output irq o signal generated by this module.
      irq_o           : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awaddr    : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awlen     : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awsize    : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awburst   : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awvalid   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awready   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wdata     : out std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wstrb     : out std_logic_vector((AXI_DATA_WIDTH / 8) - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wlast     : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wvalid    : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wready    : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bresp     : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bvalid    : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bready    : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_araddr    : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arlen     : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arsize    : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arburst   : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arvalid   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arready   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rdata     : in  std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rresp     : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rlast     : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rvalid    : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rready    : out std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata    : out std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0);
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid   : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready   : in  std_logic;
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast    : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata    : in  std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0);
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid   : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready   : out std_logic;
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast    : in  std_logic
    );
  end component;

end package interfaces_axi;
