library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.radif_pkg.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package interfaces_uart is
  -- Component declaration sourced from interfaces/hdl/radif/src/radif_uart_to_reg.vhd.
  component radif_uart_to_reg is
    generic (
      -- Width of the RADIF register data path. This bridge currently transports 32-bit words.
      DATA_WIDTH         : integer := 32;
      -- Width of the RADIF byte address path.
      ADDR_WIDTH         : integer := 16;
      -- Number of clk cycles per UART bit.
      BAUD_DIVISOR       : positive := 868;
      -- Vendor selector retained for generated package consistency.
      VENDOR_TAG         : string := "GENERIC";
      -- Device-family selector retained for generated package consistency.
      PRODUCT_SERIES_TAG : string := "GENERIC"
    );
    port (
      -- Register/UART clock.
      clk          : in  std_logic;
      -- Active-low reset.
      rstn         : in  std_logic;
      -- UART receive pin.
      uart_rx_i    : in  std_logic;
      -- UART transmit pin.
      uart_tx_o    : out std_logic;
      -- Register write address.
      reg_wr_addr  : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address.
      reg_rd_addr  : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle register write request.
      reg_wr_en    : out std_logic;
      -- One-cycle register read request.
      reg_rd_en    : out std_logic;
      -- Register write data.
      reg_data_in  : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register read data.
      reg_data_out : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register target write ready.
      reg_wr_rdy   : in  std_logic;
      -- Register target read ready.
      reg_rd_rdy   : in  std_logic;
      -- Register target write response valid.
      reg_wr_valid : in  std_logic;
      -- Register target read response valid.
      reg_rd_valid : in  std_logic;
      -- Register target error for current response.
      reg_error    : in  std_logic
    );
  end component;

end package interfaces_uart;
