-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
context interfaces_context is
  library ieee;
  use ieee.std_logic_1164.all;
  use ieee.numeric_std.all;
  library radhdl;
  use radhdl.interfaces.all;
end context interfaces_context;
