library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.radif_pkg.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package interfaces is
  -- Component declaration sourced from interfaces/hdl/radif/src/radif_reg_bank.vhd.
  component radif_reg_bank is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Configures READ ONLY REG COUNT for this instance.
      READ_ONLY_REG_COUNT  : integer := 8;
      -- Configures READ WRITE REG COUNT for this instance.
      READ_WRITE_REG_COUNT : integer := 64;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk        : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn       : in  std_logic;
      -- Wr addr interface signal.
      wr_addr    : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Readback control or data signal for host-visible captured state.
      rd_addr    : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Wr en interface signal.
      wr_en      : in  std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_en      : in  std_logic;
      -- Data in interface signal.
      data_in    : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Data out interface signal.
      data_out   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Input read only regs i signal for this module.
      read_only_regs_i  : in  radif_reg_array_t(0 to READ_ONLY_REG_COUNT - 1)(DATA_WIDTH - 1 downto 0);
      -- Output read write regs o signal generated by this module.
      read_write_regs_o : out radif_reg_array_t(0 to READ_WRITE_REG_COUNT - 1)(DATA_WIDTH - 1 downto 0);
      -- Wr rdy interface signal.
      wr_rdy     : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_rdy     : out std_logic;
      -- Wr valid interface signal.
      wr_valid   : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_valid   : out std_logic;
      -- Error interface signal.
      error      : out std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_reg_interconnect.vhd.
  component radif_reg_interconnect is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH       : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH       : integer := 16;
      -- Configures SLAVE COUNT for this instance.
      SLAVE_COUNT      : integer := 2;
      -- Configures SLAVE BASE ADDRS for this instance.
      SLAVE_BASE_ADDRS : std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0) := x"00000000";
      -- Configures SLAVE ADDR MASKS for this instance.
      SLAVE_ADDR_MASKS : std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0) := x"F000F000";
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG       : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk             : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn            : in  std_logic;
      -- Input wr addr i signal for this module.
      wr_addr_i       : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Readback control or data signal for host-visible captured state.
      rd_addr_i       : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Input wr en i signal for this module.
      wr_en_i         : in  std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_en_i         : in  std_logic;
      -- Input data in i signal for this module.
      data_in_i       : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Output data out o signal generated by this module.
      data_out_o      : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Output wr rdy o signal generated by this module.
      wr_rdy_o        : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_rdy_o        : out std_logic;
      -- Output valid qualifier aligned with the produced result.
      wr_valid_o      : out std_logic;
      -- Readback control or data signal for host-visible captured state.
      rd_valid_o      : out std_logic;
      -- Output error o signal generated by this module.
      error_o         : out std_logic;
      -- Output s wr addr o signal generated by this module.
      s_wr_addr_o     : out std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0);
      -- Output s rd addr o signal generated by this module.
      s_rd_addr_o     : out std_logic_vector((SLAVE_COUNT * ADDR_WIDTH) - 1 downto 0);
      -- Output s wr en o signal generated by this module.
      s_wr_en_o       : out std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Output s rd en o signal generated by this module.
      s_rd_en_o       : out std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Output s data in o signal generated by this module.
      s_data_in_o     : out std_logic_vector((SLAVE_COUNT * DATA_WIDTH) - 1 downto 0);
      -- Input s data out i signal for this module.
      s_data_out_i    : in  std_logic_vector((SLAVE_COUNT * DATA_WIDTH) - 1 downto 0);
      -- Input s wr rdy i signal for this module.
      s_wr_rdy_i      : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Input s rd rdy i signal for this module.
      s_rd_rdy_i      : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Input valid qualifier for this operation or sideband channel.
      s_wr_valid_i    : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Input valid qualifier for this operation or sideband channel.
      s_rd_valid_i    : in  std_logic_vector(SLAVE_COUNT - 1 downto 0);
      -- Input s error i signal for this module.
      s_error_i       : in  std_logic_vector(SLAVE_COUNT - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_gpio_reg_block.vhd.
  component radif_gpio_reg_block is
    generic (
      -- Width of the RADIF register data path.
      DATA_WIDTH         : integer := 32;
      -- Width of the RADIF byte address path.
      REG_ADDR_WIDTH     : integer := 16;
      -- Number of GPIO pins controlled or observed by this block.
      GPIO_WIDTH         : positive := 8;
      -- Reset value for GPIO outputs.
      RESET_OUT_VALUE    : std_logic_vector(GPIO_WIDTH - 1 downto 0) := (others => '0');
      -- Reset value for GPIO output enables.
      RESET_OUT_ENABLE   : std_logic_vector(GPIO_WIDTH - 1 downto 0) := (others => '0');
      -- Vendor selector retained for generated package consistency.
      VENDOR_TAG         : string  := "GENERIC";
      -- Device-family selector retained for generated package consistency.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Register clock.
      clk           : in  std_logic;
      -- Active-low register reset.
      rstn          : in  std_logic;
      -- External GPIO input pins synchronized into clk.
      gpio_i        : in  std_logic_vector(GPIO_WIDTH - 1 downto 0);
      -- GPIO output drive values.
      gpio_o        : out std_logic_vector(GPIO_WIDTH - 1 downto 0);
      -- GPIO output enable bits.
      gpio_oe_o     : out std_logic_vector(GPIO_WIDTH - 1 downto 0);
      -- Interrupt asserted when an enabled edge-detect pending bit is set.
      irq_o         : out std_logic;
      -- Register write address.
      reg_wr_addr   : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address.
      reg_rd_addr   : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle register write request.
      reg_wr_en     : in  std_logic;
      -- One-cycle register read request.
      reg_rd_en     : in  std_logic;
      -- Register write data.
      reg_data_in   : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register read data.
      reg_data_out  : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register write ready.
      reg_wr_rdy    : out std_logic;
      -- Register read ready.
      reg_rd_rdy    : out std_logic;
      -- Register write response valid.
      reg_wr_valid  : out std_logic;
      -- Register read response valid.
      reg_rd_valid  : out std_logic;
      -- Register transaction error.
      reg_error     : out std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_irq_controller.vhd.
  component radif_irq_controller is
    generic (
      -- Width of the RADIF register data path.
      DATA_WIDTH         : integer := 32;
      -- Width of the RADIF byte address path.
      REG_ADDR_WIDTH     : integer := 16;
      -- Number of interrupt source inputs.
      IRQ_COUNT          : positive := 8;
      -- Vendor selector retained for generated package consistency.
      VENDOR_TAG         : string := "GENERIC";
      -- Device-family selector retained for generated package consistency.
      PRODUCT_SERIES_TAG : string := "GENERIC"
    );
    port (
      -- Register clock.
      clk           : in  std_logic;
      -- Active-low register reset.
      rstn          : in  std_logic;
      -- Raw interrupt source inputs.
      irq_i         : in  std_logic_vector(IRQ_COUNT - 1 downto 0);
      -- Shared masked interrupt output.
      irq_o         : out std_logic;
      -- Masked pending interrupt bits.
      irq_pending_o : out std_logic_vector(IRQ_COUNT - 1 downto 0);
      -- Register write address.
      reg_wr_addr   : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address.
      reg_rd_addr   : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle register write request.
      reg_wr_en     : in  std_logic;
      -- One-cycle register read request.
      reg_rd_en     : in  std_logic;
      -- Register write data.
      reg_data_in   : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register read data.
      reg_data_out  : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register write ready.
      reg_wr_rdy    : out std_logic;
      -- Register read ready.
      reg_rd_rdy    : out std_logic;
      -- Register write response valid.
      reg_wr_valid  : out std_logic;
      -- Register read response valid.
      reg_rd_valid  : out std_logic;
      -- Register transaction error.
      reg_error     : out std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_axi_lite_to_reg.vhd.
  component radif_axi_lite_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Sets the bit width for AXI ADDR WIDTH values carried by this module.
      AXI_ADDR_WIDTH     : integer := 16;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk          : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn         : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awaddr : in  std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awprot : in  std_logic_vector(2 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awvalid: in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_awready: out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wdata  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wstrb  : in  std_logic_vector((DATA_WIDTH / 8) - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wvalid : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_wready : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_bresp  : out std_logic_vector(1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_bvalid : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_bready : in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_araddr : in  std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_arprot : in  std_logic_vector(2 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_arvalid: in  std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_arready: out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rdata  : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rresp  : out std_logic_vector(1 downto 0);
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rvalid : out std_logic;
      -- AXI4-Lite slave-channel signal used for host register access.
      s_axi_rready : in  std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr  : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr  : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en    : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en    : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in  : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy   : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy   : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error    : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_uart_to_reg.vhd.
  component radif_uart_to_reg is
    generic (
      -- Width of the RADIF register data path. This bridge currently transports 32-bit words.
      DATA_WIDTH         : integer := 32;
      -- Width of the RADIF byte address path.
      ADDR_WIDTH         : integer := 16;
      -- Number of clk cycles per UART bit.
      BAUD_DIVISOR       : positive := 868;
      -- Vendor selector retained for generated package consistency.
      VENDOR_TAG         : string := "GENERIC";
      -- Device-family selector retained for generated package consistency.
      PRODUCT_SERIES_TAG : string := "GENERIC"
    );
    port (
      -- Register/UART clock.
      clk          : in  std_logic;
      -- Active-low reset.
      rstn         : in  std_logic;
      -- UART receive pin.
      uart_rx_i    : in  std_logic;
      -- UART transmit pin.
      uart_tx_o    : out std_logic;
      -- Register write address.
      reg_wr_addr  : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address.
      reg_rd_addr  : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle register write request.
      reg_wr_en    : out std_logic;
      -- One-cycle register read request.
      reg_rd_en    : out std_logic;
      -- Register write data.
      reg_data_in  : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register read data.
      reg_data_out : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register target write ready.
      reg_wr_rdy   : in  std_logic;
      -- Register target read ready.
      reg_rd_rdy   : in  std_logic;
      -- Register target write response valid.
      reg_wr_valid : in  std_logic;
      -- Register target read response valid.
      reg_rd_valid : in  std_logic;
      -- Register target error for current response.
      reg_error    : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_i2s_axis.vhd.
  component radif_i2s_axis is
    generic (
      -- Sample width per left/right channel.
      SAMPLE_WIDTH       : positive := 24;
      -- AXI-Stream payload width. The low half carries right-channel data and the high half carries left-channel data.
      AXIS_DATA_WIDTH    : positive := 64;
      -- Width of the RADIF register data bus.
      REG_DATA_WIDTH     : positive := 32;
      -- Width of the RADIF register address bus.
      REG_ADDR_WIDTH     : positive := 16;
      -- Default MCLK half-period divider. Ignored when GENERATE_MCLK is false.
      DEFAULT_MCLK_DIV   : natural  := 1;
      -- Default BCLK half-period divider used when USE_EXTERNAL_BCLK is false.
      DEFAULT_BCLK_DIV   : natural  := 7;
      -- Default number of BCLK rising edges per LRCK half-frame.
      DEFAULT_LRCK_BITS  : positive := 32;
      -- Use the external MCLK pin as a timing reference indicator instead of generating MCLK.
      USE_EXTERNAL_MCLK  : boolean  := false;
      -- Disable MCLK generation and leave MCLK output released.
      NO_MCLK            : boolean  := false;
      -- Use the external BCLK/LRCK pins for I2S timing instead of generating them.
      USE_EXTERNAL_BCLK  : boolean  := false;
      -- Emit I2S-to-AXIS receive datapath logic.
      ENABLE_I2S_TO_AXIS : boolean  := true;
      -- Emit AXIS-to-I2S transmit datapath logic.
      ENABLE_AXIS_TO_I2S : boolean  := true;
      -- Selects the vendor-specific implementation path. This core is portable RTL for all values.
      VENDOR_TAG         : string   := "GENERIC";
      -- Identifies the target FPGA family for generated project metadata.
      PRODUCT_SERIES_TAG : string   := "GENERIC"
    );
    port (
      -- FPGA/register clock domain.
      clk           : in  std_logic;
      -- Active-low reset for the FPGA/register clock domain.
      rstn          : in  std_logic;

      -- Register write address.
      reg_wr_addr   : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address.
      reg_rd_addr   : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle register write request.
      reg_wr_en     : in  std_logic;
      -- One-cycle register read request.
      reg_rd_en     : in  std_logic;
      -- Register write data.
      reg_data_in   : in  std_logic_vector(REG_DATA_WIDTH - 1 downto 0);
      -- Register read data.
      reg_data_out  : out std_logic_vector(REG_DATA_WIDTH - 1 downto 0);
      -- Register write ready.
      reg_wr_rdy    : out std_logic;
      -- Register read ready.
      reg_rd_rdy    : out std_logic;
      -- Register write response valid.
      reg_wr_valid  : out std_logic;
      -- Register read response valid.
      reg_rd_valid  : out std_logic;
      -- Register address or runtime error.
      reg_error     : out std_logic;

      -- External MCLK input when USE_EXTERNAL_MCLK is true.
      i2s_mclk_i    : in  std_logic;
      -- Generated MCLK output when enabled.
      i2s_mclk_o    : out std_logic;
      -- MCLK output-enable. A value of 1 enables the generated MCLK output.
      i2s_mclk_oe   : out std_logic;
      -- External BCLK input when USE_EXTERNAL_BCLK is true.
      i2s_bclk_i    : in  std_logic;
      -- Generated BCLK output when USE_EXTERNAL_BCLK is false.
      i2s_bclk_o    : out std_logic;
      -- BCLK output-enable. A value of 1 enables the generated BCLK output.
      i2s_bclk_oe   : out std_logic;
      -- External LRCK input when USE_EXTERNAL_BCLK is true.
      i2s_lrck_i    : in  std_logic;
      -- Generated LRCK output when USE_EXTERNAL_BCLK is false.
      i2s_lrck_o    : out std_logic;
      -- LRCK output-enable. A value of 1 enables the generated LRCK output.
      i2s_lrck_oe   : out std_logic;
      -- I2S serial data input.
      i2s_sdata_i   : in  std_logic;
      -- I2S serial data output.
      i2s_sdata_o   : out std_logic;
      -- Serial data output-enable. A value of 1 enables the generated serial data output.
      i2s_sdata_oe  : out std_logic;

      -- AXI-Stream output generated from received I2S stereo frames.
      m_axis_tdata  : out std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0);
      -- AXI-Stream output valid.
      m_axis_tvalid : out std_logic;
      -- AXI-Stream output ready.
      m_axis_tready : in  std_logic;
      -- AXI-Stream output frame marker.
      m_axis_tlast  : out std_logic;

      -- AXI-Stream input consumed for I2S transmit stereo frames.
      s_axis_tdata  : in  std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0);
      -- AXI-Stream input valid.
      s_axis_tvalid : in  std_logic;
      -- AXI-Stream input ready.
      s_axis_tready : out std_logic;
      -- AXI-Stream input frame marker.
      s_axis_tlast  : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_reg_to_i2c_master.vhd.
  component radif_reg_to_i2c_master is
    generic (
      -- Width of the RADIF register data bus.
      DATA_WIDTH         : positive := 32;
      -- Width of the RADIF register address bus.
      REG_ADDR_WIDTH     : positive := 16;
      -- Default SCL half-period divider. The active half-period is divider + 1 FPGA clock cycles.
      DEFAULT_SCL_DIV    : natural  := 124;
      -- Selects the vendor-specific implementation path. This core is portable RTL for all values.
      VENDOR_TAG         : string   := "GENERIC";
      -- Identifies the target FPGA family for generated project metadata.
      PRODUCT_SERIES_TAG : string   := "GENERIC"
    );
    port (
      -- FPGA/register clock domain.
      clk          : in  std_logic;
      -- Active-low reset for the FPGA/register clock domain.
      rstn         : in  std_logic;

      -- Register write address.
      reg_wr_addr  : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address.
      reg_rd_addr  : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle register write request.
      reg_wr_en    : in  std_logic;
      -- One-cycle register read request.
      reg_rd_en    : in  std_logic;
      -- Register write data.
      reg_data_in  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register read data.
      reg_data_out : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register write ready.
      reg_wr_rdy   : out std_logic;
      -- Register read ready.
      reg_rd_rdy   : out std_logic;
      -- Register write response valid.
      reg_wr_valid : out std_logic;
      -- Register read response valid.
      reg_rd_valid : out std_logic;
      -- Register address or transaction error.
      reg_error    : out std_logic;

      -- Open-drain SCL input as observed at the pin.
      i2c_scl_i    : in  std_logic;
      -- Open-drain SDA input as observed at the pin.
      i2c_sda_i    : in  std_logic;
      -- SCL output-enable. A value of 0 drives SCL low; a value of 1 releases SCL.
      i2c_scl_oen  : out std_logic;
      -- SDA output-enable. A value of 0 drives SDA low; a value of 1 releases SDA.
      i2c_sda_oen  : out std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_reg_to_spi_master.vhd.
  component radif_reg_to_spi_master is
    generic (
      -- Width of the RADIF register data bus and the maximum SPI transfer word.
      DATA_WIDTH         : positive := 32;
      -- Width of the RADIF register address bus.
      REG_ADDR_WIDTH     : positive := 16;
      -- Default half-period divider for SCLK generation. The active half-period is divider + 1 FPGA clock cycles.
      DEFAULT_SCLK_DIV   : natural  := 124;
      -- Default number of bits shifted per transfer.
      DEFAULT_BIT_COUNT  : positive := 8;
      -- Selects the vendor-specific implementation path. This core is portable RTL for all values.
      VENDOR_TAG         : string   := "GENERIC";
      -- Identifies the target FPGA family for generated project metadata.
      PRODUCT_SERIES_TAG : string   := "GENERIC"
    );
    port (
      -- FPGA/register clock domain.
      clk          : in  std_logic;
      -- Active-low reset for the FPGA/register clock domain.
      rstn         : in  std_logic;

      -- Register write address.
      reg_wr_addr  : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address.
      reg_rd_addr  : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle register write request.
      reg_wr_en    : in  std_logic;
      -- One-cycle register read request.
      reg_rd_en    : in  std_logic;
      -- Register write data.
      reg_data_in  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register read data.
      reg_data_out : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register write ready.
      reg_wr_rdy   : out std_logic;
      -- Register read ready.
      reg_rd_rdy   : out std_logic;
      -- Register write response valid.
      reg_wr_valid : out std_logic;
      -- Register read response valid.
      reg_rd_valid : out std_logic;
      -- Register address or transaction error.
      reg_error    : out std_logic;

      -- SPI serial clock.
      spi_sclk_o   : out std_logic;
      -- SPI chip select, active low by default.
      spi_cs_n_o   : out std_logic;
      -- SPI master-out/slave-in data.
      spi_mosi_o   : out std_logic;
      -- SPI master-in/slave-out data sampled into the RX_DATA register.
      spi_miso_i   : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_spi_slave_to_reg.vhd.
  component radif_spi_slave_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Configures SPI MODE for this instance.
      SPI_MODE           : integer := 0;
      -- Configures ENABLE CRC16 for this instance.
      ENABLE_CRC16       : boolean := false;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn          : in  std_logic;
      -- Input spi sclk i signal for this module.
      spi_sclk_i    : in  std_logic;
      -- Input spi cs n i signal for this module.
      spi_cs_n_i    : in  std_logic;
      -- Input spi mosi i signal for this module.
      spi_mosi_i    : in  std_logic;
      -- Output spi miso o signal generated by this module.
      spi_miso_o    : out std_logic;
      -- Spi miso oen interface signal.
      spi_miso_oen  : out std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en     : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en     : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy    : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy    : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid  : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid  : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error     : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_qspi_slave_to_reg.vhd.
  component radif_qspi_slave_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Configures ENABLE QUAD DATA for this instance.
      ENABLE_QUAD_DATA   : boolean := true;
      -- Configures ENABLE CRC16 for this instance.
      ENABLE_CRC16       : boolean := false;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn          : in  std_logic;
      -- Input qspi sclk i signal for this module.
      qspi_sclk_i   : in  std_logic;
      -- Input qspi cs n i signal for this module.
      qspi_cs_n_i   : in  std_logic;
      -- Input qspi io i signal for this module.
      qspi_io_i     : in  std_logic_vector(3 downto 0);
      -- Output qspi io o signal generated by this module.
      qspi_io_o     : out std_logic_vector(3 downto 0);
      -- Qspi io oen interface signal.
      qspi_io_oen   : out std_logic_vector(3 downto 0);
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en     : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en     : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy    : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy    : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid  : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid  : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error     : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_i2c_slave_to_reg.vhd.
  component radif_i2c_slave_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Configures I2C ADDR for this instance.
      I2C_ADDR           : std_logic_vector(6 downto 0) := "0101010";
      -- Configures ENABLE CRC16 for this instance.
      ENABLE_CRC16       : boolean := false;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn          : in  std_logic;
      -- Input i2c scl i signal for this module.
      i2c_scl_i     : in  std_logic;
      -- Input i2c sda i signal for this module.
      i2c_sda_i     : in  std_logic;
      -- I2c sda oen interface signal.
      i2c_sda_oen   : out std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en     : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en     : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy    : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy    : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid  : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid  : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error     : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_smi16_to_reg.vhd.
  component radif_smi16_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for REG ADDR WIDTH values carried by this module.
      REG_ADDR_WIDTH     : integer := 16;
      -- Sets the bit width for SMI ADDR WIDTH values carried by this module.
      SMI_ADDR_WIDTH     : integer := 16;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn          : in  std_logic;
      -- Input smi cs n i signal for this module.
      smi_cs_n_i    : in  std_logic;
      -- Input smi rd n i signal for this module.
      smi_rd_n_i    : in  std_logic;
      -- Input smi wr n i signal for this module.
      smi_wr_n_i    : in  std_logic;
      -- Input smi addr i signal for this module.
      smi_addr_i    : in  std_logic_vector(SMI_ADDR_WIDTH - 1 downto 0);
      -- Input smi data i signal for this module.
      smi_data_i    : in  std_logic_vector(15 downto 0);
      -- Output smi data o signal generated by this module.
      smi_data_o    : out std_logic_vector(15 downto 0);
      -- Smi data oen interface signal.
      smi_data_oen  : out std_logic;
      -- Output smi ack o signal generated by this module.
      smi_ack_o     : out std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr   : out std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr   : out std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en     : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en     : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy    : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy    : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid  : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid  : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error     : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_axi4_axis_dma.vhd.
  component radif_axi4_axis_dma is
    generic (
      -- Sets the bit width for REG DATA WIDTH values carried by this module.
      REG_DATA_WIDTH     : integer := 32;
      -- Sets the bit width for REG ADDR WIDTH values carried by this module.
      REG_ADDR_WIDTH     : integer := 16;
      -- Sets the bit width for AXI ADDR WIDTH values carried by this module.
      AXI_ADDR_WIDTH     : integer := 32;
      -- Sets the bit width for AXI DATA WIDTH values carried by this module.
      AXI_DATA_WIDTH     : integer := 32;
      -- Sets the bit width for AXIS DATA WIDTH values carried by this module.
      AXIS_DATA_WIDTH    : integer := 32;
      -- Configures ENABLE MM2S for this instance.
      ENABLE_MM2S        : boolean := true;
      -- Configures ENABLE S2MM for this instance.
      ENABLE_S2MM        : boolean := true;
      -- Sets the storage depth, frame length, or number of buffered samples used internally.
      FIFO_DEPTH         : integer := 1024;
      -- Configures FIFO FWFT for this instance.
      FIFO_FWFT          : boolean := true;
      -- Configures MAX BURST LEN for this instance.
      MAX_BURST_LEN      : integer := 16;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk             : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn            : in  std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr     : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr     : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en       : in  std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en       : in  std_logic;
      -- Write data presented to the internal register target.
      reg_data_in     : in  std_logic_vector(REG_DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out    : out std_logic_vector(REG_DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy      : out std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy      : out std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid    : out std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid    : out std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error       : out std_logic;
      -- Output irq o signal generated by this module.
      irq_o           : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awaddr    : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awlen     : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awsize    : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awburst   : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awvalid   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awready   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wdata     : out std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wstrb     : out std_logic_vector((AXI_DATA_WIDTH / 8) - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wlast     : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wvalid    : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wready    : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bresp     : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bvalid    : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bready    : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_araddr    : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arlen     : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arsize    : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arburst   : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arvalid   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arready   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rdata     : in  std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rresp     : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rlast     : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rvalid    : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rready    : out std_logic;
      -- Output AXI-stream payload containing packed processed result lanes.
      m_axis_tdata    : out std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0);
      -- Output AXI-stream valid qualifier for the current result beat.
      m_axis_tvalid   : out std_logic;
      -- Output AXI-stream ready input from the downstream block.
      m_axis_tready   : in  std_logic;
      -- Output AXI-stream frame marker aligned with the processed result beat.
      m_axis_tlast    : out std_logic;
      -- Input AXI-stream payload containing packed sample or feature lanes.
      s_axis_tdata    : in  std_logic_vector(AXIS_DATA_WIDTH - 1 downto 0);
      -- Input AXI-stream valid qualifier for the current sample beat.
      s_axis_tvalid   : in  std_logic;
      -- Input AXI-stream ready response indicating this block can accept a beat.
      s_axis_tready   : out std_logic;
      -- Input AXI-stream frame marker for the final beat of a frame.
      s_axis_tlast    : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_spi_axi_master.vhd.
  component radif_spi_axi_master is
    generic (
      -- Sets the bit width for AXI DATA WIDTH values carried by this module.
      AXI_DATA_WIDTH     : integer := 32;
      -- Sets the bit width for AXI ADDR WIDTH values carried by this module.
      AXI_ADDR_WIDTH     : integer := 32;
      -- Configures AXI MODE for this instance.
      AXI_MODE           : string  := "AXI_LITE";
      -- Configures ENABLE CRC16 for this instance.
      ENABLE_CRC16       : boolean := false;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk            : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn           : in  std_logic;
      -- Input spi sclk i signal for this module.
      spi_sclk_i     : in  std_logic;
      -- Input spi cs n i signal for this module.
      spi_cs_n_i     : in  std_logic;
      -- Input spi mosi i signal for this module.
      spi_mosi_i     : in  std_logic;
      -- Output spi miso o signal generated by this module.
      spi_miso_o     : out std_logic;
      -- Spi miso oen interface signal.
      spi_miso_oen   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awaddr   : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awlen    : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awsize   : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awburst  : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awvalid  : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awready  : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wdata    : out std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wstrb    : out std_logic_vector((AXI_DATA_WIDTH / 8) - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wlast    : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wvalid   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wready   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bresp    : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bvalid   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bready   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_araddr   : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arlen    : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arsize   : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arburst  : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arvalid  : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arready  : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rdata    : in  std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rresp    : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rlast    : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rvalid   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rready   : out std_logic
    );
  end component;

end package interfaces;
