library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.radif_pkg.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package interfaces_smi is
  -- Component declaration sourced from interfaces/hdl/radif/src/radif_smi16_to_reg.vhd.
  component radif_smi16_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for REG ADDR WIDTH values carried by this module.
      REG_ADDR_WIDTH     : integer := 16;
      -- Sets the bit width for SMI ADDR WIDTH values carried by this module.
      SMI_ADDR_WIDTH     : integer := 16;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn          : in  std_logic;
      -- Input smi cs n i signal for this module.
      smi_cs_n_i    : in  std_logic;
      -- Input smi rd n i signal for this module.
      smi_rd_n_i    : in  std_logic;
      -- Input smi wr n i signal for this module.
      smi_wr_n_i    : in  std_logic;
      -- Input smi addr i signal for this module.
      smi_addr_i    : in  std_logic_vector(SMI_ADDR_WIDTH - 1 downto 0);
      -- Input smi data i signal for this module.
      smi_data_i    : in  std_logic_vector(15 downto 0);
      -- Output smi data o signal generated by this module.
      smi_data_o    : out std_logic_vector(15 downto 0);
      -- Smi data oen interface signal.
      smi_data_oen  : out std_logic;
      -- Output smi ack o signal generated by this module.
      smi_ack_o     : out std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr   : out std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr   : out std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en     : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en     : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy    : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy    : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid  : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid  : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error     : in  std_logic
    );
  end component;

end package interfaces_smi;
