library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.radif_pkg.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package interfaces_spi is
  -- Component declaration sourced from interfaces/hdl/radif/src/radif_spi_slave_to_reg.vhd.
  component radif_spi_slave_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Configures SPI MODE for this instance.
      SPI_MODE           : integer := 0;
      -- Configures ENABLE CRC16 for this instance.
      ENABLE_CRC16       : boolean := false;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn          : in  std_logic;
      -- Input spi sclk i signal for this module.
      spi_sclk_i    : in  std_logic;
      -- Input spi cs n i signal for this module.
      spi_cs_n_i    : in  std_logic;
      -- Input spi mosi i signal for this module.
      spi_mosi_i    : in  std_logic;
      -- Output spi miso o signal generated by this module.
      spi_miso_o    : out std_logic;
      -- Spi miso oen interface signal.
      spi_miso_oen  : out std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en     : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en     : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy    : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy    : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid  : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid  : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error     : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_qspi_slave_to_reg.vhd.
  component radif_qspi_slave_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Configures ENABLE QUAD DATA for this instance.
      ENABLE_QUAD_DATA   : boolean := true;
      -- Configures ENABLE CRC16 for this instance.
      ENABLE_CRC16       : boolean := false;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn          : in  std_logic;
      -- Input qspi sclk i signal for this module.
      qspi_sclk_i   : in  std_logic;
      -- Input qspi cs n i signal for this module.
      qspi_cs_n_i   : in  std_logic;
      -- Input qspi io i signal for this module.
      qspi_io_i     : in  std_logic_vector(3 downto 0);
      -- Output qspi io o signal generated by this module.
      qspi_io_o     : out std_logic_vector(3 downto 0);
      -- Qspi io oen interface signal.
      qspi_io_oen   : out std_logic_vector(3 downto 0);
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en     : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en     : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy    : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy    : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid  : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid  : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error     : in  std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_spi_axi_master.vhd.
  component radif_spi_axi_master is
    generic (
      -- Sets the bit width for AXI DATA WIDTH values carried by this module.
      AXI_DATA_WIDTH     : integer := 32;
      -- Sets the bit width for AXI ADDR WIDTH values carried by this module.
      AXI_ADDR_WIDTH     : integer := 32;
      -- Configures AXI MODE for this instance.
      AXI_MODE           : string  := "AXI_LITE";
      -- Configures ENABLE CRC16 for this instance.
      ENABLE_CRC16       : boolean := false;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk            : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn           : in  std_logic;
      -- Input spi sclk i signal for this module.
      spi_sclk_i     : in  std_logic;
      -- Input spi cs n i signal for this module.
      spi_cs_n_i     : in  std_logic;
      -- Input spi mosi i signal for this module.
      spi_mosi_i     : in  std_logic;
      -- Output spi miso o signal generated by this module.
      spi_miso_o     : out std_logic;
      -- Spi miso oen interface signal.
      spi_miso_oen   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awaddr   : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awlen    : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awsize   : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awburst  : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awvalid  : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_awready  : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wdata    : out std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wstrb    : out std_logic_vector((AXI_DATA_WIDTH / 8) - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wlast    : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wvalid   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_wready   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bresp    : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bvalid   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_bready   : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_araddr   : out std_logic_vector(AXI_ADDR_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arlen    : out std_logic_vector(7 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arsize   : out std_logic_vector(2 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arburst  : out std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arvalid  : out std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_arready  : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rdata    : in  std_logic_vector(AXI_DATA_WIDTH - 1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rresp    : in  std_logic_vector(1 downto 0);
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rlast    : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rvalid   : in  std_logic;
      -- AXI master-channel signal used for memory-mapped transfer generation.
      m_axi_rready   : out std_logic
    );
  end component;

end package interfaces_spi;
