library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.radif_pkg.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package interfaces_i2c is
  -- Component declaration sourced from interfaces/hdl/radif/src/radif_reg_to_i2c_master.vhd.
  component radif_reg_to_i2c_master is
    generic (
      -- Width of the RADIF register data bus.
      DATA_WIDTH         : positive := 32;
      -- Width of the RADIF register address bus.
      REG_ADDR_WIDTH     : positive := 16;
      -- Default SCL half-period divider. The active half-period is divider + 1 FPGA clock cycles.
      DEFAULT_SCL_DIV    : natural  := 124;
      -- Selects the vendor-specific implementation path. This core is portable RTL for all values.
      VENDOR_TAG         : string   := "GENERIC";
      -- Identifies the target FPGA family for generated project metadata.
      PRODUCT_SERIES_TAG : string   := "GENERIC"
    );
    port (
      -- FPGA/register clock domain.
      clk          : in  std_logic;
      -- Active-low reset for the FPGA/register clock domain.
      rstn         : in  std_logic;

      -- Register write address.
      reg_wr_addr  : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- Register read address.
      reg_rd_addr  : in  std_logic_vector(REG_ADDR_WIDTH - 1 downto 0);
      -- One-cycle register write request.
      reg_wr_en    : in  std_logic;
      -- One-cycle register read request.
      reg_rd_en    : in  std_logic;
      -- Register write data.
      reg_data_in  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register read data.
      reg_data_out : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Register write ready.
      reg_wr_rdy   : out std_logic;
      -- Register read ready.
      reg_rd_rdy   : out std_logic;
      -- Register write response valid.
      reg_wr_valid : out std_logic;
      -- Register read response valid.
      reg_rd_valid : out std_logic;
      -- Register address or transaction error.
      reg_error    : out std_logic;

      -- Open-drain SCL input as observed at the pin.
      i2c_scl_i    : in  std_logic;
      -- Open-drain SDA input as observed at the pin.
      i2c_sda_i    : in  std_logic;
      -- SCL output-enable. A value of 0 drives SCL low; a value of 1 releases SCL.
      i2c_scl_oen  : out std_logic;
      -- SDA output-enable. A value of 0 drives SDA low; a value of 1 releases SDA.
      i2c_sda_oen  : out std_logic
    );
  end component;

  -- Component declaration sourced from interfaces/hdl/radif/src/radif_i2c_slave_to_reg.vhd.
  component radif_i2c_slave_to_reg is
    generic (
      -- Sets the bit width for DATA WIDTH values carried by this module.
      DATA_WIDTH         : integer := 32;
      -- Sets the bit width for ADDR WIDTH values carried by this module.
      ADDR_WIDTH         : integer := 16;
      -- Configures I2C ADDR for this instance.
      I2C_ADDR           : std_logic_vector(6 downto 0) := "0101010";
      -- Configures ENABLE CRC16 for this instance.
      ENABLE_CRC16       : boolean := false;
      -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
      VENDOR_TAG         : string  := "XILINX";
      -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
      PRODUCT_SERIES_TAG : string  := "GENERIC"
    );
    port (
      -- Clock for the associated synchronous logic and handshake domain.
      clk           : in  std_logic;
      -- Active-low reset for this clock domain.
      rstn          : in  std_logic;
      -- Input i2c scl i signal for this module.
      i2c_scl_i     : in  std_logic;
      -- Input i2c sda i signal for this module.
      i2c_sda_i     : in  std_logic;
      -- I2c sda oen interface signal.
      i2c_sda_oen   : out std_logic;
      -- Register write address issued to the internal RadIF register target.
      reg_wr_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- Register read address issued to the internal RadIF register target.
      reg_rd_addr   : out std_logic_vector(ADDR_WIDTH - 1 downto 0);
      -- One-cycle write request pulse for the internal register target.
      reg_wr_en     : out std_logic;
      -- One-cycle read request pulse for the internal register target.
      reg_rd_en     : out std_logic;
      -- Write data presented to the internal register target.
      reg_data_in   : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Read data returned by the internal register target.
      reg_data_out  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      -- Write-side ready indication from the internal register target.
      reg_wr_rdy    : in  std_logic;
      -- Read-side ready indication from the internal register target.
      reg_rd_rdy    : in  std_logic;
      -- Write response valid indication from the internal register target.
      reg_wr_valid  : in  std_logic;
      -- Read response valid indication from the internal register target.
      reg_rd_valid  : in  std_logic;
      -- Register target error flag converted into the external bus error response.
      reg_error     : in  std_logic
    );
  end component;

end package interfaces_i2c;
