library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.
package RadPrimitive is
  -- Component declaration sourced from common/hdl/src/radhdl_cdc.vhd.
  component rad_cdc_single is
    generic (
      VENDOR : string := "generic";
      STAGES : positive := 2;
      INIT   : std_logic := '0'
    );
    port (
      dest_clk : in  std_logic;
      src_i    : in  std_logic;
      dest_o   : out std_logic
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_cdc.vhd.
  component rad_cdc_array_single is
    generic (
      VENDOR     : string := "generic";
      DATA_WIDTH : positive := 1;
      STAGES     : positive := 2;
      INIT       : std_logic := '0'
    );
    port (
      dest_clk : in  std_logic;
      src_i    : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      dest_o   : out std_logic_vector(DATA_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_cdc.vhd.
  component rad_cdc_sync_rst is
    generic (
      VENDOR      : string := "generic";
      STAGES      : positive := 2;
      ACTIVE_HIGH : boolean := true
    );
    port (
      dest_clk : in  std_logic;
      rst_i    : in  std_logic;
      rst_o    : out std_logic
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_cdc.vhd.
  component rad_cdc_async_rst is
    generic (
      VENDOR      : string := "generic";
      STAGES      : positive := 2;
      ACTIVE_HIGH : boolean := true
    );
    port (
      dest_clk : in  std_logic;
      rst_i    : in  std_logic;
      rst_o    : out std_logic
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_cdc.vhd.
  component rad_cdc_pulse is
    generic (
      VENDOR : string := "generic";
      STAGES : positive := 2
    );
    port (
      src_clk      : in  std_logic;
      src_rst      : in  std_logic;
      src_pulse_i  : in  std_logic;
      dest_clk     : in  std_logic;
      dest_rst     : in  std_logic;
      dest_pulse_o : out std_logic
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_cdc.vhd.
  component rad_cdc_gray is
    generic (
      VENDOR     : string := "generic";
      DATA_WIDTH : positive := 4;
      STAGES     : positive := 2
    );
    port (
      dest_clk    : in  std_logic;
      src_gray_i  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      dest_gray_o : out std_logic_vector(DATA_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_cdc.vhd.
  component rad_cdc_handshake is
    generic (
      VENDOR     : string := "generic";
      DATA_WIDTH : positive := 1;
      STAGES     : positive := 2
    );
    port (
      src_clk     : in  std_logic;
      src_rst     : in  std_logic;
      src_valid_i : in  std_logic;
      src_data_i  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      src_ready_o : out std_logic;
      dest_clk    : in  std_logic;
      dest_rst    : in  std_logic;
      dest_valid_o: out std_logic;
      dest_data_o : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      dest_ready_i: in  std_logic
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_ram.vhd.
  component radhdl_ram is
    generic (
      VENDOR           : string   := "xilinx";
      DEVICE_FAMILY    : string   := "7series";
      MODE             : string   := "tdp";
      MEMORY_KIND      : string   := "bram";
      DATA_WIDTH       : positive := 18;
      ADDR_WIDTH       : positive := 10;
      DEPTH            : positive := 1024;
      CLOCKING_MODE    : string   := "common_clock";
      MEMORY_INIT_FILE : string   := "none";
      USE_MEM_INIT     : integer  := 0;
      SIMULATION       : boolean  := false
    );
    port (
      clka   : in  std_logic;
      rsta   : in  std_logic;
      a_addr : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      a_din  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      a_dout : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      a_we   : in  std_logic;
      clkb   : in  std_logic;
      rstb   : in  std_logic;
      b_addr : in  std_logic_vector(ADDR_WIDTH - 1 downto 0);
      b_din  : in  std_logic_vector(DATA_WIDTH - 1 downto 0);
      b_dout : out std_logic_vector(DATA_WIDTH - 1 downto 0);
      b_we   : in  std_logic
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_fifo.vhd.
  component radhdl_fifo is
    generic (
      VENDOR              : string  := "xilinx";
      DEVICE_FAMILY       : string  := "7series";
      FIFO_MODE           : string  := "sync";
      ASYNC               : boolean := false;
      CASCADE_HEIGHT      : integer := 0;
      DOUT_RESET_VALUE    : string  := "0";
      ECC_MODE            : string  := "no_ecc";
      FIFO_MEMORY_TYPE    : string  := "auto";
      FIFO_READ_LATENCY   : integer := 1;
      FIFO_WRITE_DEPTH    : integer := 1024;
      FULL_RESET_VALUE    : integer := 0;
      PROG_EMPTY_THRESH   : integer := 10;
      PROG_FULL_THRESH    : integer := 10;
      RD_DATA_COUNT_WIDTH : integer := 1;
      READ_DATA_WIDTH     : integer := 32;
      READ_MODE           : string  := "std";
      SIM_ASSERT_CHK      : integer := 0;
      USE_ADV_FEATURES    : string  := "0707";
      WAKEUP_TIME         : integer := 0;
      WRITE_DATA_WIDTH    : integer := 32;
      WR_DATA_COUNT_WIDTH : integer := 1
    );
    port (
      almost_empty  : out std_logic;
      almost_full   : out std_logic;
      data_valid    : out std_logic;
      dbiterr       : out std_logic;
      dout          : out std_logic_vector(READ_DATA_WIDTH - 1 downto 0);
      empty         : out std_logic;
      full          : out std_logic;
      overflow      : out std_logic;
      prog_empty    : out std_logic;
      prog_full     : out std_logic;
      rd_data_count : out std_logic_vector(RD_DATA_COUNT_WIDTH - 1 downto 0);
      rd_rst_busy   : out std_logic;
      sbiterr       : out std_logic;
      underflow     : out std_logic;
      wr_ack        : out std_logic;
      wr_data_count : out std_logic_vector(WR_DATA_COUNT_WIDTH - 1 downto 0);
      wr_rst_busy   : out std_logic;
      din           : in  std_logic_vector(WRITE_DATA_WIDTH - 1 downto 0);
      injectdbiterr : in  std_logic;
      injectsbiterr : in  std_logic;
      rd_en         : in  std_logic;
      rst           : in  std_logic;
      sleep         : in  std_logic;
      rd_clk        : in  std_logic := '0';
      wr_clk        : in  std_logic;
      wr_en         : in  std_logic
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_fifo_sync.vhd.
  component radhdl_fifo_sync is
    generic (
      VENDOR              : string  := "xilinx";
      DEVICE_FAMILY       : string  := "7series";
      CASCADE_HEIGHT      : integer := 0;
      DOUT_RESET_VALUE    : string  := "0";
      ECC_MODE            : string  := "no_ecc";
      FIFO_MEMORY_TYPE    : string  := "auto";
      FIFO_READ_LATENCY   : integer := 1;
      FIFO_WRITE_DEPTH    : integer := 1024;
      FULL_RESET_VALUE    : integer := 0;
      PROG_EMPTY_THRESH   : integer := 10;
      PROG_FULL_THRESH    : integer := 10;
      RD_DATA_COUNT_WIDTH : integer := 1;
      READ_DATA_WIDTH     : integer := 32;
      READ_MODE           : string  := "std";
      SIM_ASSERT_CHK      : integer := 0;
      USE_ADV_FEATURES    : string  := "0707";
      WAKEUP_TIME         : integer := 0;
      WRITE_DATA_WIDTH    : integer := 32;
      WR_DATA_COUNT_WIDTH : integer := 1
    );
    port (
      almost_empty  : out std_logic;
      almost_full   : out std_logic;
      data_valid    : out std_logic;
      dbiterr       : out std_logic;
      dout          : out std_logic_vector(READ_DATA_WIDTH - 1 downto 0);
      empty         : out std_logic;
      full          : out std_logic;
      overflow      : out std_logic;
      prog_empty    : out std_logic;
      prog_full     : out std_logic;
      rd_data_count : out std_logic_vector(RD_DATA_COUNT_WIDTH - 1 downto 0);
      rd_rst_busy   : out std_logic;
      sbiterr       : out std_logic;
      underflow     : out std_logic;
      wr_ack        : out std_logic;
      wr_data_count : out std_logic_vector(WR_DATA_COUNT_WIDTH - 1 downto 0);
      wr_rst_busy   : out std_logic;
      din           : in  std_logic_vector(WRITE_DATA_WIDTH - 1 downto 0);
      injectdbiterr : in  std_logic;
      injectsbiterr : in  std_logic;
      rd_en         : in  std_logic;
      rst           : in  std_logic;
      sleep         : in  std_logic;
      wr_clk        : in  std_logic;
      wr_en         : in  std_logic
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_fifo_async.vhd.
  component radhdl_fifo_async is
    generic (
      VENDOR              : string  := "xilinx";
      DEVICE_FAMILY       : string  := "7series";
      FIFO_READ_LATENCY   : integer := 1;
      FIFO_WRITE_DEPTH    : integer := 1024;
      RD_DATA_COUNT_WIDTH : integer := 1;
      READ_DATA_WIDTH     : integer := 32;
      READ_MODE           : string  := "std";
      WRITE_DATA_WIDTH    : integer := 32;
      WR_DATA_COUNT_WIDTH : integer := 1
    );
    port (
      almost_empty  : out std_logic;
      almost_full   : out std_logic;
      data_valid    : out std_logic;
      dout          : out std_logic_vector(READ_DATA_WIDTH - 1 downto 0);
      empty         : out std_logic;
      full          : out std_logic;
      rd_data_count : out std_logic_vector(RD_DATA_COUNT_WIDTH - 1 downto 0);
      wr_data_count : out std_logic_vector(WR_DATA_COUNT_WIDTH - 1 downto 0);
      din           : in  std_logic_vector(WRITE_DATA_WIDTH - 1 downto 0);
      rd_clk        : in  std_logic;
      rd_en         : in  std_logic;
      rst           : in  std_logic;
      wr_clk        : in  std_logic;
      wr_en         : in  std_logic
    );
  end component;

  -- Component declaration sourced from common/hdl/src/radhdl_sample_ram.vhd.
  component radhdl_sample_ram is
    generic (
      VENDOR        : string   := "xilinx";
      DEVICE_FAMILY : string   := "7series";
      DATA_WIDTH    : positive := 16;
      ADDR_WIDTH    : positive := 10;
      DEPTH         : positive := 1024
    );
    port (
      clk     : in  std_logic;
      wr_en   : in  std_logic;
      wr_addr : in  unsigned(ADDR_WIDTH - 1 downto 0);
      wr_data : in  signed(DATA_WIDTH - 1 downto 0);
      rd_addr : in  unsigned(ADDR_WIDTH - 1 downto 0);
      rd_data : out signed(DATA_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_mul.vhd.
  component raddsp_mul is
    generic (
      VENDOR        : string  := "xilinx";
      DEVICE_FAMILY : string  := "7series";
      A_WIDTH       : positive := 16;
      B_WIDTH       : positive := 18;
      SIMULATION    : boolean  := false
    );
    port (
      clk        : in  std_logic;
      rst        : in  std_logic;
      valid_i    : in  std_logic;
      subtract_i : in  std_logic;
      last_i     : in  std_logic;
      a_i        : in  signed(A_WIDTH - 1 downto 0);
      b_i        : in  signed(B_WIDTH - 1 downto 0);
      valid_o    : out std_logic;
      subtract_o : out std_logic;
      last_o     : out std_logic;
      p_o        : out signed(47 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_wide_mul.vhd.
  component raddsp_wide_mul is
    generic (
      VENDOR        : string := "xilinx";
      DEVICE_FAMILY : string := "7series";
      A_WIDTH       : positive := 16;
      B_WIDTH       : positive := 16;
      PRODUCT_WIDTH : positive := 64;
      CHUNK_WIDTH   : positive := 16
    );
    port (
      clk      : in  std_logic;
      rst      : in  std_logic;
      valid_i  : in  std_logic;
      a_i      : in  signed(A_WIDTH - 1 downto 0);
      b_i      : in  signed(B_WIDTH - 1 downto 0);
      valid_o  : out std_logic;
      p_o      : out signed(PRODUCT_WIDTH - 1 downto 0)
    );
  end component;

  -- Component declaration sourced from dsp/hdl/raddsp/src/raddsp_square_seq.vhd.
  component raddsp_square_seq is
    generic (
      VENDOR        : string := "xilinx";
      DEVICE_FAMILY : string := "7series";
      WIDTH         : positive := 32
    );
    port (
      clk     : in  std_logic;
      rst     : in  std_logic;
      start_i : in  std_logic;
      x_i     : in  signed(WIDTH - 1 downto 0);
      busy_o  : out std_logic;
      valid_o : out std_logic;
      y_o     : out unsigned((2 * WIDTH) - 1 downto 0)
    );
  end component;

end package RadPrimitive;
