# Generated by scripts/generate_radhdl_library.py. Do not hand-edit.

namespace eval ::RadHDL {
    variable ROOT [file normalize [file join [file dirname [info script]] ..]]
    variable RADHDL_API_FILES [list \
        [file join $::RadHDL::ROOT hdl radhdl src dsp.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src dsp_comms.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src dsp_detection.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src dsp_filter.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src dsp_matrix.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src dsp_transform.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src interfaces.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src interfaces_axi.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src interfaces_i2s.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src interfaces_i2c.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src interfaces_regbank.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src interfaces_smi.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src interfaces_spi.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src interfaces_uart.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src debug.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src dsp_context.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src interfaces_context.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src debug_context.vhd] \
        [file join $::RadHDL::ROOT hdl radhdl src radhdl_context.vhd] \
    ]
    variable COMMON_PROTOCOL_FILES [list \
        [file join $::RadHDL::ROOT common hdl src radhdl_axi_pkg.vhd] \
        [file join $::RadHDL::ROOT common hdl src radhdl_axis_pkg.vhd] \
        [file join $::RadHDL::ROOT common hdl src radhdl_spi_pkg.vhd] \
    ]
    variable DEBUG_RADILA_FILES [list \
        [file join $::RadHDL::ROOT debug radila hdl radila radila_core.vhd] \
        [file join $::RadHDL::ROOT debug radila hdl radila raddebughub.vhd] \
    ]
    variable DSP_RADDSP_RAW_FILES [list \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_pkg.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src zc_reference_pkg.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src cordic_atan_pkg.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_fft_twiddle_pkg.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src fft_tdp_ram.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_fft_twiddle_rom.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_sqrt_u32.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_xilinx_dsp48_mul.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_xilinx_dsp48_square_seq.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_xilinx_dsp48_wide_mul.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src cordic_atan2.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src fft_radix2_batch_core.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_gain.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_mix2.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_one_pole_lowpass.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_fir.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_biquad.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_dds.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_am_iq_modulator.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_am_iq_demodulator.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_float_to_fixed.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_fixed_to_float.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_iq_magnitude_sq.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_frame_stats.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_fft_fingerprint.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_fingerprint_matcher.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_matrix_elementwise.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_matrix_dot.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_fft_bin_product.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_radfft_batch.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_radfft_radix2_tdp.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_radfft_radix4_tdp.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_radfft_parallel8.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_radfft_iterative.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_radfft_streaming.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_radfft.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src raddsp_axis_radfft_ddr.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src zc_cross_correlator.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src zc_peak_detector.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp src zc_chirp_frame_detector.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp wrappers raddsp_zc_chirp_frame_detector.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp wrappers raddsp_cordic_atan2.vhd] \
        [file join $::RadHDL::ROOT dsp hdl raddsp wrappers raddsp_fft_radix2_batch_core.vhd] \
    ]
    variable DSP_RADDSP_XCI_FILES [list \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_cordic_atan2_0 raddsp_cordic_atan2_0.xci] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_fft_radix2_batch_core_0 raddsp_fft_radix2_batch_core_0.xci] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_zc_chirp_frame_detector_0 raddsp_zc_chirp_frame_detector_0.xci] \
    ]
    variable DSP_RADDSP_XCI_VHDL_FILES [list \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_zc_chirp_frame_detector_0 src zc_reference_pkg.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_zc_chirp_frame_detector_0 src zc_chirp_frame_detector.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_zc_chirp_frame_detector_0 src raddsp_zc_chirp_frame_detector.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_zc_chirp_frame_detector_0 synth raddsp_zc_chirp_frame_detector_0.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_cordic_atan2_0 src cordic_atan_pkg.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_cordic_atan2_0 src cordic_atan2.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_cordic_atan2_0 src raddsp_cordic_atan2.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_cordic_atan2_0 synth raddsp_cordic_atan2_0.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_fft_radix2_batch_core_0 src fft_tdp_ram.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_fft_radix2_batch_core_0 src fft_radix2_batch_core.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_fft_radix2_batch_core_0 src raddsp_fft_radix2_batch_core.vhd] \
        [file join $::RadHDL::ROOT dsp hdl xci raddsp_fft_radix2_batch_core_0 synth raddsp_fft_radix2_batch_core_0.vhd] \
    ]
    variable INTERFACES_RADIF_FILES [list \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_pkg.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_reg_bank.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_reg_interconnect.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_gpio_reg_block.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_irq_controller.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_axi_lite_to_reg.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_uart_to_reg.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_i2s_axis.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_reg_to_i2c_master.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_reg_to_spi_master.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_spi_slave_to_reg.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_qspi_slave_to_reg.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_i2c_slave_to_reg.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_smi16_to_reg.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_axi4_axis_dma.vhd] \
        [file join $::RadHDL::ROOT interfaces hdl radif src radif_spi_axi_master.vhd] \
    ]
    variable DSP_RADDSP_IP_REPO [file join $ROOT dsp hdl iprepo]

    proc files {library} {
        variable DEBUG_RADILA_FILES
        variable RADHDL_API_FILES
        variable COMMON_PROTOCOL_FILES
        variable DSP_RADDSP_RAW_FILES
        variable DSP_RADDSP_XCI_FILES
        variable DSP_RADDSP_XCI_VHDL_FILES
        variable INTERFACES_RADIF_FILES

        switch -- $library {
            radhdl.api { return $RADHDL_API_FILES }
            radhdl.protocol { return $COMMON_PROTOCOL_FILES }
            protocol { return $COMMON_PROTOCOL_FILES }
            radhdl.all { return [concat $COMMON_PROTOCOL_FILES $DSP_RADDSP_RAW_FILES $INTERFACES_RADIF_FILES $DEBUG_RADILA_FILES $RADHDL_API_FILES] }
            all { return [concat $COMMON_PROTOCOL_FILES $DSP_RADDSP_RAW_FILES $INTERFACES_RADIF_FILES $DEBUG_RADILA_FILES $RADHDL_API_FILES] }
            debug.radila { return $DEBUG_RADILA_FILES }
            debug { return $DEBUG_RADILA_FILES }
            dsp.raddsp.raw { return [concat $COMMON_PROTOCOL_FILES $DSP_RADDSP_RAW_FILES] }
            dsp.raw { return [concat $COMMON_PROTOCOL_FILES $DSP_RADDSP_RAW_FILES] }
            dsp.raddsp.xci { return $DSP_RADDSP_XCI_FILES }
            dsp.xci { return $DSP_RADDSP_XCI_FILES }
            dsp.raddsp.xci_vhdl { return $DSP_RADDSP_XCI_VHDL_FILES }
            dsp.xci_vhdl { return $DSP_RADDSP_XCI_VHDL_FILES }
            interfaces.radif { return [concat $COMMON_PROTOCOL_FILES $INTERFACES_RADIF_FILES] }
            interfaces { return [concat $COMMON_PROTOCOL_FILES $INTERFACES_RADIF_FILES] }
            default { error "unknown RadHDL library '$library'" }
        }
    }

    proc existing_files {library} {
        set out {}
        foreach f [files $library] {
            if {[file exists $f]} {
                lappend out $f
            }
        }
        return $out
    }

    proc require_files {library} {
        set missing {}
        set out {}
        foreach f [files $library] {
            if {[file exists $f]} {
                lappend out $f
            } else {
                lappend missing $f
            }
        }
        if {[llength $missing] > 0} {
            error "missing RadHDL $library files: $missing"
        }
        return $out
    }

    proc ip_repo_paths {args} {
        variable DSP_RADDSP_IP_REPO
        set paths {}
        foreach name $args {
            switch -- $name {
                dsp.raddsp - dsp { lappend paths $DSP_RADDSP_IP_REPO }
                default { error "unknown RadHDL IP repo '$name'" }
            }
        }
        return $paths
    }

    proc add_files {library args} {
        set files [require_files $library]
        if {[llength $files] > 0} {
            uplevel 1 [list add_files {*}$args -norecurse $files]
        }
        return $files
    }
}
