#!/usr/bin/env python3
from __future__ import annotations

import re
import textwrap
from dataclasses import dataclass
from pathlib import Path

from generate_radhdl_library import DEBUG_RADILA, DSP_RADDSP_RAW, INTERFACES_RADIF, ROOT


OUT_DIR = ROOT / "hdl" / "radhdl" / "src"


@dataclass(frozen=True)
class EntityDecl:
    name: str
    source: str
    generic: str
    port: str


DSP_GROUPS: dict[str, tuple[str, ...]] = {
    "dsp_comms": (
        "am_iq",
        "comms",
        "modulator",
        "demodulator",
    ),
    "dsp_filter": (
        "biquad",
        "fir",
        "filter",
        "one_pole",
        "lowpass",
    ),
    "dsp_matrix": (
        "matrix",
    ),
    "dsp_detection": (
        "fingerprint",
        "frame_stats",
        "zc_",
        "chirp",
        "peak_detector",
        "cross_correlator",
    ),
    "dsp_transform": (
        "cordic",
        "dds",
        "dsp48",
        "fft",
        "fixed_to_float",
        "float_to_fixed",
        "gain",
        "iq_magnitude",
        "mix",
        "radfft",
        "sqrt",
        "twiddle",
    ),
}

INTERFACE_GROUPS: dict[str, tuple[str, ...]] = {
    "interfaces_i2s": ("i2s",),
    "interfaces_i2c": ("i2c",),
    "interfaces_smi": ("smi",),
    "interfaces_spi": ("spi", "qspi"),
    "interfaces_uart": ("uart",),
    "interfaces_regbank": ("reg_bank", "reg_interconnect", "gpio", "irq_controller"),
    "interfaces_axi": ("axi", "axis"),
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def find_matching_paren(text: str, open_index: int) -> int:
    depth = 0
    index = open_index
    while index < len(text):
        char = text[index]
        if char == "(":
            depth += 1
        elif char == ")":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    raise ValueError("unbalanced VHDL parenthesis")


def extract_clause(entity_text: str, keyword: str) -> str:
    match = re.search(rf"\b{keyword}\s*\(", entity_text, re.IGNORECASE)
    if not match:
        return ""
    open_index = entity_text.find("(", match.start())
    close_index = find_matching_paren(entity_text, open_index)
    return textwrap.dedent(entity_text[open_index + 1 : close_index]).strip()


def parse_entities(relative_path: str) -> list[EntityDecl]:
    path = ROOT / relative_path
    if not path.exists():
        return []
    text = read_text(path)
    entities: list[EntityDecl] = []
    for match in re.finditer(r"\bentity\s+([A-Za-z][A-Za-z0-9_]*)\s+is\b", text, re.IGNORECASE):
        name = match.group(1)
        end_match = re.search(
            rf"\bend\s+(?:(?:entity)(?:\s+{re.escape(name)})?|{re.escape(name)})?\s*;",
            text[match.end() :],
            re.IGNORECASE,
        )
        if not end_match:
            continue
        entity_text = text[match.start() : match.end() + end_match.end()]
        entities.append(
            EntityDecl(
                name=name,
                source=relative_path,
                generic=extract_clause(entity_text, "generic"),
                port=extract_clause(entity_text, "port"),
            )
        )
    return entities


def normalize_lines(text: str, indent: str) -> list[str]:
    if not text:
        return []
    return [f"{indent}{line.rstrip()}" if line.strip() else "" for line in text.splitlines()]


def component_decl(entity: EntityDecl) -> str:
    lines = [f"  component {entity.name} is"]
    if entity.generic:
        lines.append("    generic (")
        lines.extend(normalize_lines(entity.generic, "      "))
        lines.append("    );")
    if entity.port:
        lines.append("    port (")
        lines.extend(normalize_lines(entity.port, "      "))
        lines.append("    );")
    lines.append("  end component;")
    return "\n".join(lines)


def package_text(package_name: str, entities: list[EntityDecl], extra_uses: tuple[str, ...] = ()) -> str:
    header = [
        "library ieee;",
        "use ieee.std_logic_1164.all;",
        "use ieee.numeric_std.all;",
    ]
    header.extend(extra_uses)
    body = [
        "",
        f"-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.",
        f"package {package_name} is",
    ]
    for entity in entities:
        body.append(f"  -- Component declaration sourced from {entity.source}.")
        body.append(component_decl(entity))
        body.append("")
    body.append(f"end package {package_name};")
    return "\n".join(header + body) + "\n"


def context_text(context_name: str, packages: tuple[str, ...]) -> str:
    lines = [
        f"-- Generated by scripts/generate_radhdl_api.py. Do not hand-edit.",
        f"context {context_name} is",
        "  library ieee;",
        "  use ieee.std_logic_1164.all;",
        "  use ieee.numeric_std.all;",
        "  library radhdl;",
    ]
    lines.extend(f"  use radhdl.{package}.all;" for package in packages)
    lines.append(f"end context {context_name};")
    return "\n".join(lines) + "\n"


def first_matching_group(name: str, groups: dict[str, tuple[str, ...]], default: str) -> str:
    lower = name.lower()
    for group, tokens in groups.items():
        if any(token in lower for token in tokens):
            return group
    return default


def collect_unique(paths: list[str]) -> list[EntityDecl]:
    entities: list[EntityDecl] = []
    seen: set[str] = set()
    for path in paths:
        for entity in parse_entities(path):
            key = entity.name.lower()
            if key not in seen:
                entities.append(entity)
                seen.add(key)
    return entities


def write_file(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> None:
    dsp_entities = collect_unique(DSP_RADDSP_RAW)
    interface_entities = collect_unique(INTERFACES_RADIF)
    debug_entities = collect_unique(DEBUG_RADILA)

    package_entities: dict[str, list[EntityDecl]] = {
        "dsp": dsp_entities,
        "interfaces": interface_entities,
        "debug": debug_entities,
    }
    for entity in dsp_entities:
        package_entities.setdefault(first_matching_group(entity.name, DSP_GROUPS, "dsp_transform"), []).append(entity)
    for entity in interface_entities:
        package_entities.setdefault(first_matching_group(entity.name, INTERFACE_GROUPS, "interfaces_axi"), []).append(entity)

    interface_uses = ("use work.radif_pkg.all;",)
    for package_name in sorted(package_entities):
        uses = interface_uses if package_name.startswith("interfaces") else ()
        write_file(OUT_DIR / f"{package_name}.vhd", package_text(package_name, package_entities[package_name], uses))

    write_file(OUT_DIR / "dsp_context.vhd", context_text("dsp_context", ("dsp",)))
    write_file(OUT_DIR / "interfaces_context.vhd", context_text("interfaces_context", ("interfaces",)))
    write_file(OUT_DIR / "debug_context.vhd", context_text("debug_context", ("debug",)))
    write_file(
        OUT_DIR / "radhdl_context.vhd",
        context_text("radhdl_context", ("dsp", "interfaces", "debug")),
    )


if __name__ == "__main__":
    main()
