#!/usr/bin/env python3
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "hdl" / "radhdl_library.tcl"


DEBUG_RADILA = [
    "debug/radila/hdl/radila/radila_core.vhd",
    "debug/radila/hdl/radila/raddebughub_axi.vhd",
    "debug/radila/hdl/radila/radila_axi_top.vhd",
]

DSP_RADDSP_RAW = [
    "dsp/hdl/raddsp/src/zc_reference_pkg.vhd",
    "dsp/hdl/raddsp/src/cordic_atan_pkg.vhd",
    "dsp/hdl/raddsp/src/fft_tdp_ram.vhd",
    "dsp/hdl/raddsp/src/zc_cross_correlator.vhd",
    "dsp/hdl/raddsp/src/zc_peak_detector.vhd",
    "dsp/hdl/raddsp/src/zc_chirp_frame_detector.vhd",
    "dsp/hdl/raddsp/src/cordic_atan2.vhd",
    "dsp/hdl/raddsp/src/fft_radix2_batch_core.vhd",
    "dsp/hdl/raddsp/wrappers/raddsp_zc_chirp_frame_detector.vhd",
    "dsp/hdl/raddsp/wrappers/raddsp_cordic_atan2.vhd",
    "dsp/hdl/raddsp/wrappers/raddsp_fft_radix2_batch_core.vhd",
]

DSP_RADDSP_XCI = [
    "dsp/hdl/xci/raddsp_cordic_atan2_0/raddsp_cordic_atan2_0.xci",
    "dsp/hdl/xci/raddsp_fft_radix2_batch_core_0/raddsp_fft_radix2_batch_core_0.xci",
    "dsp/hdl/xci/raddsp_zc_chirp_frame_detector_0/raddsp_zc_chirp_frame_detector_0.xci",
]

DSP_RADDSP_XCI_VHDL = [
    "dsp/hdl/xci/raddsp_zc_chirp_frame_detector_0/src/zc_reference_pkg.vhd",
    "dsp/hdl/xci/raddsp_zc_chirp_frame_detector_0/src/zc_chirp_frame_detector.vhd",
    "dsp/hdl/xci/raddsp_zc_chirp_frame_detector_0/src/raddsp_zc_chirp_frame_detector.vhd",
    "dsp/hdl/xci/raddsp_zc_chirp_frame_detector_0/synth/raddsp_zc_chirp_frame_detector_0.vhd",
    "dsp/hdl/xci/raddsp_cordic_atan2_0/src/cordic_atan_pkg.vhd",
    "dsp/hdl/xci/raddsp_cordic_atan2_0/src/cordic_atan2.vhd",
    "dsp/hdl/xci/raddsp_cordic_atan2_0/src/raddsp_cordic_atan2.vhd",
    "dsp/hdl/xci/raddsp_cordic_atan2_0/synth/raddsp_cordic_atan2_0.vhd",
    "dsp/hdl/xci/raddsp_fft_radix2_batch_core_0/src/fft_tdp_ram.vhd",
    "dsp/hdl/xci/raddsp_fft_radix2_batch_core_0/src/fft_radix2_batch_core.vhd",
    "dsp/hdl/xci/raddsp_fft_radix2_batch_core_0/src/raddsp_fft_radix2_batch_core.vhd",
    "dsp/hdl/xci/raddsp_fft_radix2_batch_core_0/synth/raddsp_fft_radix2_batch_core_0.vhd",
]


def tcl_list(paths):
    items = " \\\n".join(f"        [file join $::RadHDL::ROOT {' '.join(p.split('/'))}]" for p in paths)
    return f"[list \\\n{items} \\\n    ]"


def write_library():
    text = f"""# Generated by scripts/generate_radhdl_library.py. Do not hand-edit.

namespace eval ::RadHDL {{
    variable ROOT [file normalize [file join [file dirname [info script]] ..]]
    variable DEBUG_RADILA_FILES {tcl_list(DEBUG_RADILA)}
    variable DSP_RADDSP_RAW_FILES {tcl_list(DSP_RADDSP_RAW)}
    variable DSP_RADDSP_XCI_FILES {tcl_list(DSP_RADDSP_XCI)}
    variable DSP_RADDSP_XCI_VHDL_FILES {tcl_list(DSP_RADDSP_XCI_VHDL)}
    variable DSP_RADDSP_IP_REPO [file join $ROOT dsp hdl iprepo]

    proc files {{library}} {{
        variable DEBUG_RADILA_FILES
        variable DSP_RADDSP_RAW_FILES
        variable DSP_RADDSP_XCI_FILES
        variable DSP_RADDSP_XCI_VHDL_FILES

        switch -- $library {{
            debug.radila {{ return $DEBUG_RADILA_FILES }}
            debug {{ return $DEBUG_RADILA_FILES }}
            dsp.raddsp.raw {{ return $DSP_RADDSP_RAW_FILES }}
            dsp.raw {{ return $DSP_RADDSP_RAW_FILES }}
            dsp.raddsp.xci {{ return $DSP_RADDSP_XCI_FILES }}
            dsp.xci {{ return $DSP_RADDSP_XCI_FILES }}
            dsp.raddsp.xci_vhdl {{ return $DSP_RADDSP_XCI_VHDL_FILES }}
            dsp.xci_vhdl {{ return $DSP_RADDSP_XCI_VHDL_FILES }}
            default {{ error "unknown RadHDL library '$library'" }}
        }}
    }}

    proc existing_files {{library}} {{
        set out {{}}
        foreach f [files $library] {{
            if {{[file exists $f]}} {{
                lappend out $f
            }}
        }}
        return $out
    }}

    proc require_files {{library}} {{
        set missing {{}}
        set out {{}}
        foreach f [files $library] {{
            if {{[file exists $f]}} {{
                lappend out $f
            }} else {{
                lappend missing $f
            }}
        }}
        if {{[llength $missing] > 0}} {{
            error "missing RadHDL $library files: $missing"
        }}
        return $out
    }}

    proc ip_repo_paths {{args}} {{
        variable DSP_RADDSP_IP_REPO
        set paths {{}}
        foreach name $args {{
            switch -- $name {{
                dsp.raddsp - dsp {{ lappend paths $DSP_RADDSP_IP_REPO }}
                default {{ error "unknown RadHDL IP repo '$name'" }}
            }}
        }}
        return $paths
    }}

    proc add_files {{library args}} {{
        set files [require_files $library]
        if {{[llength $files] > 0}} {{
            uplevel 1 [list add_files {{*}}$args -norecurse $files]
        }}
        return $files
    }}
}}
"""
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)


if __name__ == "__main__":
    write_library()
