library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

library radif;
library raddsp;

-- Top level for the FFT DMA high-performance-controller reference design.
-- Combines FFT datapath, DMA movement, and processing-system interfaces for platform-level validation.
entity radhdl_fft_dma_hpc_top is
  generic (
    -- Selects the vendor-specific implementation path, usually XILINX for DSP48/XPM-backed builds or generic for portable RTL.
    VENDOR_TAG         : string := "XILINX";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    PRODUCT_SERIES_TAG : string := "ZYNQ_USPLUS";
    -- Identifies the target FPGA family so wrappers can choose the correct primitive or conservative portable behavior.
    DEVICE_FAMILY      : string := "ultrascale+";
    -- Sets the transform, frame, or vector size used by the datapath.
    FFT_RADIX          : positive := 4;
    -- Sets the transform, frame, or vector size used by the datapath.
    FFT_POINTS         : positive := 16;
    -- Sets the bit width for FFT SAMPLE WIDTH values carried by this module.
    FFT_SAMPLE_WIDTH   : positive := 16;
    -- Sets the bit width for FFT TWIDDLE WIDTH values carried by this module.
    FFT_TWIDDLE_WIDTH  : positive := 16;
    -- Sets the transform, frame, or vector size used by the datapath.
    FFT_MEMORY_STYLE   : string := "block"
  );
  port (
    -- Aclk interface signal.
    aclk           : in  std_logic;
    -- Aresetn interface signal.
    aresetn        : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awaddr   : in  std_logic_vector(15 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awprot   : in  std_logic_vector(2 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awvalid  : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_awready  : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wdata    : in  std_logic_vector(31 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wstrb    : in  std_logic_vector(3 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wvalid   : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_wready   : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_bresp    : out std_logic_vector(1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_bvalid   : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_bready   : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_araddr   : in  std_logic_vector(15 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_arprot   : in  std_logic_vector(2 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_arvalid  : in  std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_arready  : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rdata    : out std_logic_vector(31 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rresp    : out std_logic_vector(1 downto 0);
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rvalid   : out std_logic;
    -- AXI4-Lite slave-channel signal used for host register access.
    s_axi_rready   : in  std_logic;
    -- Output irq o signal generated by this module.
    irq_o          : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awaddr   : out std_logic_vector(31 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awlen    : out std_logic_vector(7 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awsize   : out std_logic_vector(2 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awburst  : out std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awvalid  : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_awready  : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wdata    : out std_logic_vector((2 * FFT_SAMPLE_WIDTH) - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wstrb    : out std_logic_vector(((2 * FFT_SAMPLE_WIDTH) / 8) - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wlast    : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wvalid   : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_wready   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bresp    : in  std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bvalid   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_bready   : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_araddr   : out std_logic_vector(31 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arlen    : out std_logic_vector(7 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arsize   : out std_logic_vector(2 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arburst  : out std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arvalid  : out std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_arready  : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rdata    : in  std_logic_vector((2 * FFT_SAMPLE_WIDTH) - 1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rresp    : in  std_logic_vector(1 downto 0);
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rlast    : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rvalid   : in  std_logic;
    -- AXI master-channel signal used for memory-mapped transfer generation.
    m_axi_rready   : out std_logic
  );
end entity;

architecture rtl of radhdl_fft_dma_hpc_top is
  constant C_REG_DATA_WIDTH : integer := 32;
  constant C_REG_ADDR_WIDTH : integer := 16;
  constant C_AXIS_WIDTH     : integer := 2 * FFT_SAMPLE_WIDTH;

  signal reg_wr_addr   : std_logic_vector(C_REG_ADDR_WIDTH - 1 downto 0);
  signal reg_rd_addr   : std_logic_vector(C_REG_ADDR_WIDTH - 1 downto 0);
  signal reg_wr_en     : std_logic;
  signal reg_rd_en     : std_logic;
  signal reg_data_in   : std_logic_vector(C_REG_DATA_WIDTH - 1 downto 0);
  signal reg_data_out  : std_logic_vector(C_REG_DATA_WIDTH - 1 downto 0);
  signal reg_wr_rdy    : std_logic;
  signal reg_rd_rdy    : std_logic;
  signal reg_wr_valid  : std_logic;
  signal reg_rd_valid  : std_logic;
  signal reg_error     : std_logic;

  signal dma_m_tdata   : std_logic_vector(C_AXIS_WIDTH - 1 downto 0);
  signal dma_m_tvalid  : std_logic;
  signal dma_m_tready  : std_logic;
  signal dma_m_tlast   : std_logic;
  signal fft_m_tdata   : std_logic_vector(C_AXIS_WIDTH - 1 downto 0);
  signal fft_m_tvalid  : std_logic;
  signal fft_m_tready  : std_logic;
  signal fft_m_tlast   : std_logic;
  signal tw_addr       : std_logic_vector(31 downto 0);
  signal tw_re         : std_logic_vector(FFT_TWIDDLE_WIDTH - 1 downto 0);
  signal tw_im         : std_logic_vector(FFT_TWIDDLE_WIDTH - 1 downto 0);
  signal dma_irq       : std_logic;
  signal fft_busy      : std_logic;
  signal fft_done      : std_logic;

  function twiddle_re(addr : std_logic_vector) return std_logic_vector is
    variable a : integer := to_integer(unsigned(addr(2 downto 0)));
    variable v : integer := 0;
  begin
    case a is
      when 0 => v := 16384;
      when 1 => v := 15137;
      when 2 => v := 11585;
      when 3 => v := 6270;
      when 4 => v := 0;
      when 5 => v := -6270;
      when 6 => v := -11585;
      when others => v := -15137;
    end case;
    return std_logic_vector(to_signed(v, FFT_TWIDDLE_WIDTH));
  end function;

  function twiddle_im(addr : std_logic_vector) return std_logic_vector is
    variable a : integer := to_integer(unsigned(addr(2 downto 0)));
    variable v : integer := 0;
  begin
    case a is
      when 0 => v := 0;
      when 1 => v := -6270;
      when 2 => v := -11585;
      when 3 => v := -15137;
      when 4 => v := -16384;
      when 5 => v := -15137;
      when 6 => v := -11585;
      when others => v := -6270;
    end case;
    return std_logic_vector(to_signed(v, FFT_TWIDDLE_WIDTH));
  end function;
begin
  assert FFT_POINTS = 16
    report "radhdl_fft_dma_hpc_top example currently provides an internal 16-point twiddle ROM"
    severity failure;
  assert C_AXIS_WIDTH = 32
    report "radhdl_fft_dma_hpc_top currently expects 16-bit I/Q samples on a 32-bit DMA stream"
    severity failure;

  tw_re <= twiddle_re(tw_addr);
  tw_im <= twiddle_im(tw_addr);
  irq_o <= dma_irq or fft_done;

  axi_lite_i: entity radif.radif_axi_lite_to_reg
    generic map (
      DATA_WIDTH => C_REG_DATA_WIDTH,
      ADDR_WIDTH => C_REG_ADDR_WIDTH,
      AXI_ADDR_WIDTH => 16,
      VENDOR_TAG => VENDOR_TAG,
      PRODUCT_SERIES_TAG => PRODUCT_SERIES_TAG
    )
    port map (
      clk => aclk,
      rstn => aresetn,
      s_axi_awaddr => s_axi_awaddr,
      s_axi_awprot => s_axi_awprot,
      s_axi_awvalid => s_axi_awvalid,
      s_axi_awready => s_axi_awready,
      s_axi_wdata => s_axi_wdata,
      s_axi_wstrb => s_axi_wstrb,
      s_axi_wvalid => s_axi_wvalid,
      s_axi_wready => s_axi_wready,
      s_axi_bresp => s_axi_bresp,
      s_axi_bvalid => s_axi_bvalid,
      s_axi_bready => s_axi_bready,
      s_axi_araddr => s_axi_araddr,
      s_axi_arprot => s_axi_arprot,
      s_axi_arvalid => s_axi_arvalid,
      s_axi_arready => s_axi_arready,
      s_axi_rdata => s_axi_rdata,
      s_axi_rresp => s_axi_rresp,
      s_axi_rvalid => s_axi_rvalid,
      s_axi_rready => s_axi_rready,
      reg_wr_addr => reg_wr_addr,
      reg_rd_addr => reg_rd_addr,
      reg_wr_en => reg_wr_en,
      reg_rd_en => reg_rd_en,
      reg_data_in => reg_data_in,
      reg_data_out => reg_data_out,
      reg_wr_rdy => reg_wr_rdy,
      reg_rd_rdy => reg_rd_rdy,
      reg_wr_valid => reg_wr_valid,
      reg_rd_valid => reg_rd_valid,
      reg_error => reg_error
    );

  dma_i: entity radif.radif_axi4_axis_dma
    generic map (
      REG_DATA_WIDTH => C_REG_DATA_WIDTH,
      REG_ADDR_WIDTH => C_REG_ADDR_WIDTH,
      AXI_ADDR_WIDTH => 32,
      AXI_DATA_WIDTH => C_AXIS_WIDTH,
      AXIS_DATA_WIDTH => C_AXIS_WIDTH,
      ENABLE_MM2S => true,
      ENABLE_S2MM => true,
      FIFO_DEPTH => 1024,
      FIFO_FWFT => true,
      VENDOR_TAG => VENDOR_TAG,
      PRODUCT_SERIES_TAG => PRODUCT_SERIES_TAG
    )
    port map (
      clk => aclk,
      rstn => aresetn,
      reg_wr_addr => reg_wr_addr,
      reg_rd_addr => reg_rd_addr,
      reg_wr_en => reg_wr_en,
      reg_rd_en => reg_rd_en,
      reg_data_in => reg_data_in,
      reg_data_out => reg_data_out,
      reg_wr_rdy => reg_wr_rdy,
      reg_rd_rdy => reg_rd_rdy,
      reg_wr_valid => reg_wr_valid,
      reg_rd_valid => reg_rd_valid,
      reg_error => reg_error,
      irq_o => dma_irq,
      m_axi_awaddr => m_axi_awaddr,
      m_axi_awlen => m_axi_awlen,
      m_axi_awsize => m_axi_awsize,
      m_axi_awburst => m_axi_awburst,
      m_axi_awvalid => m_axi_awvalid,
      m_axi_awready => m_axi_awready,
      m_axi_wdata => m_axi_wdata,
      m_axi_wstrb => m_axi_wstrb,
      m_axi_wlast => m_axi_wlast,
      m_axi_wvalid => m_axi_wvalid,
      m_axi_wready => m_axi_wready,
      m_axi_bresp => m_axi_bresp,
      m_axi_bvalid => m_axi_bvalid,
      m_axi_bready => m_axi_bready,
      m_axi_araddr => m_axi_araddr,
      m_axi_arlen => m_axi_arlen,
      m_axi_arsize => m_axi_arsize,
      m_axi_arburst => m_axi_arburst,
      m_axi_arvalid => m_axi_arvalid,
      m_axi_arready => m_axi_arready,
      m_axi_rdata => m_axi_rdata,
      m_axi_rresp => m_axi_rresp,
      m_axi_rlast => m_axi_rlast,
      m_axi_rvalid => m_axi_rvalid,
      m_axi_rready => m_axi_rready,
      m_axis_tdata => dma_m_tdata,
      m_axis_tvalid => dma_m_tvalid,
      m_axis_tready => dma_m_tready,
      m_axis_tlast => dma_m_tlast,
      s_axis_tdata => fft_m_tdata,
      s_axis_tvalid => fft_m_tvalid,
      s_axis_tready => fft_m_tready,
      s_axis_tlast => fft_m_tlast
    );

  fft_i: entity raddsp.raddsp_axis_radfft
    generic map (
      VENDOR => VENDOR_TAG,
      DEVICE_FAMILY => DEVICE_FAMILY,
      G_POINTS => FFT_POINTS,
      G_MAX_POINTS => 2048,
      G_RADIX => FFT_RADIX,
      G_PIPELINED_STREAMING => false,
      G_INPUT_WIDTH => FFT_SAMPLE_WIDTH,
      G_TWIDDLE_WIDTH => FFT_TWIDDLE_WIDTH,
      G_OUTPUT_WIDTH => FFT_SAMPLE_WIDTH,
      G_SCALE_EACH_STAGE => true,
      G_MEMORY_STYLE => FFT_MEMORY_STYLE
    )
    port map (
      clk => aclk,
      rst => not aresetn,
      s_axis_tvalid => dma_m_tvalid,
      s_axis_tready => dma_m_tready,
      s_axis_tdata => dma_m_tdata,
      s_axis_tlast => dma_m_tlast,
      m_axis_tvalid => fft_m_tvalid,
      m_axis_tready => fft_m_tready,
      m_axis_tdata => fft_m_tdata,
      m_axis_tlast => fft_m_tlast,
      twiddle_addr_o => tw_addr,
      twiddle_re_i => tw_re,
      twiddle_im_i => tw_im,
      busy_o => fft_busy,
      frame_done_o => fft_done
    );
end architecture;
